### ISSUE TITLE
Discuss: can we power directive docs using scaladoc?

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#10]
@2beaucoup said:

> Maintaining the directive docs in their current form will require a lot of effort. Maybe we can enrich the nicely grouped ScalaDoc with code samples, link to it and call it a day?

I think that's a great idea. It would require tooling and we would need it before the first stable release probably...

Would someone step up to impl this?

**Comment by patriknw** [comment]
The downside is that code snippets in ScalaDoc are not compiled, or can we solve that?

**Comment by 2beaucoup** [comment]
`includeCode` for ScalaDoc?

**Comment by patriknw** [comment]
yes, it must work with genjavadoc also, so perhaps a pre-processor?

**Comment by 2beaucoup** [comment]
related: https://github.com/akka/akka/issues/18660

**Comment by ktoso** [comment]
Yes, I think it would be really awesome and perhaps not even that hard to pull off.
We simply could grep for `#directive-doc-scala` / `#directive-doc-java` or something specific like that, slam it into files and run.

Anyone would like to help on this? If not then this is something I could pick up though it would be "evenings" for me, so not sure when done hm

**Comment by patriknw** [comment]
You say that the code should live in the Scaladoc of the ordinary source? We extract it and run it?

I think that will be complicated, you need things around the snippet to be able to run it. I was thinking the other way around. Snippets live in test sources as today. Scaladoc uses some include directive that we replace with the actual source in a pre-processor before running `sbt doc`.

**Comment by 2beaucoup** [comment]
I vote for keeping them where they are and moving the includes to ScalaDoc where a magic tool replaces them with the `@example`s.

**Comment by ktoso** [comment]
Oh, I see - that's less impacting the dev experience and simpler to implement too.
Sounds good, let's go with it 👍

**Comment by ktoso** [comment]
got a ticket, resolving the discussion https://github.com/akka/akka-http/issues/11
