### ISSUE TITLE
Fix scaladoc hyperlinks in local build, where git tag is not set

### ISSUE THREAD

**Issue by richard-imaoka** [akka/akka-http#1002]
**correction**: it was nothing to do with scaladoc style 2.12 vs. 2.11. @scaladoc derectives are **NOT** resolved to URLs under [http://doc.akka.io/api/akka-http/**current**/](http://doc.akka.io/api/akka-http/current/) which has scladoc 2.12 style.

<strike>We should leverage lightbend/paradox#52 to fix this issue. -> I will submit a PR.</strike>

<strike>Paradox locally generated broken scaladoc links like the below example, "predefines". </strike>

>  <strike>Similarly to media types, Akka HTTP [predefines](http://doc.akka.io/api/akka-http/current/#akka.http.scaladsl.model.StatusCodes$) well-known status codes, ...</strike>

<strike>The scaladoc URL style is already 2.12.</strike>

FYI, the official ["current" doc](http://doc.akka.io/docs/akka-http/current/scala/http/common/http-model.html#registering-custom-status-codes) works fine, 
>  Similarly to media types, Akka HTTP [predefines](http://doc.akka.io/api/akka-http/10.0.5/#akka.http.scaladsl.model.StatusCodes$) well-known status codes, ...

as the hyperlink "predefines" points to 

> http://doc.akka.io/api/akka-http/10.0.5/#akka.http.scaladsl.model.StatusCodes$

(i.e. ver. = 10.0.5, not "current") where the URL style is still in 2.11.

**Comment by richard-imaoka** [comment]
Sorry, the original comment was wrong ... :| the actual behavior was this:

On a locally generating paradox page,  a [@scaladoc directive](http://developer.lightbend.com/docs/paradox/latest/features/linking.html#scaladoc-directive) turns into something like this:

>  [http://doc.akka.io/api/akka-http/**0.0.0+300-0106fc93**/#akka.http.scaladsl.model.StatusCodes$](http://doc.akka.io/api/akka-http/0.0.0+300-0106fc93/#akka.http.scaladsl.model.StatusCodes$)

were you get 404 Not Found. This is due to [sbt-dyver](https://github.com/dwijnand/sbt-dynver), which sets version = 0.0.0+300-0106fc93 from `git describe`. In released versions, sbt-dynver sets the version from git tags, so no such issues.

I thought it was inconvenient when checking generated hyperlinks from @scaladoc directives locally, but probably ok... I could not find a quick way to tell "is this a released version or sbt-dyver generated the version from git commit hash?"

I'm closing this as it is not a big issue for me anymore, but please reopen if anyone thinks it is an issue.

**Comment by jonas** [comment]
@richard-imaoka Inspired by this issue I played around with an option to link local paradox pages to local unidoc files. Not sure if this would be of use to you.

https://github.com/jonas/akka-http/commits/paradox-localapi

**Comment by richard-imaoka** [comment]
Ah this is cool! I ran yours locally and it worked nicely :)
