### ISSUE TITLE
Implicit resolution precedence in traits containing routes? 

### ISSUE THREAD

**Issue by ALPSMAC** [akka/akka-http#1016]
It's entirely possible I'm just missing something, but I have the following traits: 

```scala
package org.mypackage.whatever

import org.mypackage.utils.ActorResourcePool
import spray.json.DefaultJsonProtocol._
import spray.json._

import scala.concurrent._
import akka.http.scaladsl.Http
import akka.http.scaladsl.Http.ServerBinding
import akka.http.scaladsl.model._
import akka.http.scaladsl.server.Directives._
import akka.stream.ActorMaterializer
import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport
import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport._
import akka.http.scaladsl.model.headers._
import akka.http.scaladsl.unmarshalling.{FromRequestUnmarshaller, Unmarshaller}
import org.mypackage.models.PEBatchRequest
import scala.concurrent.duration._

trait BatchRoute extends JsonSerDe with ActorResourcePool {

  // Code does not compile (fails to resolve implicit Unmarshaller) unless the block
  // below is uncommented to explicitly force resolution. 
  /*private lazy implicit val ec: ExecutionContext = default_system.dispatcher

  private lazy val um = SprayJsonSupport.sprayJsonUnmarshaller[PEBatchRequest](peBatchRequestFormat.asInstanceOf[RootJsonReader[PEBatchRequest]])

  implicit private lazy val req: FromRequestUnmarshaller[PEBatchRequest] =
    Unmarshaller.apply[HttpRequest, PEBatchRequest]{ ec => req =>
      req.entity.toStrict(10.seconds).map{ e =>
        JsonParser(e.data.decodeString("utf8")).asJsObject.convertTo[PEBatchRequest]
      }(ec) //had to explicitly specify the ExecutionContext here... why?
    }*/

  lazy val batchRoute = path("spark" / "pe" / "batch"){
    post{
      entity(as[PEBatchRequest]){ req =>
        complete("")
      }
    }
  }

}
```

```scala
trait JsonSerDe extends DefaultJsonProtocol with SprayJsonSupport {
  //PEBatchRequest is a trait itself with multiple implementations - the code within the JsonFormat
  // here handles switching on the json fields to detect the appropriate subclass. 
  protected lazy implicit val peBatchRequestFormat = new JsonFormat[PEBatchRequest]{...}
}
```

```scala
trait ActorResourcePool {
  @transient protected lazy implicit val default_system: ActorSystem = ActorResourcePool.system
  @transient protected lazy implicit val default_materializer: ActorMaterializer = ActorResourcePool.materializer
}
```

I can't seem to get the implicit `FromRequestUnmarshaller[PEBatchRequest]` to resolve without explicitly declaring it in the commented-out portion of code above.  I have a feeling that somehow I'm being bitten by the precedence/ordering of implicit resolution within a trait vice a class or object, but I'm not sure exactly how to make this work (or if it was ever intended to).  

I'm writing this up as an issue because if this is related to the order of implicit resolution it makes "mixing in" a bunch of traits to compose routes together for an Akka Http service more challenging than it should be and does seem to me like an unexpected edge case that should perhaps be documented (maybe just in a 'best practices' or 'faq' section?).  

Of course, maybe (hopefully) I'm just being bone-headed and missing something simpler here, but I'm just not quite sure why this wouldn't work unless it's got something to do with implicit precedence within traits. 

This is in Akka-Http 10.0.1, Scala 2.11.8, Java 1.8.0 u121, and SBT 0.13.13.

**Comment by ALPSMAC** [comment]
Root cause seems to be related to the way I've declared the `JsonFormat[PEBatchRequest]`.  Somewhere along the way I managed to miss that this must be a `RootJsonFormat[PEBatchRequest]` in order to provide evidence that `PEBatchRequest` can be (de)materialized as a valid JSON object or array (as opposed to a primitive type).  

I'm not sure where I got the convention from for using `JsonFormat[T]` for custom formatters - on referencing the README.md at https://github.com/spray/spray-json it's clear one should be using the `Root*` typeclasses.

I'll close this issue and chalk it up to my own ignorance :confused: 

It would be nice if there were a bit more documentation in the Akka-Http docs themselves around the Spray Json support since it does seem to be the defacto standard for the time being.  Centralizing that documentation might help avoid confusion like this in the future.

**Comment by ktoso** [comment]
A Great start would be if you wrote up something into a PR :) it is an open
source project after all and docs controls are as useful as code contribs

We do work on new docs structure, but my above invitation still stands :)

**Comment by raboof** [comment]
Hi Andy, glad to hear you figured it out!

Yeah, implicits *not* applying can be tricky to figure out.

Did you see http://doc.akka.io/docs/akka-http/10.0.5/scala/http/common/json-support.html#spray-json-support ? If not, where did you look? Perhaps we need a reference here or there - e.g. from the Marshalling sections?

Indeed it might be good to add an example of an explicit custom `RootJsonFormat` there - as @ktoso says above, contributions are most welcome ;).
