### ISSUE TITLE
Add examples of `Route.concat`

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1020]
**EDIT**
As discussed below, the original issue as it was is not needed, but we could still add at least 1 example using `concat` under the [Directives page](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/index.html), so people can see the alternative.

---------------------------------

**Original Issue**
Title: Promote `Route.concat` instead of `~`
All examples for the Scala DSL about Directive concatenation are based on the `~` operator. Even though using `~` comes very handy because of it's length and the fact that can be used as an operator, it's really error prone as it's very easy to forget one `~`. We already have a note on the [Directives page](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/index.html#composing-directives) warning users about the risk of using `~` and forgetting one.
What do you think about rewriting some of the existing examples under the [Directives page](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/index.html) so they use `concat` instead?

Some other comments about `~`:
- It's weirdly aligned when using formatting tools
- It's easy to forget one, and most of the times there is no compiler error to help
- When reading some existing code, some newcomers to Akka HTTP had a hard time to see that there was a `~` at the end of the line.

**Comment by ktoso** [comment]
On the other hand, we finally managed to get intellij start with a full-on effort to support Akka specific things.

This includes https://youtrack.jetbrains.com/issue/SCL-11632 which will warm about mistakes 2) and 3) that you mention.

I would not want to switch right now in other words.

**Comment by jlprat** [comment]
Oh! Good! I wasn't aware of this. Then, my worries are reduced :smiley:.


WDYT about adding 1 example using `concat`. It's only mentioned in the note right now.

**Comment by ktoso** [comment]
Absolutely, we can show it off in more places :)

**Comment by jlprat** [comment]
Then I'll edit this issue to just add 1 or 2 examples in the docs using `concat`.

**Comment by domitian** [comment]
@jlprat is it okay if I add the examples of concat(under Composing Directives) as I haven't seen any corresponding pull request related to this issue?

**Comment by jlprat** [comment]
Sure! Go ahead!
Thanks for taking this one!

**Comment by ktoso** [comment]
Yes please, thanks in advance!
