### ISSUE TITLE
[docs] scala ToC links to java docs

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1022]
On http://doc.akka.io/docs/akka-http/current/scala.html, the ToC on the left links to the java variation of the docs, while the ToC on the right links to the scala variation...

**Comment by jlprat** [comment]
I'm not sure I follow you, If I go to http://doc.akka.io/docs/akka-http/current/scala.html the links on the left have both Java and Scala ToC.
![hugescreen](https://cloud.githubusercontent.com/assets/3337739/24863457/33157026-1e01-11e7-9280-07b42870af57.png)

Top links of the ToC refer to Java bottom ones to Scala

**Comment by raboof** [comment]
Oh! You're completely right. I missed they're both in the ToC ;)

**Comment by raboof** [comment]
Hmm, I feel this could be made more usable, but not sure about any specific way how... let's close this for now.

**Comment by ktoso** [comment]
The new docs layout has a switcher between languages. So that should help.
In http we have been contemplating going to the one page for both pangs
style FYI

**Comment by jlprat** [comment]
What @ktoso is mentioning can be found here https://github.com/akka/akka-http/issues/527 (towards the end of the discussion)
