### ISSUE TITLE
parameterMap ignores "+"

### ISSUE THREAD

**Issue by magoeke** [akka/akka-http#1024]
Hi. I came across a problem. 
I'm using akka-http to provide a simple REST-API that allows a user to sort the data (s)he wants. The following example shows how I want to provide it:

/user?name=max&sort=+birthday .

The important part is the parameter sort. The user should list all the parameters comma separated with a leading "-" or "+".

The concrete problem is that the "+" gets ignored. I'll show you the printed parameterMap of the example call:

> Map(name -> max, sort ->  birthday)

It's hard to notice but instead of an leading "+" there is an whitespace.

Or better to see in this example:
> users?name=max&sort=+birth+day 
> Map(name -> max, sort ->  birth day)

Did I something wrong or is it a bug?

ps: I'm using the high-level api

**Comment by jlprat** [comment]
Need to check if it is in any spec, but I remember that `+` is treated as a space.

>Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.

From https://www.w3.org/Addressing/URL/4_URI_Recommentations.html

You could try doing a `URL.encode` of that value with the + sign.

**Comment by magoeke** [comment]
Thank you for your answer! If it's specified like that then I'll find about an other way for it.

**Comment by jlprat** [comment]
I couldn't read the RFC yet, but at least W3C says `+` signs are spaces in query strings.
I will reopen this issue if the RFC doesn't mention `+` as reserved for query strings.

**Comment by raboof** [comment]
Indeed if you want to encode a `+` in the query string you'll need to encode it as `%2B`. If you just want the URL to look it contains a `+` you could interpret a leading space as a `+` in your code - a bit questionable of course. Another option would be to only prefix the 'reversed' ordering and simply interpret `birthday` as the default sort on birthday.
