### ISSUE TITLE
Marshalling to HttpResponse

### ISSUE THREAD

**Issue by YashdeepSharma** [akka/akka-http#1042]
I wanted to know how to use Marshal to convert scala case classes to HttpResponse also i need to set different StatusCodes based on Failures and Success, using spray json for converting case classes to Json. 

case class Account()
case class Failure()

Marshal(StatusCodes.OK for account and need as json).to[HttpResponse]
Marshal(StatusCodes.PaymentRequired for failure and need as json).to[HttpResponse]

**Comment by jlprat** [comment]
Hi,
I think this type of questions are better suited for our mailing list (https://groups.google.com/forum/m/#!forum/akka-user) or our gitter channel (gitter.im/akka/akka).
It's better if github issues are used only to report bugs, or ask for new features.

Regarding your question, you might want to take a look at the documentation sections about Marshalling, ExceptionHabdlers and RejectionHandlers.

**Comment by ktoso** [comment]
I agree with @jlprat, please post questions to the mailing list.
