### ISSUE TITLE
Tests become false positive when hyphen is used instead of tilde

### ISSUE THREAD

**Issue by Max-Meldrum** [akka/akka-http#1046]
My tests were passing when they should not have. This was giving me such a headache, and after a while I realise I had been using hyphens instead of tilde signs

So my assert in the following code was just getting passed. It should really give an error or warning at least?
`Get() -> route -> check {}`

I am not so familiar with the code base,  but if someone gives a hint where to look, I could have a go at it.

**Comment by ktoso** [comment]
Hi Max,
I don't think that's something we'll be able to make impossible to write.
The `->` syntax is simply Scala's Tuple2 syntax, I'm not sure if there's a way to disable it via compiler flags - you could do that I guess, but it would be global to the entire program.

To disable it selectively it would be a really difficult thing I fear. If we could pull off not allowing -> on HttpRequest we'd break putting it into a map with idiomatic scala etc.

I don't think this is something we can do in other words. The arrow is defined in `Predef`, and the Route  testing ~> operator is defined as `WithTransformation2` inside `RouteTest` and `ArrowAssoc`.

I'll close this ticket, but if you find a way feel free to reopen it.
