### ISSUE TITLE
Create official g8 templates for Akka HTTP

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1055]
In order to have a better getting started experience, it would be good to provide some official g8 templates for Akka HTTP for both Java and Scala

**Comment by patriknw** [comment]
I have created github repos:
https://github.com/akka/akka-http-scala-seed.g8
https://github.com/akka/akka-http-java-seed.g8

**Comment by ktoso** [comment]
Yes we should create them, help very welcome on that @jlprat :)

**Comment by jlprat** [comment]
Done via https://github.com/akka/akka-http-scala-seed.g8/pull/1/commits/a0a359d05ffb48a8b5c311aaa176eb212a54fb58

**Comment by jonas** [comment]
Should we create a new ticket to populate the Java seed?
It would be nice to also promote the seed projects in the docs.

**Comment by jlprat** [comment]
I will now create a ticket for the Java one. I already have a skeleton for it :smiley:
