### ISSUE TITLE
FAILED javadsl FutureDirectivesExamplesTest.testOnCompleteWithBreaker onCompleteWithBreaker

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1063]
```
Error Message

Unexpected status code! expected:<503 Service Unavailable> but was:<500 Internal Server Error>   Request was:      HttpRequest(HttpMethod(GET),/divide/10/0,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))   Route result was: Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(text/plain; charset=UTF-8,An error occurred: / by zero),HttpProtocol(HTTP/1.1))) 
Stacktrace

java.lang.AssertionError: Unexpected status code! expected:<503 Service Unavailable> but was:<500 Internal Server Error>
  Request was:      HttpRequest(HttpMethod(GET),/divide/10/0,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
  Route result was: Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(text/plain; charset=UTF-8,An error occurred: / by zero),HttpProtocol(HTTP/1.1)))

	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.reportDetails(JUnitRouteTest.scala:47)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.assertEquals(JUnitRouteTest.scala:32)
	at akka.http.javadsl.testkit.TestRouteResult.assertEqualsKind(TestRouteResult.scala:227)
	at akka.http.javadsl.testkit.TestRouteResult.assertStatusCode(TestRouteResult.scala:136)
	at docs.http.javadsl.server.directives.FutureDirectivesExamplesTest.testOnCompleteWithBreaker(FutureDirectivesExamplesTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
```

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1002/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by ktoso** [comment]
Again here https://jenkins.akka.io:8498/job/pr-validator-akka-http/1293/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jrudolph** [comment]
Another instance:

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1333/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jlprat** [comment]
Another instance https://jenkins.akka.io:8498/job/pr-validator-akka-http/1394/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jonas** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1624/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by ktoso** [comment]
Again https://jenkins.akka.io:8498/job/pr-validator-akka-http/1676/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1847/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1857/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by raboof** [comment]
It appears the circuit breaker was not successfully tripped.

The circuit breaker uses `sun.misc.Unsafe.instance.compareAndSwapObject` to set the circuit breaker state, which 'atomically' updates the value, but that doesn't mean that change is immediately visible to other threads right? (unlike in `java.util.concurrent.atomic`)

Might that explain the failure, if the second request is handled on another thread and might not successfully read the updated value for the circuit breaker state? Should we "fix" the circuit breaker (possibly taking a performance hit) or somehow make the test more forgiving?

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1988/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2013/testReport/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2012/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4-on-scala-2.12/9/testReport/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by johanandren** [comment]
@raboof As far as I understood it `Unsafe.compareAndSwapObject` makes no guarantees about volatile ordering, but, it does provide ordering on x86. (I'm curious though if all that Unsafe-trixery is really worth it given that there is a Future/promise and a few lambdas allocated per call etc.)

**Comment by jrudolph** [comment]
@johanandren do you have any more information about this? As I understood it, `Unsafe.compareAndSwapObject` should have basically the same semantics as `compareAndSet` from the `Atomic...`  classes. They built on top of volatile semantics, so it should give the same ordering guarantees as volatiles. According to the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/package-summary.html):

> compareAndSet and all other read-and-update operations such as getAndIncrement have the memory effects of both reading and writing volatile variables.

But without documentation you cannot really know as `Unsafe.compareAndSwap` could also have the same semantics as `weakCompareAndSet` which doesn't necessarily offer the happens-before guarantee. And some places I read that `compareAndSet` and `weakCompareAndSet` might be exactly the same on x86, so it might be that all of that including the `Unsafe` variant indeed establish a happens-before relationship.

> (I'm curious though if all that Unsafe-trixery is really worth it given that there is a Future/promise and a few lambdas allocated per call etc.)

That's what I thought as well. For as little as the CircuitBreaker does it seems quite overengineered.

**Comment by johanandren** [comment]
Ah, I see now, atomic ref uses a volatile, even if it uses `compareAndSwapObject` for both cas and weak-cas (which I guess could then become different intrinsics on different archs perhaps).

No good references, so could be just urban myth about the ordering.

**Comment by raboof** [comment]
Let's revisit when we have the extra diagnostics from #1734 

The CircuitBreaker *seems* fine as it determines the `currentState` with `getObjectVolatile`, but indeed I don't see a clear benefit over just having a volatile field there...

**Comment by jrudolph** [comment]
Latest one:

https://jenkins.akka.io:8498/job/pr-validator-akka-http/2052/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by jrudolph** [comment]
Here's the error message (I guess that's what we were looking for?):

```
[info] Test docs.http.javadsl.server.directives.FutureDirectivesExamplesTest.testOnCompleteWithBreaker started
[error] Test docs.http.javadsl.server.directives.FutureDirectivesExamplesTest.testOnCompleteWithBreaker failed: Unexpected entity! expected:<[The server is currently unavailable (because it is overloaded or down for maintenance).]> but was:<[An error occurred: java.lang.ArithmeticException: / by zero]>
[error]   Request was:      HttpRequest(HttpMethod(GET),/divide/10/0,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
[error]   Route result was: Future(Success(Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(text/plain; charset=UTF-8,An error occurred: java.lang.ArithmeticException: / by zero),HttpProtocol(HTTP/1.1)))))
[error] , took 0.127 sec
```

**Comment by jrudolph** [comment]
Great it doesn't show a line or a stack trace, but I guess it's from line 137.

**Comment by jrudolph** [comment]
Tripping the breaker is likely in a race against the server observing the failure of the request. So, there's no guarantee that after the server returned an error, it has also tripped the breaker. I filed https://github.com/akka/akka/issues/24228 to improve ordering if possible.

We can observe the breaker so maybe we can fix it by just waiting until the breaker has tripped.

**Comment by johanandren** [comment]
Can't we just do something like an `awaitAssert` for the test? We don't know exact ordering but sometime very soon it should start failing because the breaker tripped.
