### ISSUE TITLE
Chunked + GZIP Request/Response

### ISSUE THREAD

**Issue by grillorafael** [akka/akka-http#1084]
Hi guys,

I have a simple Akka Http server running with `encodeReponse` on my routes and a simple client using `headers.`Accept-Encoding`(HttpEncodings.gzip)`.

When I request things using `curl --compressed` I get a `chunked + gzip` response but when I do a simple http request with the header above, I get only gzip without chunked.

I'm decoding as the docs specify and then Unmarshalling the entity into my case class (From Circe JSON)

Any idea on how to make it work like curl does? (gzip + chunked)

**Comment by jrudolph** [comment]
Hi @grillorafael, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on the [gitter channel](https://gitter.im/akka/akka) or the [mailing list](https://groups.google.com/forum/#!forum/akka-user)? 

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.

(When asking there I'd suggest to add information why you care about the response being chunked and how you observe that it isn't.)

**Comment by grillorafael** [comment]
Sure thing. Sorry for that
