### ISSUE TITLE
Cannot use FiniteDuration with Parameter

### ISSUE THREAD

**Issue by dubeejw** [akka/akka-http#1093]
When trying to use a scala.concurrent.duration.FiniteDuration as a parameter value, I get the following error:

```
too many arguments for method parameter: (pdm: akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet)pdm.Out
```

Example:
```
parameter(time: 60.seconds) { (wait) =>
...
}
```

**Comment by jrudolph** [comment]
Hi @dubeejw, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on the [gitter channel](https://gitter.im/akka/akka) or the [mailing list](https://groups.google.com/forum/#!forum/akka-user)? 

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.

(Your code isn't valid Scala code, when posting to the mailing list, try to add more information about what you want to achieve with the code.)

**Comment by dubeejw** [comment]
This is a bug.

**Comment by dubeejw** [comment]
@jrudolph, please explain how it is not valid syntax. It works fine with Spray.

**Comment by jrudolph** [comment]
Can you show the code you used in spray? Maybe it was a bit different than the example above?
