### ISSUE TITLE
Allow to setup HTTPS/TLS without providing an SSLContext

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1104]
Instead, `HttpsConnectionContext` should provide one or more constructors for an `SSLEngine`. That will allow us to use the native netty openssl engine more easily (see #736) and also allows to get rid of the SSLContext mock in [Play's `AkkaHttpServer`](https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L108)).

We already improved the akka stream TLS API in exactly the same way not to depend on `SSLContext` in https://github.com/akka/akka/pull/21822.

**Comment by ktoso** [comment]
Sounds good, I added it to out "http2 for play" milestone, but feel free to move it around

**Comment by johanandren** [comment]
This exists since #2845
