### ISSUE TITLE
Add a documentation page with compatibility information

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1106]
Should cover:

 * [ ] general information about our compatibility guarantees
 * [x] information about which Scala and Akka versions are supported and what to do to make it work (e.g. for Akka 2.4 vs. 2.5)
 * [ ] a list of non-stable components and modules

**Comment by ktoso** [comment]
Yeah and would be good to do this soon, with the 2.5 confusion etc, assigned as pick next.

**Comment by ktoso** [comment]
Explained how to use with 2.5 here: https://github.com/akka/akka-http/pull/1230

**Comment by ktoso** [comment]
So I handled only the 2.5 part of that in #1230, but that's done at least

**Comment by jrudolph** [comment]
#1305 contains our current ideas for versioning / compatibility for the future.

**Comment by jlprat** [comment]
I will take this one :)

**Comment by jlprat** [comment]
Just to clarify:
- First point is basically take the text in #1305 and adapt it to the latest changes like, Akka being a provided dependency and 10.1.x depending on Akka 2.5. Right?
- Second point's goal is to list all non stable APIs e.g. everything that is marked with `@ApiMayChange`?

**Comment by ktoso** [comment]
Yeah sounds good

**Comment by ktoso** [comment]
This may want to be done quickly as we hope to release 10.1.0 tomorrow

**Comment by jlprat** [comment]
Or if you want to work on it right away, also feel free :)

**Comment by jlprat** [comment]
As #1910 is merged now, I guess this can be closed
