### ISSUE TITLE
FAILED: akka.http.scaladsl.server.HttpAppSpec.HttpApp should start without ActorSystem

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1121]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1102/testReport/junit/akka.http.scaladsl.server/HttpAppSpec/HttpApp_should_start_without_ActorSystem/

**Comment by jlprat** [comment]
Probably related to https://github.com/akka/akka-http/issues/1061

**Comment by 2m** [comment]
Fixed in #1207
