### ISSUE TITLE
How to make a Inputstream(java) after fileupload?

### ISSUE THREAD

**Issue by TopSpoofer** [akka/akka-http#1126]
Here i am want to upload a file and store it in the Minio (a distributed storage system), but the minio's sdk just provide a api for java's Inputstream ! I don't want to save the uploaded file and open it by Inputstream before save it to Minio. How can i do, some suggest?

**Comment by jrudolph** [comment]
Hi @TopSpoofer,

you can use one of the methods in akka-stream's [StreamConverters](http://doc.akka.io/api/akka/2.5/akka/stream/javadsl/StreamConverters$.html#asInputStream():akka.stream.javadsl.Sink[akka.util.ByteString,java.io.InputStream]) to drain a source from an InputStream.

Please note, that we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on the [gitter channel](https://gitter.im/akka/akka) or the [mailing list](https://groups.google.com/forum/#!forum/akka-user)? 

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.
