### ISSUE TITLE
Document file upload with akka http client

### ISSUE THREAD

**Issue by epiphyllum** [akka/akka-http#1132]
How to use Http().single to post a form with  normal fields plus fileupload field

I can not see any examples like this in akka-http-test

**Comment by jrudolph** [comment]
@epiphyllum I agree that should be (better?) documented. This is currently tracked in #285 so I close this issue as a duplicate.

The example in that other ticket might still work. See https://gist.github.com/jrudolph/08d0d28e1eddcd64dbd0#file-testmultipartfileupload-scala-L78
