### ISSUE TITLE
Replace confusing === with shouldEqual or similar in docs

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka-http#1136]
There is sample code:
```scala
 "return a MethodNotAllowed error for PUT requests to the root path" in {
      // tests:
      Put() ~> Route.seal(smallRoute) ~> check {
        status === StatusCodes.MethodNotAllowed
        responseAs[String] shouldEqual "HTTP method not allowed, supported methods: GET"
      }
    }
```
the line `status === StatusCodes.MethodNotAllowed` actually does no check, but only returns `boolean` value, it is confusing and can lead to errors in tests and code.

**Comment by jrudolph** [comment]
Great, catch. I think those are left overs from previous switches between specs2 and scalatest which differ in behavior in that regard.

Could you create a small PR to fix it?

**Comment by manonthegithub** [comment]
yeah, with pleasure).
I'll try to do it in a week)

**Comment by manonthegithub** [comment]
I was looking on version 10.0.4 of docs, and in current it was fixed. But nevertheless I found another class `FullSpecs2TestKitExampleSpec` where it was.

**Comment by jonas** [comment]
As discussed [here](https://github.com/akka/akka-http/pull/1146#discussion_r117324096), `===` works as expected, but the assertions are different from the other examples, so this ticket is about using the same way of checking in the examples.

**Comment by nikom1337** [comment]
After pr #1750 is merged there will be only one triple equals assertions to fix in `akka.http.impl.engine.ws.Utf8CodingSpecs` test class.

**Comment by jlprat** [comment]
I'd say this one is solved, am I right?
If not please re-open
