### ISSUE TITLE
Depend on Akka 2.5 directly, and call it 10.1.x

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1151]
Please note that Akka HTTP 10.0.x *does* work with Akka 2.5, due to all the compatibility rules we have in place.

We do however depend on 2.4 nowadays since we want to still be compatible with it, thus do not want to leak in 2.5 only API usage.

What we should do to avoid confusion like in https://github.com/akka/akka-http/issues/1101 : 

- Depend on 2.5 directly
- *Always* test with 2.4 and 2.5 in PR validation and other jobs
- Announce it as 10.1.0 as if someone only depended on the "akka http version" then it would upgrade their Akka (actor etc), so we should bump the minor to signify this

**Comment by ktoso** [comment]
Ah, the super ticket is here: https://github.com/akka/akka-http/issues/821

**Comment by ktoso** [comment]
Should we decide on a specific plan here some time soon?

**Comment by ktoso** [comment]
The 1.1.10 milestone does not have issues assigned; if we have any issues that we want to address before doing this jump we should assign them to this milestone and figure out a timeline for it :)

**Comment by raboof** [comment]
We have discussed this further, and as Akka 2.4 is nearing EOL (this month), it makes sense to require Akka 2.5 for akka-http 10.1.x, and not to test against 2.4 anymore at all.

If we encounter any really serious (e.g. security) issues we should back-port them to 10.0.x to also make the fix available for users who are still on 10.0.x, but this should be rare.

**Comment by jrudolph** [comment]
:+1: 

We'll track the next steps for 10.1.x in #1645. Closing this ticket.
