### ISSUE TITLE
[Doc] Document how to increase default timeout of 1 second in TestKit

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1152]
The default timeout of the Route TestKit is 1 second. On the current documentation page there is no information, nor hints on how to increase it.

Please provide documentation (and maybe an example?) on how to change the default timeout.

(AFAIK for Scala one should provide an implicit of type `RouteTestTimeout`)

**Comment by jypma** [comment]
hmm, does it come from [RouteTestTimeout](https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestTimeout.scala) ?

**Comment by jypma** [comment]
yeah, see [RouteTest](https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala#L143). If you have an implicit `RouteTestTimeout` instance in scope when you say `~>` in your test, that's the timout that'll be used. In Scala.

**Comment by jlprat** [comment]
Yeah, I'd say it comes from [RouteTestTimeout](https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestTimeout.scala)

After adding an `implicit val timeout = RouteTestTimeout(3 seconds)` the test apparently waits up to 3 seconds for the response.
