### ISSUE TITLE
Make sure seed templates included in Lightbend kickstarter

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1155]
Make sure akka http seed templates are listed in: http://developer.lightbend.com/start/?group=akka

**Comment by ktoso** [comment]
AFAIR they way to add these is Lightbend internal so we'll have to do that in the Lightbend team

**Comment by jonas** [comment]
For discoverability it would also be nice to add GitHub tags to the seed projects.

**Comment by ktoso** [comment]
Good point, will do that (and I'll also give you all write access there)

**Comment by raboof** [comment]
we merged the seed projects and the quickstarts together, and those are available on developer.lightbend.com
