### ISSUE TITLE
Http2: RemoteAddress setting not working for HTTP/1 behind ALPNSwitch

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1160]
The reason is that the settings are not passed to the HTTP1 `serverLayer` here: https://github.com/akka/akka-http/blob/2e0d2b5b219c21ce3acd1ced0cb2a2e7cd6aa1ee/akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala#L79-L79

**Comment by ktoso** [comment]
Hmm... Have you reproduced the issue or just looked at it?
I mean: 

```
class Http2Ext(private val config: Config)(implicit val system: ActorSystem)
```

so:

```
      AlpnSwitch(getChosenProtocol, Http().serverLayer(), http2Layer()) atop
```

is actually:

```
      AlpnSwitch(getChosenProtocol, Http()(system).serverLayer(), http2Layer()) atop
```

so it uses the right actor system, since the Http1 extension got the system, and the only place it could get it from is that implicit. So I don't think that was the issue.
