### ISSUE TITLE
Question: How to terminate akka http connection pools on sys.exit(0)

### ISSUE THREAD

**Issue by alisiikh** [akka/akka-http#1184]
Hello,

I'm trying to figure out how to terminate akka and akka-http gracefully and to adapt this code:
```
val terminationFuture = Http().shutdownAllConnectionPools().flatMap { _ =>
   materializer.shutdown()
   system.shutdown()
}

Await.result(terminationFuture, 30 seconds)
```

But I want this code to be executed during sys.exit(0).

In fact Akka registers a terminate call on itself in shutdown hooks, so if I add a shutdown hook, my code will be executed after akka's terminate, and it would lead either to AdburptTerminationException or to a deadlock.

Is there any way out of this? How can I do this akka http shutdown before system termination?
Any ideas? Thank you! :)

**Comment by jlprat** [comment]
Github issues are not the best place to ask questions. For such things we have the gitter channel (https://gitter.im/akka/dev) and the mailing list: (https://groups.google.com/forum/#!forum/akka-user).

That being said, maybe you are looking for something similar to:
```
sys.addShutdownHook {
   // do your shutting down here
}
```

**Comment by alisiikh** [comment]
Ok, thanks. Will go ask there, excuse me for taking your time.

**Comment by jlprat** [comment]
No worries! :)
