### ISSUE TITLE
Reenable JUnit test for PR validation

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1191]
Since #1189 our own Java JUnit tests are not run any more.

Unfortunately, just enabling the JUnit test interface for sbt is not sufficient because of https://github.com/sbt/junit-interface/issues/35.

So for now, we might need to introduce another intermediate class for our own tests that also extends from `JUnitSpecLike` to run JUnit tests with Scalatest as before.

**Comment by jrudolph** [comment]
We should also test if setting `crossPaths := false` would be possible for `akka-http-testkit` but I wonder if that leads to issues during cross-building.

**Comment by jrudolph** [comment]
Actually, the tests did work, what did I see before?

**Comment by ktoso** [comment]
:)
