### ISSUE TITLE
Add documentation for SSE API and (un)marshallers

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1198]
Follow up to #1116.

**Comment by ktoso** [comment]
We should do this as soon as possible, releasing a feature with zero docs is not something we should be doing in general. Marking as pick next.

**Comment by jrudolph** [comment]
There's a bit of documentation and examples at https://github.com/hseeberger/akka-sse that we could port over to over docs. wdyt @hseeberger?

**Comment by hseeberger** [comment]
We can build upon the README and examples from akka-sse, but I think we need more in order to match the Akka documentation standards. I guess I will have some time later this week to get the work started.

**Comment by ktoso** [comment]
Thanks @hseeberger !
