### ISSUE TITLE
http: formField(s) and multipart/form-data

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#120]
<a href="https://github.com/stanch"><img src="https://avatars.githubusercontent.com/u/2670454?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stanch](https://github.com/stanch)**
_Tuesday Sep 08, 2015 at 19:32 GMT_
_Originally opened as https://github.com/akka/akka/issues/18426_

---

It seems that `formField` and `formFields` directives fail to read the fields from `multipart/form-data` if their arguments (i.e. field names) are specified not in the same order as they are in the data. I don’t have a distilled reproduction yet, but I observed this behavior several times and managed to switch it on and off by rearranging the field names. Unfortunately the order is by no means reliable. It seems that even the same browser can choose to send the same fields in a different order. The error message is:

```
The form field X was malformed. Unexpected end of multipart entity
```

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Monday Sep 14, 2015 at 11:43 GMT_

----

Thanks for reporting!

**Comment by jrudolph** [comment]
We haven't seen a reproducer here and no one else seemed to complain. This might be a symptom of another problem. We are still considering better support for multiple toStrict calls in the infrastructure.

So, closing for now.

**Comment by stanch** [comment]
Pretty sure the underlying issue is the same as https://github.com/akka/akka-http/issues/73.
