### ISSUE TITLE
Support Authorization with Proxy server (in client)

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1213]
In https://github.com/akka/akka-http/pull/1200#issuecomment-309601053 we implemented HTTP(S) proxy support, however we did not yet implement authorization support, this ticket is to address that.

**Comment by ktoso** [comment]
FYI @note

**Comment by Scalahansolo** [comment]
After giving this a couple shots I am getting lost trying to implement this. Until I have time to do some more digging, I don't quite have the knowledge necessary to figure out how to pass the proxy auth header after the proxy responds with a 407. I also don't have the greatest understanding of how BiDi flows work, which I am now trying to level up on.

**Comment by jrudolph** [comment]
Actually, I would send the authorization data proactively before the proxy can even respond with 407. After it has responded it might even be impossible to use `CONNECT` on the same connection again. I'd say that retrying CONNECT on another connection is currently out of scope.

Basically, how the thing should work is by adding optional credentials (could be of type `HttpCredentials` to support all kinds of credentials even if basic authorization is probably the most common one?) to the `httpsProxy` constructor and passing them on to the stage. In the stage, the initial `CONNECT` request is currently built using string manipulation. For now, it would be ok to add the authentication header there manually by string as well. You should probably create an instance of `model.headers.Proxy-Authorization` with the credentials and use its `render` method with a `StringRendering` to render the header.

Does that explanation make sense. Hopefully that would be enough for a first cut.

**Comment by Scalahansolo** [comment]
In trying to hack together something just to get something working prior to wiring a real impl together I am having the following problem. 

At https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala#L51 I have added the following. 

`  val proxyHeader: HttpHeader = `Proxy-Authorization`(HttpCredentials.createBasicHttpCredentials("XXXXX", "XXXXX"))

  private var connectMsg = ByteString(s"CONNECT $targetHostName:$targetPort HTTP/1.1\r\nHost: $targetHostName\r\n\r\n$proxyHeader")`

When this renders, it all looks correct from quick visual check for what I would expect it to look like. However, I am still getting 407s.

**Comment by ktoso** [comment]
Solved by @Scalahansolo, thanks!
