### ISSUE TITLE
FAILED: TimeoutDirectivesExamplesTest

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1220]
docs.http.javadsl.server.directives.TimeoutDirectivesExamplesTest.testRequestTimeoutIsConfigurable

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1256/

```
Error Message

No value present

Stacktrace

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at docs.http.javadsl.server.directives.TimeoutDirectivesExamplesTest.testRequestTimeoutIsConfigurable(TimeoutDirectivesExamplesTest.java:111)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1378/testReport/junit/docs.http.javadsl.server.directives/TimeoutDirectivesExamplesTest/testRequestTimeoutIsConfigurable/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1678/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1773/testReport/junit/docs.http.javadsl.server.directives/TimeoutDirectivesExamplesTest/testRequestTimeoutIsConfigurable/

**Comment by jrudolph** [comment]
Didn't happen for a long time.
