### ISSUE TITLE
Clarify whether https HTTP CONNECT can be used for http endpoints

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1228]
If not, it might be good to mention it in http://doc.akka.io/docs/akka-http/current/scala/http/client-side/client-transport.html#https-proxy .

**Comment by jrudolph** [comment]
Technologically, it should support any kind of protocol as an HTTPS proxy shouldn't look into the payload (and you wouldn't expect to see anything with HTTPS). Proxies might still be administratively restricted by not allowing connections everywhere.

**Comment by ktoso** [comment]
I think it "should" work, but I tried some proxies and none of them (free ones) allowed getting to a random http site hm (my homesite). The good news though is that we fail nicely then, saying that `failStage(new ProxyConnectionFailedException(s"The HTTPS proxy rejected to open a connection to $targetHostName:$targetPort with status code: $statusCode"))`

But yeah, in theory should work...

**Comment by jrudolph** [comment]
Fixed in #1250.
