### ISSUE TITLE
how customize the error message

### ISSUE THREAD

**Issue by epiphyllum** [akka/akka-http#1231]
when akka http bind form values to our case class,   akka-http will reject the request with some error message if the binding violate some rules.    but the error message is akka-defined. 
are there error message customizable?  and how

**Comment by raboof** [comment]
Hello Hary,

I haven't checked but those binding violations should lead to rejections,
which are then turned into error messages. You can register a custom
rejection handler to customize the messages. See
http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/rejections.html
.


Kind regards,

Arnout

**Comment by jrudolph** [comment]
Closing for now because it is probably no bug.
