### ISSUE TITLE
Reusing the ToResponseMarshaller

### ISSUE THREAD

**Issue by Gabology** [akka/akka-http#1247]
I have a typical use case where I have an arbitrary resource, `T` and a corresponding endpoint `GET /T`. This maps to a method which returns a `CompletionStage<Optional<T>>` now I wasn't able to find any predefined routing directive that would let me return `200 OK` if the optional contains the resource and `404 Not found` if the resource was not found.

I am thinking I might have to use the `completeWithFuture` that accepts a `CompletionStage<HttpResponse>` and that's fine except I also need to serialise the POJO into a JSON response and I wasn't able to find something akin to  the `completeOK` overload which accepts a value `T` and a `Marshaller<T, ResponseEntity>`. Ideally if I could find a function accepting `T` and `Marshaller<T, ResponseEntity>` and returning a `HttpResponse`.

**Comment by jrudolph** [comment]
On the Scala side there's a pattern for that:
 * use the available `Option[T]` marshaller which will marshal `None` to an empty response
 * use `rejectEmptyResponse` that allows to convert an empty response into an empty rejection (that will be rendered as 404)

On the Java side, I think we also have `rejectEmptyResponse` but I think you cannot access the `Option` marshaller right now.

One solution for Java could be to provide an `Option` marshaller consistently with the Scala side and use it with `rejectEmptyResponse`. Another option could be to have another kind of marshaller that marshals `None` directly to a `404` response.

The marshaller should live in `javadsl.marshalling.Marshaller` and should have a signature like this:

```
def optionToOKOrNotFoundResponse[A](m: Marshaller[A, HttpResponse]): Marshaller[Option[A], HttpResponse]
```

Anyone up to that?
