### ISSUE TITLE
Tune createServerHttpsContext for server-side

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1261]
Currently `createServerHttpsContext` issues a warning and just re-uses `createClientHttpsContext` to build the `HttpsConnectionContext`. We might want to tune this specifically for server-side use.

**Comment by jrudolph** [comment]
IIRC this issue was also related: https://github.com/akka/akka-http/issues/55

**Comment by raboof** [comment]
Yeah I think we can actually consider this issue a duplicate of #55
