### ISSUE TITLE
fileUpload & uploadedFile directives don't support multiple files upload

### ISSUE THREAD

**Issue by patrox** [akka/akka-http#1273]
At the moment, the mentioned directives ([`fileUpload`](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala#L68) and [`uploadedFile`](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala#L35)) support only single file uploads, so sth like:

```
curl -v -F "file1=@file1" httpbin.org/post
```

```
*   Trying 54.227.244.176...
* Connected to httpbin.org (54.227.244.176) port 80 (#0)
> POST /post HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 206
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------5f9b54e9aa8d5aff
> 
* Done waiting for 100-continue
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: meinheld/0.6.1
< Date: Fri, 07 Jul 2017 18:53:28 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Powered-By: Flask
< X-Processed-Time: 0.00159978866577
< Content-Length: 463
< Via: 1.1 vegur
< 
{
  "args": {}, 
  "data": "", 
  "files": {
    "file1": "Hello \n\n"
  }, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Content-Length": "206", 
    "Content-Type": "multipart/form-data; boundary=------------------------5f9b54e9aa8d5aff", 
    "Expect": "100-continue", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.47.0"
  }, 
  "json": null, 
  "origin": "89.79.154.104", 
  "url": "http://httpbin.org/post"
}
* Connection #0 to host httpbin.org left intact
```

But, the multi-file upload is not currently supported, so you cannot do sth like:

```
curl -v -F "file1=@file1" -F "file2=@file2" -F "file3=@file3" httpbin.org/post
```

```
*   Trying 54.243.246.56...
* Connected to httpbin.org (54.243.246.56) port 80 (#0)
> POST /post HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 519
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------8db1604fa6d38907
> 
* Done waiting for 100-continue
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: meinheld/0.6.1
< Date: Fri, 07 Jul 2017 18:57:26 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Powered-By: Flask
< X-Processed-Time: 0.00107789039612
< Content-Length: 510
< Via: 1.1 vegur
< 
{
  "args": {}, 
  "data": "", 
  "files": {
    "file1": "Hello \n\n", 
    "file2": "World \n", 
    "file3": "!\n"
  }, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Content-Length": "519", 
    "Content-Type": "multipart/form-data; boundary=------------------------8db1604fa6d38907", 
    "Expect": "100-continue", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.47.0"
  }, 
  "json": null, 
  "origin": "89.79.154.104", 
  "url": "http://httpbin.org/post"
}
* Connection #0 to host httpbin.org left intact
```

My initial idea is to provide alternative directives, which would use the `files` map available in the request :

```
  "files": {
    "file1": "Hello \n\n", 
    "file2": "World \n", 
    "file3": "!\n"
  }
```

and which would provide means to operate on **all** files which were uploaded in a given http request.

Is it a reasonable approach ? Do you see any issues with this approach ?

**Comment by patrox** [comment]
UPDATE:

I already have some code ready which could support multiple file uploads, basically what I did was to add a slightly modified version of `fileUpload` directive, with the following signature:

```scala
def fileUploads(): Directive1[Seq[(FileInfo, Source[ByteString, Any])]]
```

**Comment by ktoso** [comment]
Seems interesting, would you like to send in a PR with that directive?

**Comment by patrox** [comment]
@ktoso Sure, I just need to add some tests and update the docs, but the core functionality is already done.

**Comment by jrudolph** [comment]
We already have a PR, https://github.com/akka/akka-http/pull/1033, open for that functionality.

It is actually not so easy to implement it correctly for files of every size because of the head-of-line blocking issue inherent in the multipart format. I.e. you cannot create that `Seq[(FileInfo, Source)]`, because the `FileInfo` for the next file will only be ready when the first info has been read (it seems to work for small files but will break for larger ones when buffers are filled up). In that PR, the solution is to buffer all data on disk before returning something. We haven't yet got to verifying that this is indeed the best solution.

**Comment by jrudolph** [comment]
@patrox if you want to help with getting that PR merged, it could be worthwhile to try the code given there, e.g. by copying the code of the new directive into you project and see if it would work for you.

**Comment by patrox** [comment]
@jrudolph Thank you very much for pointing to the PR #1033, as I missed it, while searching if there is an issue for similiar functionality already opened (otherwise I wouldn't create this one, as it looks like a duplicate).

I'll take a look at that PR then, as it doesn't seem active anymore.
