### ISSUE TITLE
Incorrect request URIs with HTTP/2

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-http#1274]
This issue occurs with Play 2.6.1 which uses Akka HTTP 10.0.9. A Play user has reported an issue with handling requests with query parameters in the path, e.g. `/test?param=s`. Issue: https://github.com/playframework/playframework/issues/7596

* When requests are served with HTTP/1 the request URI parsed by Akka HTTP is correct (`http://localhost:9000/test?param=s`). When served with HTTP/2 the request URI is incorrect: the query part of the URI is included in the URI path (`https://localhost:9443/test%3Fparam=s`).
* In addition, the special `Raw-Request-URI` header is correctly provided with the HTTP/1 request, but not with the HTTP/2 request.

You can see debug output showing the `HttpRequest` values here: https://github.com/playframework/playframework/issues/7596#issuecomment-313975065.

**Comment by ktoso** [comment]
Thanks for reporting! Entire weeks following this one we'll work on http so will fix this then :)

**Comment by richdougherty** [comment]
OK thanks, someone on the Play team may have time but we can discuss how we're placed when you have time.

By the way, I've traced the error to the `http2.RequestParsing` object. It has a line:

```scala
val uri = Uri(scheme, authority).withPath(Uri.Path(path))
```

Unfortunately the value of `path` can be `/test?param=s`, which is a path _and_ a query string, but it is parsed with the `Uri.Path.apply` method, which only handles paths. In contrast, HTTP/1's `HttpRequestParser` uses a specialised URI parsing method: `Uri.parseHttpRequestTarget` to parse the target of an HTTP/1 request. Maybe HTTP/2 needs a special URI parsing method too, which parses a _scheme_, _authority_ and _pathAndQuery_ into a `Uri`?

The `http2.RequestParsing` class also needs a line like the one from HTTP/1's `HttpRequestParser`:

```scala
val allHeaders0 =
  if (rawRequestUriHeader) `Raw-Request-URI`(uriBytes.decodeString(HttpCharsets.`US-ASCII`.nioCharset)) :: headers
  else headers
```

E.g. something like:

```scala
if (rawRequestUriHeader) headers += `Raw-Request-URI`(scheme + "://" + authority + pathAndQuery)
```

**Comment by jrudolph** [comment]
Thanks for bringing it up, @richdougherty.

> In contrast, HTTP/1's HttpRequestParser uses a specialised URI parsing method: Uri.parseHttpRequestTarget to parse the target of an HTTP/1 request. Maybe HTTP/2 needs a special URI parsing method too, which parses a scheme, authority and pathAndQuery into a Uri?

Yes, from a cursory look into it that might be the best solution.

**Comment by richdougherty** [comment]
Hi, just wondering if you've had a chance to look at it? We might be able to look at it soon if you're too busy.

**Comment by jrudolph** [comment]
@richdougherty, sorry, no didn't get to it so far. Would be nice if you could help us out with that one.

**Comment by richdougherty** [comment]
OK, I think I should have a chance too look at it soon - hopefully next week :)
