### ISSUE TITLE
Logging with println in Http2ServerDemux

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-http#1275]
When I was running a Play application with default settings I noticed that the `Http2ServerDemux` is using `println` to log its debug information:

```
Got 3 settings!
Ignoring setting SETTINGS_HEADER_TABLE_SIZE -> 65536 (in Demux)
Setting max concurrent streams to 1000 (not enforced)
Setting initial window to 6291456
Applied SETTINGS_HEADER_TABLE_SIZE(65536) in header compression
Got unhandled event SettingsAckFrame(List())
Got unhandled event GoAwayFrame(0,PROTOCOL_ERROR,debug:<hidden>)
```

See: https://github.com/akka/akka-http/blob/d325304de1bfd3b08da34f3f4b052a29f3e18151/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala#L204

**Comment by richdougherty** [comment]
Play issue to track this: https://github.com/playframework/playframework/issues/7601

**Comment by ktoso** [comment]
Good point, we should begin to clean up the infra slowly since it's getting used.
Thanks for the ticket Rich 👍
