### ISSUE TITLE
Weird content when I uploaded a file

### ISSUE THREAD

**Issue by dinegri** [akka/akka-http#1277]
I wrote it from an example on akka.io: 

```scala
def createEntity(file: File): Future[MessageEntity] = {
    require(file.exists())
    val formData =
      Multipart.FormData(
        Source.single(
          Multipart.FormData.BodyPart(
            "file",
            HttpEntity(MediaTypes.`application/octet-stream`, file.length(), FileIO.fromFile(file, chunkSize = 100000)), // the chunk size here is currently critical for performance
            Map("filename" -> file.getName))))
    
    
    Marshal(formData).to[MessageEntity]
}

def uploadFile(url: String, entity: RequestEntity) = {
    Http().singleRequest(HttpRequest(uri = url, method = HttpMethods.PUT, entity = entity))
}
```

So I can upload a file and everything is ok, but when I have checked the file content, I have got this content below:

```text
--Wtjpyz4KNAF1LbynJlZA603H
Content-Type: text/plain; charset=UTF-8
Content-Disposition: form-data; filename="data.csv"; name="csv"

1,5,7

--Wtjpyz4KNAF1LbynJlZA603H--
```

but my file content is only 1,5,7

Why the entire content of multipart form-data is going to my uploaded file?

**Comment by jlprat** [comment]
When you say you got the whole multipart in your file content, you mean in the server that process that `PUT`?
How does the server look like?

**Comment by dinegri** [comment]
@jlprat yes I mean in the server that process PUT

 I uploaded one file using curl into the server without any issue (without the whole multipart content)

**Comment by jlprat** [comment]
Hi @dinegri!
In order to better assess this, it would be awesome to have a full reproducer. Could you share the server code as well?

**Comment by jrudolph** [comment]
Can you share the curl command line?

**Comment by dinegri** [comment]
@jlprat I do not have access to the server

@jrudolph for sure, it`s a upload in two steps. First step give me a location header for upload the file


```bash
curl -i -X PUT "http://quickstart.cloudera:50070/webhdfs/v1/tmp/webhdfs/file_201206.txt?op=CREATE&overwrite=true" 
curl -i -T file_201206.txt "http://quickstart.cloudera:50075/webhdfs/v1/tmp/webhdfs/webhdfs-test-new.txt?op=CREATE&user.name=cloudera&namenoderpcaddress=quickstart.cloudera:8020&overwrite=false"
```

**Comment by jrudolph** [comment]
@dinegri using `curl -T` will not create a multipart upload but will include the file verbatim in the request body.

The akka-http code you've shown will be approximately equivalent to

```
curl --form file=@file1 
```

which would be the same as uploading through an html `<form>`.

To get something roughly equivalent to `curl -T` try including the file stream directly in the request entity:

```scala
HttpRequest(...,
  entity = HttpEntity(MediaTypes.`application/octet-stream`, file.length(), FileIO.fromFile(file, chunkSize = 100000))
)
```

**Comment by jrudolph** [comment]
I'm closing this issue for now but feel free to comment or ask to reopen if you still think this is a bug.
