### ISSUE TITLE
SSE unmarshaller should allow an idle timeout

### ISSUE THREAD

**Issue by jroper** [akka/akka-http#1279]
One problem with consuming data from long lived network connections that you never send data on, such as is the case when consuming SSE event streams, is that there's no way to detect if the remote end suddenly disappeared (eg, network partition), since the only way to detect that is to send data upstream and not get a TCP ack back.

Well behaving SSE servers send heartbeats to ensure proxies don't cut them off, this can be used by the client to detect disconnects, and this can be done in Akka streams by inserting an idle timeout into the flow. To do this with the Akka SSE client unmarshaller, the timeout needs to be inserted before the decoder, since the decoder ignores the heartbeats and doesn't emit anything in response to them.  So you can't just attach an idle timeout to the Source produced by the unmarshaller, it has to be the unmarshaller itself that inserts the timeout, before the decoder.  This timeout could perhaps be passed explicitly, or via an implicit timeout parameter.

**Comment by jroper** [comment]
Example solution:

```scala
  implicit def fromEventStream(implicit timeout: Timeout): FromEntityUnmarshaller[Source[ServerSentEvent, NotUsed]] = {
      def unmarshal(entity: HttpEntity) =
        entity
          .withoutSizeLimit
          .dataBytes
          .idleTimeout(timeout.duration)  
          .viaMat(eventStreamParser)(Keep.none)
      Unmarshaller.strict(unmarshal).forContentTypes(`text/event-stream`)
  }
```

Happy to submit a PR if this change is deemed necessary. We could provide a sensible default value for the timeout (5 minutes ?) to maintain source compatibility.

**Comment by jroper** [comment]
@hseeberger does this sound ok to you?

**Comment by hseeberger** [comment]
Sounds like a great idea. PR please.

**Comment by jrudolph** [comment]
It seems that scenario should be covered by the connection-level idle-timeout. Especially on the client side, I don't see why it wouldn't. On the server side, it might take a lot longer until the timeout triggers if you send heartbeats because either the send buffers need to run full so that the connection-level idle-timeout will trigger or the TCP stack will timeout after a lot of retries (see `tcp_retries2`).

So closing this for now.
