### ISSUE TITLE
PoolInterfaceActor should have configurable localAddress

### ISSUE THREAD

**Issue by kuki** [akka/akka-http#1284]
Pool cannot be used on different then default interface. It's only available by Http().outgoingConnection(Https)(host, port, **localAddr**, ccs).
Event the Http().singleRequest doesn't allow to specify localAddr socket.
It would also be nice to provide example on how to re-use created outgoing connections 👍

It would be a nice addition to host-connection-pool configuration. And use in PoolInterfaceActor:

```
  private def initConnectionFlow() = {
    import context.system
    import hcps._
    import setup._

    val connectionFlow = connectionContext match {
      case httpsContext: HttpsConnectionContext ⇒ Http().outgoingConnectionHttps(host, port, httpsContext, None, settings.connectionSettings, setup.log)
      case _                                    ⇒ Http().outgoingConnection(host, port, None, settings.connectionSettings, setup.log)
    }
```

**Comment by jrudolph** [comment]
Hi @kuki, out of curiosity: what is a real-life use case for this? Usually, the OS will choose the right interface for outgoing connection based on the routing table if no local address was given. Is it just to have more control on the port? Or, to use several interfaces if the number of ports isn't enough when creating more than 2^16 connections per target?

In any case, we basically added that feature in 10.0.8 here: https://github.com/akka/akka-http/commit/2c4e299a4283d51501cf7d9780301e08f44a2a94

You can now set the `localAddress` programmatically by adjusting the `ClientConnectionSettings` which you can pass to all of the client's entry methods.

> It would also be nice to provide example on how to re-use created outgoing connections

Just use one of the pool methods and existing connections will be reused.

**Comment by kuki** [comment]
Hi @jrudolph, case it that my application have to use configured interface for communication. Some devices are available through more than one interface and sometimes OS can have bad configuration  and I don't want to depend on it's routing table.

I'll have to bump up my http version to .8 from .4.

For the re-use of outgoingConnection I've managed to do it by using:
```
Http().outgoingConnection(host, port, localAddr, ccs)
case object ComplMsg
Source.actorRef(1, OverflowStrategy.dropNew).via(flow).to(Sink.actorRef(self, ComplMsg)).run()
```

Thanks 👍

**Comment by jrudolph** [comment]
Thanks, @kuki. I'd recommend upgrading to the latest version directly, 10.0.9.

Reusing it like this should work, but then you still have to manage reconnection if the connection fails, etc. Usually using `Http().singleRequest()` is the better solution.
