### ISSUE TITLE
Consolidate java/scala content in akka-http

### ISSUE THREAD

**Issue by richardimaoka** [akka/akka-http#1290]
Like we are doing on akka/akka#23052  "consolidate java/scala content", let's consolidate the java and scala contents in akka-http, too.

Below is the procedure described by @raboof.

The process is as follows:

* Mention in this issue which pages you're planning to merge 
  * Either the Akka maintainers or @richard-imaoka can update the list below
* Compare a file in `docs/src/main/paradox/java/...` with the same one under `docs/src/main/paradox/scala/....` They should cover the same contents, but one is for Java and the other is for Scala. The 'compare files' feature of IntelliJ IDEA is a nice tool for this.
* Update the file in the `scala` folder to contain both the Scala and Java content. You may use:
`@scala` and `@java` directives for inline text
`@@@ div { .group-scala }` for blocks
[code blocks](http://developer.lightbend.com/docs/paradox/latest/features/groups.html) become tabbed
* Replace the 'java' version of the page with a symlink:
  * Remove the old version (`git rm akka-docs/src/main/paradox/java/...`)
  * Create a symlink (`cd akka-docs/src/main/paradox/java; ln -s ../scala/... ...; cd -`)
  * Add the symlink to git (`git add akka-docs/src/main/paradox/java/...`)
Test your changes (`sbt akka-docs/paradox`, see CONTRIBUTING.md for details, check both the Java and Scala versions)

You could look at https://github.com/akka/akka/pull/23039/files as an example - it's probably best to contribute PR's on a page-per-page basis at least at first. Feel free to let us know if you have any questions/problems!

**Comment by richard-imaoka** [comment]
Let me know which one you want to work on, and I'll mark your name for the file!

Under **docs/src/main/paradox/java/http/**
* [ ] client-side/client-https-support.md
* [ ] client-side/connection-level.md
* [ ] client-side/host-level.md
* [ ] client-side/index.md
* [ ] client-side/pool-overflow.md
* [ ] client-side/request-level.md
* [ ] client-side/websocket-support.md
* [ ] common/de-coding.md
* [ ] common/http-model.md
* [ ] common/index.md
* [ ] common/json-support.md
* [ ] common/marshalling.md
* [ ] common/timeouts.md
* [ ] common/unmarshalling.md
* [ ] common/uri-model.md
* [ ] configuration.md
* [ ] handling-blocking-operations-in-akka-http-routes.md
* [ ] implications-of-streaming-http-entity.md
* [ ] index.md
* [ ] introduction.md
* [ ] migration-guide/index.md
* [ ] migration-guide/migration-from-old-http-javadsl.md
* [ ] migration-guide/migration-guide-2.4.x-10.0.x.md
* [ ] routing-dsl/directives/alphabetically.md
* [ ] routing-dsl/directives/basic-directives/cancelRejection.md
* [ ] routing-dsl/directives/basic-directives/cancelRejections.md
* [ ] routing-dsl/directives/basic-directives/extract.md
* [ ] routing-dsl/directives/basic-directives/extractActorSystem.md
* [ ] routing-dsl/directives/basic-directives/extractDataBytes.md
* [ ] routing-dsl/directives/basic-directives/extractExecutionContext.md
* [ ] routing-dsl/directives/basic-directives/extractLog.md
* [ ] routing-dsl/directives/basic-directives/extractMatchedPath.md
* [ ] routing-dsl/directives/basic-directives/extractMaterializer.md
* [ ] routing-dsl/directives/basic-directives/extractParserSettings.md
* [ ] routing-dsl/directives/basic-directives/extractRequest.md
* [ ] routing-dsl/directives/basic-directives/extractRequestContext.md
* [ ] routing-dsl/directives/basic-directives/extractRequestEntity.md
* [ ] routing-dsl/directives/basic-directives/extractSettings.md
* [ ] routing-dsl/directives/basic-directives/extractStrictEntity.md
* [ ] routing-dsl/directives/basic-directives/extractUnmatchedPath.md
* [ ] routing-dsl/directives/basic-directives/extractUri.md
* [ ] routing-dsl/directives/basic-directives/index.md
* [ ] routing-dsl/directives/basic-directives/mapInnerRoute.md
* [ ] routing-dsl/directives/basic-directives/mapRejections.md
* [ ] routing-dsl/directives/basic-directives/mapRequest.md
* [ ] routing-dsl/directives/basic-directives/mapRequestContext.md
* [ ] routing-dsl/directives/basic-directives/mapResponse.md
* [ ] routing-dsl/directives/basic-directives/mapResponseEntity.md
* [ ] routing-dsl/directives/basic-directives/mapResponseHeaders.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResult.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultFuture.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultPF.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultWith.md
* [ ] routing-dsl/directives/basic-directives/mapRouteResultWithPF.md
* [ ] routing-dsl/directives/basic-directives/mapSettings.md
* [ ] routing-dsl/directives/basic-directives/mapUnmatchedPath.md
* [ ] routing-dsl/directives/basic-directives/pass.md
* [ ] routing-dsl/directives/basic-directives/provide.md
* [ ] routing-dsl/directives/basic-directives/recoverRejections.md
* [ ] routing-dsl/directives/basic-directives/recoverRejectionsWith.md
* [ ] routing-dsl/directives/basic-directives/toStrictEntity.md
* [ ] routing-dsl/directives/basic-directives/withExecutionContext.md
* [ ] routing-dsl/directives/basic-directives/withLog.md
* [ ] routing-dsl/directives/basic-directives/withMaterializer.md
* [ ] routing-dsl/directives/basic-directives/withSettings.md
* [ ] routing-dsl/directives/by-trait.md
* [ ] routing-dsl/directives/cache-condition-directives/conditional.md
* [ ] routing-dsl/directives/cache-condition-directives/index.md
* [ ] routing-dsl/directives/coding-directives/decodeRequest.md
* [ ] routing-dsl/directives/coding-directives/decodeRequestWith.md
* [ ] routing-dsl/directives/coding-directives/encodeResponse.md
* [ ] routing-dsl/directives/coding-directives/encodeResponseWith.md
* [ ] routing-dsl/directives/coding-directives/index.md
* [ ] routing-dsl/directives/coding-directives/requestEncodedWith.md
* [ ] routing-dsl/directives/coding-directives/responseEncodingAccepted.md
* [ ] routing-dsl/directives/coding-directives/withPrecompressedMediaTypeSupport.md
* [ ] routing-dsl/directives/cookie-directives/cookie.md
* [ ] routing-dsl/directives/cookie-directives/deleteCookie.md
* [ ] routing-dsl/directives/cookie-directives/index.md
* [ ] routing-dsl/directives/cookie-directives/optionalCookie.md
* [ ] routing-dsl/directives/cookie-directives/setCookie.md
* [ ] routing-dsl/directives/custom-directives.md
* [ ] routing-dsl/directives/debugging-directives/index.md
* [ ] routing-dsl/directives/debugging-directives/logRequest.md
* [ ] routing-dsl/directives/debugging-directives/logRequestResult.md
* [ ] routing-dsl/directives/debugging-directives/logResult.md
* [ ] routing-dsl/directives/execution-directives/handleExceptions.md
* [ ] routing-dsl/directives/execution-directives/handleRejections.md
* [ ] routing-dsl/directives/execution-directives/index.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromBrowseableDirectories.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromBrowseableDirectory.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromDirectory.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromFile.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromResource.md
* [ ] routing-dsl/directives/file-and-resource-directives/getFromResourceDirectory.md
* [ ] routing-dsl/directives/file-and-resource-directives/index.md
* [ ] routing-dsl/directives/file-and-resource-directives/listDirectoryContents.md
* [ ] routing-dsl/directives/file-upload-directives/fileUpload.md
* [ ] routing-dsl/directives/file-upload-directives/index.md
* [ ] routing-dsl/directives/file-upload-directives/uploadedFile.md
* [ ] routing-dsl/directives/form-field-directives/formField.md
* [ ] routing-dsl/directives/form-field-directives/formFieldList.md
* [ ] routing-dsl/directives/form-field-directives/formFieldMap.md
* [ ] routing-dsl/directives/form-field-directives/formFieldMultiMap.md
* [ ] routing-dsl/directives/form-field-directives/index.md
* [ ] routing-dsl/directives/future-directives/completeOrRecoverWith.md
* [ ] routing-dsl/directives/future-directives/index.md
* [ ] routing-dsl/directives/future-directives/onComplete.md
* [ ] routing-dsl/directives/future-directives/onCompleteWithBreaker.md
* [ ] routing-dsl/directives/future-directives/onSuccess.md
* [ ] routing-dsl/directives/header-directives/checkSameOrigin.md
* [ ] routing-dsl/directives/header-directives/headerValue.md
* [ ] routing-dsl/directives/header-directives/headerValueByName.md
* [ ] routing-dsl/directives/header-directives/headerValueByType.md
* [ ] routing-dsl/directives/header-directives/headerValuePF.md
* [ ] routing-dsl/directives/header-directives/index.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValue.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValueByName.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValueByType.md
* [ ] routing-dsl/directives/header-directives/optionalHeaderValuePF.md
* [ ] routing-dsl/directives/host-directives/extractHostName.md
* [ ] routing-dsl/directives/host-directives/host.md
* [ ] routing-dsl/directives/host-directives/index.md
* [ ] routing-dsl/directives/index.md
* [ ] routing-dsl/directives/marshalling-directives/completeWith.md
* [ ] routing-dsl/directives/marshalling-directives/entity.md
* [ ] routing-dsl/directives/marshalling-directives/handleWith.md
* [ ] routing-dsl/directives/marshalling-directives/index.md
* [ ] routing-dsl/directives/method-directives/delete.md
* [ ] routing-dsl/directives/method-directives/extractMethod.md
* [ ] routing-dsl/directives/method-directives/get.md
* [ ] routing-dsl/directives/method-directives/head.md
* [ ] routing-dsl/directives/method-directives/index.md
* [ ] routing-dsl/directives/method-directives/method.md
* [ ] routing-dsl/directives/method-directives/options.md
* [ ] routing-dsl/directives/method-directives/overrideMethodWithParameter.md
* [ ] routing-dsl/directives/method-directives/patch.md
* [ ] routing-dsl/directives/method-directives/post.md
* [ ] routing-dsl/directives/method-directives/put.md
* [ ] routing-dsl/directives/misc-directives/extractClientIP.md
* [ ] routing-dsl/directives/misc-directives/index.md
* [ ] routing-dsl/directives/misc-directives/rejectEmptyResponse.md
* [ ] routing-dsl/directives/misc-directives/requestEntityEmpty.md
* [ ] routing-dsl/directives/misc-directives/requestEntityPresent.md
* [ ] routing-dsl/directives/misc-directives/selectPreferredLanguage.md
* [ ] routing-dsl/directives/misc-directives/validate.md
* [ ] routing-dsl/directives/misc-directives/withoutSizeLimit.md
* [ ] routing-dsl/directives/misc-directives/withSizeLimit.md
* [ ] routing-dsl/directives/parameter-directives/index.md
* [ ] routing-dsl/directives/parameter-directives/parameter.md
* [ ] routing-dsl/directives/parameter-directives/parameterMap.md
* [ ] routing-dsl/directives/parameter-directives/parameterMultiMap.md
* [ ] routing-dsl/directives/parameter-directives/parameters.md
* [ ] routing-dsl/directives/parameter-directives/parameterSeq.md
* [ ] routing-dsl/directives/path-directives/index.md
* [ ] routing-dsl/directives/path-directives/path.md
* [ ] routing-dsl/directives/path-directives/pathEnd.md
* [ ] routing-dsl/directives/path-directives/pathEndOrSingleSlash.md
* [ ] routing-dsl/directives/path-directives/pathPrefix.md
* [ ] routing-dsl/directives/path-directives/pathPrefixTest.md
* [ ] routing-dsl/directives/path-directives/pathSingleSlash.md
* [ ] routing-dsl/directives/path-directives/pathSuffix.md
* [ ] routing-dsl/directives/path-directives/pathSuffixTest.md
* [ ] routing-dsl/directives/path-directives/rawPathPrefix.md
* [ ] routing-dsl/directives/path-directives/rawPathPrefixTest.md
* [ ] routing-dsl/directives/path-directives/redirectToNoTrailingSlashIfPresent.md
* [ ] routing-dsl/directives/path-directives/redirectToTrailingSlashIfMissing.md
* [ ] routing-dsl/directives/path-directives.md
* [ ] routing-dsl/directives/range-directives/index.md
* [ ] routing-dsl/directives/range-directives/withRangeSupport.md
* [ ] routing-dsl/directives/respond-with-directives/index.md
* [ ] routing-dsl/directives/respond-with-directives/respondWithDefaultHeader.md
* [ ] routing-dsl/directives/respond-with-directives/respondWithDefaultHeaders.md
* [ ] routing-dsl/directives/respond-with-directives/respondWithHeader.md
* [ ] routing-dsl/directives/respond-with-directives/respondWithHeaders.md
* [ ] routing-dsl/directives/route-directives/complete.md
* [ ] routing-dsl/directives/route-directives/failWith.md
* [ ] routing-dsl/directives/route-directives/index.md
* [ ] routing-dsl/directives/route-directives/redirect.md
* [ ] routing-dsl/directives/route-directives/reject.md
* [ ] routing-dsl/directives/scheme-directives/extractScheme.md
* [ ] routing-dsl/directives/scheme-directives/index.md
* [ ] routing-dsl/directives/scheme-directives/scheme.md
* [ ] routing-dsl/directives/security-directives/authenticateBasic.md
* [ ] routing-dsl/directives/security-directives/authenticateBasicAsync.md
* [ ] routing-dsl/directives/security-directives/authenticateBasicPF.md
* [ ] routing-dsl/directives/security-directives/authenticateBasicPFAsync.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2Async.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2PF.md
* [ ] routing-dsl/directives/security-directives/authenticateOAuth2PFAsync.md
* [ ] routing-dsl/directives/security-directives/authenticateOrRejectWithChallenge.md
* [ ] routing-dsl/directives/security-directives/authorize.md
* [ ] routing-dsl/directives/security-directives/authorizeAsync.md
* [ ] routing-dsl/directives/security-directives/extractCredentials.md
* [ ] routing-dsl/directives/security-directives/index.md
* [ ] routing-dsl/directives/timeout-directives/index.md
* [ ] routing-dsl/directives/timeout-directives/withoutRequestTimeout.md
* [ ] routing-dsl/directives/timeout-directives/withRequestTimeout.md
* [ ] routing-dsl/directives/timeout-directives/withRequestTimeoutResponse.md
* [ ] routing-dsl/directives/websocket-directives/extractOfferedWsProtocols.md
* [ ] routing-dsl/directives/websocket-directives/extractUpgradeToWebSocket.md
* [ ] routing-dsl/directives/websocket-directives/handleWebSocketMessages.md
* [ ] routing-dsl/directives/websocket-directives/handleWebSocketMessagesForOptionalProtocol.md
* [ ] routing-dsl/directives/websocket-directives/handleWebSocketMessagesForProtocol.md
* [ ] routing-dsl/directives/websocket-directives/index.md
* [ ] routing-dsl/exception-handling.md
* [ ] routing-dsl/HttpApp.md
* [ ] routing-dsl/index.md
* [ ] routing-dsl/marshalling.md
* [ ] routing-dsl/overview.md
* [ ] routing-dsl/rejections.md
* [ ] routing-dsl/routes.md
* [ ] routing-dsl/source-streaming-support.md
* [ ] routing-dsl/testkit.md
* [ ] server-side/low-level-server-side-api.md
* [ ] server-side/websocket-support.md
* [ ] server-side-https-support.md

and

* [ ] docs/src/main/paradox/java.md

**Comment by jrudolph** [comment]
Thanks a lot @richard-imaoka for getting this initiative started. I think we might want to exclude the directives details pages for now. One reason is that they don't all map 1-to-1 and the other is that the other documentation is currently more important to be merged.

**Comment by richard-imaoka** [comment]
OK sure, removed the directives details pages.

**Comment by jrudolph** [comment]
:+1:, thanks. Let's start with the other ones.

**Comment by jlprat** [comment]
What if a whole section should be on the Scala version but not on the Java one (or vice-versa)? What's the way to do it?

**Comment by raboof** [comment]
@jlprat Unfortunately we don't have a way to make ToC elements conditional yet, see https://github.com/lightbend/paradox/issues/128

**Comment by jlprat** [comment]
OK, from the top of my head, there are a couple of pages where some sections are missing on Java (custom headers for example)

**Comment by jrudolph** [comment]
Yes, there will probably some difficulties but that shouldn't stop us from starting the work on the easier cases.

**Comment by jlprat** [comment]
Indeed! I will take one of them later today

**Comment by jlprat** [comment]
I take `HttpApp`

**Comment by jonas** [comment]
Did
- client-side/client-https-support.md
- client-side/client-transport.md
- client-side/connection-level.md
- common/timeouts.md

**Comment by jonas** [comment]
I wrote a small script to help track status and to do the initial work of merging a page:

```
>  scripts/doc-merge.sh status
client-side/client-https-support.md                          : Merged
client-side/client-transport.md                              : Merged
client-side/connection-level.md                              : Merged
client-side/host-level.md                                    : 54 insertions(+), 18 deletions(-)
client-side/index.md                                         : 5 insertions(+), 1 deletion(-)
client-side/pool-overflow.md                                 : Merged
client-side/request-level.md                                 : 21 insertions(+), 30 deletions(-)
client-side/websocket-support.md                             : 23 insertions(+), 27 deletions(-)
common/de-coding.md                                          : 2 insertions(+), 2 deletions(-)
common/http-model.md                                         : 97 insertions(+), 84 deletions(-)
common/index.md                                              : 2 insertions(+), 1 deletion(-)
common/json-support.md                                       : 35 insertions(+), 13 deletions(-)
common/marshalling.md                                        : 6 insertions(+), 9 deletions(-)
common/timeouts.md                                           : Merged
common/unmarshalling.md                                      : 6 insertions(+), 12 deletions(-)
common/uri-model.md                                          : 22 insertions(+), 26 deletions(-)
common/xml-support.md                                        : No java version
migration-guide/index.md                                     : Merged
migration-guide/migration-from-old-http-javadsl.md           : Merged
migration-guide/migration-from-spray.md                      : Merged
migration-guide/migration-guide-10.0.x.md                    : Merged
migration-guide/migration-guide-2.4.x-10.0.x.md              : Merged
routing-dsl/HttpApp.md                                       : Merged
routing-dsl/case-class-extraction.md                         : No java version
routing-dsl/exception-handling.md                            : 16 insertions(+), 15 deletions(-)
routing-dsl/index.md                                         : 31 insertions(+), 12 deletions(-)
routing-dsl/marshalling.md                                   : No scala version
routing-dsl/overview.md                                      : 31 insertions(+), 20 deletions(-)
routing-dsl/path-matchers.md                                 : No java version
routing-dsl/rejections.md                                    : 34 insertions(+), 27 deletions(-)
routing-dsl/routes.md                                        : 63 insertions(+), 54 deletions(-)
routing-dsl/source-streaming-support.md                      : 69 insertions(+), 21 deletions(-)
routing-dsl/testkit.md                                       : 104 insertions(+), 72 deletions(-)
security/2016-09-30-windows-directory-traversal.md           : Merged
security/2017-01-23-denial-of-service-via-leak-on-unconsumed-closed-connections.md : Merged
security/2017-05-03-illegal-media-range-in-accept-header-causes-stackoverflowerror.md : Merged
server-side/low-level-server-side-api.md                     : No scala version
server-side/websocket-support.md                             : No scala version
```

[doc-merge.sh.txt](https://github.com/akka/akka-http/files/1176787/doc-merge.sh.txt)

**Comment by jlprat** [comment]
The 2 last ones (`server-side/...`) have the Scala equivalent 1 level up.

**Comment by jonas** [comment]
@jlprat Is the plan to move the Scala pages into the `server-side` directory?

**Comment by jlprat** [comment]
I have no strong opinion about it, but I'd say better move the Java ones 1 level up, as the folder server-side makes not much sense with only those 2 files

**Comment by jlprat** [comment]
For the page `Implications of the Streaming Nature...` I need https://github.com/akka/akka-http/pull/1322 to be merged as it references `server-side/low-level-server-side-api.md`

**Comment by ktoso** [comment]
Marked request level client as done by @jlprat

**Comment by jonas** [comment]
Added `sse-support.md` with pending PR in #1349

**Comment by jlprat** [comment]
BTW, what's the plan for the Java docs for common Marshalling and Unmarshalling. They have a big nice TODO on the header. Shall we merge, and then do the overhaul?
http://doc.akka.io/docs/akka-http/current/java/http/common/marshalling.html
http://doc.akka.io/docs/akka-http/current/java/http/common/unmarshalling.html

**Comment by atiqsayyed** [comment]
Can I pick these??

-  routing-dsl/routes.md
-  routing-dsl/source-streaming-support.md
-  routing-dsl/testkit.md

**Comment by jlprat** [comment]
Sure!
Thanks @atiqsayyed

**Comment by jonas** [comment]
Will take the remaining pages in common.

**Comment by jlprat** [comment]
Do we have any way to have a java/scala-dependent TOC entry?

**Comment by raboof** [comment]
I'm afraid we ended up not needing that yet for the Akka docs so that's still an open issue (https://github.com/lightbend/paradox/issues/128).

**Comment by jlprat** [comment]
We need that for http://doc.akka.io/docs/akka-http/current/java/http/routing-dsl/index.html vs http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/index.html
"Case Class Extraction" only exists on Scala. Any suggestion?

**Comment by jonas** [comment]
Yay, we are down to ~9 pages remaining.

@atiqsayyed How is going with merging the Routing DSL pages?

**Comment by atiqsayyed** [comment]
@jonas should be done by tomorrow :)

**Comment by ktoso** [comment]
Thanks @atiqsayyed for handling `source-streaming-support.md`!  Just a few left :)

**Comment by raboof** [comment]
@jlprat I think I found a nice solution for java/scala-specific ToC entries, https://github.com/akka/akka-http/pull/1600

**Comment by jlprat** [comment]
Cool! I will take a look!

**Comment by raboof** [comment]
Just about there for the 'regular' documentation, seems like it's time to start tackling the directives now. I've already scripted some common differences, but there's plenty left:

[x] routing-dsl/directives/cookie-directives/setCookie.md
[x] routing-dsl/directives/cookie-directives/deleteCookie.md
[x] routing-dsl/directives/cookie-directives/cookie.md
[x] routing-dsl/directives/cookie-directives/optionalCookie.md
[x] routing-dsl/directives/scheme-directives/extractScheme.md
[x] routing-dsl/directives/scheme-directives/scheme.md
[x] routing-dsl/directives/cache-condition-directives/conditional.md
[x] routing-dsl/directives/caching-directives/alwaysCache.md
[x] routing-dsl/directives/caching-directives/cachingProhibited.md
[x] routing-dsl/directives/header-directives/headerValuePF.md
[x] routing-dsl/directives/websocket-directives/handleWebSocketMessages.md
[x] routing-dsl/directives/websocket-directives/handleWebSocketMessagesForProtocol.md
[x] routing-dsl/directives/path-directives/redirectToNoTrailingSlashIfPresent.md
[x] routing-dsl/directives/path-directives/redirectToTrailingSlashIfMissing.md
[x] routing-dsl/directives/path-directives/pathSuffixTest.md
[x] routing-dsl/directives/path-directives/ignoreTrailingSlash.md
[x] routing-dsl/directives/misc-directives/requestEntityPresent.md
[x] routing-dsl/directives/misc-directives/requestEntityEmpty.md
[x] routing-dsl/directives/misc-directives/selectPreferredLanguage.md
[x] routing-dsl/directives/misc-directives/withoutSizeLimit.md
[x] routing-dsl/directives/file-upload-directives/uploadedFile.md
[x] routing-dsl/directives/route-directives/reject.md
[x] routing-dsl/directives/route-directives/failWith.md
[x] routing-dsl/directives/file-and-resource-directives/getFromBrowseableDirectories.md
[x] routing-dsl/directives/file-and-resource-directives/getFromDirectory.md
[x] routing-dsl/directives/file-and-resource-directives/getFromFile.md
[x] routing-dsl/directives/coding-directives/withPrecompressedMediaTypeSupport.md
[x] routing-dsl/directives/coding-directives/encodeResponse.md
[x] routing-dsl/directives/coding-directives/decodeRequest.md
[x] routing-dsl/directives/coding-directives/decodeRequestWith.md
[x] routing-dsl/directives/coding-directives/encodeResponseWith.md
[x] routing-dsl/directives/coding-directives/responseEncodingAccepted.md
[x] routing-dsl/directives/timeout-directives/withRequestTimeoutResponse.md
[x] routing-dsl/directives/timeout-directives/withoutRequestTimeout.md
[x] routing-dsl/directives/execution-directives/handleRejections.md
[x] routing-dsl/directives/execution-directives/handleExceptions.md
[x] routing-dsl/directives/respond-with-directives/respondWithHeaders.md
[x] routing-dsl/directives/respond-with-directives/respondWithDefaultHeader.md
[x] routing-dsl/directives/respond-with-directives/respondWithHeader.md
[x] routing-dsl/directives/basic-directives/extractMatchedPath.md
[x] routing-dsl/directives/basic-directives/extractMaterializer.md
[x] routing-dsl/directives/basic-directives/extractUri.md
[x] routing-dsl/directives/basic-directives/extractActorSystem.md
[x] routing-dsl/directives/basic-directives/extractSettings.md
[x] routing-dsl/directives/basic-directives/mapUnmatchedPath.md
[x] routing-dsl/directives/basic-directives/extractStrictEntity.md
[x] routing-dsl/directives/basic-directives/extractRequestEntity.md
[x] routing-dsl/directives/basic-directives/extractExecutionContext.md
[x] routing-dsl/directives/basic-directives/extractRequestContext.md
[x] routing-dsl/directives/basic-directives/cancelRejection.md
[x] routing-dsl/directives/basic-directives/cancelRejections.md
[x] routing-dsl/directives/basic-directives/withMaterializer.md
[x] routing-dsl/directives/basic-directives/withSettings.md
[x] routing-dsl/directives/basic-directives/pass.md
[x] routing-dsl/directives/basic-directives/mapInnerRoute.md
[x] routing-dsl/directives/basic-directives/toStrictEntity.md
[x] routing-dsl/directives/basic-directives/withLog.md
[ ] routing-dsl/directives/cookie-directives/setCookie.md
[ ] routing-dsl/directives/cookie-directives/deleteCookie.md
[ ] routing-dsl/directives/cookie-directives/cookie.md
[ ] routing-dsl/directives/cookie-directives/optionalCookie.md
[ ] routing-dsl/directives/scheme-directives/extractScheme.md
[ ] routing-dsl/directives/scheme-directives/scheme.md
[ ] routing-dsl/directives/cache-condition-directives/conditional.md
[ ] routing-dsl/directives/caching-directives/alwaysCache.md
[ ] routing-dsl/directives/caching-directives/cachingProhibited.md
[ ] routing-dsl/directives/header-directives/headerValuePF.md
[ ] routing-dsl/directives/websocket-directives/handleWebSocketMessages.md
[ ] routing-dsl/directives/websocket-directives/handleWebSocketMessagesForProtocol.md
[ ] routing-dsl/directives/path-directives/redirectToNoTrailingSlashIfPresent.md
[ ] routing-dsl/directives/path-directives/redirectToTrailingSlashIfMissing.md
[ ] routing-dsl/directives/path-directives/pathSuffixTest.md
[ ] routing-dsl/directives/path-directives/ignoreTrailingSlash.md
[ ] routing-dsl/directives/misc-directives/requestEntityPresent.md
[ ] routing-dsl/directives/misc-directives/requestEntityEmpty.md
[ ] routing-dsl/directives/misc-directives/selectPreferredLanguage.md
[ ] routing-dsl/directives/misc-directives/withoutSizeLimit.md
[ ] routing-dsl/directives/file-upload-directives/uploadedFile.md
[ ] routing-dsl/directives/route-directives/reject.md
[ ] routing-dsl/directives/route-directives/failWith.md
[ ] routing-dsl/directives/file-and-resource-directives/getFromBrowseableDirectories.md
[ ] routing-dsl/directives/file-and-resource-directives/getFromDirectory.md
[ ] routing-dsl/directives/file-and-resource-directives/getFromFile.md
[ ] routing-dsl/directives/coding-directives/withPrecompressedMediaTypeSupport.md
[ ] routing-dsl/directives/coding-directives/encodeResponse.md
[ ] routing-dsl/directives/coding-directives/decodeRequest.md
[ ] routing-dsl/directives/coding-directives/decodeRequestWith.md
[ ] routing-dsl/directives/coding-directives/encodeResponseWith.md
[ ] routing-dsl/directives/coding-directives/responseEncodingAccepted.md
[ ] routing-dsl/directives/timeout-directives/withRequestTimeoutResponse.md
[ ] routing-dsl/directives/timeout-directives/withoutRequestTimeout.md
[ ] routing-dsl/directives/execution-directives/handleRejections.md
[ ] routing-dsl/directives/execution-directives/handleExceptions.md
[ ] routing-dsl/directives/respond-with-directives/respondWithHeaders.md
[ ] routing-dsl/directives/respond-with-directives/respondWithDefaultHeader.md
[ ] routing-dsl/directives/respond-with-directives/respondWithHeader.md
[ ] routing-dsl/directives/basic-directives/extractMatchedPath.md
[ ] routing-dsl/directives/basic-directives/extractMaterializer.md
[ ] routing-dsl/directives/basic-directives/extractUri.md
[ ] routing-dsl/directives/basic-directives/extractActorSystem.md
[ ] routing-dsl/directives/basic-directives/extractSettings.md
[ ] routing-dsl/directives/basic-directives/mapUnmatchedPath.md
[ ] routing-dsl/directives/basic-directives/extractStrictEntity.md
[ ] routing-dsl/directives/basic-directives/extractRequestEntity.md
[ ] routing-dsl/directives/basic-directives/extractExecutionContext.md
[ ] routing-dsl/directives/basic-directives/extractRequestContext.md
[ ] routing-dsl/directives/basic-directives/cancelRejection.md
[ ] routing-dsl/directives/basic-directives/cancelRejections.md
[ ] routing-dsl/directives/basic-directives/withMaterializer.md
[ ] routing-dsl/directives/basic-directives/withSettings.md
[ ] routing-dsl/directives/basic-directives/pass.md
[ ] routing-dsl/directives/basic-directives/mapInnerRoute.md
[ ] routing-dsl/directives/basic-directives/toStrictEntity.md
[ ] routing-dsl/directives/basic-directives/withLog.md

**Comment by jonas** [comment]
@raboof I suggest to close this ticket and track consolidation of the routing DSL docs in a new ticket since the history is getting quite long.

**Comment by raboof** [comment]
@jonas works for me! @richardimaoka you want to help keep inventory of progress again?

**Comment by raboof** [comment]
@richardimaoka did you see the ping above? :)

**Comment by richardimaoka** [comment]
Sorry I misses the earlier message. I didn’t fully go thorough the conversation in detail but it’s about closing this issue and open a new one? Fine for me then.

**Comment by raboof** [comment]
@richardimaoka Indeed! Do you want to create the ticket again?

**Comment by richardimaoka** [comment]
What's the most recent status? Is it tracked in https://github.com/akka/akka-http/issues/1290#issuecomment-316255843, or should I run @jonas's script to check the status?

**Comment by raboof** [comment]
I think that comment should be accurate - I haven't run the script myself

**Comment by richardimaoka** [comment]
OK, here you go ! #1624
