### ISSUE TITLE
HttpChallenge rendering is broken if realm parameter is None

### ISSUE THREAD

**Issue by jostick** [akka/akka-http#1295]
A challenge like this

```scala
HttpChallenge("Bearer", None, Map("error" ->"invalid_token", "error_description" -> "The access token expired"))
```

is rendered as 
`Bearer,error=invalid_token,error_description="The access token expired"`

Expected behaviour: The header value should be
`Bearer error=invalid_token,error_description="The access token expired"`

Realm is not required by RF7235 and even in the constructor the realm is an Option. I'm using akka-http 10.0.9 but HttpChallenge seems to be unchanged in master.

**Comment by jrudolph** [comment]
Yes, seems that was changed in https://github.com/akka/akka/pull/21043/files without adding tests for the new case.

**Comment by jrudolph** [comment]
Seems simple enough to fix, though. Can you open a PR? Needs a test case in akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala.

**Comment by jostick** [comment]
Yes, I'll make a PR. Probably tomorrow.
