### ISSUE TITLE
HttpApp Simplify `startServer` overloaded methods

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1300]
Currently we have quite some overloaded methods on `startServer`. Ideally these should be simplified and only a couple of them should be offered. Probably:
- `startServer(host, port)`
- `startServer(host, port, system)`

For any other type of customisation/configuration, a builder patter could be used. As an example:
```
myHttApp
  .withSettings(...)
  .withSystem(...)
  .withRejectionHandler(...)
  .at(host, port)
  .startServer()
```

**Comment by jrudolph** [comment]
:+1: from me

**Comment by Prithvirajbilla** [comment]
I'd like to take this one. But I see this is an old ticket. 

LMK if this is still relevant.

**Comment by jlprat** [comment]
It's up for picking. If you find a nice way to implement it, go ahead.
Please not that despite the fact that the class is marked as `@ApiMayChange` we still try to keep binary compatibility if possible.

**Comment by jlprat** [comment]
Not needed anymore
