### ISSUE TITLE
Future Akka HTTP Versioning And Compatibility

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1305]
Akka HTTP 10.0.0 was released in November 2016. Since then it has seen a total of currently 10 patch releases that included changes of various sizes and scopes. Some delivered critical security bug fixes, most fixed smaller issues and introduced or improved documentation. In some releases we introduced new features.

From the beginning, our goals have been

 * incremental improvements and fixes
 * maintaining binary compatibility
 * improving stability

We have not always succeeded in all of those goals. There were regressions and sometimes we introduced changes more aggeressively than expected. On the other hand, we tried really hard to stay compatible and were conservative about many changes which at times might have slowed down progress a bit. Overall we are quite happy with our successes so far for this first stable release of Akka HTTP.

Going forward, we have to decide how to structure upcoming releases. We want to keep achieving the above goals but also understand that some users would like to see an even more conservative release scheme. On the other hand, each extra version to maintain takes time from us that we could use otherwise to improve Akka HTTP in other ways. 

We considered a few alternatives and came up with a versioning scheme that is very similar with Akka's existing versioning scheme. Here are the details in a nutshell:

 * Starting from 10.1.0, there will be two active release branches:
   * The "current" release line (in master), where we will basically continue to evolve Akka HTTP in the same way as currently. New features will introduced here incrementally.
   * The "previous" release line (in a release-10.x branch), where the focus is on stability. We will continue to maintain the previous release by fixing serious bugs but it will not see new features. Previous releases will see less frequent releases over time.
 * It is planned to rotate versions in an annual fashion. This would mean that we strive for a 10.1.0 release this fall, moving the 10.0.x series over into maintenance mode, making it the "previous" release. The former "previous" release has reached its end of life at this point (not applicable this year). This way every release line is supported for two years.
 * We will keep binary backwards compatibility between previous and current release. Exempt from this guarantee are APIs marked as `@InternalAPI` or `@ApiMayChange`. Also, in the "current" release line, we might decide to introduce minor binary compatibilities when it seems likely that no or few users will be affected if benefits outweigh the costs. Public stable API symbols may be deprecated at any time (with workarounds or replacements).
 * We currently do not intend to break binary compatibility, i.e. no binary incompatible 11.x.y release is currently planned. Such a release would split up our user base and would pose serious downstream library dependency issues.
 * One question is which Akka versions to support and which to build and test against. We want to support all active Akka versions (currently 2.4.x and 2.5.x) with the same codebase (#821). We are considering to make Akka a "provided" dependency to emphasize that you are not forced to a particular version. We might have to rely on hacks to make use of 2.5.x features (or, going forward, any version newer than the oldest actively maintained Akka version). We should introduce testing of the binaries against all active versions of Akka (#826).

@akka/akka-http-team WDYT?

**Comment by jlprat** [comment]
When you say:
> We will keep binary backwards compatibility between previous and current release

You mean between 10.0.x and 10.1.x or between 10.1.{x} and 10.1.{x+1}. I understood is the latter, but I wanted to be sure.

**Comment by ktoso** [comment]
It means we propose to adopt, and stay with the successful scheme that Akka is on since 2.3->2.4->2.5 - all those are binary compatible, with the exception of ApiMayChange / TestKits / InternalApi or removals of deprecated things if a thing was deprecated for one full minor release cycle [a full x in 10.x in that sense).

In other words, we believe we can get away with keeping strong compatibility, same as Akka itself managed to for the last years and anticipate a lot of benefits for the wider ecosystem thanks to that.

**Comment by jlprat** [comment]
Makes sense. Thanks!

**Comment by sarahgerweck** [comment]
I'm the one who filed the "10.0.8 misnumbered" issue, in part to try to make sure these questions were being considered. I'm not a committer, but I do ship complex enterprise software on Akka HTTP. My opinions are just that: opinions—but perhaps they'll be useful.

First, I agree completely that Akka HTTP has done a great job at being both stable and compatible between version. I've been very impressed at how relatively painless it was to migrate from Spray and how easily the complex project I run has moved between different versions of Akka HTTP (with the exception of the 10.0.8 issues).

Next, I'd say that for a project as young as Akka HTTP, restricting the changes to only one minor release per year feels _very_ conservative. I agree that Akka HTTP needs to evolve in a deliberate manner, but probably not quite to the same degree that Akka Core does.

I also think that deciding in advance that you're only going to bump the minor number once per year creates a strong incentive to fudge on the question of what's going to affect "few users."

My view remains that 10.0.8 really should have been called 10.1.0. `ContentType` is not an `InternalAPI` or `ApiMayChange`, so this change would not be allowed under your criteria except under the "few users" rationale. I think it's fair to say that this change probably actually affected a substantial portion of users until some additional changes were made in 10.0.9.

If it had been numbered 10.1.0 to indicate that there was a more substantial change involved, people would have been less surprised that the change to a public API had repercussions beyond those that were expected. (Bugs happen in any project and I'm not suggesting that this was a disaster—just a moment for reflection & discussion.)

I'm happy with how the Akka HTTP project has gone. However, I would prefer to see a 10.1 come sooner than yearly if it means a) a potentially disruptive change is not labeled as a patch release or b) high-value features like more HTTP/2 support are integrated more quickly.

Either way, thanks for all your hard work. I've said my peace now 😄 .

**Comment by jrudolph** [comment]
> One question is which Akka versions to support and which to build and test against. We want to support all active Akka versions (currently 2.4.x and 2.5.x) with the same codebase.

I wonder if that still makes sense with the release times of Akka and Akka HTTP minor releases not being in sync. Could we consider dropping Akka 2.4 support with Akka HTTP 10.1.0? That would at least allow us to get rid of the duplicate encoding / decoding code since we now have compression support in Akka 2.5.

**Comment by ktoso** [comment]
Timing wise it would make sense to drop supporting 2.4 in 10.1.0, since Akka 2.4 is end of life after December.

**Comment by jrudolph** [comment]
Yep, good point.

**Comment by jrudolph** [comment]
Closing, we'll track the next steps for 10.1.x in #1645.
