### ISSUE TITLE
Rewrite host connection pool as single GraphStage

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1312]
As far as I can see that should remove lots of the stream related bugs. The custom GraphStage should contain all logic from `PoolInterfaceActor`, `PoolConductor`, `PoolSlot`. The external interface should probably be a `FlowShape[HttpRequest, HttpResponse]`. The `PoolMasterActor` can then use that instead of sending messages to the current `PoolInterfaceActor`.

I guess in the best case, we would make this new implementation available under a feature flag depending on our confidence on getting it right.

**Comment by tomrf1** [comment]
This sounds like an interesting one.
The `PoolInterfaceActor` currently has a request buffer with size `max-open-requests`. Is the intention to continue using the buffer, inside the new GraphStage? (Perhaps as a [rate decoupled graph stage](https://doc.akka.io/docs/akka/2.5.6/scala/stream/stream-customize.html#rate-decoupled-graph-stages)).
I'm not sure what the reason for the buffering here is. Why not just backpressure all the way and let the user decide whether or not to buffer?

**Comment by jrudolph** [comment]
@tomrf1, good point. The reason for the buffer is that requests can always be pushed towards a pool by running them via `Http.singleRequest`. I think previously there was also another concern that new stream materializations created by `Http.cachedHostConnectionPool` or `Http.superPool` also need some buffer space because a pool cannot know from which of those materializations to request from, so it requests from all of them.

I think we might want to separate the effort into a part of just rewriting `PoolConductor`, `PoolFlow`, and `PoolSlot` leaving `PoolInterfaceActor` as it is.

Rewriting `PoolInterfaceActor` into something else could be another step in the effort.

**Comment by jrudolph** [comment]
The new pool implementation will be available in 10.0.11 under a flag. I'm closing this one in favor of follow up tickets to flesh out details of behavior in the new implementation when it got some more testing.

**Comment by benjamingeer** [comment]
Is the new pool implementation still available only under a flag in 10.1.1, and if so, what's the flag? And does it resolve #1459?

**Comment by raboof** [comment]
The new host connection pool is the default since [10.1.0](https://doc.akka.io/docs/akka-http/current/release-notes/10.1.x.html#10-1-0). I'm not familiar enough with #1459 to say whether it is expected to resolve #1459.
