### ISSUE TITLE
[Failed] HttpsProxyGraphStageSpec .A ProxyGraphStage should send CONNECT message with ProxyAuth header and then forward incoming messages

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1319]
Jenkins output:
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1384/testReport/junit/akka.http.impl.engine.client/HttpsProxyGraphStageSpec/A_ProxyGraphStage_should_send_CONNECT_message_with_ProxyAuth_header_and_then_forward_incoming_messages/

**Comment by ktoso** [comment]
Seems like a bug in test where I merged something today.
Thanks! Tests were good so I wonder what happened (I've run all tests hm). 
Will fix this
