### ISSUE TITLE
An official way to modify the http Route information?

### ISSUE THREAD

**Issue by Birdflying1005** [akka/akka-http#1323]
Hi, 

I am wondering is it impossible to provide an API to modify the http route information dynamically?

Sean WANG

**Comment by Birdflying1005** [comment]
My purpose is to change the route rule after the http server started.

**Comment by jonas** [comment]
Please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/akka-user) or in the [Gitter chat room](https://gitter.im/akka/akka) as they are better suited for discussions.

Akka HTTP provides several ways to dynamically change the routing behaviour. One possibility is to use [mapInnerRoute](http://doc.akka.io/docs/akka-http/10.0.9/scala/http/routing-dsl/directives/basic-directives/mapInnerRoute.html#mapinnerroute) to conditionally run one route or another.
