### ISSUE TITLE
server-side idle timeout should not fire with active requests for socket

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1340]
<a href="https://github.com/rdmoore"><img src="https://avatars1.githubusercontent.com/u/4184640?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rdmoore](https://github.com/rdmoore)**
_Monday Aug 07, 2017 at 16:29 GMT_
_Originally opened as https://github.com/akka/akka/issues/23486_

----

If request-timeout exceeds idle-timeout - e.g., 

>  akka.http.server.request-timeout=10 minutes 
> akka.http.server.idle-timeout=60 seconds

client will get a socket disconnect `Recv failure: Connection reset by peer` while waiting for a long running response from the server.
This seemed to tie these two parameters together in an undesirable way. I would prefer that a socket for which there are outstanding, not-yet-timed-out requests being processed to be busy, not idle.

**Comment by ktoso** [comment]
<a href="https://github.com/jlprat"><img src="https://avatars0.githubusercontent.com/u/3337739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jlprat](https://github.com/jlprat)**
_Monday Aug 07, 2017 at 16:32 GMT_

----

Hi @rdmoore thanks for the report. This repository is, however, for Akka. Akka HTTP has moved, since some months, to its own repository: https://github.com/akka/akka-http

**Comment by jrudolph** [comment]
I'd say this is as designed. The idle-timeout is a very low-level tool to prevent that inactive connections stay around for too long for whatever reason. I agree that it is a bit weird that it even closes the connection if the server does not come up with a response in time (which is also covered by the request-timeout).

Changing the idle-timeout to take the request state into account is actually quite hard as the idle-timeout sits in a place where it doesn't have this information available.

**Comment by jrudolph** [comment]
As a workaround I'd suggest increasing the idle-timeout.

**Comment by jrudolph** [comment]
Closing for now as we are not going to change the behavior for now.
