### ISSUE TITLE
Failure in HttpServerSpec: expected 200, got 503

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1376]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1465/testReport/junit/akka.http.impl.engine.server/HttpServerSpec/The_server_implementation_should_support_request_timeouts_which_are_programmatically_increased__not_expiring_/

Might be related to #595 but does not appear to be quite the same.

**Comment by jonas** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1574/testReport/junit/akka.http.impl.engine.server/HttpServerSpec/The_server_implementation_should_support_request_timeouts_which_are_programmatically_increased__not_expiring_/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/42//consoleFull

**Comment by jrudolph** [comment]
Didn't happen for a long time.
