### ISSUE TITLE
``Uri.withQuery`` does not percentage-encode

### ISSUE THREAD

**Issue by angiolep** [akka/akka-http#1379]
I ran the following application against ``akka-http_2.11-10.0.9`` with the purpose to generate an URI to get the authorization code from an OAuth2 authorization server.

```
import akka.http.scaladsl.model.Uri
import akka.http.scaladsl.model.Uri.Query

object Issue extends App {

  val uri = Uri("http://oauth2.server.net/authorize").withQuery(Query(
    "redirect_uri" -> "http://oauth2.client.net/callback"
  ))

  assert(uri.rawQueryString.get == "http://oauth2.server.net/authorize?redirect_uri=http%3A%2F%2Foauth2.client.net%2Fcallback")
}
```

Unfortunately the assertion throws expcetion. Please bear in mind that I am not parsing an existing URI but rather generating one with a query string which I expect to be properly percentage-encoded (a.k.a. URL-encoded). The query string I'm testing with clearly contains reserved characters, such as ``:`` (colon) and ``/`` (slash), in the values of its ``redirect_uri`` property ... but the above Akka-based code does not perform any percentage-encode as programmers would intuitively expect to happen.

I had a look at the Akka internals and understood that the ``Uri.withQuery`` is just delegating to ``Query.toString`` which in turn delegates to  ``UriRendering.QueryRenderer.renderQuery``. The existing rendering implementation doesn't seem to perform the percentage encode operation.

It is not clear when, where and if the percentage encode operation is performed within the current Akka implementation. As it stands now, the API behaviour is quite confusing.

Could this issue be linked to #1280?

**Comment by jrudolph** [comment]
Hi @angiolep, thanks for the report.

According to https://tools.ietf.org/html/rfc3986#appendix-A both `/` and `:` are allowed in queries and don't need to be percent encoded:

```
   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
   query         = *( pchar / "/" / "?" )
```

I checked it with a browser which also doesn't percent encode these characters. So, I'd say everything works as expected.

Are there any other specifications that would suggest another encoding?

**Comment by angiolep** [comment]
Hi jrudolph,

this issue can be closed as I didn't find any other specification which suggests different encoding rules.

Thank you
