### ISSUE TITLE
"Directives from scratch" could use a code example

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1381]
As easily creating new directives is one of the strengths of our DSL, it'd be nice to have a code example in http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/custom-directives.html#directives-from-scratch

**Comment by satansk** [comment]
Hi @raboof , I notice that the [HostDirectives](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/host-directives/index.html) can only filter based on hostname. Sometimes people want to filter by the whole host(hostname + port), so I think a customed directive about this would be not bad, how do you think?

**Comment by raboof** [comment]
That could be a neat example, I agree!

**Comment by satansk** [comment]
I'm very glad to have a try @raboof !

**Comment by satansk** [comment]
Hi @raboof , the example is ready, but I'm not sure whether it's qualified, so any advice is welcome!

```
object HostnameAndPort extends Directive[(String, Int)] {

  private val hostnameAndPort =
    textract(ctx => (ctx.request.uri.authority.host.address(), ctx.request.uri.authority.port))

  override def tapply(f: ((String, Int)) => Route): Route = hostnameAndPort {
    (hostname, port) => f(hostname, port)
  }
}

val route = HostnameAndPort {
  (hostname, port) => complete(s"The hostname is $hostname and the port is $port")
}
  
Get() ~> Host("akka.io", 8080) ~> route ~> check {
  status shouldEqual OK
  responseAs[String] shouldEqual "The hostname is akka.io and the port is 8080"
}
```
