### ISSUE TITLE
publish documentation snapshots

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1384]
For akka we publish the documentation for 'master' as http://doc.akka.io/docs/akka/snapshot/scala/index.html , it might be nice to do the same for akka-http

**Comment by ktoso** [comment]
Yes that would be very good - how do we do that?

**Comment by raboof** [comment]
For Akka we have a separate jenkins job (https://jenkins.akka.io:8498/job/akka-docs/configure), but for akka-http perhaps it'd be neater to configure Travis to do it for 'branch' builds on master

**Comment by ktoso** [comment]
I'd rather be as similar to the akka build as possible so we don't have 20 different ways. I'll copy that build :)

**Comment by ktoso** [comment]
(Meh, dropping it for now though... will try later, trying to finish different task - feel free to hack on this if you have time :))

**Comment by raboof** [comment]
Agreed not having 20 different ways is good - I like how with travis the configuration is checked into version control though, perhaps we should move publishing snapshot akka docs to travis as well? :)

**Comment by ktoso** [comment]
Yeah, would be good to get both into that style at the same time I guess.
Best at one go, so we don't leave it hanging done in one but not the other
:)

**Comment by raboof** [comment]
This is now done, https://doc.akka.io/docs/akka-http/snapshot/ https://doc.akka.io/api/akka-http/snapshot/ https://doc.akka.io/japi/akka-http/snapshot/

**Comment by jrudolph** [comment]
Very nice!
