### ISSUE TITLE
Use Framing instead of LineParser?

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1392]
We include a [LineParser](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParser.scala) - is there any reason we can't use [Framing]( http://doc.akka.io/docs/akka/current/scala/stream/stream-cookbook.html#parsing-lines-from-a-stream-of-bytestrings) instead?

**Comment by jrudolph** [comment]
Our parser allows all of CR, LF, and CRLF as line endings which currently isn't supported by Framing.
