### ISSUE TITLE
akka.http.scaladsl.model.ws.Message should extend javadsl

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#14]
We have a fixme for it.
The problem is that it would be binary incompatible, right?

`// FIXME: Why don't we extend akka.http.javadsl.model.ws.Message here?`

**Comment by jrudolph** [comment]
Was changed in https://github.com/akka/akka-http/commit/75dc20b89f8567dbd9096d445ddfb5e8d36ec14c (for whatever reason).
