### ISSUE TITLE
There's a typo in the contributing guidelines

### ISSUE THREAD

**Issue by satansk** [akka/akka-http#1402]
In the chapter of General Workflow:

> In general a PR is expected to get 2 LGTMs from the team before it is merged. If the PR is trivial, or under under special circumstances ...

There are two 'under's, and I am glad to fix it.

**Comment by jlprat** [comment]
Hi @satansk! Thanks for the report!
Yes please, it would really cool if you could provide a Pull Request with the fix!

**Comment by satansk** [comment]
@jlprat I have sent a PR, and I really hope it will be helpful.

**Comment by satansk** [comment]
I have fixed it, so just close the issue.
