### ISSUE TITLE
A missing import in the document of Routing DSL for HTTP servers

### ISSUE THREAD

**Issue by satansk** [akka/akka-http#1406]
There is a missing import for `scala.concurrent.Future` in the last example of [Routing DSL for HTTP servers](http://doc.akka.io/docs/akka-http/current/scala/http/introduction.html#routing-dsl-for-http-servers), specifically, the example shows interaction of Akka HTTP with actors.

Can I send a PR for this?

**Comment by jlprat** [comment]
You are right, it's missing.
Yes please, PR is highly welcome!
Thanks!

**Comment by satansk** [comment]
Thank you @jlprat , and I have sent the PR.
