### ISSUE TITLE
Question about an example

### ISSUE THREAD

**Issue by Sammers21** [akka/akka-http#1412]
On this [page](http://doc.akka.io/docs/akka-http/10.0.8/scala/http/routing-dsl/directives/method-directives/get.html) there are some code snippet:
```scala
val route = get { complete("This is a GET request.") }

// tests:
Get("/") ~> route ~> check {
  responseAs[String] shouldEqual "This is a GET request."
}
```

And I can't figure out: what a package contains `Get` class?

**Comment by jonas** [comment]
Please do not use GitHub issues for Q&A, there are better ways for asking questions such as [Gitter](https://gitter.im/akka/akka), [stackoverflow](https://stackoverflow.com/questions/tagged/akka-http) and the [mailing list](https://groups.google.com/forum/#!forum/akka-user).

Take a look at the [RequestBuilding trait](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/client/RequestBuilding.scala#L55) which is mixed into `RouteTest`.
