### ISSUE TITLE
There is typo in "When to use which subtype?"

### ISSUE THREAD

**Issue by satansk** [akka/akka-http#1414]
The last rule of [When to use which subtype?](http://doc.akka.io/docs/akka-http/current/scala/http/common/http-model.html#httpentity):

```
In a Multipart.Bodypart use IndefiniteLength for content of unknown length.
```
The `Multipart.Bodypart` should be `Multipart.BodyPart`, and I will fix it~~

**Comment by ktoso** [comment]
Thanks :)
