### ISSUE TITLE
Provide support for List to Route generators

### ISSUE THREAD

**Issue by DrakkenSaer** [akka/akka-http#1426]
Given a `List("person", IntNumber, "profile")`, it would be nice to get back a route the same as `path("person" / IntNumber / "profile")`. Currently there seems to be no good way of doing this.

**Comment by ktoso** [comment]
If you put it into a list like that you've lost all type information - it just became a List[Any] losing any type information that one of them is supposed to extract an integer etc. for just matching you can always just fold over it with applying /, but that's not helping here.

What's the actual use case for this?

**Comment by raboof** [comment]
(closing for now while waiting for further background)

**Comment by DrakkenSaer** [comment]
I'm building a "serverless offline" equivalent for the JVM. It involves reading a YAML document and extracting a route in a string format like so  `something/{param}/somethingElse`. I'm breaking the string down into a list, and then taking the item with "{ }" and replacing it with Segment (or whatever value fits the bill). These routes can vary greatly, including multiple path parameters or none, so unfortunately there's know way to know in advance how to compose this.

**Comment by DrakkenSaer** [comment]
What would be really nice would be to have a list of path parameters in the HttpRequest/HttpResponse classes, with a Map[String, T] like so `Map("name" -> "bob", "personId" -> "123")`

(I say this without any knowledge of how difficult that would be)

**Comment by raboof** [comment]
@DrakkenSaer Aah, so you want to generate a `Route` based on a text/YAML DSL. That sounds a bit too specific to include in akka-http itself, but it should definitely be possible.

As you've noticed the tricky part is collecting the values: for example, if you convert `/person/{param}/profile` into `List("person", IntNumber, "profile")` then you've lost the information that the Integer parameter was called `param`.

There's various ways to approach this, one way might be to have a converter from `Directive0` to `Directive1[Map[String, Any]]` that just produces an empty map, and some further functions to combine various such directives while merging the produced maps. Does that make sense?

**Comment by jrudolph** [comment]
Maybe it could be built on top of [parameterMap](http://doc.akka.io/docs/akka-http/10.0.10/scala/http/routing-dsl/directives/parameter-directives/parameterMap.html#parametermap) dynamically parsing the parameters to some type as specified elsewhere?

**Comment by DrakkenSaer** [comment]
@raboof I will try your suggestion, that sounds promising. I should be able to get around to this either tonight or tomorrow.
