### ISSUE TITLE
HttpEntity.discardBytes Scaladoc

### ISSUE THREAD

**Issue by NeQuissimus** [akka/akka-http#1430]
I am trying to figure something out and either I am misunderstanding the documentation or it is wrong.
Either way, I would appreciate some clarification :)

My question will be about `HttpEntity.discardBytes` and `HttpMessage.discardEntityBytes` (which is essentially the same thing)
https://github.com/akka/akka-http/blob/c3b670578547616caa081d55948b84dd0a60ae5d/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala#L96

The Scaladoc says this:
```
If the dataBytes source is materialized a second time, it will fail with an "stream can cannot be materialized more than once" exception.
```

I have this code:

```scala
implicit val system = ActorSystem(name = "Playground")
val materializer = ActorMaterializer() // Non-implicit by choice

val entity = HttpEntity(ContentTypes.`application/json`, "Hello world")
val request = HttpRequest(entity = entity)

val blubb1 = Await.result(request.discardEntityBytes()(materializer).future, 10.seconds)
val blubb2 = Await.result(request.discardEntityBytes()(materializer).future, 10.seconds)

println(blubb1)
println(blubb2)
```

Should I not see an exception as per Scaladoc? Or am I misunderstanding?
I do not, both `blubb{1,2}` are printed out...

I even found this test: https://github.com/akka/akka-http/blob/74302ef20101daa8aee784a1240134eab7fffb27/akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala#L58
Am I brain-farting here or is the test not doing essentially the same I am trying?!

**Comment by ktoso** [comment]
There is a big difference between your code and what happens in real apps as well as the test you found: https://github.com/akka/akka-http/blob/74302ef20101daa8aee784a1240134eab7fffb27/akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala#L68

The difference is that your http entity is `Strict`, so it's all in memory - thus there's no streaming involved, and no multiple-materialization issue will happen - the data is not being drained from a socket, but just gets the string you gave here.

Perhaps we could improve the docs a bit, would you be willing to send a small wording polishing PR? Thanks in advance!

**Comment by NeQuissimus** [comment]
I knew I was missing something :)
So, if an entity is strict, there is no need memory leak without discarding the entity. Makes sense, since we have already drained the source by fetching the entity.

Yes, I will send a PR some time today or tomorrow.

Thanks!

**Comment by ktoso** [comment]
Please keep the ticket open until a PR is merged adding more details in docs, thanks :)
