### ISSUE TITLE
Http2 provide Tls Session Info header

### ISSUE THREAD

**Issue by LogicalTime** [akka/akka-http#1432]
I tried out http2 and found that the Tls Session Info header was not being provided. This works fine if I don't use the Java agent which makes the negotiation fall back to using http/1.1.

**Comment by jrudolph** [comment]
Thanks, @LogicalTime, makes sense.

Here's a sketch how that could be implemented for anyone who wants to try:

 * as Http2 disallows TLS renegotiation, let's assume that there's only one session.
 * in the AlpnSwitch we already wait for the first SessionBytes before deciding whether to use Http/1 or Http/2, this would be the right position to inject session info into further processing
 * this could be done by adopting the http2Stack param to take a `SSLSession` parameter
 * in the implementation the `SSLSession` should be passed to the `httpLayer` and then used in the `RequestParsing` to add the `TlsSessionInfo` header.

**Comment by greenhat** [comment]
@jrudolph Thanks for the sketch. I took a stab at it - https://github.com/akka/akka-http/pull/1801
