### ISSUE TITLE
Upgrade the build to sbt 1.0

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#1434]
Work on building Akka with sbt 1.0 has begun (https://github.com/akka/akka/pull/23651) due to the synergy of nightly build we want to be able to also update Akka HTTP to build with sbt 1.0 to ensure nightly builds continue to work.

**Comment by jonas** [comment]
Will take a look at this

**Comment by ktoso** [comment]
Yes good point. So far the only real challenge has been missing plugins not released for 1.0 yet.
Report back what you find! :)

**Comment by jonas** [comment]
Indeed the main blocker is sbt-dependency-graph which is used by `validatePullRequest`. I tried the 0.8.3-SNAPSHOT but it breaks the build due conflicting definitions of `sbt.compat` as noted [here](https://github.com/jrudolph/sbt-dependency-graph/pull/137#discussion_r139982230).

sbt-jol is also not available, however, nothing in the build actively uses it.

**Comment by ktoso** [comment]
Yeah we can ignore sbt-jol :)

**Comment by ktoso** [comment]
(though I thought i released it for 1.0... anyway, ignore it ;))

**Comment by ktoso** [comment]
FYI akka itself is also now on 1.0
