### ISSUE TITLE
UnexpectedConnectionClosureException - Automatically Retry in Idempotent requests?

### ISSUE THREAD

**Issue by mdedetrich** [akka/akka-http#1463]
For such errors
```
UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests
```
i.e. when the server disconnects akka-http when being used in client mode

According to the following documentation https://www.safaribooksonline.com/library/view/http-the-definitive/1565925092/ch04s07.html, automatically retrying idempotent requests (i.e. `GET`) is considered standard behaviour from http clients.

Does it make sense for akka-http, in such disconnect scenarios, to output a `warn` log message and retry the http request (with an option to toggle this back to the original behaviour?)

**Comment by jrudolph** [comment]
This is the current behavior. Idempotent requests are retried `akka.http.host-connection-pool.max-retries` times. It seems in the case you reported it was a `PATCH` request which is not idempotent according to [RFC 5789](https://tools.ietf.org/html/rfc5789#section-2) and thus was not retried.

**Comment by mdedetrich** [comment]
Okay thanks, I didn't realise this wasn't the case. I will close this ticket and re-open if its still valid
