### ISSUE TITLE
Show off dynamically updating routes

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1471]
One of our strong points is how the Routing DSL allows both efficient static and highly dynamic routes.

We don't always make that very clear, see for example #1470 . Perhaps we should add a section/example in the docs somewhere? Perhaps a server that changes/adds routes based on incoming requests, like a "http mock server server" where you can dynamically add mock endpoints and associated responses, behaviour etc? Should be fairly simple to do, right?

**Comment by ktoso** [comment]
Good ticket, triaged; People sometimes ask about that expecting it to be super hard but it's very simple :)
