### ISSUE TITLE
Building against akka/akka master fails

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1474]
A bit weird:

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/294//consoleFull

```
[error] /home/jenkins/.sbt/0.13/staging/8bd016127453b4b8fefa/akka/project/Formatting.scala:32: not found: value DoubleIndentConstructorArguments
[error]     .setPreference(DoubleIndentConstructorArguments, false)
[error]                    ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

**Comment by raboof** [comment]
That's weird: that's a new/renamed configuration option in sbt-scalariform that got updated in akka in b1df13d4d44.

**Comment by jrudolph** [comment]
Isn't it that the combined build might pull the scalariform version up for both projects?

**Comment by ktoso** [comment]
Yeah it's the combined build - just noticed we didn't log a specific issue for it so I did

**Comment by jonas** [comment]
Reminds me that I once volunteered to come up with a shared Akka build sbt project to avoid having 3+ copies of Formatting.scala and friends to maintain.
