### ISSUE TITLE
Charset for application/json response

### ISSUE THREAD

**Issue by guntiso** [akka/akka-http#1482]
Browsers are often failing to display non-ascii characters of application/json responses correctly, therefore utf-8 character set should be provided explicitly. It is probably not the responsibility of http protocol and clients to know default character set for any mime type.

**Comment by raboof** [comment]
It's actually well-defined in the standard that `application/json` content should be encoded in utf-8, and that there is no `encoding` parameter for this mime type. For some discussion on this topic in other ecosystems see for example https://github.com/request/request/issues/383 and other issues linked there.

Do you have a specific example of a situation where the current (standards-compliant) behavior leads to problems?

**Comment by guntiso** [comment]
Thank you for the link. One can see from that lengthy discussion that there indeed are problems with application/json and charset.
Implementations go both directions.
For example, micro added charset parameter to application/json just month ago: https://github.com/zeit/micro/pull/301

IANA registry seems to allow charset parameter - https://www.iana.org/assignments/media-types/application/json says:
> No "charset" parameter is defined for this registration.
> Adding one really has no effect on compliant recipients.

Is there a standard which prohibits charset parameter for application/json?

About specific example - I've seen problems on various browsers and operating systems, which is the reason this issue is created.
For example, Chromium 61.0.3163.100 running on Ubuntu 16.04 (64-bit).

Opinion, again - it is very simple to provide charset with message, but it is more complicated to imply it from mime type or byte ordering.

**Comment by jrudolph** [comment]
Hi @guntiso, that has been discussed a lot before. This is a well-known bug in various browsers. Some have fixed it by now but not all. We are currently not considering fixing this because it's specified very clearly that no charset parameter is needed. You can still create a custom content type if you need very specific behavior and the defaults don't suite you.

**Comment by ktoso** [comment]
This keeps coming back and we know that by-the-spec we're right etc.
I wonder if offering a flag to enable `browsers-dont-respect-the-spec-json-content-type-add-utf8-marker = on` would be helpful to people and cause us less drama each time it comes up hm...

**Comment by jrudolph** [comment]
I guess that will solve itself over time. We don't have a concrete proposal about what to improve so closing for now.
