### ISSUE TITLE
Http Client: connection (databytes)  is never canceled. 

### ISSUE THREAD

**Issue by jukkagrao** [akka/akka-http#1485]
I'm sorry if it's a dublicate.
So, I found the case when I can't cancel http connection when it consumes a stream from http server.
Despite that there are no consumers of this stream.

```
  Http().singleRequest(HttpRequest(uri = uri))
    .onComplete {
      case Success(HttpResponse(StatusCodes.OK, _, entity, _)) =>
        entity.dataBytes.idleTimeout(2.seconds) // This stream is never stop 
                                           // (of course, if stream itsef is infinite).
    } 
```

I guess that right behavior is to stop this stream and connection itself after idleTimeout, isn't?

I did a repo with reproducing of this case:
https://github.com/jukkagrao/akka-http-client-test

**Comment by jrudolph** [comment]
Hi @jukkagrao, thanks for the report. You should probably be using `response.discardEntityDataBytes()` if you are not interested in the data. If you want to use `idleTimeout` you still need to actually run the stream, so make sure to actually consume the stream e.g. using `runWith(Sink.ignore)`.

**Comment by jukkagrao** [comment]
Hi @jrudolph and thaks for reply. I interested in the data only when I have consumers of it. 
For example I want to use it like:

`dataBytes -> killSwitch ->  dynamic consumer`

So in case of call shutdown() on killSwitch, or if consumer is not interested in the data anymore connection should be closed.

**Comment by jukkagrao** [comment]
Im sorry, this is not an issue.

Right code to cancel connection if there are not consumers looks like that:
```
entity.dataBytes.backpressureTimeout(2.seconds).watchTermination() {
         (mat, futDone) => futDone.onComplete(_ => println("complete"))
           mat
        }.runWith(BroadcastHub.sink[ByteString])
```
