### ISSUE TITLE
`uploadedFile` directive doesn't work correctly on request cancellation

### ISSUE THREAD

**Issue by RobertoUa** [akka/akka-http#1488]
It gets executed with a partially uploaded file and logs an error (`Tearing down FileSink ... EntityStreamException: Entity stream truncation`).

Looks like `FileIO.toPath` returned `IOResult` but the directive didn't check for failure and turned it into a file like this `.map(_ ⇒ (fileInfo, destination))` (placeholder is `IOResult`). I was able to fix it like this. https://gist.github.com/RobertoUa/34f360a9e9a1e4c2bab0abce361775fe
Notice that I use flatMap on `IOResult`'s `status` so that error gets propagated. `FileSubscriber` still logs an error which is undesirable.

**Comment by jrudolph** [comment]
Thanks for the report, @RobertoUa. It's weird that in error cases the Future returned by `FileIO.toPath` will still succeed and return an `IOResult` with failed status instead of failing directly (filed akka/akka#23951 to improve that at some point).

Could you open a PR with your suggested fix and add a test for it?

**Comment by RobertoUa** [comment]
I'd love to, but I had troubles figuring out how to write tests for it.

**Comment by jrudolph** [comment]
Fix would go to https://github.com/akka/akka-http/blob/a1a9c27ee6224373ca01d26edba071dcc2316298/akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala#L21 but I agree it's a bit hard to simulate a file system error. I think with Java >= 8 it's possible to provide a custom `FileSystemProvider` which could be used simulate the error. I think we have used that somewhere else.

**Comment by ktoso** [comment]
Indeed we can simulate the FS and a good lib to do so is Google's jimfs https://github.com/google/jimfs ,
we use it in Akka Stream's file tests:

https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala#L30
