### ISSUE TITLE
Connectionpool leak in http client

### ISSUE THREAD

**Issue by eddykaya** [akka/akka-http#1495]
When doing HEAD requests using http.singleRequest, I can only perform 4 requests before the threadpool is exhausted. If I perform GET requests, the connections are closed properly.
If I discard the entitiy bytes after doing a HEAD request, this bug does also not occur.

Example Code broken:
`                val eventualHead: Future[HttpResponse] = http.singleRequest(HttpRequest(HttpMethods.HEAD, uri = url))
                onComplete(eventualHead) { r =>
                  r.map(_.status) match {
                    case Success(code) =>
                      complete(HttpResponse(code, entity = asJson(response.toString())))
                    case _ => complete(HttpResponse(StatusCodes.NotFound))
                  }
                }`

Workaround:
`                val eventualHead: Future[HttpResponse] = http.singleRequest(HttpRequest(HttpMethods.HEAD, uri = url))
                  .map { res =>
                    res.discardEntityBytes()
                    res
                  }
                onComplete(eventualHead) { r =>
                  r.map(_.status) match {
                    case Success(code) =>
                      complete(HttpResponse(code, entity = asJson(response.toString())))
                    case _ => complete(HttpResponse(StatusCodes.NotFound))
                  }
                }`

**Comment by jrudolph** [comment]
Hi @eddykaya, thanks for the report. Discarding entities is a good practice for responses in any case. But I agree that it is unexpected that it would be necessary for HEAD requests in particular.

**Comment by jrudolph** [comment]
Can you check what's the subtype of `response.entity`?

**Comment by eddykaya** [comment]
Debugger says class akka.http.scaladsl.model.HttpEntity$Default

**Comment by jrudolph** [comment]
I see, that's the consequence of a previous change where we somehow tried to report the content-length:

https://github.com/akka/akka-http/blob/075913c0dd4b390f86d454b69ff2cdd0001108eb/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala#L161-L168

In the simplest case, we would just return a strict empty entity here. Unfortunately, we cannot report the content length, then. A clean solution would probably be introducing a special entity subclass for HEAD responses. However, that's quite heavy-weight in terms of needed changes.

The alternative could be to treat HEAD responses differently in the pool, not to wait for the known-to-be-empty entity to be drained (we could also match `Source.empty` directly). Or, we just fall-back to the soon-to-be-introduced subscription timeout for response entities that will free pool slot entries much faster and more reliably than what the idle-timeout currently tries to achieve.

**Comment by schoeneu** [comment]
> The alternative could be to treat HEAD responses differently in the pool, not to wait for the known-to-be-empty entity to be drained

just to clarify - would that be safe? The "known-to-be-empty" part is true as far as the code handling the responses has to know, but there are many setups out there where either a non-RFC-7231-server or a reverse proxy on the way *do* indeed reply to a HEAD request with a body. So any solution to this issue would still close the connection and return it to the pool even if the server includes a body in a HEAD response?

**Comment by jrudolph** [comment]
> just to clarify - would that be safe? The "known-to-be-empty" part is true as far as the user code handling the responses has to know, but there are many setups out there where either a non-RFC-7231-server or a reverse proxy on the way _do_ indeed reply to a HEAD request with a body. So any solution to this issue would still close the connection and return it to the pool even if the server includes a body in a HEAD response?

Do you know of such a server? In any case, it wouldn't comply to any spec so I do not see any immediate requirement to support this.
