### ISSUE TITLE
Should ws.Message have toStrict() same as entities?

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#15]
The same issue around "but I want it strict" surfaces in WebSocket messages as it does with HttpEntities - for entities people can easily toStrict them - for websocket messages where toStricting usually is more safe (smaller msgs... generally speaking), we don't have this helper on the type directly.

I think it would make a nice addition, opinions? Did I miss something?

**Comment by jrudolph** [comment]
Yes, `toStrict` is the low-level API we need. We then should then have higher-level APIs that provide Source[String] / Source[ByteString] instead of messages directly.

**Comment by jrudolph** [comment]
See also akka/akka#19089 and akka/akka#20096

**Comment by ktoso** [comment]
Marked as community, I think this is not that difficult and would be very good to provide.

**Comment by blbradley** [comment]
I was wondering this yesterday as I was exploring the use of half-open websockets in an app. There is a `toStrict` member of `TextMessage.Streamed`, but it currently throws an error.

After doing something like `stringSource.runFold("")(_ + _)` to handle `TextMessage.Streamed`, I ended up using `Future[String]` throughout the steam which was making the code a bit terse. I had to settle with `stringFuture pipeTo self` inside an actor but would have preferred using a working `toStrict` method.

**Comment by ktoso** [comment]
`toStrict` will always return a Future though - since consuming the entity is async.
Yes we're missing the method here - contribs would be great if you have a moment to implement it :)

**Comment by rbudzko** [comment]
Naturally, `toStrict` on `Message` would have similar declaration as `toStrict` on `HttpEntity`, so for example `def toStrict(timeout: FiniteDuration)(implicit fm: Materializer): Future[T.Strict]` where `T` is either `TextMessage` or `BinnaryMessage`, but I've noticed that "strange" functions like `getStrictData` and `isStrict` exists already. 

While above does not block us from implementing `toStrict` it would be very confussing to have object with 3 functions out of which only 2 of them are correlated with each other. Are we really fine with simply adding `toStrict` and leaving `isStrict` and `getStrictData` as are now?

**Comment by blbradley** [comment]
@ktoso You are right. I was able to unpack `Future` using `Flow.mapAsync` instead of `pipeTo`. Did not know about that until yesterday.

@rbudzko If you are looking for API parity with other Akka HTTP types with strict and stream variants, those will need to change. Maybe not in the same PR. Thanks for the work!

**Comment by 2beaucoup** [comment]
see https://github.com/akka/akka-http/pull/611#issuecomment-275113296  by @jrudolph for the proposed API

**Comment by ktoso** [comment]
I do believe the there linked PR should be merged; and at the same time, the follow up is good and I made it a top level ticket: https://github.com/akka/akka-http/issues/1979 it would be a great contrib
