### ISSUE TITLE
FAILED: ConnectionPoolSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1502]
`akka.http.impl.engine.client.ConnectionPoolSpec.The host-level client infrastructure should respect the configured maxRetries value`

https://jenkins.akka.io:8498/job/pr-validator-akka-http/1644/testReport/junit/akka.http.impl.engine.client/ConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by jlprat** [comment]
Another instance https://jenkins.akka.io:8498/job/pr-validator-akka-http/1672/testReport/junit/akka.http.impl.engine.client/ConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by jrudolph** [comment]
Didn't happen for a long time.
