### ISSUE TITLE
[Docs] Contradiction on Akka Streams and Akka Actors use on Akka HTTP

### ISSUE THREAD

**Issue by gihankarunarathne** [akka/akka-http#1505]
Hi dev,

Seems to be these two mentions are contradicting to each other and misguide the users.

1. [migration-from-spray.md#streams-everywhere](https://github.com/akka/akka-http/blob/v10.0.10/docs/src/main/paradox/scala/http/migration-guide/migration-from-spray.md#streams-everywhere)
> Akka HTTP is not implemented on Actors any more but is now completely based on akka-stream.

2. [AKKA HTTP introduction](https://github.com/akka/akka-http/blob/v10.0.10/docs/src/main/paradox/scala/http/introduction.md#introduction)
> The Akka HTTP modules implement a full server- and client-side HTTP stack on top of akka-actor and akka-stream. 

I'm new to AKKA as well as for Scala. First time I read 1st reference above, what I felt was, I can't use AKKA HTTP (which is currently based on Streams) with Actors. After I investigate, I found the 2nd reference and got what it exactly meant to be.

I think, it'll be better to update/elaborate more the 1st reference to avoid any confusion.

Thank you!

**Comment by raboof** [comment]
Hi @gihankarunarathne, it indeed makes sense to make that more clear! Would you be interested in proposing clear wording and submitting a PR?

While indeed Akka HTTP is now implemented using streams, streams are still backed by actors and can interoperate well with them.

**Comment by ktoso** [comment]
Please spell Akka as "Akka", it's not an acronym. It's a name of a mountain :-)

**Comment by gihankarunarathne** [comment]
Hi @raboof, after you understand the fact, 1st reference explanation make sense. You'll not see any difference, since you know all the terms and history. :)

I think it's overwhelm with,
> is not implemented on Actors any more
and simply say,
> Akka HTTP is now completely based on akka-stream.
Or
> Akka HTTP is now completely based on akka-stream, and streams are still backed by actors.

I'm not sure, how it's going to fit into the context. :-/

**Comment by gihankarunarathne** [comment]
Hey @ktoso, thanks for the tip. I don't know "Akka" is a name of a mountain. 😃 

I'm using AKKA because I don't feel comfortable with "Akka", since in my mother tongue it's referring to something else. 😄 

![image](https://user-images.githubusercontent.com/1858941/32292661-d1540c00-bf66-11e7-83b5-501324baaa1b.png)

**Comment by ktoso** [comment]
Lol, I see; yeah, though please treat it as just some unique name, uppercase looks super weird as it implies it’s an acronym :)
