### ISSUE TITLE
Problem with connecting http server to outgoing tcp server throught nginx

### ISSUE THREAD

**Issue by 4repaXXX** [akka/akka-http#1511]
Hello everybody!
Problem when try to using akka http like proxy to tcp.
Condition:

- Start http server, which responsibility only to get json request from the client and send message on Tcp server through nginx, take response from it and send response back to the client. So, only like proxy.

Problem:

- Http server try to response before tcp server response. But when I remove nginx proxy between http and tcp servers everything all right. In tcp level akka http server send RST packet and right after that get RST from nginx and connection close. Tcp respond to nginx but connection already closed. With simple tcp server the same situation.

Akka version 2.4.17, akka http 10.0.10
The code below
```
val connections: Flow[ByteString, ByteString, Future[Tcp.OutgoingConnection]] =
Tcp().outgoingConnection(new InetSocketAddress(settings.tcpServerHost, settings.tcpServerPort))
def start(): Unit ={
  val requestHandler: HttpRequest => Future[HttpResponse] = {
  case HttpRequest(POST, uri@Uri.Path("/v1/doc"), _, entry, _) =>
  proxyTcp(100, uri, entry)
  case HttpRequest(POST, uri@Uri.Path("/v5/doc"), _, entry, _) =>
  proxyTcp(105, uri, entry)
  case _ => Future(HttpResponse(status = StatusCodes.NotFound))
}

  Http().bind(settings.host, settings.port).runForeach(connection => {
  connection.handleWithAsyncHandler(requestHandler)
}) }
  private def proxyTcp(version: Short, uri: Uri, entry: RequestEntity): Future[HttpResponse] = {
  val transform = Transformations(connections, version)
  entry.withoutSizeLimit().dataBytes
  .via(transform.json2tlv)
  .via(transform.connections)
  .runWith(Sink.head)
  .map(result => HttpResponse(status = StatusCodes.OK, entity = HttpEntity(ContentTypes.`application/json`, result.get)))
}
```

Thanks in advance for the answer.

**Comment by jrudolph** [comment]
HI @4repaXXX, thanks for the report. It's a bit unclear if this is more of a question about how Akka Http works or what could be wrong with your code or whether it is a bug report. If it's more of a question than the mailing list might be better suited to look into the issue. If it's more of a bug report we need more accurate information about what is expected behavior from Akka Http and how it deviates from the expectations and how to reproduce the behavior. Could you clarify what you are looking for?

**Comment by 4repaXXX** [comment]
Hi @jrudolph , thanks for reply. I could be wrong, but I'm almost sure that this is a bug. The expected behavior is getting response by akka http server from a bundle of nginx+tcp akka server. The behavoior that the server shows in that the response is not getting by akka http server, insted of this the connection cancel and we have no response. 
I belive, you can reproduce it if you make tcp client to request to tcp server between which insert nginx.

**Comment by jrudolph** [comment]
If you think it is a bug, we need more information to reproduce it (or a tcpdump) which clearly shows the error.

Also, can you try if the same error happens when you use `Http().singleRequest` for the proxy request?

**Comment by 4repaXXX** [comment]
I will try to use `Http().singleRequest`, thanks. 
Now I attach tcpdump for bundles tcpclient-nginx and nginx-tcpserver. What is strange is that akka send FIN before recieve data from server, and after that connection close.
And different situation I see when I rewrote the code on rxjava tcp client, all data received from server.
[tcpdump_client_nginx.txt](https://github.com/akka/akka-http/files/1504189/tcpdump_client_nginx.txt)
[tcpdump_client_nginx_java.txt](https://github.com/akka/akka-http/files/1504190/tcpdump_client_nginx_java.txt)
[tcpdump_nginx_tcpserver.txt](https://github.com/akka/akka-http/files/1504191/tcpdump_nginx_tcpserver.txt)
[tcpdump_nginx_tcpserver_java.txt](https://github.com/akka/akka-http/files/1504192/tcpdump_nginx_tcpserver_java.txt)

**Comment by 4repaXXX** [comment]
@jrudolph I try to send via Http.singleRequest and it's not working too. Connection drop before response from tcp-server send. The pipeline is next: `Http.singleRequest(as client) -> Http.bind(proxy server) -> nginx -> Tcp.bind(tcp server)`  and reversed response.

**Comment by jrudolph** [comment]
I don't really understand how nginx comes into the picture if you are connecting to a raw TCP server? How would nginx be able to proxy a non-HTTP connection? Is that some special mode of nginx?

**Comment by 4repaXXX** [comment]
@jrudolph  Sorry if I'm not clear. Yes, it's special mode of nginx for tcp stream.

[nginx.txt](https://github.com/akka/akka-http/files/1559820/nginx.txt)
[nginx-server.txt](https://github.com/akka/akka-http/files/1559821/nginx-server.txt)
[tcp_stream.txt](https://github.com/akka/akka-http/files/1559822/tcp_stream.txt)
[upstream.txt](https://github.com/akka/akka-http/files/1559823/upstream.txt)

**Comment by 4repaXXX** [comment]
@jrudolph I thought of to use haproxy instead of nginx and all working as expected. So, it's look like nginx problem. Sorry for consern.
