### ISSUE TITLE
Change comments in CacheDirective to scaladoc 

### ISSUE THREAD

**Issue by matsluni** [akka/akka-http#1514]
In one [comment](https://github.com/akka/akka-http/pull/1211#discussion_r122885959) of PR 1211 @ktoso requested a change from a comment to a actual scaladoc for the link to the rfc document. 

Should this be applied to all of the links in this file? 

There a more classes where this could be changed, e.g. [HttpCookie.scala](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpCookie.scala), what about those?

**Comment by raboof** [comment]
I think that would be nice!
