### ISSUE TITLE
Probable Akka HTTP bug in server side WebSockets handling

### ISSUE THREAD

**Issue by jroper** [akka/akka-http#1515]
Lagom is seeing a lot of these errors in its integration tests when using WebSockets:

```
2017-11-06 12:56:54,422 DEBUG akka.actor.RepointableActorRef - Aborting tcp connection to /127.0.0.1:42630 because of upstream failure: requirement failed: Cannot push port (SubSource.out(326501899)) twice
scala.Predef$.require(Predef.scala:224)
akka.stream.stage.GraphStageLogic.push(GraphStage.scala:548)
akka.stream.impl.fusing.SubSource$$anon$4$$anonfun$1.apply(StreamOfStreams.scala:724)
akka.stream.impl.fusing.SubSource$$anon$4$$anonfun$1.apply(StreamOfStreams.scala:721)
akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:443)
akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:453)
akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:718)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:744)
akka.actor.Actor$class.aroundReceive(Actor.scala:517)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
akka.actor.ActorCell.invoke(ActorCell.scala:496)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The problem with this stack trace is that we don't know what invoked `SubSourceOutlet.push` due to the asynchronous boundary between this method and the `SubSource` handling. However, neither Play nor Lagom use any `SubSourceOutlet`'s (it's supposed to be an internal Akka streams API anyway), so the most likely cause of this is something wrong in Akka HTTP's WebSocket support which does create a `SubSourceOutlet`. I can't think of any other way this error could end up happening.

Also note that because `SubSource` just creates a generic name `SubSource.out` for its outlet, there's no way to map this error back to the original source. I'll raise a bug about that.

More details about the bug are reported in https://github.com/lagom/lagom/pull/1054.

These tests are doing a lot of starting up WebSockets and then terminating them immediately, so it could be a race condition on startup.

**Comment by jroper** [comment]
There does seem to be a race condition in [HttpServerBluePrint.scala](https://github.com/akka/akka-http/blob/a074d432d6357c923bd15301fe019e920e719370/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala).

`fromNet` is pulled whenever `toHttp` receives a pull. There is no reason why it can't have been pulled before `switchToWebSocket` is invoked, whatever is handling HTTP requests might pull many times before emitting an HTTP response, plus even if only one HTTP request is handled at a time, there's still a possible race condition between when the response is handled and when the `fromNet` is pulled. So then the sub source is connected, but it may not pull immediately, and even if it does, if `fromNet` pushes before it's able to execute that pull, then you'll get the above exception, due to this line not checking if `sourceOut` is available before pushing to it:

https://github.com/akka/akka-http/blob/a074d432d6357c923bd15301fe019e920e719370/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L667

Essentially, we have a race condition between a client sending its first web socket frame, and the web socket handler pulling for it.

**Comment by jroper** [comment]
Fixed in #1516.

**Comment by jrudolph** [comment]
I created another ticket over there https://github.com/akka/akka/issues/23929 to track the bad stack trace. There doesn't seem to be a reason to fail eagerly with more context.

**Comment by dispalt** [comment]
@jroper thank you this fixed a big problem for me!
