### ISSUE TITLE
WS Client might send out RST packets on regular connection closure

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1518]
As @ignasi35 observed here:

![screenshot from 2017-11-06 12 20 10](https://user-images.githubusercontent.com/9868/32443314-d881e402-c2fe-11e7-9d5b-aafcbfbf77f3.png)

It's likely a case of completion vs cancellation race in `WebSocketClientBlueprint`. Adding a `delayCancellation` stage below the WS implementation should fix the problem.

As discussed in https://github.com/akka/akka/issues/17997 we should also look for a more general solution because every bidistage is affected by that problem.

**Comment by ignasi35** [comment]
@jrudolph These slides use a netty-based, Lagom-specific client. This `tcpdump` was not generated with code using `WebSocketClientBlueprint`.

**Comment by jrudolph** [comment]
Oops, if you look at that screenshot it's pretty hard to see that it isn't using akka http as the client... ;)

Anyway, then you observed a bug in that other client. ;)

From inspecting our own code, we seem to have the same bug still.

**Comment by ignasi35** [comment]
> Oops, if you look at that screenshot it's pretty hard to see that it isn't using akka http as the client... ;)

it is? it's right there, between the dots and the non-ASCII characters. ;-)

> Anyway, then you observed a bug in that other client. ;)

Yeah, I want to regression https://github.com/lagom/lagom/pull/1054 with https://github.com/akka/akka-http/pull/1516 see what's the outcome but I still think https://github.com/lagom/lagom/pull/1054 includes a surprise like you said.

**Comment by jrudolph** [comment]
Since we added cancellation delay in #2965 for the client-side we are hopefully good for this one.
