### ISSUE TITLE
Issue while setting mediatype to multipart/form-data for Multipart.FormData.BodyPart.fromPath

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1519]
<a href="https://github.com/Akhil201"><img src="https://avatars2.githubusercontent.com/u/33444872?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Akhil201](https://github.com/Akhil201)**
_Tuesday Nov 07, 2017 at 06:55 GMT_
_Originally opened as https://github.com/akka/akka/issues/23935_

----

Hi Team, 

I am trying to upload a file to external server of media type multipart/form-data. So I configured the request as follows 

def createEntity(file: File): Future[RequestEntity] = {
    
    val foo: Path = Paths.get("""C:\Users\akhilesh\Desktop\test12345720170521-41925-lzxwhi.kml""")
    require(file.exists())
    val formData =
      Multipart.FormData(
        akka.stream.scaladsl.Source(
          List(
            Multipart.FormData.BodyPart.fromPath(
              "file",MediaTypes.`multipart/form-data`,foo),
            Multipart.FormData.BodyPart("name", "akhil"))))
    Marshal(formData).to[RequestEntity]
  }

Here I set media type to ( MediaTypes.`multipart/form-data`) so here I am facing the error as type mismatch; found : akka.http.scaladsl.model.MediaType.Multipart required: akka.http.scaladsl.model.ContentType

Please help me out how to configure my multipart request with mediatype as 'multipart/form-data' in akka.

**Comment by Akhil201** [comment]
Hi ktoso, I am trying to upload .kml file for this I done the code like this...............


val foo: Path = Paths.get("""C:\Users\akhilesh\Desktop\test12345720170521-41925-lzxwhi.kml""")
    val requrl = """http://10.10.10.158:9111/api/v2/extract_path?api_key=7c28b9704353e7c365bbd272f55740f43b625057"""

    val data = Multipart.FormData {
      akka.stream.scaladsl.Source {
        List(
          Multipart.FormData.BodyPart.fromPath("file", ContentTypes.`application/json`, foo),
          Multipart.FormData.BodyPart.Strict("name", "akhil"))
      }
    }

    def req: Future[JsValue] = {

      for {
        request <- Marshal(data).to[RequestEntity]
        response <- http.singleRequest(HttpRequest(
          method = HttpMethods.POST,
          uri = requrl,
          headers = List(headers.Accept(MediaTypes.`application/vnd.google-earth.kml+xml`)),
          entity = request))
        entity <- Unmarshal(response.entity).to[JsValue]
      } yield {
        entity
      }
    } 

Mean while I wanna to get request as 

"file"=>#

<ActionDispatch::Http::UploadedFile:0x005602acd786d8 @tempfile=#<Tempfile:/tmp/RackMultipart20171106-27846-aw9ucq.kml>, 

@original_filename="7079279220170720-30032-8zzifx.kml", 

@content_type="application/vnd.google-earth.kml+xml", 

@headers="Content-Disposition: form-data; name=\"file\"; filename=\"7079279220170720-30032-8zzifx.kml\"\r\n

Content-Type: application/vnd.google-earth.kml+xml\r\n">,

 "name"=>"test", "api_key"=>"f5cc72fa471399558e386b1b98d454d4e37cf8c4"}




but it is constructing as 


{"file\r\n"=>#

<ActionDispatch::Http::UploadedFile:0x0055dc3ada1f58 @tempfile=#<Tempfile:/tmp/RackMultipart20171107-2302-1wdnaqj.kml>, 

@original_filename="test12345720170521-41925-lzxwhi.kml", 

@content_type="application/json", 

@headers="Content-Disposition: form-data; filename=test12345720170521-41925-lzxwhi.kml; name=file\r\n 

Content-Type: application/json" >, 

"name\r\n"=>"test", "api_key"=>"7c28b9704353e7c365bbd272f55740f43b625057"}

like this.


My problem is in 
Multipart.FormData.BodyPart.fromPath("file", **ContentTypes.`application/json`**, foo),
 I have to pass content type as "application/vnd.google-earth.kml+xml" but here I cant able to pass those content types, which are throwing compilation errors. 

my sbt dependencies are as follows


  "com.typesafe.akka" %% "akka-stream" % "2.4.11",
  "com.typesafe.akka" %% "akka-http-experimental" % "2.4.11",
  "com.typesafe.akka" %% "akka-http-spray-json-experimental" % "2.4.11",
  "com.typesafe.akka" %% "akka-contrib" % "2.4.8",

**Comment by jrudolph** [comment]
`MediaTypes.`application/vnd.google-earth.kml+xml`` needs a charset to become a content-type. You can use the `withCharset` or `withMissingCharset` methods to provide it. I.e. use

```scala
val contentType = `MediaTypes.`application/vnd.google-earth.kml+xml`.withCharset(Charsets.`UTF-8`)
```

Does that solve it for you?

**Comment by Akhil201** [comment]
I tried, but at last I used scalaj-http.

Problem I faced here is. I can't select particular media type for that
particular file type. If I select it is giving compilation error...

Thank you

**Comment by jrudolph** [comment]
Can you post the compile error you got when using the code I posted?

**Comment by Akhil201** [comment]
Oops sorry,  I didn't used that code. Tomorrow I will do that and I will
let you know.

And I faced one more problem while using akka http library. The problem is,
I have multipart web service which is developed in ruby, if I made request
from akka, form data is appending with CRLF characters i.e., /r/n but here
I don't that characters bcoz of this service can't fetch form data. Can you
please help me to remove CRLF characters from multi form request.

Thank you

**Comment by jrudolph** [comment]
> And I faced one more problem while using akka http library. The problem is,
> I have multipart web service which is developed in ruby, if I made request
> from akka, form data is appending with CRLF characters i.e., /r/n but here
> I don't that characters bcoz of this service can't fetch form data. Can you
> please help me to remove CRLF characters from multi form request.

You'll probably have to fix the other side. It's unlikely that we introduce non-standard behavior.

**Comment by Akhil201** [comment]
Okay, Thank you.

May I know good link for OAuth server side implementation for akka http

**Comment by jrudolph** [comment]
Nothing built in for OAuth but there have been community projects. Try asking on the mailing list or the gitter channel.
