### ISSUE TITLE
MinConnections can not be configured on a specific ConnectionPoolSettings

### ISSUE THREAD

**Issue by RustedBones** [akka/akka-http#1525]
I am writing a small library that uses the akka-http host connection pool client to interact with an external system.

For this library, I don't want to use the default `akka.http.host-connection-pool` configuration but a very specific one. This to ensure that other usage of `Http().cachedHostConnectionPool(...)` in the final application do not use the same pool configuration as the library.

To do this, I've done the following:
```scala
private val connectionPoolSettings = ConnectionPoolSettings(system)
    .withMaxConnections(maxConnections)
    .withMaxOpenRequests(maxConnections)
    .withMaxRetries(maxRetries)
```
This seems to be the easiest way to go, because it allows using the default settings and only overwrite the interesting values.

However, `ConnectionPoolSettings` does not provide a modifier for `minConnections`. I suppose this has just been forgotten.

**Comment by jrudolph** [comment]
Fixed in #1526.
