### ISSUE TITLE
Client connection pool leaking slots when proxying requests

### ISSUE THREAD

**Issue by DWvanGeest** [akka/akka-http#1529]
Hi there,

We're running an Akka HTTP server that proxies incoming requests via an instance of Akka HTTP client. These proxied requests go to an internal backend. It's a similar idea to https://github.com/akka/akka-http/issues/240, but with some custom work.

The client interface in use is `Http.singleRequest`, `max-connections` is set to `100`, and `min-connections` is set to `5`. What we see is that after a few days, somehow those connections are exhausted and we hit `BufferOverflowException`.

I turned on `DEBUG` logging for the `PoolGateway`. What I can see is that initially, lower numbered slots are used (e.g. 1 - 5). Over the next couple days, we get up to 99, and then shortly after hit the error condition. The logs I'm referring to are:

```
PoolGateway: [5] <unconnected> pushing request to connection: GET /api/v1/foo Empty
....
PoolGateway: [99] <unconnected> pushing request to connection: GET /api/v1/foo Empty
```

One thing I've noticed is that the backend server (NGINX) doesn't seem to like `keepalive` connections. It closes the connection immedidately after sending the response. So, the connection pool is constantly establishing new connections and having them closed:

```
connection was closed by peer while no requests were in flight
```

While this is strange behaviour I would like to solve, it seems that it should not ultimately cause the situation I'm seeing.

In looking through other similar issues (#1248, #843), it does seem like not consuming the returned HTTP entity is a common theme. My initial assumption was that this would happen automatically because the response from the back-end is being immediately sent to to the original client. This happens just fine in the happy path, but I'm wondering if some error cases cause this not to happen, which leads to the connection slot leak.

Specifically, I do tend to see quite a few (hundreds over a couple days) of these:

```
PoolGateway: [0] </192.168.42.2:43770->localhost:3000> connection failed while running GET /api/v1/bar Empty: akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests
```

Here's some (simplified) code to illustrate our proxy setup:

``` scala
class HttpProxy(httpClient: HttpExt) {
  def request(request: HttpRequest, target: Authority, useHttps: Boolean): Future[HttpResponse] = {
    val scheme = if (useHttps) "https" else "http"
    val proxyUri = request.uri.withScheme(scheme).withAuthority(target)

    val proxyRequest = request.withUri(proxyUri)

    httpClient.singleRequest(proxyRequest)
  }
}

val target = Authority(Uri.Host("localhost"), 3000) // there's a local haproxy instance that routes to the NGINX backends

val route = extractRequest { req =>
    complete(proxy.request(req, target, false)
  }
```

Any ideas? Is this perhaps due to one of those known bugs? Thanks!

**Comment by DWvanGeest** [comment]
I am considering changing the `HttpProxy` to explicitly consume the entity like this:

``` scala
def request(request: HttpRequest, target: Authority, useHttps: Boolean): Future[HttpResponse] = {
  // ...
  val response = httpClient.singleRequest(proxyRequest)
  response.flatMap { r =>
    r.entity.toStrict(20.seconds).map { e =>
      r.withEntity(e)
    }
  }
}
```

But, am unsure if it will help at all. Workaround ideas very welcome.

**Comment by jrudolph** [comment]
HI @DWvanGeest, thanks for the report. Yes, the most likely cause is that entities are not consumed. This could happen in the proxy case when the user connection to the server breaks before a response can be delivered. So, it would be interesting to see if making all entities strict before sending them out would help.

We are currently also working on rewriting part of the pool infrastructure to harden them against these kinds of situations.

**Comment by DWvanGeest** [comment]
Thanks for the response @jrudolph. A couple updates:

- Adding the above code to convert to strict entitites seems to be working. In the last couple days the logging from `PoolGateway` is showing that we're still using lower-numbered slots. This is in direct contrast to the error case where the slot numbers would migrate to higher numbers.

- I did try to reproduce the scenario you suggested, where the user connection to the server is either broken explicitly by the user, or by having the Akka HTTP server timeout the request (by setting `request-timeout` to an artifically low value). In both cases it seems that the response from the back-end is still consumed somehow. In the logs, I see:

```
PoolGateway: [1] </127.0.0.1:49454->localhost:3000> Received response: GET /api/v3/foo Empty -> 200 OK Strict(35 bytes)
PoolGateway: [1] </127.0.0.1:49454->localhost:3000> Finished reading response entity for GET /api/v3/foo Empty -> 200 OK Strict(35 bytes)
PoolGateway: [1] Loaded(1) -> Idle
```

This is running in development, so there are a couple differences, namely that the back-end is just another test Akka HTTP server instead of NGINX. But, I'm a bit confused as to how the entity is being consumed in this case, and why it may not be in other cases..... perhaps the back-end is too simple, and needs to do chunking to reproduce the leakage?

**Comment by jrudolph** [comment]
> perhaps the back-end is too simple, and needs to do chunking to reproduce the leakage?

Yes, exactly that's also needed to trigger the problem.

**Comment by DWvanGeest** [comment]
OK, fair enough. This seems to be our error then and I will close the bug. I do look forward to the pool infra being more tolerant of these sorts of errors.

Out of curiosity, I suppose that if we wanted to wanted to keep everything fully streaming, it would be necessary to keep the server request handling and the proxy request in the same graph? That would mean that a cancelled or timed-out user request would also hopefully cancel the proxy request properly.

**Comment by jrudolph** [comment]
> Out of curiosity, I suppose that if we wanted to wanted to keep everything fully streaming, it would be necessary to keep the server request handling and the proxy request in the same graph?

Not sure what you mean exactly with that.

> That would mean that a cancelled or timed-out user request would also hopefully cancel the proxy request properly.

I guess something like this was the issue here that not all of the streaming entities were actually connected by some piece of Akka HTTP infrastructure when a request or response was dropped for whatever reason. The general solution to that is probably to be more "lenient" when it comes to never subscribing to request / response entities. In previous versions we had subscription timeouts on those to clean up automatically after a short time. I think we need to introduce those again on the lower levels.

**Comment by DWvanGeest** [comment]
>> Out of curiosity, I suppose that if we wanted to wanted to keep everything fully streaming, it would be necessary to keep the server request handling and the proxy request in the same graph?

> Not sure what you mean exactly with that.

Sorry, I'm probably not being very clear or using the correct terminology. 

The fix to my issue involved converting the proxy response body into a strict entity, which I believe means that the whole body is read into memory. Hypothetically, if I wanted to avoid that, it seems that I would need to handle the user request and the proxy request together in one connected stream such that the cancelling of one request meant the other would also be cancelled. 

It seems to me that with the above code using the Future-based API, the two requests are handled in different and independent streams, which can lead to the issue we experienced.

Am I making any sense? I'm a bit new to this stuff. I really appreciate the time you're taking to talk this through.

**Comment by jrudolph** [comment]
> Hypothetically, if I wanted to avoid that, it seems that I would need to handle the user request and the proxy request together in one connected stream such that the cancelling of one request meant the other would also be cancelled.

Yes, exactly, that's how it should be ideally. 

In reality, the issue might then be, that it is still too easy to sometimes miss some response and drop an entity that has not been drained. We are currently trying to improve the situation to warn or auto discard an entity after a shorter while than the current idle-timeout.
