### ISSUE TITLE
current master fails to compile (on Scala 2.12.4)

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-http#1542]
```
[info] Compiling 7 Scala sources and 1 Java source to /Users/tisue/akka-http/akka-http-caching/target/scala-2.12/classes ...
[error] /Users/tisue/akka-http/akka-http-caching/src/main/scala/akka/http/caching/LfuCache.scala:93:39: Class javax.annotation.Nonnull not found - continuing with a stub.
[error]   private def dummyLoader[K, V] = new AsyncCacheLoader[K, V] {
[error]                                       ^
[warn] one warning found
[error] one error found
[error] (akka-http-caching/compile:compileIncremental) Compilation failed
```

this turned up in the Scala community build (at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2252/), but is also reproducible outside it

**Comment by SethTisue** [comment]
in the community build, working around it for now by freezing akka-http at an older commit: https://github.com/scala/community-builds/commit/bd612bfe6c7cb9ef46b8ce23e69ceecc970b849b

**Comment by jonas** [comment]
Caffeine has a dependency on [`com.google.code.findbugs:jsr305:3.0.2`](https://github.com/ben-manes/caffeine/blob/1f8ddd3773da0b97412bf4147b0d91832efc1e5f/gradle/dependencies.gradle#L108) which is marked [`provided`](https://github.com/ben-manes/caffeine/blob/1f8ddd3773da0b97412bf4147b0d91832efc1e5f/build.gradle#L87). We might have to have to do the same in the build.

I wonder if the reason we don't see it in the build (and locally) can be that the community build uses OpenJDK 8?

**Comment by SethTisue** [comment]
> I wonder if the reason we don't see it in the CI build (and locally) can be that the community build uses OpenJDK 8?

the community build does use OpenJDK 8

**Comment by SethTisue** [comment]
but, the problem is also reproducible on my macOS 10.3.1 machine on Oracle Java 8. I fire up sbt, run `++2.12.4` then `akka-http-caching/compile`, and boom.

**Comment by jonas** [comment]
Thanks @SethTisue for kindly restating the Scala version. Doh!
Fix proposed.
