### ISSUE TITLE
AhcWSClient in Akka-http 10.10 AcceptAnyCertificate

### ISSUE THREAD

**Issue by CodeCombiner** [akka/akka-http#1549]
Hi guys
I have posted details log here

[https://stackoverflow.com/questions/47445217/can-not-configure-ahcwsclient-in-akka-http-10-10-to-acceptanycertificate](https://stackoverflow.com/questions/47445217/can-not-configure-ahcwsclient-in-akka-http-10-10-to-acceptanycertificate)

In the post you can see: `config.wsClientConfig.ssl.loose.withAllowUnsafeRenegotiation(Some(true))` is set to true but log says:

Allow unsafe renegotiation: false
Is secure renegotiation: false

**Comment by raboof** [comment]
Hi @CodeCombiner! We try to use github issues only for tracking features and bugs, not for questions like this one. I'll answer on stackoverflow.

**Comment by CodeCombiner** [comment]
Hi @raboof , thank you and sorry, I thought is was potential issue with `ssl.loose` settings

**Comment by raboof** [comment]
No problem!
