### ISSUE TITLE
Add support for Retry-After Http header

### ISSUE THREAD

**Issue by ivanopagano** [akka/akka-http#1554]
As per [RFC7231](https://tools.ietf.org/html/rfc7231#section-7.1.3), add framework support to read and add the header from/to the response.

**Comment by ivanopagano** [comment]
The WIP branch is on my [fork](https://github.com/ivanopagano/akka-http/tree/retry-after-header-http-core) but I can't yet open a PR because I need support for a failing test for which I can't fathom the cause.

The failing test is [here](https://github.com/ivanopagano/akka-http/commit/10616a860d6ffd0e9efb316b5b5d7ad84c1caeb2#diff-49a3dd98ddc9a8db7812dc5d874fa512) and instead of converting the `h.toString` to the expected value of `Retry-After: 120` it serialize to `Content-Type: 120` (!).

I looked into the `HeaderParser` and `HttpHeader` definitions a few times without figuring out what's missing: any help is appreaciated.

**Comment by ivanopagano** [comment]
I would also appreciate to be directed to any other missteps

**Comment by ktoso** [comment]
> The WIP branch is on my fork but I can't yet open a PR because I need support for a failing test for which I can't fathom the cause.

To clarify: It's absolutely fine to open a PR and ask in there about the remaining issue :)

I'll look into it

**Comment by ivanopagano** [comment]
the test should be ok now, thanks to Rooney.
I'll run the `validatePullRequest` now to figure out if something else is missing.

**Comment by ivanopagano** [comment]
All issues have been solved and the PR is ready on its way to be picked up

Thanks everyone

**Comment by jrudolph** [comment]
Fixed in #1555.
