### ISSUE TITLE
FAILED: FileAndResourceDirectivesSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1573]
```

[info] - should reject requests to directory resources from an archive  *** FAILED ***
[info]   true did not equal false (FileAndResourceDirectivesSpec.scala:211)
```

Full logs: https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/347//consoleFull

**Comment by raboof** [comment]
Looks like this happened before #1565 was merged, let's close for now and reopen (or open a new one) if we see it again.
