### ISSUE TITLE
Jenkins akka-http-nightly-against-akka-release-2.4 is failing

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1574]
```

[info] Loading settings from build.sbt ...
Cloning into '/home/jenkins/.sbt/1.0/staging/b6b4d92ad38a8e4b5179/akka'...
/home/jenkins/.sbt/1.0/staging/b6b4d92ad38a8e4b5179/akka/project/plugins.sbt:1: error: value typesafeResolver is not a member of object sbt.Classpaths
resolvers += Classpaths.typesafeResolver
                        ^
[error] Type error in expression
```

Is this because 2.4 is not sbt 1.0? should we disable that build or upgrade sbt there?

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-release-2.4/338//consoleFull

**Comment by jonas** [comment]
Also reported in #1517

**Comment by ktoso** [comment]
Yeah, closing then. Makes quite a lot of noise... :-\

**Comment by jrudolph** [comment]
Yeah sorry forgot about that it was disabled and hit the rebuild button
yesterday.

Am 29.11.2017 03:57 schrieb "ktoso" <notifications@github.com>:
