### ISSUE TITLE
More precise error about forget to consume entity.

### ISSUE THREAD

**Issue by kghost** [akka/akka-http#1580]
Just find it is very hard to diagnose the problem that forget to consume entity of response.

The stream was closed silently, no error at all. The only hint I got is:

`Aborting tcp connection to 10.185.0.207:12345 because of upstream failure: TCP idle-timeout encountered on connection to [10.185.0.207:12345], no bytes passed in the last 1 minute
`

After digging several hours, only to find out that I forgot to discord the response entity.

Can we improve the error message a little bit, so people can know that connection is not reused and disconnected due to that the entity is not consumed.

**Comment by tom-walford** [comment]
The only similar error message I can see to this is the `HTTP idle-timeout encountered on connection to [..]`

However it might be worth adding a `If you're seeing this message in error, you might've forgotten to discard the response entity` to the error message - thoughts?

**Comment by jrudolph** [comment]
In the new client connection pool that will be the default in 10.1.0, we introduced a response entity subscription timeout which will quickly point out that a response entity was not subscribed to.

I think that solves the issue for now. Thanks for raising it, @kghost.
