### ISSUE TITLE
404s for source code for this page links

### ISSUE THREAD

**Issue by brharrington** [akka/akka-http#1581]
The "The source code for this page can be found here." links at the bottom of some of the documentation pages results in a 404. One example:

https://doc.akka.io/docs/akka-http/current/java/http/server-side/server-https-support.html

Links to:

http://github.com/akka/akka-http/tree/master/docs/src/main/paradox/java/http/server-side/server-https-support.md

It looks like in the repo, the `java/http/server-side` is a link to `scala/http/server-side`, but that seems to break the links back to the repo.

**Comment by jonas** [comment]
Thanks for reporting this. Yes, this is indeed a problem. Once we complete the consolidation of the Java and Scala documentation (#1290) we should be able to fix this by removing the `java/http` and `scala/http` prefix.

**Comment by jlprat** [comment]
This issue might be fixed by: https://github.com/akka/akka-http/pull/1710

**Comment by jrudolph** [comment]
Good catch, it seems this is now indeed fixed according to the snapshot that @raboof published to https://doc.akka.io/docs/akka-http/10.0.11+154-91b7071b+20171222-1715/
