### ISSUE TITLE
Binary incompatibility in 10.0.11 vs 10.0.10

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#1603]
Some bridge methods to the old API in HttpExt taking an implicit materializer are private in 10.0.11.
They used to be public API as far as I understand.

* `def cachedHostConnectionPoolHttps[T]` with materializer
* `def cachedHostConnectionPool[T]` with materializer

possibly even more

**Comment by jrudolph** [comment]
Thanks for the report, @ennru. Did you encounter any really problems with this? We marked them as `private[http]` which means they cannot be used any more when newly compiling. However, `private[http]` is compiled into `public` when you look at the bytecode which means that binary compatibility should still be maintained.

There's a potential source incompatibility if you passed the materializer explicitly.

**Comment by ennru** [comment]
I discovered it as a source incompatibility in the Alpakka DynamoDb module which has an explicit materializer parameter (for no particular reason as far as I can see).
Didn't know that `private[...]` becomes effectively public in bytecode.

**Comment by jrudolph** [comment]
Yes, we are not as strict about source compatibility but it would have been good to be mentioned in the release notes.

**Comment by 2m** [comment]
Ahh, then it was not an oversight, but a smart foresight by @jrudolph :)

Sorry about not realizing this earlier.

**Comment by jlprat** [comment]
Then we might convert this task to document a source incompatibility for 10.0.11. WDYT?

**Comment by jrudolph** [comment]
Yes, see #1607.
