### ISSUE TITLE
Create outgoingConnection from uri ?

### ISSUE THREAD

**Issue by fmeriaux** [akka/akka-http#1611]
Hello,

I work regularly with the client connection level, and I usually pass the server uri in configuration.

So I regularly have this snippet of code : 

```scala
 private val uri = Uri(Configuration.apiUrl)

val connectionFlow: Flow[HttpRequest, HttpResponse, _] = uri.scheme match {
    case "https" => Http().outgoingConnectionHttps(host = uri.authority.host.address(), port = uri.effectivePort)
    case "http" => Http().outgoingConnection(host = uri.authority.host.address(), port = uri.effectivePort)
    case unsupported =>
      throw new UnsupportedSchemeException(s"Unsupported scheme '$unsupported', must be http or https")
  }
```

I think it might be interesting to include a creation function from an URI with all custom parameters.

```scala
Http().outgoingConnectionUri(uri /*, more parameters */)
```

If you agree, I would attach it to PR.

**Comment by jrudolph** [comment]
Seems we never answered on that one. It sounds as if `Http().singleRequest` might be a better fit for the use case.

Closing for now.

**Comment by jrudolph** [comment]
Seems we never answered on that one. It sounds as if `Http().singleRequest` might be a better fit for the use case.

Closing for now.
