### ISSUE TITLE
Convert remaining akka.io links to HTTPS

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#1620]
It looks like <akka.io> now supports HTTPS, so it would be nice to have [links](https://github.com/akka/akka-http/search?l=Markdown&q=%22akka.io%22+http%3A%2F%2F&type=&utf8=%E2%9C%93) from the README and Paradox documentation use it by default.

#1579 started converting Paradox links in the `build.sbt` but a few remain.

**Comment by jrudolph** [comment]
Fixed by #1621.
