### ISSUE TITLE
LegacyConnectionPoolSpec: The superPool client infrastructure be able to handle 500 pipelined requests with connection termination

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1643]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1904/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/be_able_to_handle_500_pipelined_requests_with_connection_termination/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1905/consoleFull

**Comment by jlprat** [comment]
Another one: https://jenkins.akka.io:8498/job/pr-validator-akka-http/1936/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/16/testReport/akka.http.impl.engine.client/LegacyConnectionPoolSpec/be_able_to_handle_500_pipelined_requests_with_connection_termination/

**Comment by jrudolph** [comment]
Didn't happen for a long time.
