### ISSUE TITLE
HTTPS cached connection pool

### ISSUE THREAD

**Issue by rraziel** [akka/akka-http#1644]
I've been using this for a while, to have a flow going towards a host (this is a reverse proxy application), which works fine:
```java
Http.get(actorSystem).cachedHostConnectionPool(someConnectHttp);
```

However when `someConnectHttp` is an HTTPS target, the scheme is ignored.
I noticed there is a `cachedHostConnectionPoolHttps`, but it takes some settings and a logging adapter.

Is there an HTTPS equivalent to the simple `cachedHostConnectionPool`? And if not, shouldn't there be one (or couldn't it at least handle HTTPS targets)?

**Comment by jrudolph** [comment]
Thanks for the report @rraziel. It seems there's indeed an overload missing in the javadsl which just takes a `host` and uses default (Https and other) settings otherwise.

**Comment by jrudolph** [comment]
Fixed by #1665.

**Comment by ktoso** [comment]
Forgot to close the issue?

**Comment by jrudolph** [comment]
Woops, thanks ;)
