### ISSUE TITLE
HostConnectionPoolSpec.LegacyPoolImplementation on PassThrough should create a new connection when previous one failed between requests

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1653]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1915/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/
```
java.lang.AssertionError: assertion failed: timeout (4500 milliseconds) during expectMsgClass waiting for class akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$SetupWithServerProbes$2$ServerConnection
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:508)
	at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:481)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:882)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$SetupWithServerProbes$2.expectNextConnection(HostConnectionPoolSpec.scala:444)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$16$$anon$12.<init>(HostConnectionPoolSpec.scala:269)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$16.apply(HostConnectionPoolSpec.scala:259)
	at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$16.apply(HostConnectionPoolSpec.scala:259)
```

**Comment by jrudolph** [comment]
On release-10.0 branch:

https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-release-10.0-against-akka-master/lastCompletedBuild/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1963/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/5/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/5/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1973/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
Almost the same:

https://jenkins.akka.io:8498/job/pr-validator-akka-http/2012/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineNoNetwork_should_create_a_new_connection_when_previous_one_was_closed_regularly_between_requests/

**Comment by jlprat** [comment]
Another one: #1719

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/375/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master-on-2.12/6/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/7/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master/9/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_was_closed_regularly_between_requests/

**Comment by jrudolph** [comment]
The same on AkkaHttpEngineNoNetwork:

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/10/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineNoNetwork_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/16/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
Disabled in #1735.
