### ISSUE TITLE
FAILED: NewConnectionPoolSpec: should respect the configured `maxRetries` value

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1667]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1934/consoleFull
```
[info] - should respect the configured `maxRetries` value *** FAILED ***
[info]   5 did not equal 0 (ConnectionPoolSpec.scala:267)
```

**Comment by jlprat** [comment]
Another occurrence:
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2019/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/6/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by johanandren** [comment]
Duplicate or related perhaps: #1502

**Comment by jrudolph** [comment]
This one is for the new implementation and #1502 for the old. If the test is to blame then it could indeed solved both at the same time.

**Comment by johanandren** [comment]
Looking at the test case for a bit I can't see how it could possibly be the test that is faulty

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4-on-scala-2.12/25/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by jrudolph** [comment]
Likely fixed by now.
