### ISSUE TITLE
LegacyConnectionPoolSpec:The host-level client infrastructure should never close hot connections when minConnections key is given and >0

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1669]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1936/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2052/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/76/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
Didn't happen for a long time (doesn't make much sense to fix LegacyPool issues).

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/616/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/
