### ISSUE TITLE
X-Real-IP should probably be preferred over X-Forwarded-For in _extraClientIP directive?

### ISSUE THREAD

**Issue by timorantalaiho** [akka/akka-http#1670]
Hello,

I was happy to find a [utility to find out the real client IP address](https://github.com/akka/akka-http/blob/e7301c8128f666730e865b35a3e75b022a615bba/akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala#L109-L113) in akka-http. However, it seems to prefer the first in list of `X-Forwarded-For` instead of `X-Real-IP`.

It seems that even though the leftmost value of `X-Forwarded-For` is generally the original client IP address, [this is not universally so](http://totaluptime.com/kb/prevent-x-forwarded-for-spoofing-or-manipulation/), and there exist modules for at least Apache and Nginx web servers to provide the correct resolution of the client IP address and setting it as the `X-Real-IP` value.

So maybe `X-Real-IP` should be prioritised over the first address of `X-Forwarded-For`?
There could also be a log message (at least on INFO level) if the `X-Forwarded-For` contained multiple addresses without the presence of `X-Real-IP`, preferable including the value of `X-Forwarded-For`.

**Comment by raboof** [comment]
I'm not so sure.

Usually the reason for using [extractClientIP](https://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/misc-directives/extractClientIP.html#extractclientip) is for some kind of 'security' feature, where you know there are some routers that you control in front of your application.

When using `X-Forwarded-For`, routers can append to the list of addresses, making the first value the 'original' IP. Of course, an attacker could add his own `X-Forwarded-For` of `X-Real-IP` header. It is up to you to make sure your routers to avoid passing along `X-Forwarded-For` or `X-Real-IP` headers from untrusted sources.

I don't see a clear reason to prioritise `X-Real-IP` over `X-Forwarded-For`. `X-Forwarded-For` could be a little more reliable when you have multiple proxies in your infrastructure, though you will indeed still be responsible to configure those proxies not to forward data from untrusted sources.

Moreover, we can't really reverse the behavior of [extractClientIP](https://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/misc-directives/extractClientIP.html#extractclientip) at this point: that would mean users that have set up their proxies to publish the correct `X-Forwarded-For` could be compromised by attackers adding an `X-Real-IP` header.

Does that make sense? We should add this kind of information to the documentation btw.

**Comment by timorantalaiho** [comment]
Thanks, maintaining backwards compatibility is a very good point. I guess that our setup of determining the real client IP address by filtering out the trusted proxies from `X-Forwarded-For` (with [ngx_http_realip_module](http://nginx.org/en/docs/http/ngx_http_realip_module.html) of nginx)  _and_ storing the real customer IP to `X-Real-IP` is coincidental in the end. We just have to refrain from using `extractClientIP` and read and log the relevant headers by ourselves.
