### ISSUE TITLE
Jackson support for Scala DSL

### ISSUE THREAD

**Issue by danielyli** [akka/akka-http#1684]
I noticed that the `akka-http-jackson` package is under the `javadsl` package but not the `scaladsl`.  Is there a reason for this?

**Comment by jrudolph** [comment]
Right now we recommend to use one of the Scala JSON libraries on the Scala side.

**Comment by ktoso** [comment]
Feel free to use this library of JSON library marshallers for akka http:
https://github.com/hseeberger/akka-http-json

It also has jackson if you want to use it.
