### ISSUE TITLE
FAILED: LegacyConnectionPoolSpec.The host-level client infrastructure should respect the configured `maxRetries` value

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1690]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1977/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

```
Error Message

2 did not equal 0

Stacktrace

org.scalatest.exceptions.TestFailedException: 2 did not equal 0
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6742)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anon$12.<init>(ConnectionPoolSpec.scala:266)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(ConnectionPoolSpec.scala:249)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(ConnectionPoolSpec.scala:249)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/397/testReport/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/30/testReport/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.4/lastCompletedBuild/testReport/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2497/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_respect_the_configured__maxRetries__value/

**Comment by raboof** [comment]
The logging shows the route indeed crashes only 3 times before finishing the test, explaining the `2 did not equal 0` error (we expected 4 retries, so 5 crashes). Since this happens only in the legacy pool, perhaps makes sense to disable the test there?
