### ISSUE TITLE
Http: `DeflateCompressor.compressAndFinish` uses unbounded buffer for data compression

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#171]
<a href="https://github.com/ataraxer"><img src="https://avatars.githubusercontent.com/u/1394955?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ataraxer](https://github.com/ataraxer)**
_Tuesday Dec 08, 2015 at 07:21 GMT_
_Originally opened as https://github.com/akka/akka/issues/19119_

---

Original discussion can be found at #19100.

Possible solutions:
- add upper bound for buffer size;
- allow to configure buffer size in a similar to `DeflateDecompressor` way for consistency and transparency (would require incompatible changes, might be a good idea to squeeze this one before 2.0 releases);
- add scaladoc warning about potential extensive memory footprint for large inputs.

**Comment by jrudolph** [comment]
Doesn't really matter. The buffer is not really unbounded but as large as the input. In any case you have to expect some buffer copying around during such an operation. (Also the API is not used by akka-http itself)
