### ISSUE TITLE
Security docs page caught in redirect loop in /current/ (1.1.0-RC1)

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1714]
Redirect loop for the RC for the security announcements.

See: http://doc.akka.io/docs/akka-http/current/security.html?language=scala

Seems the redirects somehow don't quite work (loop around)

> Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
>    This problem can sometimes be caused by disabling or refusing to accept cookies.

Workaround: Browse https://doc.akka.io/docs/akka-http/10.0.10/scala/http/security.html instead

**Comment by raboof** [comment]
should be fixed now, thanks for the heads-up!

**Comment by jlprat** [comment]
I can confirm it works for me :+1:

**Comment by jrudolph** [comment]
Thanks, @raboof for the quick fix. What was broken?

**Comment by raboof** [comment]
There was an outdated redirect in `/etc/apache2/conf-available/redirects.conf` - I think it was specific to the `security` section, but I don't remember exactly

**Comment by jrudolph** [comment]
Ah, I see, thanks for the explanation. I guess it was from before our current `.htaccess` file solution.

**Comment by raboof** [comment]
Jup, very happy we can have those under version control now :)
