### ISSUE TITLE
Anomaly with presumed default rejection handler (akka-http 10.1.0-RC1)

### ISSUE THREAD

**Issue by akauppi** [akka/akka-http#1716]
![screen shot 2017-12-28 at 14 25 04](https://user-images.githubusercontent.com/1297734/34417433-d0afaf7a-ebf8-11e7-859c-2be53531e3b8.png)

I saw this today, and have tried to find what causes the weird class mentioning at the `title` field. Unfortunately, I didn't find the culprit, even after looking into akka-http sources.

Filing it here in case it raises enough eyebrows and is indeed caused by the akka-http default rejection handler.

What happens is: my code has a query parameter marshaller, which throws a `RuntimeException`. There is a rejection handler for not matching paths, but this case should be passed on to akka-http in that code.

Then, I think akka-http does the handling, and for some reason concatenates an unnecessary class instance to the otherwise meaningful "Request rejected" string.

I am truly sorry if this is not, indeed, an akka-http issue. Not able to make a minimum project that would showcase it, either, I'm afraid.

akka-http 10.1.0-RC1

**Comment by jrudolph** [comment]
Thanks for the report, @akauppi. The "Request rejected" error message and the json formatting of errors is not part of akka-http, so maybe you are using some third-party library / directives that produce these kinds of messages?

**Comment by akauppi** [comment]
Thanks for the comment. I think this is noise, and will close it. 

Tried to check all non-akka-http causes first, but may have missed some.
