### ISSUE TITLE
FAILED. LegacyPoolImplementation on AkkaHttpEngineNoNetwork should create a new connection when previous one was closed regularly between requests

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1721]
Encountered in #1719
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2020/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineNoNetwork_should_create_a_new_connection_when_previous_one_was_closed_regularly_between_requests/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/13/testReport/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineNoNetwork_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by jrudolph** [comment]
Probably very similar to #1653

**Comment by jrudolph** [comment]
Test disabled in #1735.
