### ISSUE TITLE
NewConnectionPoolSpec.The host-level client infrastructure should retry failed requests

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1722]
Occurred in #1719 
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2024/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_retry_failed_requests/

**Comment by ktoso** [comment]
Again here https://jenkins.akka.io:8498/job/pr-validator-akka-http/2385/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/be_able_to_handle_500__Connection__close__requests_against_the_test_server/

**Comment by jrudolph** [comment]
Didn't happen for a long time and logs have been deleted by now.
