### ISSUE TITLE
FAILED NewConnectionPoolSpec.The host-level client infrastructure should never close hot connections when minConnections key is given and >0 (minConnections = 5)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1726]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/8/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

```
Error Message

assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnNext

Stacktrace

java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnNext
	at scala.Predef$.assert(Predef.scala:219)
	at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:508)
	at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:481)
	at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:481)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:882)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:374)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anon$17.$anonfun$new$23(ConnectionPoolSpec.scala:341)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anon$17.$anonfun$new$23$adapted(ConnectionPoolSpec.scala:336)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anon$17.<init>(ConnectionPoolSpec.scala:336)
	at akka.http.impl.engine.client.ConnectionPoolSpec.$anonfun$new$22(ConnectionPoolSpec.scala:326)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4/15/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2089/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/31/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-against-akka-2.5/31/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/31/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5-on-2.12/32/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/401/testReport/junit/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-against-akka-master-on-2.12/lastCompletedBuild/testReport/akka.http.impl.engine.client/NewConnectionPoolSpec/The_host_level_client_infrastructure_should_never_close_hot_connections_when_minConnections_key_is_given_and__0__minConnections___5_/
