### ISSUE TITLE
FAILED: akka.http.impl.engine.client.LegacyConnectionPoolSpec.The host-level client infrastructure should not open a second connection if there is an idle one available

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1758]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master/407/testReport/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_not_open_a_second_connection_if_there_is_an_idle_one_available/

```
Error Message

Expected OnNext(_), yet no element signaled during 5 seconds

Stacktrace

java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 5 seconds
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anon$7.<init>(ConnectionPoolSpec.scala:138)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ConnectionPoolSpec.scala:127)
	at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ConnectionPoolSpec.scala:127)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/21/testReport/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_not_open_a_second_connection_if_there_is_an_idle_one_available/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/2096/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_not_open_a_second_connection_if_there_is_an_idle_one_available/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-against-akka-2.5/31/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_not_open_a_second_connection_if_there_is_an_idle_one_available/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/39/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master/433//consoleFull

**Comment by jrudolph** [comment]
Seems like a test prone to race conditions. See https://github.com/akka/akka-http/pull/1826 for an attempt to make it less likely. We could also mark the test as pending as long as it cannot be observed in a deterministic fashion.

**Comment by jrudolph** [comment]
Still failed:

https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-release-10.0-against-akka-master-on-2.12/47/testReport/junit/akka.http.impl.engine.client/LegacyConnectionPoolSpec/The_host_level_client_infrastructure_should_not_open_a_second_connection_if_there_is_an_idle_one_available/

**Comment by jrudolph** [comment]
The last failure was on release-10.0 branch which hasn't got the fix so everything seems to be well.

**Comment by ktoso** [comment]
great!
