### ISSUE TITLE
FAILED: LegacyPoolImplementation on PassThrough create a new connection when previous one failed between requests 

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1765]
```

[info] - should create a new connection when previous one failed between requests *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.http.impl.engine.client.HostConnectionPoolSpec$SetupWithServerProbes$2$ServerConnection
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:508)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:481)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:481)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:890)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$SetupWithServerProbes$2.expectNextConnection(HostConnectionPoolSpec.scala:444)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$$anon$12.<init>(HostConnectionPoolSpec.scala:269)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec.$anonfun$testSet$17(HostConnectionPoolSpec.scala:259)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master-on-2.12/27//consoleFull

I thought we don't run the Legacy one anymore?

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/396/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_AkkaHttpEngineTCP_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master/25/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/LegacyPoolImplementation_on_PassThrough_should_create_a_new_connection_when_previous_one_failed_between_requests/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-master-on-2.12/26/

**Comment by jrudolph** [comment]
Test was disabled for now in #1788.
