### ISSUE TITLE
Support OAuth2 access token in URI query component as defined in RFC6750

### ISSUE THREAD

**Issue by mwegrz** [akka/akka-http#1769]
Currently OAuth2 authentication in Akka HTTP supports access tokens only in `Authorization: Bearer ..` header. [RFC6750 in section 2.3](https://tools.ietf.org/html/rfc6750#section-2.3) allows (but does not recommend) including access tokens also in the URI query component. Akka HTTP might support this use case and leave the decision what method to use to the client making the call.

**Comment by jrudolph** [comment]
Implemented in #1771.
