### ISSUE TITLE
Failed: NewPoolImplementation on PassThrough should fail a request if the connection stream fails while waiting for request entity bytes

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#1770]
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-2.5/27/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_PassThrough_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
Let's treat this as a duplicate of #1757.
