### ISSUE TITLE
Failed: NewPoolImplementation on AkkaHttpEngineTCP should fail a request if the connection stream fails while waiting for request entity bytes

### ISSUE THREAD

**Issue by 2m** [akka/akka-http#1782]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4/33/testReport/junit/akka.http.impl.engine.client/HostConnectionPoolSpec/NewPoolImplementation_on_AkkaHttpEngineTCP_should_fail_a_request_if_the_connection_stream_fails_while_waiting_for_request_entity_bytes/

**Comment by jrudolph** [comment]
Probably same as #1757.
