### ISSUE TITLE
Uri.Path ?/ operator

### ISSUE THREAD

**Issue by tg44** [akka/akka-http#1793]
We can write something like this now:
`Path("abc") / "def"` which will be `abc/def`
But if we have a tailing / we will get:
`Path("abc/") / "def"` => `abc//def` which is not so handy

If you use akka-http-core as a http client too this small thing is really irritating... So I wrote a small helper to solve this problem, but it would be better in the official lib.
(PR coming.)

**Comment by jrudolph** [comment]
Fixed by #1794.
