### ISSUE TITLE
osgi.ee require capability in manifest file is wrong

### ISSUE THREAD

**Issue by mrulli** [akka/akka-http#1797]
The following directive in the akka-http manifest is invalid:

`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8.0_144))"`

version should be formatted as a valid OSGi version as follows:

`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"`

**Comment by jrudolph** [comment]
The osgi support of akka-http is unmaintained and will probably be removed as long as no maintainer steps up that can provide support to fix issues like that and more importantly makes sure that releasing doesn't break regularly.

**Comment by jrudolph** [comment]
OSGi is still gone, so there's currently nothing to fix.
