### ISSUE TITLE
Server request timeouts are silent

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1810]
When the server request timeout triggers (`akka.http.server.request-timeout`, https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L302), we produce a `503` response with a nice message, but the logging is silent.

While this could happen during normal operation, it is also something that might point to a problem, so it might make sense to log at INFO level when this timeout is hit (and leave it up to monitoring solutions to give more detailed insight)?

**Comment by jrudolph** [comment]
:+1:

**Comment by napgab** [comment]
Is there any way to control the default behaviour of the log in case of timeout? Sometimes a timeout can be considered an ERROR, so INFO level can be too low... Moreover, the default log string "Request timeout encountered for request ...." contains a very low amount of information and could be useful have a way to specify a default handler for timeouts (for example, print the body of the request if it is smaller than X bytes).
