### ISSUE TITLE
Ability to access current response timeout

### ISSUE THREAD

**Issue by kag0** [akka/akka-http#1811]
It's currently possible to modify the request timeout with the `withRequestTimeout` directive which internally uses the `Timeout-Access` header and `TimeoutAccess` trait. However, it's not possible to access the currently set request timeout. If we added a method like `getRequestTimeout` to the `TimeoutAccess` trait then it would be easy to add an `extractRequestTimeout` directive to retrieve that value.

[related SO](https://stackoverflow.com/questions/48433026/how-to-get-the-current-server-request-timeout-in-akka-http)

**Comment by jrudolph** [comment]
Seems simple enough I agree.

**Comment by kag0** [comment]
took a quick pass at a pr https://github.com/akka/akka-http/pull/1828

**Comment by jlprat** [comment]
The corresponding PR is merged, so I guess we can close thin one.
And it's actually released under 10.1.0 if I'm not mistaken

**Comment by jrudolph** [comment]
:+1:

Am 14.03.2018 19:49 schrieb "Josep Prat" <notifications@github.com>:
