### ISSUE TITLE
"Illegal character ' ' in chunk start" for some pages when parsing response with akka-http

### ISSUE THREAD

**Issue by SakulK** [akka/akka-http#1812]
This is my example/test page: http://archiwum.teatrszekspirowski.pl/
I attached a stacktrace which isn't all that useful but I tried to debug the problem and found out that it is in HttpMessageParser.parseChunk.parseSize, there is no case for whitespace characters and an error is thrown:
https://github.com/akka/akka-http/blob/40bd7a2d14ecd92eb1527d43a3f56d51e2c17e23/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala#L246
I tried a dirty hack by simply adding a case like this:
`case c if CharacterClasses.WSP(c) ⇒ parseSize(cursor + 1, size)`
And it does 'fix' the problem but I don't know how to actually do it properly. Also found a bug report with the same issue in spray:
https://github.com/spray/spray/issues/1063
I can create a pull request with a fix if someone can give me advice what would be the correct way of fixing this issue.
This is the mentioned stacktrace:
>  akka.http.scaladsl.model.EntityStreamException:
> 
>  Illegal character ' ' in chunk start
> 	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$chunkedEntity$1$$anonfun$2.applyOrElse(HttpMessageParser.scala:329)
> 	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$chunkedEntity$1$$anonfun$2.applyOrElse(HttpMessageParser.scala:327)
> 	at akka.stream.impl.fusing.Collect$$anon$2$$anonfun$10.apply(Ops.scala:212)
> 	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:173)
> 	at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:214)
> 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
> 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
> 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
> 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
> 	at akka.actor.Actor$class.aroundReceive(Actor.scala:514)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
> 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
> 	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
> 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
> 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ktoso** [comment]
Thanks for the report with reproducer.
Wrapping up for today (JST timezone...), but will look into next week.

Just requesting the main page causes the error?

**Comment by SakulK** [comment]
I tried requesting a few links from that domain and all had the same problem.

Thanks, have a nice weekend :)

**Comment by ktoso** [comment]
Looking into it today

**Comment by ktoso** [comment]
So it seems your webserver is rendering chunks in an illegal way (it violates the HTTP spec's Chunked format). It adds 2 spaces after a single digit chunked size:

![capturing_from_wi-fi__en0](https://user-images.githubusercontent.com/120979/35495536-acfe9206-0504-11e8-92be-78d5a3857e8a.png)

(green is chunk size 2, then the weird spaces, followed by the right `\r\n`, then yellow being the last piece, that's valid).

Which is illegal according to the spec: 

```
     chunked-body   = *chunk
                      last-chunk
                      trailer-part
                      CRLF

     chunk          = chunk-size [ chunk-ext ] CRLF
                      chunk-data CRLF
     chunk-size     = 1*HEXDIG
     last-chunk     = 1*("0") [ chunk-ext ] CRLF

     chunk-data     = 1*OCTET ; a sequence of chunk-size octets
```

https://tools.ietf.org/html/rfc7230#section-4.1

So... your server is doing weird things, but it seems it's just plain php and apache...:

```
< HTTP/1.1 200 OK
< Date: Mon, 29 Jan 2018 05:21:06 GMT
< Server: Apache/1.3.34 (Debian) PHP/4.3.10 mod_gzip/1.3.26.1a
< X-Powered-By: PHP/4.3.10
< Transfer-Encoding: chunked
```

So, I guess perhaps we could add the additional check as you propose. WDYT @jrudolph ? Have a patch ready, but as it's just what @SakulK proposes we may ask him to submit the PR, WDYT?

**Comment by SakulK** [comment]
I created a pull request since I had it ready anyway ;)
