### ISSUE TITLE
websocket-support - The documentation is messed up

### ISSUE THREAD

**Issue by dxxvi** [akka/akka-http#1818]
https://doc.akka.io/docs/akka-http/current/server-side/websocket-support.html in the Server API section.

**Comment by raboof** [comment]
Oops you're right! The source for this page is at https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/server-side/websocket-support.md , would you be interested in taking a stab at it yourself?

**Comment by ktoso** [comment]
Thanks for the follow up ticket after the twitter ping ;-) I'll fix it quickly.

**Comment by ktoso** [comment]
Seems solved on master already, I think it may have been a paradox version update?

![server-side_websocket_support_ _akka_http](https://user-images.githubusercontent.com/120979/35491226-7cd87338-04e8-11e8-9779-90ec3c7b0bb7.png)

**Comment by ktoso** [comment]
Thanks for reporting :) We'll release this week so this will be fixed

**Comment by raboof** [comment]
Uh, except 10.0.10+129 is not latest master :). I'll give it a shot :)

**Comment by ktoso** [comment]
Oh lol :) Seems I forgot to pull before checking, got a fix though :)

**Comment by ktoso** [comment]
Fixed now!
