### ISSUE TITLE
getFromFile resulting in 404 when doing a refresh (w/ if-modified-since headers)

### ISSUE THREAD

**Issue by minamesephy** [akka/akka-http#1838]
I'm using akka-http for my React-based single page application's web  server, and having issues where when I refresh my website. I get back a  404 for the requested resource (just getFromFile for index.html). 
```
~ {
  getFromFile(s"$STATIC_CONTENT_ROOT/index.html")
}
```

Doing a "super  refresh" (ctrl + refresh) works fine and everything loads as expected.  But when I do a normal refresh, and the if-modified-since or if-none-match headers are included in the request headers, I noticed that the server gives back a  404 response. 

I did some more digging and found the directive code for getFromFile():
https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L58-L78

I updated my router settings to set withFileGetConditional(false) and this solved the issue. 
However, when this was true instead of false, why did it return a 404 instead of a 304, as mentioned here: https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/cache-condition-directives/conditional.html ?

**Comment by raboof** [comment]
Interesting, that sounds like a bug. Would you have a chance to come up with a small example project or even a unit test that demonstrates it?

**Comment by raboof** [comment]
Hmm, I looked at the code paths a bit and don't see a path that would return a 404 there.

Shot in the dark: is this for resources that are auto-updated by your react toolchain? In that case perhaps `file.isFile && file.canRead` is temporarily false and leads to the 404? If that was the issue then I don't see how `withFileGetConditional(false)` could have helped though...

**Comment by jrudolph** [comment]
Closing for now lacking new information. Please comment or reopen, @minamesephy if you still think there's a problem in akka-http.
