### ISSUE TITLE
Issues around log directives in docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#1841]
Broken markup on this page: https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/debugging-directives/logRequestResult.html#building-advanced-directives

Also, the page refers to a `logResponseTime` that doesn't seem to have any docs at all? Does it really exist?

**Comment by jlprat** [comment]
I fail to see the broken markup in that page.

**Comment by johanandren** [comment]
Sorry, should have been more clear/detailed about that:

<img width="758" alt="screen shot 2018-02-08 at 10 00 40" src="https://user-images.githubusercontent.com/666915/35964094-fa46783a-0cb6-11e8-8912-1ccb2e65cd21.png">

**Comment by jlprat** [comment]
Ah! I see

**Comment by Philippus** [comment]
@johanandren the page is showing how to build your own `logResponseTime` directive as an example
