### ISSUE TITLE
Support trailing request and response headers in HTTP/2

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1843]
Challenges:

 * incoming request: Http/2 allows trailers on entities with or without content length set, however, our model only allows trailers in Chunked requests (potential solution: always throw away length info and create chunked ones to be prepared for trailers?)
 * `Http2SubStream` does not support trailers so far in its model which models entities as `Source[ByteString]`

**Comment by jrudolph** [comment]
The problem that we cannot support content-length and trailers at the same time can maybe solved differently for requests and responses:

 * for requests, we can choose not to change trailer behavior for now (i.e. keep ignoring them) since grpc does not require request trailers
 * for responses, make sure that we support trailers when an `HttpEntity.Chunked` is given, for that we need to change `Http2SubStream` (or create another variant) to support `ChunkStreamPart` elements instead of plain `ByteString`

Changes are necessary
 * in `ResponseRendering` to pass the `ChunkStreamPart` to the `Http2SubStream`
 * in `Http2Multiplexer` to actually produce `ParsedHeadersFrame` for `LastChunk` if trailers are defined (Or should frame generation live in `ResponseRendering` as well and `Http2SubStream` should deliver frames directly? Anyway it needs to work with buffer management in `Http2Multiplexer`.)

**Comment by raboof** [comment]
Sending headers is done in #1857, let's track receiving headers in #1869
