### ISSUE TITLE
store and retrieve password

### ISSUE THREAD

**Issue by rain101** [akka/akka-http#1850]
Hey, I am new to Akka, when I go through official document about [https support](https://doc.akka.io/docs/akka-http/current/server-side/server-https-support.html), this line puzzles me:
`val password: Array[Char] = "change me".toCharArray // do not store passwords in code, read them from somewhere safe!"`
I assume val password = "somepassword".toCharArray is not safe, because it says not to store them in code. What other option do we have, where is good place to store passwords? In application.conf? In a xml or json file? I google a bit and couldn't find any answer, hope somebody knows it.

Cheers!

**Comment by ktoso** [comment]
Same as with any password for any system.
You can use various secret management tools or environment variables.
Depending on your cloud provider they also may have solutions for storing
secrets.

-- 
Konrad Malawski

**Comment by rain101** [comment]
@ktoso Thank for replying, I will just use Vault.

**Comment by ktoso** [comment]
sounds good. closing
