### ISSUE TITLE
Clarify Path matcher pipe operator followed by  /

### ISSUE THREAD

**Issue by subotic** [akka/akka-http#1861]
According to the [docs](https://doc.akka.io/docs/akka-http/current/routing-dsl/path-matchers.html#combinators) (at least as I understand them), the path matcher pipe operator `"foo" | "bar"` will match either “foo” or “bar”, e.g.,

```
val path = path("v1" | "v2" / "fu") {
    complete("fu")
}

Get ("/v1/fu") ~> path ~> check {
    responseAs[String] should be ("fu")
}

Get ("/v2/fu") ~> path ~> check {
    responseAs[String] should be ("fu")
}
```

This results in `Request was rejected` and not the expected "fu" string.
Tried on `10.0.11` and `10.1.0-RC2`.

**Comment by ktoso** [comment]
You're right that's what it does, however when combined with something after such pair, you have to embrace the `|` pair in a `()` otherwise the `/` applies only to the latter (bar) AFAICS:

```
  """pathPrefix("foo" | "bar" / "example")""" should {
    val test = testFor(pathPrefix(("foo" | "bar") / "example") { echoUnmatchedPath })
    // nope:    val test = testFor(pathPrefix("foo" | "bar" / "example") { echoUnmatchedPath })
    "accept [/foo/example]" inThe test("")
    "accept [/bar/example]" inThe test("")
    "reject [/baz]" inThe test()
    "reject [/bar/nein]" inThe test()
  }

```

I'll improve the docs around this now, thanks for reporting

**Comment by subotic** [comment]
great, thanks,
