### ISSUE TITLE
Having issue with setDefaultClientHttpsContext 

### ISSUE THREAD

**Issue by fadzlyzahari** [akka/akka-http#1866]
Hi,

I have an issue with setDefaultClientHttpsContext. My code is as below:

```scala
Http().setDefaultClientHttpsContext(ConnectionContext.https(keystoreHandling(path, password)))
      port match {
        case -1 => Http().outgoingConnectionHttps(host)
        case _ => Http().outgoingConnectionHttps(host, port)
      }
```

```scala
def keystoreHandling(path: String, passwordDR: DRPassword): SSLContext = {

    object NoCheckX509TrustManager extends X509TrustManager {
      override def checkClientTrusted(chain: Array[X509Certificate], authType: String) = ()

      override def checkServerTrusted(chain: Array[X509Certificate], authType: String) = ()

      override def getAcceptedIssuers = Array[X509Certificate]()
    }
    val context = SSLContext.getInstance("TLS")
    if (path == null || path.isEmpty) {
      context.init(Array[KeyManager](), Array(NoCheckX509TrustManager), null)
    }else {
      println("Keystore Path: " + path + ", Path empty string: " + path.isEmpty)
      val password: Array[Char] = passwordDR.getValue.toCharArray
      val ks: KeyStore = KeyStore.getInstance("JKS")
      ks.load(new FileInputStream(path), password)

      val keyManagerFactory: KeyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm)
      keyManagerFactory.init(ks, password)

      val tmf: TrustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm)
      tmf.init(ks)

      context.init(keyManagerFactory.getKeyManagers, tmf.getTrustManagers, new SecureRandom)
    }
    context
  
```

It seems fine if value for both keystore path and password is empty. 
But it does not work if i put value of the keystore path and password.

I get an error like this:

```
Feb 19 17:09:36: ***
Feb 19 17:09:36: restClient-akka.actor.default-dispatcher-14, fatal error: 46: General SSLEngine problem
Feb 19 17:09:36: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Feb 19 17:09:36: %% Invalidated:  [Session-2, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256]
Feb 19 17:09:36: restClient-akka.actor.default-dispatcher-14, SEND TLSv1.2 ALERT:  fatal, description = certificate_unknown
Feb 19 17:09:36: restClient-akka.actor.default-dispatcher-14, WRITE: TLSv1.2 Alert, length = 2
Feb 19 17:09:36: restClient-akka.actor.default-dispatcher-14, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLHandshakeException: General SSLEngine problem
Feb 19 17:09:36: [Raw write]: length = 7
Feb 19 17:09:36: 0000: 15 03 03 00 02 02 2E                               .......
Feb 19 17:09:36: restClient-akka.actor.default-dispatcher-14, called closeInbound()
Feb 19 17:09:36: restClient-akka.actor.default-dispatcher-14, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
```

I am stuck with this issues at the moment. Could anyone help me on this issues?
Could it be related to akka/akka#18334

By the way, it works fine as well if I commented out setDefaultClientHttpsContext line.

Thanks
Fadzly

**Comment by jrudolph** [comment]
Most likely the KeyStore cannot be loaded successfully any more. Check if all of the return values are non-zero. Unfortunately, the JDK SSL error messages are seldomly useful. You could try turning on JDK SSL debugging flags with `-Djavax.net.debug=all`. See https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html for more info.

**Comment by fadzlyzahari** [comment]
Details as below link
https://gist.github.com/fadzlyzahari/fa78ddd086441bc349e5b6aacb6fe722

I think it's loaded fine as well.

**Comment by jrudolph** [comment]
I think the error is that one:

```
Feb 19 14:46:22: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

which might mean that your keystore is missing one or more certificates to the root certificates.

**Comment by jrudolph** [comment]
Maybe you can start by explaining why you are using `setDefaultClientHttpsContext` at all? It seems the host you are connecting against is providing a valid certificate (provided by GoDaddy)? Usually, your client machine should contain a trusted root certificate from GoDaddy. Maybe you need to update the root certifactes on that machine?

**Comment by fadzlyzahari** [comment]
Actually I was developing a rest client application to be used by the user. 
User requested that we provide user input for keystore path and password for them in order for them to easily configure the keystore value rather than insert manually to cacert. So in order to fulfill the request, I used the `setDefaultClientHttpsContext`. 
The GoDaddy is one of the public rest server that we use to test against with for our testing purposes.

**Comment by jrudolph** [comment]
> The GoDaddy is one of the public rest server that we use to test against with for our testing purposes.

So, did you add GoDaddy's certificate to your manually created trust store?

**Comment by fadzlyzahari** [comment]
Yeah, it seems that the GoDaddy's certificate is missing... now it works fine... 

thank you

**Comment by jrudolph** [comment]
Cool, great you solved it.
