### ISSUE TITLE
too many arguments for method parameters

### ISSUE THREAD

**Issue by sidhant92** [akka/akka-http#1871]
Hi,

I am getting this error:
too many arguments for method parameters: (pdm: akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet)

I am using scala 2.11.11

I have noticed that this error comes up when I start accepting more than 22 parameters as input.

**Comment by jrudolph** [comment]
Hi @sidhant92, yes, that's as expected, only 22 parameters are supported per `parameters` usage. You can use multiple nested ones to get above that limit to support really long lists of parameters:

```scala
parameters("arg1", ..., "arg22") { (arg1, ..., arg22) =>
   parameters("arg23", ..., "arg44") { (arg23, ..., arg44) =>
      parameters("arg45", ..., "arg66") { (arg45, ..., arg66) =>
        parameters("arg67", ..., "arg88") { (arg67, ..., arg88) =>
          parameters("arg89", ..., "arg110") { (arg89, ..., arg110) =>
            // ...
          }
        }
      }
   }
}
```

**Comment by sidhant92** [comment]
@jrudolph But how do i use this with https://doc.akka.io/docs/akka-http/current/routing-dsl/case-class-extraction.html

**Comment by ktoso** [comment]
Exacly the same -- `parameters("arg1".as[One], .......) { one => parameters("23".as[TwoThree], ...) { ... => `

**Comment by sidhant92** [comment]
@ktoso I want to extract a single case class which has more than 22 parameters.

**Comment by ktoso** [comment]
```
parameters("arg1", ..., "arg22") { (arg1, ..., arg22) =>
   parameters("arg23", ..., "arg44") { (arg23, ..., arg44) =>
      parameters("arg45", ..., "arg66") { (arg45, ..., arg66) => new Thingy(arg1, ..., arg66)
```


Nothing automatic.

**Comment by sidhant92** [comment]
@ktoso Thanks for the suggestion. But any reason why the limit of 22?

**Comment by jrudolph** [comment]
> @ktoso Thanks for the suggestion. But any reason why the limit of 22?

I guess because there needs to be some limit and 22 is already a lot over what is supposed to be good practice. Also 22 used to be a limit in the Scala compiler for tuples, functions, and products (and still is to some extent).

**Comment by fsanaulla** [comment]
Hello, I have an issue that can be related with title.
```
too many arguments (2) for method parameters: (pdm: akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet)pdm.Out
[error]       "endDate".as[LocalDate] ? LocalDate.now()
```
Scala: 2.13.1
Sbt: 1.3.7
akka-http: 10.1.11

**Comment by jrudolph** [comment]
Do you have a suitable unmarshaller for `LocalDate` in scope?

**Comment by fsanaulla** [comment]
@jrudolph Oh, you are right. Thank you!
