### ISSUE TITLE
Add a link to Swakka in the the Akka-Http docs

### ISSUE THREAD

**Issue by jtownson** [akka/akka-http#1874]
Patrik Nordwall recommended linking to Swakka from the Akka-Http docs (https://groups.google.com/forum/#!topic/akka-user/Pet2WaavbJA).

Swakka is a library that provides an AST representing OpenApi documentation. From this AST it generates Akka-Http Routes and Swagger JSON. It is thus a way to provide OpenApi docs for APIs using Akka-Http.

It is hosted on github at https://github.com/jtownson/swakka.

**Comment by raboof** [comment]
Yes that would be great! Would you be interested in preparing a PR?

**Comment by ktoso** [comment]
Yep, cool thing to link to from our docs 👍

**Comment by jtownson** [comment]
Sure, I can prepare a PR. What is a good section to update. I had a look at possible places. Perhaps 
-- Section 6 (Extensions). This would not actually involve any changes, so much as getting scaladex to pick up swakka.
-- Section 7 (Supported techs). Could add an openapi section and provide a link to swakka there. Should probably mention other libraries in this space like swagger-akka-http. It might become a bit more 'blog post' than 'reference docs' though.

What are your thoughts?

**Comment by jtownson** [comment]
I have updated swakka's scaladex entry so that it lists akka-http as a topic.

This means that now Section 6, Extensions of the akka-http docs clicks through to a scaladex page that includes swakka.

Suggest we can close this.

**Comment by jrudolph** [comment]
Cool, thanks for dealing with this, @jtownson.

**Comment by ktoso** [comment]
Hmm, though I wonder if it wouldn't be nice to list some of the more interesting ones like this, session and json explicitly?

**Comment by ktoso** [comment]
WDYT @raboof ?

**Comment by ktoso** [comment]
Also ping here @raboof

**Comment by ktoso** [comment]
I think it would be good to add explicit links to some things w think are cool - swakka, https://github.com/twilio/guardrail and akka-http-json, akka-http-session are notable examples

**Comment by raboof** [comment]
Agreed, would be fun to highlight/'endorse' some of the particularly interesting/mature projects

**Comment by ktoso** [comment]
Made a ticket https://github.com/akka/akka-http/issues/1968
