### ISSUE TITLE
transformDataBytes is blocking the closing of the response

### ISSUE THREAD

**Issue by AlessandroEmm** [akka/akka-http#1875]
Hey there

I have this portion of code:
https://gist.github.com/AlessandroEmm/4a7483bd19c1a1b36aa93c4af16f4cbb

..where I replace some chunks in the streamed response entity (streaming from the file via getFromResource). This works just fine - the problem is it seems to block the actual server side closing of the outbound socket (buffer) as it only finishes the response when the the http client runs into a timeout and closes its connect from the client side. Oh and I'm serving via TLS, so it could be related to https://github.com/akka/akka-http/issues/380.

Any clue what I'm doing wrong? I tested the latest versions of akka-http .11 and tried .9 and .10  1.0-RC2 as well, with the same behaviour.

Thanks a lot
Alessandro

**Comment by jrudolph** [comment]
Hi @AlessandroEmm. Thanks for the report. It would be nice if you could post a self-contained reproducer somewhere, otherwise, it will be hard to reproduce.

**Comment by jrudolph** [comment]
Closing for now as we don't have enough information to reproduce. Please reopen or create a new ticket with more information about how to reproduce the issue.
