### ISSUE TITLE
akka-http 10.0.11 not available for akka 2.5.9 

### ISSUE THREAD

**Issue by ngu04** [akka/akka-http#1876]
I am getting following warning if use akka-http 10.0.11 and akka-stream-alpakka-cassandra_2.12:0.17

[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * com.typesafe.akka:akka-stream_2.12:2.5.9 is selected over 2.4.20
[warn]      +- com.lightbend.akka:akka-stream-alpakka-cassandra_2.12:0.17 () (depends on 2.5.9)
[warn]      +- com.typesafe.akka:akka-http-core_2.12:10.0.11 ()   (depends on 2.4.20)
[warn]  * com.typesafe.akka:akka-actor_2.12:2.5.9 is selected over 2.4.20
[warn]      +- com.typesafe.akka:akka-stream_2.12:2.5.9 ()        (depends on 2.5.9)
[warn]      +- com.typesafe.akka:akka-parsing_2.12:10.0.11 ()     (depends on 2.4.20)

I have following dependencies

  lazy val akkaVersion = "2.5.9"
  lazy val akkaHttpV = "10.0.11"

  val  xxxdependencies = deps(Seq(
      "com.typesafe.akka" %%  "akka-actor"  % akkaVersion,
      "com.typesafe.akka" %%  "akka-stream" % akkaVersion,
      "com.typesafe.akka" %% "akka-http" % akkaHttpV,
      "com.typesafe.akka" %% "akka-http-testkit" % akkaHttpV % Test,
      "de.heikoseeberger" %% "akka-http-circe" % "1.19.0",
      "com.lightbend.akka" %% "akka-stream-alpakka-cassandra" % "0.17",
      "joda-time" % "joda-time" % "2.9.9"
  ))

**Comment by ktoso** [comment]
It is, please read the docs.
https://doc.akka.io/docs/akka-http/current/compatibility-guidelines.html#compatibility-with-akka

You're mixing versions, depend on the 2.5.9 akka streams explicitly

**Comment by ktoso** [comment]
(10.1 by default depends on 2.5)

**Comment by raboof** [comment]
(to clarify: the warning is harmless because in actual fact akka 2.5 is in fact binary compatible with akka 2.4, but whatever code generates that warning cannot know that. Indeed this warning should go away in akka-http 10.1.x)
