### ISSUE TITLE
akka http 10.0.11 under OSGi container (apache karaf 4.1.5)

### ISSUE THREAD

**Issue by kcris** [akka/akka-http#1891]
Hi,

I plan to use akka http 10.0.11 under an osgi container (apache karaf 4.1.5)

I ran into troubles while trying to setup the provisioning for my application. (feature.xml descriptor with all required dependencies).

An OSGi-fied jar uses some extra manifest entries and I noticed that these 3 jars that I need (transitive dependencies)

- com.typesafe.akka/akka-http_2.12/10.0.11
- com.typesafe.akka/akka-http-core_2.12/10.0.11
- com.typesafe.akka/akka-parsing_2.12/10.0.11

have a line in their manifests, like this

Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8.0_144))"

which I believe is wrong, and should be something like

Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version>=1.8))"

I assume that a precise java version is not what is required.

**Comment by jrudolph** [comment]
I agree that seems wrong. However, we don't have any OSGI experts and something is always wrong with the OSGI config so as long as no one steps up, we'll probably dropping osgi support for 10.1.x (see #1852).

**Comment by kcris** [comment]
I think a simple fix would do for now, just requiring java >=1.8 in the manifest.
I tried to figure it out myself, but I don't know how the manifest is created in your sbt build.
I am used to maven, can someone point out how the manifest is created?
Thanks a lot

**Comment by jrudolph** [comment]
For now the OSGI configuration bits have already been removed. Here's the commit that removed it with all the bits that did it before: https://github.com/akka/akka-http/commit/8e065aac7f9d9aa99f90a00d6e1ef7125b47e439

The problem is that I also cannot point out where the `Require-Capability` constraint came from exactly. It seems to have been generated automatically but I don't know why.

**Comment by kcris** [comment]
build still uses sbt-osgi plugin

which has some defaults, like:
`requireCapability: value for Require-Capability header, defaults to osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=*PROJECT JAVAC VERSION*))"
`
I think this is the source of my problem

**Comment by kcris** [comment]
until OSGi support is resurrected, I think the `sbt-osgi` plugin should be removed from `project/plugins.sbt`

**Comment by atooni** [comment]
Hi there, we are using Akka and Akka - Http for our framework as well (https://github.com/woq-blended/blended). For spray, which we have used before we used the wrapped spray libraries, but with Akka Http we were happy to see proper bundles.

Is there anything we could do to bring back OSGi support ?

**Comment by atooni** [comment]
Is there a branch and testcases to start from ?

**Comment by raboof** [comment]
I don't think so (which might have been part of the problem) - https://github.com/akka/akka-http/commit/8e065aac7f9d9aa99f90a00d6e1ef7125b47e439 could be a starting point though.

**Comment by atooni** [comment]
Thanks. I have seen that. I need to look into some other stuff, but eventually I might have a go. For now we have wrapped the libs with proper OSGI Manifests as we did with Spray before.

**Comment by ennru** [comment]
Future versions of Akka and Akka HTTP will not support OSGi.
