### ISSUE TITLE
update akka version to 2.5.11 and fix docs

### ISSUE THREAD

**Issue by shkoder** [akka/akka-http#1892]
For the changes in #1879 I'd need akka `2.5.10`, specifically the fixes for akka/akka#24357. As `2.5.10` had a regression (though not strictly impacting akka-http) it's cleaner to update to `2.5.11`.

Straightforward version update fails with:
```
[error] (docs / Compile / paradoxMarkdownToHtml) Error writing content for page server-side/websocket-support.html: 
3 matches found for Message, but not javadsl/scaladsl: akka.http.javadsl.model.ws.Message, akka.http.scaladsl.model.ws.Message, akka.protobuf.Message
```
Which is alike to the issues previously fixed with #1889.

**Comment by jrudolph** [comment]
Fixed by #1893.
