### ISSUE TITLE
On client give better exception instead of OutputTruncationException

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1896]
What it should say is: "Server closed connection while waiting for {n} responses to request GET /abcd".

**Comment by 2m** [comment]
I think this is already the case:
https://github.com/akka/akka-http/blob/eb2f9b5bc139e22f5376db222b997c8b6949d59e/akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala#L121-L127

https://github.com/akka/akka-http/blob/eb2f9b5bc139e22f5376db222b997c8b6949d59e/akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala#L357-L359

**Comment by jrudolph** [comment]
You are right, the issue which was being reported, was a server issue, probably related to #1028.
