### ISSUE TITLE
Have `Route.seal` not require any implicit parameters

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1898]
As discussed in https://github.com/akka/akka-http/pull/1894#discussion_r172199319 we can change the `seal` method in `Route` to not require any implicit parameters.

**Comment by jlprat** [comment]
I was looking at this issue, and we could remove all implicits except the exception and rejection handler. If we would remove those, this code would not be possible: https://doc.akka.io/docs/akka-http/current/routing-dsl/rejections.html#customising-rejection-http-responses

Is that what you had in mind @jrudolph?

**Comment by ktoso** [comment]
Thanks!

**Comment by jlprat** [comment]
Solved by https://github.com/akka/akka-http/commit/5826729506bec56a271ec25bcb2c79e983f0b409
