### ISSUE TITLE
Need Automatic-Module-Name in MANIFEST.MF

### ISSUE THREAD

**Issue by xuning97** [akka/akka-http#1914]
Can we have such meta data,?

**Comment by ktoso** [comment]
Please search before opening new tickets.

Yes, it's planned.

**Comment by ktoso** [comment]
Duplicate of https://github.com/akka/akka-http/issues/1853

**Comment by ktoso** [comment]
Set to be shipped today

**Comment by xuning97** [comment]
thanks a lot!
