### ISSUE TITLE
Add support for proxying HTTPS server connections on the client side

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#192]
<a href="https://github.com/sirthias"><img src="https://avatars.githubusercontent.com/u/135347?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sirthias](https://github.com/sirthias)**
_Monday Oct 27, 2014 at 15:52 GMT_
_Originally opened as https://github.com/akka/akka/issues/16153_

---

Required for one connection:
1. Establish plain-text connection to proxy
2. Send plain-text `CONNECT target.host:443 HTTP/1.1` request to the proxy
3. Wait for `2xx` response (afterwards all communication on the connection will be directly tunneled through to the target host)
4. Start SSL handshake, i.e. upgrade the connection to TLS/SSL
5. Send the actual requests, read actual responses

This feature should likely be implemented on the level of host-level client-side API as in most cases you'll want a managed connection pool to the proxy.

Some pointers:
- http://tools.ietf.org/html/rfc2817#section-5.2 (The other "upgrading a connection" parts of that RFC appear to be rarely used)
- http://stackoverflow.com/questions/6594604/connect-request-to-a-forward-http-proxy-over-an-ssl-connection/6594880#6594880

**Comment by ktoso** [comment]
<a href="https://github.com/sirthias"><img src="https://avatars.githubusercontent.com/u/135347?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sirthias](https://github.com/sirthias)**
_Monday Oct 27, 2014 at 15:55 GMT_

----

/cc @jrudolph

**Comment by ktoso** [comment]
<a href="https://github.com/mackler"><img src="https://avatars.githubusercontent.com/u/1840214?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mackler](https://github.com/mackler)**
_Tuesday Oct 28, 2014 at 19:41 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/mlenner"><img src="https://avatars.githubusercontent.com/u/2656905?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mlenner](https://github.com/mlenner)**
_Monday Nov 03, 2014 at 15:03 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/salanki"><img src="https://avatars.githubusercontent.com/u/192223?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salanki](https://github.com/salanki)**
_Tuesday Mar 31, 2015 at 21:59 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/jkew"><img src="https://avatars.githubusercontent.com/u/723652?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jkew](https://github.com/jkew)**
_Tuesday Apr 07, 2015 at 22:21 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/rikardNL"><img src="https://avatars.githubusercontent.com/u/10027114?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rikardNL](https://github.com/rikardNL)**
_Tuesday May 26, 2015 at 05:33 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/gonstr"><img src="https://avatars.githubusercontent.com/u/1374839?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gonstr](https://github.com/gonstr)**
_Thursday May 28, 2015 at 11:47 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/bdwashbu"><img src="https://avatars.githubusercontent.com/u/3521646?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bdwashbu](https://github.com/bdwashbu)**
_Wednesday Jul 15, 2015 at 15:01 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Jul 15, 2015 at 21:10 GMT_

----

Relates to https://github.com/akka/akka/issues/17976

**Comment by ktoso** [comment]
<a href="https://github.com/nilsga"><img src="https://avatars.githubusercontent.com/u/42919?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nilsga](https://github.com/nilsga)**
_Tuesday Oct 27, 2015 at 07:52 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/carl297r"><img src="https://avatars.githubusercontent.com/u/3174285?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [carl297r](https://github.com/carl297r)**
_Thursday Nov 05, 2015 at 02:22 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Thursday Nov 12, 2015 at 00:41 GMT_

----

Logging a "very big" +1 here, we may want to think how and when we could address this.

**Comment by ktoso** [comment]
<a href="https://github.com/ashugupt"><img src="https://avatars.githubusercontent.com/u/2785488?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ashugupt](https://github.com/ashugupt)**
_Monday Dec 28, 2015 at 09:01 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/Madder"><img src="https://avatars.githubusercontent.com/u/324300?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Madder](https://github.com/Madder)**
_Monday Dec 28, 2015 at 13:56 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/mirelon"><img src="https://avatars.githubusercontent.com/u/1101497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mirelon](https://github.com/mirelon)**
_Thursday Feb 04, 2016 at 14:16 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Feb 10, 2016 at 11:05 GMT_

----

Logging another +1 (for my reference, sorry for the noise)

**Comment by ktoso** [comment]
<a href="https://github.com/andrasp3a"><img src="https://avatars.githubusercontent.com/u/8876220?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andrasp3a](https://github.com/andrasp3a)**
_Wednesday Mar 30, 2016 at 09:43 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/rahulsinghai"><img src="https://avatars.githubusercontent.com/u/1098632?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rahulsinghai](https://github.com/rahulsinghai)**
_Thursday Mar 31, 2016 at 15:44 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/mlangc"><img src="https://avatars.githubusercontent.com/u/7326646?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mlangc](https://github.com/mlangc)**
_Wednesday Apr 20, 2016 at 07:27 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/lregnier"><img src="https://avatars.githubusercontent.com/u/2325451?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lregnier](https://github.com/lregnier)**
_Friday Apr 29, 2016 at 14:49 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/douglaz"><img src="https://avatars.githubusercontent.com/u/163706?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [douglaz](https://github.com/douglaz)**
_Wednesday Jun 29, 2016 at 14:43 GMT_

----

+1000

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Jun 29, 2016 at 14:44 GMT_

----

Akka team won't be able (time wise) to pick up this issue in the short-term, so we'd like to encourage you to try to contribute this feature, or contact us if you'd like sponsor its development.

**Comment by ktoso** [comment]
<a href="https://github.com/nanothermite"><img src="https://avatars.githubusercontent.com/u/8728152?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nanothermite](https://github.com/nanothermite)**
_Wednesday Aug 24, 2016 at 17:46 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/greenhost87"><img src="https://avatars.githubusercontent.com/u/2277175?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [greenhost87](https://github.com/greenhost87)**
_Thursday Sep 01, 2016 at 20:43 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/nemccarthy"><img src="https://avatars.githubusercontent.com/u/8044836?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemccarthy](https://github.com/nemccarthy)**
_Thursday Sep 08, 2016 at 02:07 GMT_

----

+1

**Comment by ktoso** [comment]
<a href="https://github.com/Yeitijem"><img src="https://avatars.githubusercontent.com/u/8930642?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Yeitijem](https://github.com/Yeitijem)**
_Thursday Sep 08, 2016 at 12:50 GMT_

----

+1

**Comment by carl297r** [comment]
+1

**Comment by henriquedsg89** [comment]
+1

**Comment by jesinity** [comment]
+1

**Comment by kstokoz** [comment]
+1

**Comment by rklaehn** [comment]
Any update on this? Every single corporate firewall on the planet requires you to connect to the outside world via an https proxy, so not having this makes the akka-http client functionality pretty much useless.

**Comment by mcamou** [comment]
+1

**Comment by alvarow** [comment]
+1

**Comment by note** [comment]
I was playing around this issue and managed to complete HTTPS request via proxy. Here is my code: https://github.com/akka/akka-http/compare/master...note:192-https-proxy?expand=1. It's not ready to be a PR, there is still a lot of work to do, I am mostly sharing it for early validation. So the solution boils down to having additional `GraphStage` (I called it `ProxyGraphStage`) between `tlsStage` and `transportFlow`. Its only goal is to send `CONNECT`, wait for `OK` answer and then simply forward all messages untouched. In future there should be correct error handling and so on. @jrudolph  Does such approach makes sense? If it makes sense I will work further on this and prepare a PR.

**Comment by jrudolph** [comment]
Great work, @note for taking a stab at it. I just opened another PR yesterday which could be used as groundwork for it: it allows to redefine the transport the pool (or a single client connection) uses to access a host. The only predefined transport so far would be the existing TCP transport. Your HTTPS proxy support could be an `HttpsProxyTransport`, then we could have a SOCKS transport etc.

The basic change you would need to do is to include your underlying TCP connection to the HTTPS proxy into your code. Apart from that no changes to the existing http-core infrastructure would be necessary. WDYT?

It certainly looks promising, so please open a PR. I'll try to merge my PR this week so you can rebase on top of that.

**Comment by ktoso** [comment]
For reference, the pluggable transport PR https://github.com/akka/akka-http/pull/917

**Comment by note** [comment]
@jrudolph Thanks for your feedback, your PR seems very helpful - with that I think there's a great chance I will be able to implement Https proxy without touching `Http.scala` at all. Will continue to work on this at latest on Monday.

**Comment by jrudolph** [comment]
Great, thanks, @note. We (and lots of other people) are looking forward to it.
