### ISSUE TITLE
Travis will try to release twice

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#1922]
Because since https://github.com/akka/akka-http/commit/9a35a0734536daf4e0f602515d78a14793a583d8 two version numbers are now active on travis also for releasing which happens with `+ publish`. One solution could be to use `++$TRAVIS_SCALA_VERSION publish` in `.travis.yml` to publish for both Scala versions in parallel. One concern with this solution could be that we need to maintain the Scala versions in `.travis.yml` actively which seems somewhat error prone.

This time I just cancelled one of the two jobs.

**Comment by raboof** [comment]
#1923 makes sure each build publishes for its respective scala version, that seems sufficient and the burden of keeping the list of scala versions up-to-date in the .travis.yml seems acceptable.
