### ISSUE TITLE
HttpResponse.mapEntity shouldn't map if there can be no entity

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#1929]
If there's a `HttpResponse` for `StatusCodes.NoContent`, and one invokes `.mapEntity(_.transformDataBytes(...))` on it, it blows up with 
```
java.lang.IllegalArgumentException: requirement failed: Responses with this status code must have an empty entity
        at scala.Predef$.require(Predef.scala:224)
        at akka.http.scaladsl.model.HttpResponse.<init>(HttpMessage.scala:407)
        at akka.http.scaladsl.model.HttpResponse.copy(HttpMessage.scala:441)
        at akka.http.scaladsl.model.HttpResponse.withEntity(HttpMessage.scala:427)
        at akka.http.scaladsl.model.HttpResponse.mapEntity(HttpMessage.scala:431)
```
which of course is true, `NoContent` shouldn't have an entity. But we knew that going in, and the expression is only trying to transform the body if there is one.

A nicer way of handling this could be to simply not invoke `mapEntity` if we know that the status can't have one, but that could be not precise enough. Thoughts?

**Comment by jrudolph** [comment]
This is quite old and we never acted on it. My current thinking is that this is probably invalid (or already almost as good as possible).

If a response is not allowed to have an entity, then either 1. using mapEntity should be forbidden (= fails at runtime) or 2. should be allowed but only if the resulting entity is known to be empty. Currently 2. is implemented which even seems like the more friendly solution.

Closing for now. I might be missing something, so if that still bothers you, @jypma, please feel free to comment.
