### ISSUE TITLE
Increase timeouts and add dilated to HTTP test durations

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#194]
<a href="https://github.com/drewhk"><img src="https://avatars.githubusercontent.com/u/932285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [drewhk](https://github.com/drewhk)**
_Wednesday Oct 08, 2014 at 13:26 GMT_
_Originally opened as https://github.com/akka/akka/issues/16054_

---

**Comment by ktoso** [comment]
<a href="https://github.com/rkuhn"><img src="https://avatars.githubusercontent.com/u/470469?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rkuhn](https://github.com/rkuhn)**
_Wednesday Mar 23, 2016 at 16:11 GMT_

----

This is important and should be done soon—many HTTP tests have unsuitably short timeouts that lead to CI flakiness.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Thursday Mar 24, 2016 at 17:14 GMT_

----

I agree, will do it next week

**Comment by jrudolph** [comment]
Closed by #781.
