### ISSUE TITLE
Definition of routes via configuration

### ISSUE THREAD

**Issue by stephen-lazarionok** [akka/akka-http#1940]
Are there any plans to support routes definition via configuration like it's done in Play - https://www.playframework.com/documentation/2.6.x/JavaRouting#the-routes-file-syntax ?

**Comment by ktoso** [comment]
There are no such plans -- feel free to use play if you like that style of defining routes.
The inter-op between Play and Akka HTTP will be improving more and more, so one might combine routes with the play routes file perhaps some time in the future, but Akka is not going to use the routes style file by itself. 

Closing but thanks for the question, hope the above explains the goals and plans well.

PS: Please use the github issues for reporting issues/bugs etc, questions about plans etc should rather be asked on https://discuss.akka.io/ thanks!
