### ISSUE TITLE
Support conversion between scaladsl.Uri and javadsl.Uri

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#1949]
Before Akka Http 1.1.0 we could convert a Javadsl URI to its Scaladsl counterpart via
```
uri.asInstanceOf[akka.http.impl.model.JavaUri].uri`
```
This is now forbidden as JavaUri was made private.

Scaladsl to Javadsl conversion used to be possible with
```
JavaUri(sUri)
```

Akka Http should add an official way to convert between these types.

See https://github.com/akka/alpakka/issues/847

**Comment by ktoso** [comment]
We should add a create overload in javadsl I think.
Would you want to PR this @ennru ?

**Comment by ennru** [comment]
Can do. 
What about javadsl to scaladsl? 
1. An `asScala` method in `akka.http.javadsl.model.Uri`?
1. A `scaladsl.model.Uri.apply(javadsl.model.Uri)` method?
1. An implicit `scaladsl.model.Uri.apply(javadsl.model.Uri)` method?
1. Conversion support somewhere else?

**Comment by ktoso** [comment]
Internally we have mappings between everything via JavaMappings, but it's a bit messy so we've not opened those yet.

I'd be ok with adding an asScala
