### ISSUE TITLE
MergeLast List[Source[T]] => Source[List[T]] 

### ISSUE THREAD

**Issue by fmasion** [akka/akka-http#1959]
Add MergeLast 

transform List[Source[T]] => Source[List[T]] 
The same way Future.sequence does with Future but while keeping the streaming nature of sources

A picture worth 1000 words :
https://blogs.endjin.com/wp-content/uploads/2014/05/combine-latest.png

here is the discussion on [gitter](https://gitter.im/akka/akka?at=5ab2ffb1458cbde55760b573)

here is a very naïve implementation [exemple gist](https://gist.github.com/fmasion/24707eaeb728ddaec8522989ed7d9b4d) (with no generic Traversable, canBuildfrom....)

Hope you find it useful

**Comment by ktoso** [comment]
Thanks for the ticket and explanation, can be useful indeed!

**Comment by ktoso** [comment]
Though opened in the wrong repository :-) Akka-streams live in https://github.com/akka/akka

I'll copy the ticket.

**Comment by fmasion** [comment]
@ktoso oups sorry
