### ISSUE TITLE
Add links/endorse more mature akka-http support projects

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1968]
We should endorse a number of projects more, rather than just linking "go to scaladex"

We should point out:

- akka-http-json - json
- swakka - code => swagger
- https://github.com/twilio/guardrail - swagger => route
- https://github.com/lomigmegard/akka-http-cors
- https://github.com/softwaremill/akka-http-session

perhaps something else I missed?

See more: https://github.com/akka/akka-http/issues/1874

**Comment by jlprat** [comment]
Closing this one as PR was merged
Done via https://github.com/akka/akka-http/commit/2cbec2c2a881ef6866df351b209598a9223d6eb2
