### ISSUE TITLE
Move `akka.http.util.EnhancedXXX` features to `akka.util`

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#198]
<a href="https://github.com/sirthias"><img src="https://avatars.githubusercontent.com/u/135347?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sirthias](https://github.com/sirthias)**
_Tuesday Jun 10, 2014 at 12:40 GMT_
_Originally opened as https://github.com/akka/akka/issues/15387_

---

For example the methods currently in  `akka.http.util.EnhancedConfig` should really live in `akka.util.ConfigOps`.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Tuesday Oct 20, 2015 at 08:06 GMT_

----

Once we've moved to master. 
And remove "StreamUtils" etc

**Comment by jrudolph** [comment]
Currently not worth the effort.
