### ISSUE TITLE
Fail if ALPN agent is missing 

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#1987]
We have a nice section in the docs explaining how to get the Jetty ALPN agent, but since it will never work without it (when running "normal" HTTP2) could we perhaps fail or log an error if the ALPN agent is missing?

**Comment by gmethvin** [comment]
I'd be ok with failing completely if the agent isn't specified. It should at least log an error.

**Comment by raboof** [comment]
I agree it would make sense to perform this check when `akka.http.server.(preview.)enable-http2` is turned on :+1:. Not sure how hard it would be to check for it though.

**Comment by mkurz** [comment]
@raboof I guess this issue can be closed now since the situation changed with JDK8u252?

**Comment by raboof** [comment]
Hmm, we should perhaps still detect it if `akka.http.server.(preview.)enable-http2` is set and the user is not loading the agent nor running at least on 8u252?

**Comment by mkurz** [comment]
@raboof Up to you.

**Comment by jrudolph** [comment]
We removed jetty alpn support in 10.2.0 and we have a warning/error when running on a version < 8u252, so I think we are good for now.
