### ISSUE TITLE
Why akka http is slow using ab benchmark (without -k flag)?

### ISSUE THREAD

**Issue by lozzenko** [akka/akka-http#1989]
Hi, Akka team.

Disclaimer: I understand that `ab` is not that right utility to measure requests performance (https://groups.google.com/forum/#!topic/akka-user/yt3QXBXq6zg). 

We're currently investigating the right platform to build web servers and I'm super curious to understand why akka http is slow compared to other stacks like Go or NodeJS. 

We're using simple `ab` benchmark for 10k requests:
`ab -T application/json -p post.json -c 1 -n 10000 <TARGET_SERVICE>`
with simple POST route that returns `complete("OK")`

With these benchmarks, `Akka Http` shows 30% performance with average requests near `~700req/sec` compared to `Go/NodeJS` `~2k req/sec` 

It's obvious that with `ab's ``-k` flag Akka Http speed-ups quickly simultaneously with other platforms. 
My question is here: is it possible to make some tuning/optimization for the current benchmark to have more requests/sec?

**Comment by johanandren** [comment]
Hi @lozzenko, we try to use the issue tracker only for issues and feature-tracking, please use the [new forums](https://discuss.akka.io) or the [gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!

A previous question on the mailing list that may shed some light on what you wonder:
https://groups.google.com/d/topic/akka-user/yt3QXBXq6zg/discussion

**Comment by lozzenko** [comment]
Thanks, and please be more attentive, as it is the same link I've put in the description.

**Comment by johanandren** [comment]
Ah, sorry, missed that!
