### ISSUE TITLE
Java directives seem to not have static method versions

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1994]
PR in https://github.com/akka/akka-http/pull/1993

Reported in: https://discuss.lightbend.com/t/why-are-routing-directives-not-static-methods-in-java/757/3

Likely a problem on Scala 2.12 and static forwarders, which is weird since it is a class + companion so it should have worked

**Comment by johanandren** [comment]
Didn't we figure out that this was a non-issue?

**Comment by ktoso** [comment]
Correct, my bad for not closing the issue

**Comment by ktoso** [comment]
Also see the follow up PR https://github.com/akka/akka-http/pull/1997
