### ISSUE TITLE
Add Java API to create custom MediaTypes

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#2008]
As discussed in https://discuss.lightbend.com/t/akka-http-java-api-need-to-create-a-contenttype-from-a-string-mime-type/957 we discovered that one of the Scala APIs is missing for the Java one.

```
private val custom: MediaType.Binary = MediaType.customBinary("application", "wat", MediaType.Compressible)
private val binary = ContentType(custom)
println(s"binary = ${binary}")
```

To ease Java API users, we should have the same APIs available for both languages.

**Comment by jlprat** [comment]
Closed via https://github.com/akka/akka-http/commit/f9622687075f731f047c36c0a62297557af7ef1a

**Comment by ktoso** [comment]
Thanks :)
