### ISSUE TITLE
Multipart.FormData.BodyPart. additionalHeaders empty?

### ISSUE THREAD

**Issue by guntiso** [akka/akka-http#2011]
Unable to access Content-Type using TestMultipartFileUpload sample because additionalHeaders are empty. Fork here: https://gist.github.com/guntiso/10f227f4b300e7393d488546f58fac90/revisions

**Comment by jrudolph** [comment]
This is pretty old (sorry for never answering). So, just ftr `Content-Type` will never be part of headers but always be part of the entity, so this probably works if you look at the right place, i.e. `p.entity.contentType` in this example.
