### ISSUE TITLE
release for scala 2.13.0-M4

### ISSUE THREAD

**Issue by pjfanning** [akka/akka-http#2017]
https://www.scala-lang.org/download/2.13.0-M4.html - has been released

Depends on:
* https://github.com/akka/akka/issues/25105
* https://github.com/spray/spray-json/issues/265

**Comment by ktoso** [comment]
Title should say M4 ;-)

**Comment by ktoso** [comment]
We'll release soon enough, we are in close collaboration with the Scala team after all, don't worry :-)

**Comment by pjfanning** [comment]
Maybe best to merge this with https://github.com/akka/akka-http/issues/2166

**Comment by jrudolph** [comment]
Yep, let's track further progress in #2166.
