### ISSUE TITLE
Akka http 2.4.9 and 2.4.10 issue with blocking/timeout on Source[ByteString, Any].runWith(StreamConverters.asInputStream())

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#202]
<a href="https://github.com/tummybunny"><img src="https://avatars.githubusercontent.com/u/22067638?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tummybunny](https://github.com/tummybunny)**
_Friday Sep 09, 2016 at 02:37 GMT_
_Originally opened as https://github.com/akka/akka/issues/21410_

---

This is to re-open issue https://github.com/akka/akka/issues/21008 which has been closed although it is still an issue in 2.4.9 and 2.4.10

``` scala
import java.io._
import java.nio.file._
import java.util.concurrent.atomic.AtomicInteger
import akka.actor._
import akka.stream._
import akka.stream.scaladsl.StreamConverters
import akka.util.Timeout
import akka.http.scaladsl.model._
import akka.http.scaladsl.model.StatusCodes._
import akka.http.scaladsl._
import akka.http.scaladsl.server._
import akka.http.scaladsl.server.Directives._

object AkkaTest extends App {

  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  implicit val executionContext = system.dispatcher

  def processUpload(formData: Multipart.FormData) = {
    val sources = formData.parts.map(e => e.entity.dataBytes)
    val i = new AtomicInteger(0)
    val f = sources.runForeach { source =>
      val prefix = s"[FILE #${i.incrementAndGet()}]"
      println(s"$prefix START PROCESSING ")
      val inputStream = source.runWith(StreamConverters.asInputStream())
      try {
        println(s"$prefix WRITING")
        val tmp = Files.createTempFile("a", "b")
        Files.copy(inputStream, tmp, StandardCopyOption.REPLACE_EXISTING)
        Files.delete(tmp)
        println(s"$prefix DONE WRITING")
      } finally {
        inputStream.close()
      }
    }
    f
  }

  def processMultiPartData: Route = {
    pathPrefix("upload") {
      (post & entity(as[Multipart.FormData])) { formData =>
        complete {
          processUpload(formData).map { _ =>
            println("*** DONE ****")
            HttpResponse(StatusCodes.OK, entity = s"Data: datasuccessfully processed.")
          }
        }
      }
    }
  }
  val routes = processMultiPartData
  Http().bindAndHandle(handler = routes, interface = "0.0.0.0", port = 9090)
}
```

Executed this command:

```
$ curl "http://localhost:9090/upload" -F "file=@/whatever.zip"
There was an internal server error.
```

Std out:

```
Produces:
09-09-16 10:29:26:297 [default-akka.actor.default-dispatcher-4] [] INFO  a.e.s.Slf4jLogger - Slf4jLogger started
[FILE #1] START PROCESSING 
[FILE #1] WRITING
09-09-16 10:30:20:761 [default-akka.actor.default-dispatcher-9] [] ERROR a.a.ActorSystemImpl - Error during processing of request HttpRequest(HttpMethod(POST),http://localhost:9090/upload,List(User-Agent: curl/7.37.0, Host: localhost:9090, Accept: */*, Expect: 100-continue, Timeout-Access: <function1>),HttpEntity.Default(multipart/form-data; boundary=------------------------ae1c9b442e9074c1; charset=UTF-8,272 bytes total),HttpProtocol(HTTP/1.1))
java.io.IOException: Timeout on waiting for new data
    at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply$mcI$sp(InputStreamSinkStage.scala:144) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:129) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:129) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:109) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:129) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:120) ~[akka-stream_2.11-2.4.9.jar:na]
    at java.nio.file.Files.copy(Files.java:2908) ~[na:1.8.0_45]
    at java.nio.file.Files.copy(Files.java:3027) ~[na:1.8.0_45]
    at AkkaTest$$anonfun$2.apply(HH.scala:32) ~[classes/:na]
    at AkkaTest$$anonfun$2.apply(HH.scala:25) ~[classes/:na]
    at akka.stream.impl.fusing.Map$$anon$5.onPush(Ops.scala:42) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:755) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:657) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:470) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:422) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:602) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:593) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.9.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:528) ~[akka-stream_2.11-2.4.9.jar:na]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.9.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.9.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.9.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.9.jar:na]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.9.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
```

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Friday Sep 09, 2016 at 06:32 GMT_

----

#21008 about a specific bug in one of the stages, this is probably something else although it manifest in an exception looking the same.

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Friday Sep 09, 2016 at 06:34 GMT_

----

`asInputStream` takes a read timeout which is by default 5 seconds, perhaps your filesystem is just slower than that?

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Friday Sep 09, 2016 at 06:40 GMT_

----

Ran the sample locally, it's failing here as well, so we can rule the slow fs out

**Comment by ktoso** [comment]
<a href="https://github.com/tummybunny"><img src="https://avatars.githubusercontent.com/u/22067638?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tummybunny](https://github.com/tummybunny)**
_Friday Sep 09, 2016 at 06:47 GMT_

----

absolutely not. The curl command uses a zip file less than 10kb (a zip of a readme.txt) and it timed out after 30 seconds.

Something like this works fine, i.e. converting the ByteSource into Future[IOResult] and flat map it:

```scala

  def processUpload(formData: Multipart.FormData) = {
    val sources = formData.parts.map(e => e.entity.dataBytes)
    val i = new AtomicInteger(0)
    var fileFut: Future[Any] = Future.successful(Unit)
    val f = sources.runForeach { source =>
      val prefix = s"[FILE #${i.incrementAndGet()}]"
      println(s"$prefix START PROCESSING ")
      val tmp = Files.createTempFile("f-", ".tmp")
      val out = Files.newOutputStream(tmp, StandardOpenOption.WRITE)
      fileFut = fileFut.flatMap{ _ => source.runWith(StreamConverters.fromOutputStream(() => out)).map { _ =>
         out.close()
         println(s"$prefix DONE WRITING")
      }}
    }.flatMap( _ => fileFut)
  }
```

**Comment by ktoso** [comment]
<a href="https://github.com/tummybunny"><img src="https://avatars.githubusercontent.com/u/22067638?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tummybunny](https://github.com/tummybunny)**
_Friday Sep 09, 2016 at 06:48 GMT_

----

my comment above was reply your second comment ;)

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Friday Sep 09, 2016 at 07:00 GMT_

----

Yeah, seems a bit like a deadlock somewhere in the HTTP graph or possibly in the Multipart.FormData unmarshaller.

**Comment by jrudolph** [comment]
Seems to be still a problem in 10.0.4. Investigating...

**Comment by jrudolph** [comment]
This is not a bug. Running blocking code like reading an `InputStream` must not be run on managed threads (like here in `runForeach` of streams infrastructure). This can often lead to deadlocks which is here the case: as the context which runs `runForeach` is the same as the one which drives the `InputStream`, blocking on `InputStream.read` will block the other part of the stream of providing the `InputStream` with data.

A simple workaround for this particular case is adding either 

```
val f = sources.async.runForeach { source ⇒
```

or

```scala
val f = sources.mapAsync(1) { source ⇒
  Future {
    ...
  }(<your-specialized-blocking-io-execution-context>)
}.runWith(Sink.ignore)
```

It might be possible to improve the error diagnostics in such a case to point to the deadlock directly. I created https://github.com/akka/akka/issues/22405 to find a solution or document better.

**Comment by tummybunny** [comment]
Thanks Johannes. I will test it.

**Comment by tkesslerKedev** [comment]
Hi! I experience the same issue. This is my code snippet (Java-API):

`protected static void buildWebServer(ActorSystem system, ProcessorConfiguration procConfig) {

		final Materializer materializer = ActorMaterializer.create(system);
		ExecutionContext executionContext = system.dispatchers().lookup("web-dispatcher");

		Source<IncomingConnection, CompletionStage<ServerBinding>> serverSource = Http.get(system).bind(
				ConnectHttp.toHost(procConfig.getHttpServerAddress(), procConfig.getHttpServerPort()), materializer);

		final Function<HttpRequest, HttpResponse> requestHandler = new Function<HttpRequest, HttpResponse>() {
			private final HttpResponse NOT_FOUND = HttpResponse.create().withStatus(404)
					.withEntity("Unknown resource!");

			@Override
			public HttpResponse apply(HttpRequest request) throws Exception {
				Uri uri = request.getUri();
				if (request.method() == HttpMethods.POST) {
					if (uri.path().equals("/reprocess")) {

						InputStream requestInputStream = request.entity().getDataBytes()
								.runWith(StreamConverters.asInputStream(), materializer);


						String encodedData = readStringFromInputStream(requestInputStream);
						List<String> files = extractZipFromRequest(encodedData);

						return HttpResponse.create().withEntity(ContentTypes.TEXT_HTML_UTF8, "<html><body><read>"
								+ files.stream().map(String::toString).collect(Collectors.joining("</read><read>"))
								+ "</body></html>");
					} else {
						return NOT_FOUND;
					}
				} else {
					return NOT_FOUND;
				}
			}

		};

		CompletionStage<ServerBinding> serverBindingFuture = serverSource.to(Sink.foreach(connection -> {
			connection.handleWithSyncHandler(requestHandler, materializer);
		})).run(materializer);
	`}``

**Comment by jrudolph** [comment]
Thanks @tkesslerKedev for providing another example. 

The point is the same here: you must not run code that uses InputStream or OutputStream (which may block on `read` or `write` calls) on threads from the akka / akka-stream infrastructure (see http://doc.akka.io/docs/akka/current/general/actor-systems.html#Blocking_Needs_Careful_Management).

In fact, in your case, you shouldn't use `InputStream` at all but use an unmarshaller to convert the entity to a String in an asynchronous way.

Something like this:

```
Unmarshaller.entityToString.unmarshal(request.entity, materializer, executionContext)
```

which will return a `CompletionStage[String]`. You then need to use `thenApply` on this completion stage to convert the String further.

In the end, you will have to change your setup to use `handleWithAsyncHandler` to be able to return a `CompletionStage[HttpResponse]` to offer the response in an asynchronous way.

Even better would be using the high-level Java routing API, which makes dealing with all this much more pleasant. Maybe @jypma could you help out with a quick hint how to rewrite your code with the high-level API.

**Comment by jypma** [comment]
Indeed, trying to use `InputStream` as the main way to read your requests in an akka application is not the intended usage. After all, the point of using akka over e.g. J2EE in the first place is to have a completely non-blocking application. Specifically, blocking a thread for every request means that whatever thread pool that runs on must _at least_ have the configured connection count number of threads. And I believe the default connection count for akka is 1024 :-)

@tkesslerKedev you application would benefit greatly from using the [akka server DSL](http://doc.akka.io/docs/akka-http/current/java/http/routing-dsl/index.html#minimal-example). You can code your own REST resources by changing `createRoute()` in that example.

To get the request entity as a string, you can use the [entity directive](http://doc.akka.io/docs/akka-http/current/java/http/routing-dsl/directives/marshalling-directives/entity.html#entity-java) combined with `Unmarshaller.entityToString`, e.g.

```
Route createRoute() {
  return path("reprocess", () -> 
    post(
      entity(Unmarshaller.entityToString, s -> {
        List<String> files = extractZipFromRequest(s);
        return complete( /* ... create response from [files] */ );
      })
    )
  );
}
```

**Comment by tkesslerKedev** [comment]
thank you very much! 

I'm using the approach with high-level API now, . which works perfect for me.

**Comment by jypma** [comment]
Nice to hear that!

@jrudolph how about making the high-level DSL the main and first part of the documentation, i.e. profile it as "the" way to write REST applications, reserving the lower-level server parts as "advanced" topics?

**Comment by jrudolph** [comment]
@tkesslerKedev great you found a working solution.

@jypma yes, that would definitely would be the end goal. I should try to write up the current plan how to get docs restructuring done.
