### ISSUE TITLE
Missing parameter with required value directive in Java API

### ISSUE THREAD

**Issue by nikom1337** [akka/akka-http#2025]
Hi,

I've found that Scala API has one directive to specify require value of parameter
```
parameters('color, 'action ! "true") { (color) =>
    complete(s"The color is '$color'.")
  }
```
but there is no Java API version of it. 

There is also some [inconsistency](https://github.com/akka/akka-http/blob/b84d8d905339eddb9e5fb6af1f8f2d555e858a7b/akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala#L150-L158) related to parameter directives, most of the filters are rejecting request with clearly defined Rejection (e.g MalformedRequestContentRejection), requiredFilter is using empty rejection.

I would like to suggest something like that:
```
    private def requiredFilter[T](paramName: String, fsou: FSOU[T], requiredValue: Any): Directive0 =
      extractRequestContext flatMap { ctx ⇒
        import ctx.executionContext
        import ctx.materializer
        onComplete(fsou(ctx.request.uri.query().get(paramName))) flatMap {
          case Success(value) if value == requiredValue ⇒ pass
          case Success(value)                           ⇒ reject(InvalidRequiredValueForQueryParamRejection(paramName, requiredValue.toString, value.toString))
          case _                                        ⇒ reject(MissingQueryParamRejection(paramName))
        }
      }
```

**Comment by jlprat** [comment]
Closed via fd94b5d
