### ISSUE TITLE
Websocket sub-protocol not echoed back when server subprotocol list is empty. Chrome issue

### ISSUE THREAD

**Issue by corvana-nbaker** [akka/akka-http#2042]
When a websocket server subprotocol list matches an incoming subprotocol connection, it correctly sends back a 'Sec-WebSocket-Protocol' header reflecting the match. However, if the server subprotocol list is empty (i.e. accepting all subprotocol requests) it does not send back this header. The result is a bad handshake with Chrome.

I've fixed this locally here: https://github.com/corvana-nbaker/akka-http/commit/1431c9e98a2cf1b6aee3cf9a403aaaa5148c29be#diff-2a98090cc5a7816bb19ebb5f734162e2R152

**Comment by raboof** [comment]
Thanks for bringing this up! I'm not too familiar with websockets myself but https://tools.ietf.org/html/rfc6455#section-4.2.2 mentions:
```
/subprotocol/
          Either a single value representing the subprotocol the server
          is ready to use or null.  The value chosen MUST be derived
          from the client's handshake, specifically by selecting one of
          the values from the |Sec-WebSocket-Protocol| field that the
          server is willing to use for this connection (if any).  If the
          client's handshake did not contain such a header field or if
          the server does not agree to any of the client's requested
          subprotocols, the only acceptable value is null.  The absence
          of such a field is equivalent to the null value (meaning that
          if the server does not wish to agree to one of the suggested
          subprotocols, it MUST NOT send back a |Sec-WebSocket-Protocol|
          header field in its response).
```

and in https://tools.ietf.org/html/rfc6455#section-11.3.4:

```
the |Sec-WebSocket-Protocol| header field MUST NOT appear more than once in an HTTP response.
```

This suggests your proposal of sending back a `Sec-WebSocket-Protocol` for each of the proposals by the client is probably not allowed, unless I'm reading this wrong.

Does this mean to support Chrome you must use `handleWebSocketMessagesForProtocol` and select a subprotocol you claim to accept? If so then we should probably document this, but I'd first like to understand this a bit better ;)

**Comment by corvana-nbaker** [comment]
You're right that only one can be sent back. I've yet to see multiple protocol negotiation in the real-world. I suppose in the situation where there is an empty server list we should pick the first one from the client list assuming they're sent the protocols in preferred order

**Comment by raboof** [comment]
I'm not sure I understand what you mean by an 'empty server list', can you elaborate?

If we don't have any knowledge of supported subprotocols, it seems weird to pick one at random, and I think akka-http should leave this up to the end-user to select one - however you might be using websockets in a way that I'm not familiar with, so I'm happy to learn more about it! Can you share some code?

**Comment by corvana-nbaker** [comment]
The spec seems to leave it up to the server to decide which subprotocols to accept https://tools.ietf.org/html/rfc6455#section-4.2.2

/subprotocol/
          Either a single value representing the subprotocol the server
          is ready to use or null.  The value chosen MUST be derived
          from the client's handshake, specifically by selecting one of
          the values from the |Sec-WebSocket-Protocol| field that the
          server is willing to use for this connection (if any).  If the
          client's handshake did not contain such a header field or if
          the server does not agree to any of the client's requested
          subprotocols, the only acceptable value is null.  The absence
          of such a field is equivalent to the null value (meaning that
          if the server does not wish to agree to one of the suggested
          subprotocols, it MUST NOT send back a |Sec-WebSocket-Protocol|
          header field in its response).  The empty string is not the
          same as the null value for these purposes and is not a legal
          value for this field.  The ABNF for the value of this header
          field is (token), where the definitions of constructs and
          rules are as given in [RFC2616].


I'm basing this behavior off the comments here in which it seems Akka-HTTP is to accept any websocket if the server socket definition has no defined subprotocols:
https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/WebSocketDirectives.scala#L63

Honestly, if I were designing a server I would require the server configuration to explicitly set the acceptable subprotocols, but that will complicate things on our end as Play has no way of defining the subprotocol list when creating WebSockets TMK

**Comment by raboof** [comment]
If I understand correctly, the server has 3 possible responses to a websockets upgrade request:

* reject the upgrade request
* accept the upgrade request and select one of the proposed subprotocols
* accept the upgrade request but select none of the proposed subprotocols

The directive you link can be used in 2 ways:

* passing in a `Some(subprotocol)`: accept the request with that subprotocol if that subprotocol is allowed by the client, reject it otherwise
* passing in `None`: accept the request, without agreeing to any proposed subprotocol.

You mention Chrome fails to handshake when the server does not agree to any proposed subprotocol. If that is true for most clients then we should perhaps discourage the use of this directive and recommend `handleWebSocketMessagesForProtocol` instead. I suspect there are clients that don't care about subprotocols though, and for those those directives probably make sense.

You mention Play, but if I recall correctly these directives are not used from Play. Could you explain the way you use these API's?

**Comment by corvana-nbaker** [comment]
You're right about the clients. Firefox doesn't care if the result lacks `Sec-WebSocket-Protocol`.

Not sure where the Play AkkaHttpServer code is. I tracked down their usage at one point, but a quick search for "handleWebSocketMessages" produces no results. 

handleWebSocketMessagesForOptionalProtocol really does seem like the proper way to go. I'll open a case with Play to add a protocol Seq of the WebSocket flow. In the mean-time I plan to patch Apollo-Client in our environment so as to not  send "graphql" protocol up to the server.

Thanks!

**Comment by raboof** [comment]
This issue is tracked in Play as part of https://github.com/playframework/playframework/issues/7895
