### ISSUE TITLE
Unable to set TTL on https connection pool

### ISSUE THREAD

**Issue by basitpathan** [akka/akka-http#2051]
Hello,
akka-http 10.1.1
The system we are calling over TLS has a time to live (TTL) set on their https connections. When this TTL is reached our connections are killed regardless of whether we are using them or not. Is it possible to set a TTL (less than theirs) on our connection pool, so that we close our connections gracefully?

**Comment by raboof** [comment]
We try to use the github issues for bugs and feature requests, so this question might fit better at our forums at https://discuss.akka.io.

We have a number of timeouts that are configurable at https://doc.akka.io/docs/akka-http/current/common/timeouts.html#timeouts, but nothing that fits your use case exactly.

The setting that is being contributed as https://github.com/akka/akka-http/pull/2016 might help, but is still in the pipeline.

**Comment by basitpathan** [comment]
Thanks @raboof for the response, the Pull Request mentioned fits best with our requirement. will keep an eye on it.
