### ISSUE TITLE
Java DSL: completeWithFuture is missing unwrapCompletionException

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#2054]
In modern Java, a `CompletionStage`'s failure will always be a `CompletionException`. That doesn't go very well with writing route `ExceptionHandlers`, since one would always be matching `CompletionException`. 

In order to work around this, `FutureDirectives` has a [`unwrapCompletionException`](https://github.com/akka/akka-http/blob/f3e83935ffc27bc94f586d9387b54b499c6250d4/akka-http/src/main/scala/akka/http/javadsl/server/directives/FutureDirectives.scala#L110) that auto-unwraps failed futures, so exception handlers can deal with the _actual_ exception. However, this unwrapping is missing from `completeWithFuture` (multiple variants, in [javadsl/RouteDirectives.scala](https://github.com/akka/akka-http/blob/f3e83935ffc27bc94f586d9387b54b499c6250d4/akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala#L232) ).

Now, any exception thrown by a `CompletionStage` passed to `completeWithFuture` will always be `CompletionException`, and not be handled correctly by any applied exception handler.

A quick fix would be to add `unwrapCompletionException` to `RouteDirectives` where appropriate.

**Comment by raboof** [comment]
Sounds good, I remember this being quite cumbersome.

**Comment by jlprat** [comment]
I will attempt to tackle this one :)

**Comment by jlprat** [comment]
Closed by https://github.com/akka/akka-http/commit/8bd0beca16d33ba4a62fe10c7be885d172530d32
