### ISSUE TITLE
Version conflict for scala-xml dependency

### ISSUE THREAD

**Issue by ykycxzsv** [akka/akka-http#2055]
```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn]      +- com.typesafe.akka:akka-http-xml_2.12:10.1.1 ()     (depends on 1.1.0)
[warn]      +- org.scala-lang:scala-compiler:2.12.6               (depends on 1.0.6)
```
I'm a bit confused by this. It seems like akka-http depends on a version of scala-xml not supported by the compiler?

**Comment by raboof** [comment]
This was introduced in #1909, which seems like it just a general round of updates (though 1.1.0 is not strictly compatible, https://github.com/scala/scala-xml/pull/150, this update was introduced in 10.1.0).

This dependency is only used in the `akka-http-marshallers-scala/akka-http-xml` subproject.

Is the scala-compiler dependency actually used at run time? Did you see any practical problems?

**Comment by ktoso** [comment]
I don't think we should lower the version number in an update, to avoid any weird version confusions and potential bin compat issues...

May I propose you enforce the version in your build and we close this?

**Comment by ktoso** [comment]
Closing for now, reopen or comment if you think more should be done here.
Do take into account compatibility things then though, we should not just bump "down" a version I believe
