### ISSUE TITLE
Enhance Caching Documentation

### ISSUE THREAD

**Issue by herzrasen** [akka/akka-http#2060]
I implemented Caching in my application today and found it quite hard to get it running without checking the TestSuite at https://github.com/akka/akka-http/blob/master/akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala

Maybe it is just me or wouldn't it be helpful to 

- add a `keyerFunction` and
- show the mixing in of `CachingDirectives` where `cache()` is used?

**Comment by johanandren** [comment]
Sounds like a good idea to me!

**Comment by herzrasen** [comment]
I could provide a PR in some days if it helps.

**Comment by johanandren** [comment]
Sounds excellent!
