### ISSUE TITLE
Memory leak in 10.1.2

### ISSUE THREAD

**Issue by mr-git** [akka/akka-http#2067]
With application heap set to 4G and load at 60 requests per second, server managed to survive about an hour. After that Old Gen was full, Full GC started and paused on timeout with zero reclaimed space. 

Heap dump was taken from server while it still was running under load - from 3GB taken memory, 2.9GB of objects were with strong reachability from GC roots.

From dump, it seems that `MasterServerTerminator` which retains a lot of `HashSet`, `AtomicReference`, `Promises`, `Success`, `GracefulTerminatorStage$ConnectionTerminator`, `HttpRequestParser`, `HttpHeaderParser` or some structure of these all.

Here are the top lines of "Objects by Class" as CSV dump extracted from application heap dump few minutes before it crashed.
```
"Class","Objects","Shallow Size","Retained Size"
"java.util.concurrent.atomic.AtomicReference","4692187","75074992","3059793288"
"scala.collection.immutable.HashSet$HashTrieSet","38461","923064","3059064264"
"scala.collection.immutable.HashSet[]","38461","1333608","3059058624"
"akka.http.impl.engine.server.MasterServerTerminator","1","24","3058762912"
"akka.http.impl.engine.server.MasterServerTerminator$AliveConnectionTerminators","1","16","3058762856"
"scala.collection.immutable.HashSet$HashSet1","126836","3044064","3056645720"
"akka.http.impl.engine.server.GracefulTerminatorStage$ConnectionTerminator","119883","1918128","3053744448"
"scala.concurrent.impl.Promise$DefaultPromise","488574","7817184","3052676704"
"scala.util.Success","486245","7779920","3050509744"
"akka.http.impl.engine.server.GracefulTerminatorStage$$anon$1$$Lambda$1206","119883","2877192","3047993424"
"akka.http.impl.engine.server.GracefulTerminatorStage$$anon$1","119883","12467832","3031698456"
"akka.http.impl.engine.parsing.HttpRequestParser$$anon$1","119883","14385960","1421439848"
"akka.http.impl.engine.parsing.HttpHeaderParser","120011","8640792","1176968680"
"java.lang.Object[]","4704982","316041640","713139749"
"byte[]","5129188","461609984","461609984"
"char[]","120503","421740256","421740256"
"java.lang.String","5004569","120109656","407229632"
"akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary","239811","32614296","372096144"
"akka.stream.impl.fusing.ActorGraphInterpreter$ActorOutputBoundary","239811","24940344","341388552"
"akka.stream.impl.fusing.GraphInterpreter$Connection[]","4325465","154683888","327745176"
"short[]","120075","185302776","185302776"
"akka.stream.impl.fusing.GraphInterpreter$Connection","4322526","172901040","173061224"
...
```

Maybe I forgot to amend the code during migration?

**Comment by ktoso** [comment]
What does your code do though; do you keep tons of connections around?
That is a lot of terminators though...

`"akka.http.impl.engine.server.GracefulTerminatorStage$ConnectionTerminator","119883","1918128","3053744448"` 

Seems the alive ones make sense though...

`"akka.http.impl.engine.server.MasterServerTerminator$AliveConnectionTerminators","1","16","3058762856"` 

will try to look into if we retain them longer than needed

**Comment by mr-git** [comment]
Application is very simple - there is a request, which spawns actor, which later returns response (and does finishing-cleanup). The actor communicates with other systems, but mostly, request gets served in about 500ms, actor dies some 400..500ms later.

There is health check for Kubernetes support and Prometheus metrics endpoints too - those are called by external services on regular intervals.

From heap-dump it seems that those terminators are kept in HashMap
<img width="1336" alt="screen shot 2018-06-13 at 22 23 21" src="https://user-images.githubusercontent.com/8796159/41377574-1dfc1918-6f65-11e8-9ac4-01c0a905b119.png">

**Comment by mr-git** [comment]
After I changed the version in dependencies to `10.1.1` app stared to behave very nicely, running stable for last 2.5 hours under the same load - 60 requests per second - almost 500k requests served already.

**Comment by ktoso** [comment]
Ouch, thanks for confirming... I think I see the bug and it is a very obvious leak, embarrassing that we let it in. Thanks, will look into it more and PR a fix
