### ISSUE TITLE
UserAgent differs before and after parsing

### ISSUE THREAD

**Issue by kamijin-fanta** [akka/akka-http#2078]
When parsing some character strings, User-Agent differs before and after parsing.
I always hope that the two are the same.

### example code

```scala
val ua = "Java_HotSpot(TM)_64-Bit_Server_VM/9.0.4+11"
`User-Agent`(ua) shouldEqual RawHeader("User-Agent", ua)
```

### result

```
User-Agent: Java_HotSpot (TM) _64-Bit_Server_VM/9.0.4+11 did not equal User-Agent: Java_HotSpot(TM)_64-Bit_Server_VM/9.0.4+11
```

**Comment by johanandren** [comment]
The `equals` `RawHeader` and `User-Agent` classes is the default generated one for the respective case class which can only ever be equal to a class of the same type, so you cannot compare these two instances of different classes using equals, you'd have to compare their values rather.

**Comment by kamijin-fanta** [comment]
The test code is bad. I'm sorry.

```scala
val ua = "Java_HotSpot(TM)_64-Bit_Server_VM/9.0.4+11"
`User-Agent`(ua).value shouldEqual ua
```

```
"Java_HotSpot[ (TM) ]_64-Bit_Server_VM/9...." did not equal "Java_HotSpot[(TM)]_64-Bit_Server_VM/9...."
```

An illegal space is inserted.
I think that there is a problem with the processing of ProductVersion.

**Comment by johanandren** [comment]
Hunting around for a spec a bit lead me to: https://tools.ietf.org/html/rfc2616#section-3.8 which says (collected from section 14.43, 3.8 and 2.2):

```
User-Agent     = "User-Agent" ":" 1*( product | comment )
product         = token ["/" product-version]
product-version = token
token          = 1*<any CHAR except CTLs or separators>
separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

So I this is according to spec, the `(` and `)` are considered as separators and the rest as separate products.

I'm not sure it is important that we follow the spec here though, and I have understood that many HTTP clients put whatever they feel like in this field so maybe we should loosen up this specific parser. WDYT @raboof ?

**Comment by raboof** [comment]
It would be nice to have more faithful 'roundtrip' behavior here as indeed clients probably include crazy things in here. On the other hand it might be useful to get the individual products and it's already part of the public API, I don't think it'll be easy to improve without breaking bincompat.

@kamijin-fanta did you run into this while using the AWS SDK by any chance? If so this might have been fixed upstream in https://github.com/aws/aws-sdk-java-v2/pull/421?

**Comment by ktoso** [comment]
We never promise any round-trips render the same in the model. There are some edge cases which end up being rather insane to handle.. Not sure we should spend much time on this

**Comment by kamijin-fanta** [comment]
Yes, it is the operation of AWS SDK.
In most cases it can be solved with `modeled-header-parsing = off`.
However, I thought it was not intuitive, so I reported it.
It is certainly difficult to change while keeping compatibility...

**Comment by raboof** [comment]
OK, given that this will be fixed in the AWS SDK, we're doing strictly speaking the right thing, and there's a workaround in `modeled-header-parsing = off`, I think it makes sense to close this. Thanks for the heads-up though!

**Comment by richdougherty** [comment]
> We never promise any round-trips render the same in the model.

In Play we work around [these issues](https://github.com/playframework/playframework/issues/7733) by disabling modeled headers. If you want round-trip rendering - which I agree is a good idea for an HTTP agent in general - the simplest way would be to keep the original string around and just emitting it again during rendering.

On a related note, if we're keeping the original string value, it would be possible to delay parsing. So a header could be modeled, but lazily. Accessing the string value of a header or rendering it wouldn't require parsing it and could use the original string. Accessing a modeled field would causing parsing to occur. This would suit Play very nicely and would have probably have performance benefits for many apps, as well as solving the round-tripping issue.
