### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by shubham9914** [akka/akka-http#2083]
![image](https://user-images.githubusercontent.com/39112265/41599121-d5a1fe8c-73ef-11e8-9119-b18e15b760b8.png)

**Comment by johanandren** [comment]
Do you get a compilation error, and if so what does the compilation error say?

**Comment by ktoso** [comment]
Closing until more info is provided. Please include information what does not work exactly (show the compile error), otherwise we can't provide help.

**Comment by shubham9914** [comment]
I am using SBT and when I compile it, it is giving me compile time error 

info] Compiling 129 Scala sources to /home/shubham/Documents/work/BAILE/baile/target/scala-2.12/classes ...
[error] /home/shubham/Documents/work/BAILE/baile/src/main/scala/baile/Authorization.scala:16:16: could not find implicit value for parameter routingSettings: akka.http.scaladsl.settings.RoutingSettings
[error]     Route.seal {
[error]                ^
[error] /home/shubham/Documents/work/BAILE/baile/src/main/scala/baile/routes/usermanagement/UMRoutes.scala:37:16: could not find implicit value for parameter routingSettings: akka.http.scaladsl.settings.RoutingSettings
[error]     Route.seal {
[error]                ^
[error] /home/shubham/Documents/work/BAILE/baile/src/main/scala/baile/routes/usermanagement/UMRoutes.scala:9:45: Unused import
[error] import akka.http.scaladsl.server.directives.Credentials
[error]                                             ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 27 s, completed Jun 19, 2018 8:07:25 PM

**Comment by jlprat** [comment]
One is an import that is not used, and the other two, it seems some of the implicit parameters can't be resolved.
There is not much more I can help with, but it looks like it is not an issue with the library, but more like a question on how to use it. For this, it is better to use either https://discuss.lightbend.com/c/akka/akka-http or https://gitter.im/akka/akka .
