### ISSUE TITLE
perform null check when constructing a RawHeader instance

### ISSUE THREAD

**Issue by laszlovandenhoek** [akka/akka-http#2103]
Currently, this code:
```
import scala.collection.immutable
import akka.actor.ActorSystem
import akka.http.scaladsl._
import akka.http.scaladsl.model._
import akka.http.scaladsl.model.headers._

implicit val actorSystem = ActorSystem()

val badHeader = RawHeader("NullHeader",null)

Http().singleRequest(HttpRequest(uri ="http://example.com", headers = immutable.Seq(badHeader)))
```
...will throw a `NullPointerException` from an obscure place - [see for yourself in this Scastie](https://scastie.scala-lang.org/gYTZ0znQS0aKvbrVgGhSeA).

We should add proper null checks when constructing `RawHeader` instances, catching problems early.

**Comment by jlprat** [comment]
Nulls are (or maybe I should say "should") not that common in Scala. However, this is not the case for Java where nulls are more present. I think it makes sense to have this protection

**Comment by ktoso** [comment]
Fine to add IMHO; usually "should not happen"™ but when it does it is good to fail early
