### ISSUE TITLE
No way to create a unencrypted HTTP/2 server with Java

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2110]
The juggling going on with the `ConnectHttp` in the Java version of `bindAndHandleAsync` will loose the Http2 flag when the context is not encrypted (`effectiveConnectionContext` always returns the `fallbackContext` which doesn't have http2 set since `ConnectHttpImpl` always has an empty `connectionContext`)

**Comment by chbatey** [comment]
Ahh didn't see this, would have saved me some time yesterday!
