### ISSUE TITLE
MarshallingTestUtils should get the timeout from config

### ISSUE THREAD

**Issue by MelaHub** [akka/akka-http#2127]
MarshallingTestUtils uses hardcoded 1 and 2 seconds for timeout, in case of heavy tests this causes the tests to fail with Request was neither completed nor rejected within 1 second.

MatshallingTestUtils should get the timeout from conf - e.g. akka.http.testkit.marshalling.timeout

**Comment by johanandren** [comment]
Sounds good! Would you be up for a PR adding that @MelaHub ?

**Comment by MelaHub** [comment]
Sure thing @johanandren ! I will need some help though :)

**Comment by johanandren** [comment]
Let us know what you need help with and we'll help as best as we can! (It's vacation times so the team is a bit thin though, replies may not be super-fast the coming weeks)

**Comment by MelaHub** [comment]
Just to start...how can I assign the issue to myself?  I'm going to start to work on this in the next few days - can't wait to contribute!

**Comment by jlprat** [comment]
Unfortunately, issues can only be assigned to members of the organization. But I'll label it accordingly.

**Comment by jlprat** [comment]
So feel free to start working on it 🙂

**Comment by MelaHub** [comment]
Thank you @jlprat ! Now I have something in place but I have no permission to push the branch and open the pr :(

**Comment by jlprat** [comment]
Close with https://github.com/akka/akka-http/commit/72d4f9615adaba5eb62896550dbdb4a5f898d865
