### ISSUE TITLE
Offer migration path from Spray Caching

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#213]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ktoso](https://github.com/ktoso)**
_Wednesday Jun 01, 2016 at 09:15 GMT_
_Originally opened as https://github.com/akka/akka/issues/20679_

---

The question keeps coming up, and it's only one simple file https://github.com/spray/spray/tree/master/spray-caching/src/main/scala/spray/caching

We could provide it as separate mini project, declare it community lead.
Please ping me if you'd like to contribute this port so I can create a repo for it.

**Comment by ktoso** [comment]
<a href="https://github.com/zhxiaogg"><img src="https://avatars.githubusercontent.com/u/6303886?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zhxiaogg](https://github.com/zhxiaogg)**
_Wednesday Jun 01, 2016 at 12:57 GMT_

----

@ktoso It's about migrating the spray cache directive to Akka HTTP server DSL, right? If so, I would like to give it a try.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Jun 01, 2016 at 12:59 GMT_

----

Yes exactly - shouldn't be hard I think, and I think it should live outside of the akka/akka repo, but we can host it under the `akka/` organisation perhaps as `akka/akka-http-caching`. I would like to see it be a community by-demand driven project, I don't think we (core team) will spend time on it, and at the same time we do want to allow the HTTP ecosystem to flourish a bit more.

**Comment by ktoso** [comment]
<a href="https://github.com/zhxiaogg"><img src="https://avatars.githubusercontent.com/u/6303886?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zhxiaogg](https://github.com/zhxiaogg)**
_Wednesday Jun 01, 2016 at 12:59 GMT_

----

BTW, why a new project? Is it a planned repo to hold all extra directives?

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Jun 01, 2016 at 13:01 GMT_

----

It does not quite fit nor would it be "driven by" lightbend, so a separate repo makes most sense. 
Yes, I think we'll want to have a repo to encourage more HTTP community participation, I hope to have a detailed plan for that laid out in a few weeks.

**Comment by ktoso** [comment]
<a href="https://github.com/zhxiaogg"><img src="https://avatars.githubusercontent.com/u/6303886?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zhxiaogg](https://github.com/zhxiaogg)**
_Wednesday Jun 01, 2016 at 13:09 GMT_

----

Great, looking forward to the plan.

**Comment by ktoso** [comment]
<a href="https://github.com/hepin1989"><img src="https://avatars.githubusercontent.com/u/501740?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hepin1989](https://github.com/hepin1989)**
_Wednesday Jun 01, 2016 at 15:13 GMT_

----

https://github.com/ben-manes/caffeine/
We could try to make use of this:)

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Jun 01, 2016 at 15:17 GMT_

----

Looks fun!
Another reason to have it as separate repo in which we can experiment
aggresively and deliver a cool extension that's easy to use with Akka HTTP,
rather than being limited by our mantra of not including dependencies into
Akka "core" (which is very valuable for any foundational project like Akka
is) :-)

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 1 June 2016 at 17:13:23, kerr (notifications@github.com) wrote:

https://github.com/ben-manes/caffeine/
We could try to make use of this:)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/20679#issuecomment-223024741>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAHYkyLZNwClg3PMTUGMKuI3LIYP6z-Zks5qHaGFgaJpZM4IrVz0>
.

**Comment by ktoso** [comment]
<a href="https://github.com/ben-manes"><img src="https://avatars.githubusercontent.com/u/378614?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ben-manes](https://github.com/ben-manes)**
_Wednesday Jun 01, 2016 at 17:13 GMT_

----

Thanks @hepin1989.

Please do prefer Caffeine. I no longer actively develop `ConcurrentLinkedHashMap` (used by Spray Caching) or Guava's cache. If you use the jdk8-scala adapters you might prefer to use an AsyncLoadingCache for future handling. Also note that `ascendingKeys` would use `cache.policy` to obtain the eviction order, though I'm surprised that's being used (intended for warm restart).

**Comment by ianclegg** [comment]
@zhxiaogg I assume you were not able to pick this up?

**Comment by ianclegg** [comment]
@ktoso, Had a quick look at this, Caffeine is ~impressive~ exceptional. I followed up @ben-manes suggestion, but sadly AsyncLoadingCache is not a good fit. It's designed to use a single value loader implementation across all keys. Contrast that with Spray Caching, where callers can pass a unique, key specific value loader when fetching/putting into cache and the problem is apparent.

It's not a big deal - Caffeine's BoundedLocalCache looks like the way to go.

**Comment by ben-manes** [comment]
@ianclegg can you use `Cache.get(key, mappingFunction)`?

**Comment by ben-manes** [comment]
Because there hasn't been a justification for `AsyncCache`, the quick hack is to use a dummy loader (e.g. `key -> null`). Then you can use `AsyncLoadingCache,get(key, mappingFunction)` too. The manual loading methods are on the interface to make it easy for us to add `AsyncCache` later if there's is enough demand.

**Comment by ianclegg** [comment]
@ben-manes Perfect :thumbsup:

**Comment by ben-manes** [comment]
You may also prefer to use the Scala wrapper - [Scaffeine](https://github.com/blemale/scaffeine), which provides a nice idiomatic view.

**Comment by ktoso** [comment]
Hi there! Thanks for chiming in @ben-manes :-) 
I think we'd actually prefer to depend on the raw java library - makes it easier to cross publish for different scala versions as we're not dependent on a 3rd party library then. Akka is kind of at the root of the tree of many dependencies so we try to publish for stable scala versions ASAP, so while it won't matter for a year or so it'll be nicer to depend on the raw java lib (also, since we hide the API behind directives anyway, users won't see much of the Caffeine API I think).

Sounds like you're interested in hacking on this @ianclegg? That would be really great! Let us know if you need any hints etc.

**Comment by ianclegg** [comment]
Sure, I have all the key pieces - i'll put together a PR perhaps this evening - otherwise towards the end of the week and we can refine.

**Comment by ianclegg** [comment]
@ktoso Earlier in this issue you mentioned creating a new repo for caching - whats your current thoughts on this? I noticed the unusual version number bump for akka-http 😏 should the cache/PR now sit in this repo.

We'll have around 3 or so source files consisting of the cache directive, the cache trait and the cache implementations to find a home for.

**Comment by ktoso** [comment]
Thea earlier note on separate repo was indeed before we worked out the new versioning and split of akka-http into  its own repo. Now it should be fine to include here, as separate project but in the same repo. We'd mark it as an experimental module.

Thanks in advance :)

**Comment by ianclegg** [comment]
@ben-manes Spray caching also wrapped the ```size()```, ```keySet()```, ```remove(key)``` methods on ConcurrentLinkedHashMap. It looks like the equivalent api's for Caffeine Cache can be reached via the LoadingCache from the ```synchronous()``` method.

Off the top of your head, is going via ```synchronous()``` a significant performance/memory hit over the equivalent calls for ConcurrentLinkedHashMap. That is to say is calling ```size()```, ```keySet()```, ```remove(key)``` better optimised in ConcurrentLinkedHashMap. I know thats a poor question, but whats you hunch on it 😏 

To give you the background, although Spray Caching wraps them, they are not actually required by the Caching Directive, so there may be an option to simply drop them from the wrapper if the ```synchronous()``` route is discouraged

**Comment by ben-manes** [comment]
The `synchronous()` and `asMap()` views are effectively free. For an asynchronous cache it can be more expensive if it requires blocking, e.g. to return the result. So a `cache.synchronous().invalidate(key)` would be cheaper than `cache.synchronous().asMap().remove(key)` since the latter requires returning the non-future value. Otherwise the actual removal from the hash map is similar performance to the underlying `ConcurrentHashMap`, with a little more work to maintain the other data structures.

The write performance actually increased in Caffeine compared to CLHM, which can be a bit surprising. CLHM relies on spin loops to make the operations atomic whereas Caffeine synchronizes on the entry. But I wouldn't expect the benchmarked difference to be observable in real applications.

Caffeine uses JDK8's rewritten CHM which is a big improvement. CLHM adopted a backport of that, but is loosely coupled so it worked with any `ConcurrentMap`.

I don't think there's any degradation except for the `remove(key): Option[Future[V]]` method. Since there is no asynchronous `asMap()` view it would become either a `Unit` or `V` result, the latter being blocking. That would require forgoing the async view and uses a `Cache[K, Future[V]]` instead.

We could make async caches more flexible, as I error'd on simplicity to observe usages.

**Comment by ianclegg** [comment]
Sounds like we shouldn't have a problem to continue supporting the spray Cache trait using those wrappers then. As I mentioned the remove method won't be used by the Cache Directive anyway, I think it was just there to enable the cache to be used in applications outside of Spray. Thanks again!

**Comment by ktoso** [comment]
Hi there - are you still working on this @ianclegg?

**Comment by jrudolph** [comment]
Was added with #1503 / #1539.
