### ISSUE TITLE
[Doc] Add banner warning of outdated docs while browsing old versions

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#2135]
Similarly to what has been done for Akka under https://github.com/akka/akka/issues/25244
We should have a similar warning banner for Akka HTTP. The main problem I see currently that stops me from directly copy-pasting the same PR that made it for Akka itself is that it relies on https://github.com/akka/akka.github.com/blob/master/versions.json which doesn't contain any information about Akka HTTP. Is that file updated "automatically" or is it manually curated?

**Comment by jlprat** [comment]
Not marking it as "help wanted" yet as it might involve some magic from the team if the `versions.json` is a generated one.

**Comment by jlprat** [comment]
The `version.json` update (to include data from `config.yml`) needs to be done by the core team, right?

**Comment by ktoso** [comment]
The file is here, anyone can update it https://github.com/akka/akka.github.com/blob/master/versions.json

**Comment by johanandren** [comment]
I just opened a pr over in that repo!

**Comment by jlprat** [comment]
I probably will be able to do this one this evening

**Comment by johanandren** [comment]
Excellent, thanks @jlprat !
