### ISSUE TITLE
Explain RejectionHandler in docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#214]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ktoso](https://github.com/ktoso)**
_Tuesday May 24, 2016 at 11:12 GMT_
_Originally opened as https://github.com/akka/akka/issues/20608_

---

It should be documented that RejectionHandler can be used to change HttpResponse if a rejection happens.

This relates to Route.seal

**Comment by ktoso** [comment]
<a href="https://github.com/richard-imaoka"><img src="https://avatars.githubusercontent.com/u/7414320?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richard-imaoka](https://github.com/richard-imaoka)**
_Tuesday May 24, 2016 at 21:56 GMT_

----

Hi, 
Looking at the ["Routes" doc](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/routes.html#routes) and the ["Rejections" doc](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/rejections.html#rejections), it seems this is somewhat already documented. Did you mean to add more explanation?

Otherwise, add some more examples in ["handleRejections" doc](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/directives/execution-directives/handleRejections.html) to highlight how custom handleRejections make different HttpResponse?

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Tuesday May 24, 2016 at 22:07 GMT_

----

Hm, perhaps it's more about adding an explicit example about this story:

```
Guy Dawson @Mullefa May 19 19:13
This message was deleted
I'm as using akka-http (with circe FTW ) to create a JSON API. In the routing DSL I am using entity(as[T]) to unmarshall the request entity to the given type. If the JSON is invalid, the client gets an error, in my case something like:
Content-Length: 73
Content-Type: text/plain; charset=UTF-8
Date: Thu, 19 May 2016 16:52:01 GMT
Server: akka-http/2.4.4

The request content was malformed:
UUID: El(DownField(userId),true,false)
I would like to make the response consistent with the rest of the API - in my case something like {"ok": false, "error": "INVALID_JSON"}, however, the behaviour seems to be hard coded into the entity() function. So... should I either use lower-level functionality i.e. not entity() or should entity() be made configurable via another implicit argument?

Konrad Malawski @ktoso May 19 19:59
read on RejectionHandler

Guy Dawson @Mullefa May 20 00:37
@ktoso Thanks for the pointer - funny how the actual solution is better than either of my solutions  One thing that's worth noting - I had to wrap the route with Route.seal() to ensure the implicitRejectionHandler was used. This requires an implicit RouteSettings which is found as long as an implicit ActorSystem is in scope. If this is indeed the correct way to do it, it might be worth mentioning it in the documentation (for beginner's such as myself ). I was only able to work it out thanks to a nifty trick on implicits I read in one of your blog posts 
```

:point_up: [May 20, 2016 12:37 AM](https://gitter.im/akka/akka?at=573e4023ff441ca333d32d51)

@Mullefa wanted to contribute it actually if given enough hints, let me know what's unclear and we'll help out :) There's a good point to start here https://github.com/akka/akka/blob/master/CONTRIBUTING.md

**Comment by ktoso** [comment]
<a href="https://github.com/Mullefa"><img src="https://avatars.githubusercontent.com/u/4085817?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mullefa](https://github.com/Mullefa)**
_Wednesday May 25, 2016 at 21:10 GMT_

----

Ok, cool. I should be able to do something by this weekend. If it's useful - great, but I won't mind if it's not included.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday May 25, 2016 at 21:57 GMT_

----

Thanks a lot :) I'm sure we'll find a nice place for additional docs of it!

**Comment by jlprat** [comment]
I was doing some archaeology, and I'd say this is done already: https://doc.akka.io/docs/akka-http/current/routing-dsl/rejections.html?language=scala#customizing-rejection-handling

**Comment by jlprat** [comment]
Closing, let me know if should stay open

**Comment by ktoso** [comment]
I agree, seems done there indeed
