### ISSUE TITLE
Getting client pool SlotState$BusyState exception in tests

### ISSUE THREAD

**Issue by kpritam** [akka/akka-http#2143]
Below code results into following exception on every alternate build: ` akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1: Connection was shutdown.
`

```
override protected def afterAll(): Unit = {
    binding.unbind().await
    Http(wiring.actorSystem).shutdownAllConnectionPools().await
    CoordinatedShutdown(wiring.actorSystem).run(TestFinishedReason).await
  }
```
I have seen existing open issues around graceful shutdown but as a workaround something like above code is suggested.
But in our case, this is failing very frequently causing entire build to fail. Is there proper way to clean all the resources created by akka http server and client?

**Comment by jrudolph** [comment]
Hi @kpritam, sorry for never answering. Which version are you running? Have you tested with 10.1.5?

**Comment by kpritam** [comment]
yes @jrudolph, I am using 10.1.5

**Comment by jrudolph** [comment]
Is the line the only output you get? Can you post more context or a complete stack trace? How do the tests fail (i.e. why would an `afterAll` clause fail a tests)?

**Comment by kpritam** [comment]
Yes, that is the only line gets printed. Below are some build failures for same reason

[build-2924](http://ec2-35-154-215-191.ap-south-1.compute.amazonaws.com:8080/blue/organizations/jenkins/csw-prod-dev/detail/csw-prod-dev/2924/tests), [build-2923](http://ec2-35-154-215-191.ap-south-1.compute.amazonaws.com:8080/blue/organizations/jenkins/csw-prod-dev/detail/csw-prod-dev/2923/tests), [build-2920](http://ec2-35-154-215-191.ap-south-1.compute.amazonaws.com:8080/blue/organizations/jenkins/csw-prod-dev/detail/csw-prod-dev/2920/tests)

Regarding your last question, any specific test does not fail but as this exception is getting thrown in `afterAll`, test suite gets aborted and that fails build.

I am testing below scenario:
1. `beforeAll` -> Start akka-http server
2. Client registers multiple services with server in tests
3. `afterAll` -> unregister all services via http requests through client and then afterAll from original post

**Comment by kpritam** [comment]
Also another observation, seeing these errors very frequently after upgrading akka to 2.5.17, not sure about what this has to do with original issue.

**Comment by jrudolph** [comment]
Probably outdated by now, we changed error reporting and the Client pool gateway quite a bit in the meantime.
