### ISSUE TITLE
Default Http().bindAndHandleAsync default parallelism=1 doesn't make sense for HTTP/2

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2145]
`parallelism` defaults to `1` because in HTTP/1 we assume that pipelining is switched off so handling one request at a time *per connection* is enough.

For HTTP/2, however, it doesn't really make sense as we want to allow multiplexing multiple requests per connection. It's somewhat weird that this never came up while developing and testing HTTP/2. I guess the reason is that during HTTP/2 testing we never tested running multiple `HttpRequest => Future[HttpResponse]` at the same time but only tested streaming out the response in parallel which works.

We should

 * document that you need to adapt this setting with HTTP/2
 * change samples to use a more sensible value
 * add a warning if the HTTP/2 server is run with the default of 1

**Comment by ktoso** [comment]
(Please mark in progress since has PR)

**Comment by jrudolph** [comment]
Fixed in #2146.
