### ISSUE TITLE
Use travis stages to call whitesource only once per build

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2155]
I suspect the failures we're having are related to the fact that we're invoking whitesource at roughly the same time for both the 2.11 and the 2.12 version.

If we update our travis config to check whitesource only once that might mitigate the problem. The chance that this would miss a licensing problem that is present only on 2.11 or only on 2.12 seems rather low.

**Comment by jrudolph** [comment]
> I suspect the failures we're having are related to the fact that we're invoking whitesource at roughly the same time for both the 2.11 and the 2.12 version.

Ugh, good point. Will be interesting to see if we can improve the situation :+1:

**Comment by jrudolph** [comment]
I guess that was fixed by now?
