### ISSUE TITLE
[akka-testkit] JUnitRouteTest has dependency on scalatest, and is Serializable

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#216]
<a href="https://github.com/jypma"><img src="https://avatars.githubusercontent.com/u/483519?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jypma](https://github.com/jypma)**
_Thursday May 19, 2016 at 09:26 GMT_
_Originally opened as https://github.com/akka/akka/issues/20559_

---

Since 2.4.5, `JUnitRouteTest` pulls in the trait `JUnitSuiteLike` from scalatest. This has two (unintended?) side-effects:
1. Projects using `JUnitRouteTest` must declare a dependency on scalatest themselves, since it's not a declared compile dependency for akka-testkit (apparently).
2. All Java test classes now are marked `Serializable` (since `Suite` is), triggering compiler warnings by default.

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Thursday May 19, 2016 at 09:27 GMT_

----

@ktoso ;(

**Comment by richard-imaoka** [comment]
Is the warning "Serializable class without serialVersionUID"? Somehow I didn't see any warning when I did git clone akka-http, and sbt compile on my machine.

**Comment by richard-imaoka** [comment]
ping @jypma

**Comment by richard-imaoka** [comment]
As in my PR 325 the way I proposed would not work... I might revisit this later, or if anyone else has a better idea please go ahead.

**Comment by jypma** [comment]
@richard-imaoka here's the base class we're currently using:
```
public class JUnitRouteTest extends akka.http.javadsl.testkit.RouteTest {
    private static final Config config = ConfigFactory.defaultReference();
    private static final ActorSystem _system = ActorSystem.create("route-test", config);
    private static final Materializer _materializer = ActorMaterializer.create(_system);
    
    @Override
    public TestRouteResult createTestRouteResult(HttpRequest arg0, RouteResult arg1) {
        return new TestRouteResult(arg1, awaitDuration(), _system.dispatcher(), _materializer) {
            @Override
            public void assertEquals(Object expected, Object actual, String message) {
                Assert.assertEquals(message, expected, actual);
            }

            @Override
            public void assertEquals(int expected, int actual, String message) {
                Assert.assertEquals(message, expected, actual);
            }

            @Override
            public void assertTrue(boolean predicate, String message) {
                Assert.assertTrue(message, predicate);
            }

            @Override
            public void fail(String message) {
                Assert.fail(message);
            }
        };
    }

    @Override
    public Materializer materializer() {
        return _materializer;
    }

    @Override
    public ActorSystem system() {
        return _system;
    }
}
```
That works for us, but lacks the ability to customize the `config`. One could look into integrating the existing `ActorSystemResource`.

**Comment by jrudolph** [comment]
Done a long time ago in #1147.
