### ISSUE TITLE
Release 10.0.x for Scala 2.13

### ISSUE THREAD

**Issue by dwijnand** [akka/akka-http#2172]
This would unblock https://github.com/akka/akka-management/issues/269.

**Comment by jrudolph** [comment]
We'd like to avoid publishing 10.0.x for 2.13 if possible. It would be better if we could update akka-management to Akka HTTP 10.1.x instead (which so far was vetoed because it might pull up Akka HTTP versions for Play and Lagom).

**Comment by dwijnand** [comment]
The efforts behind https://github.com/akka/akka-management/issues/269 have been abandoned.
