### ISSUE TITLE
Remove parallelism setting in Http2.bindAndHandleAsync

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2175]
We should use `Http2ServerSettings.maxConcurrentStreams` instead. Technically, `Http2` was not marked as internal API, but I think we can still treat it as such as we only documented and advertised going through the Http2Shadow.

**Comment by raboof** [comment]
(the entire HTTP/2 module is marked 'preview' in the documentation, so I agree this should be fine.

**Comment by jrudolph** [comment]
> (the entire HTTP/2 module is marked 'preview' in the documentation, so I agree this should be fine.

Ah, forgot about that. So, let's go for it :)

**Comment by jrudolph** [comment]
This ticket makes still sense as a cleanup: we now always pass `maxConcurrentStreams` from `bindAndHandleAsync` but we could just remove that parameter and use the setting directly.
