### ISSUE TITLE
Great getting started ticket: write example snippets for Akka HTTP Java DSL

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#218]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johanandren](https://github.com/johanandren)**
_Friday May 06, 2016 at 14:06 GMT_
_Originally opened as https://github.com/akka/akka/issues/20466_

---

The last couple of months we have been hard at work with providing a DSL for Java that is (almost) as neat as the Scala DSL for Akka HTTP. We are now at the point where we have the API in place in master and basic docs but what is missing is examples for each of the directives. 

Providing an example for a directive is a perfect way to start contributing to Akka, each directive is sufficiently isolated, and there is a corresponding Scala example to base the sample on.

How to do it:
- **Select a directive below**, **write a comment** that you will be working on it
- **Read the docs**, [the corresponding Scala directive docs]file(http://doc.akka.io/docs/akka/2.4.4/scala/http/routing-dsl/directives/alphabetically.html#predefined-directives) and make sure you understand what the directive does
- Look at **the Scala example** in `akka-docs/rst/scala/code/docs/http/scaladsl/server/directives` and port it to a Java example in `akka-docs/rst/java/code/docs/http/javadsl/server/directives`. Look at the existing Java samples to see how the tests should be set up
- **Run the test using** `akka-docs/testOnly docs.http.javadsl.server.directives.YourDirective`
- **Include the test in the docs** by adding comments with the label from the `.rst` documentation of the directive. 
- **Generate the docs** using `akka-docs/sphinx:generateHtml` and see that the sample is included in the docs and looks nice (you will find the docs generated as HTML under akka-docs/target/sphinx/html/index.html` so that you can preview in your browser)
- **Make a PR** to have the sample reviewed and merged into Akka HTTP

**Directives to provide samples for**
(all paths relative to `akka-docs/rst/java/http/routing-dsl/directives`)
- [x] basic-directives/cancelRejection.rst thanks @Hawstein!
- [x] basic-directives/cancelRejections.rst thanks @Hawstein!
- [x] basic-directives/extract.rst thanks @Hawstein!
- [x] basic-directives/extractExecutionContext.rst thanks @Hawstein!
- [x] basic-directives/extractLog.rst thanks @Hawstein!
- [x] basic-directives/extractMaterializer.rst thanks @Hawstein!
- [x] basic-directives/extractRequest.rst thanks @Hawstein!
- [x] basic-directives/extractRequestContext.rst thanks @Hawstein!
- [x] basic-directives/extractSettings.rst thanks @Hawstein!
- [x] basic-directives/extractUnmatchedPath.rst thanks @Hawstein!
- [x] basic-directives/extractUri.rst thanks @Hawstein!
- [x] basic-directives/mapInnerRoute.rst thanks @Hawstein!
- [x] basic-directives/mapRejections.rst thanks @Hawstein!
- [x] basic-directives/mapRequest.rst thanks @Hawstein!
- [x] basic-directives/mapRequestContext.rst thanks @Hawstein!
- [x] basic-directives/mapResponse.rst thanks @Hawstein!
- [x] basic-directives/mapResponseEntity.rst thanks @Hawstein!
- [x] basic-directives/mapResponseHeaders.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResult.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultPF.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultStage.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultWith.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultWithPF.rst thanks @Hawstein!
- [x] basic-directives/mapSettings.rst thanks @Hawstein!
- [x] basic-directives/mapUnmatchedPath.rst thanks @Hawstein!
- [x] basic-directives/pass.rst thanks @Hawstein!
- [x] basic-directives/provide.rst thanks @Hawstein!
- [x] basic-directives/recoverRejections.rst thanks @Hawstein!
- [x] basic-directives/recoverRejectionsWith.rst thanks @Hawstein!
- [x] basic-directives/withExecutionContext.rst thanks @Hawstein!
- [x] basic-directives/withLog.rst thanks @Hawstein!
- [x] basic-directives/withMaterializer.rst thanks @Hawstein!
- [x] basic-directives/withSettings.rst thanks @Hawstein!
- [x] coding-directives/decodeRequest.rst thanks @Hawstein!
- [x] coding-directives/decodeRequestWith.rst thanks @Hawstein!
- [x] coding-directives/encodeResponse.rst thanks @Hawstein!
- [x] coding-directives/encodeResponseWith.rst thanks @Hawstein!
- [x] coding-directives/responseEncodingAccepted.rst thanks @Hawstein!
- [x] cookie-directives/cookie.rst thanks @Hawstein!
- [x] cookie-directives/deleteCookie.rst thanks @Hawstein!
- [x] cookie-directives/optionalCookie.rst thanks @Hawstein!
- [x] cookie-directives/setCookie.rst thanks @Hawstein!
- [x] debugging-directives/logRequest.rst thanks @fagossa!
- [x] debugging-directives/logRequestResult.rst thanks @fagossa!
- [x] debugging-directives/logResult.rst thanks @fagossa!
- [x] execution-directives/handleExceptions.rst thanks @Hawstein!
- [x] execution-directives/handleRejections.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromBrowseableDirectories.rst thanks @Hawstein! 
- [x] file-and-resource-directives/getFromBrowseableDirectory.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromDirectory.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromFile.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromResource.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromResourceDirectory.rst thanks @Hawstein!
- [x] file-and-resource-directives/listDirectoryContents.rst thanks @Hawstein!
- [x] file-upload-directives/fileUpload.rst thanks @gosubpl!
- [x] file-upload-directives/uploadedFile.rst thanks @gosubpl!
- [x] form-field-directives/formField.rst thanks @Hawstein!
- [x] form-field-directives/formFieldList.rst thanks @Hawstein!
- [x] form-field-directives/formFieldMap.rst thanks @Hawstein!
- [x] form-field-directives/formFieldMultiMap.rst thanks @Hawstein!
- [x] future-directives/completeOrRecoverWith.rst
- [x] future-directives/onComplete.rst
- [x] future-directives/onSuccess.rst
- [x] header-directives/headerValue.rst thanks @zhxiaogg!
- [x] header-directives/headerValueByName.rst thanks @zhxiaogg!
- [x] header-directives/headerValueByType.rst thanks @zhxiaogg!
- [x] header-directives/headerValuePF.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValue.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValueByName.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValueByType.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValuePF.rst thanks @zhxiaogg!
- [ ] marshalling-directives/completeWith.rst
- [x] marshalling-directives/entity.rst
- [ ] marshalling-directives/handleWith.rst
- [x] misc-directives/extractClientIP.rst thanks @jlprat
- [x] misc-directives/rejectEmptyResponse.rst  thanks @jlprat
- [x] misc-directives/requestEntityEmpty.rst thanks @jlprat
- [x] misc-directives/requestEntityPresent.rst thanks @jlprat
- [x] misc-directives/selectPreferredLanguage.rst thanks @jlprat
- [x] misc-directives/validate.rst thanks @jlprat
- [x] parameter-directives/parameter.rst thanks @Hawstein!
- [x] parameter-directives/parameterMap.rst thanks @Hawstein!
- [x] parameter-directives/parameterMultiMap.rst thanks @Hawstein!
- [x] parameter-directives/parameters.rst thanks @Hawstein!
- [x] parameter-directives/parameterSeq.rst thanks @Hawstein!
- [x] path-directives/path.rst thanks @fagossa !
- [x] path-directives/pathEnd.rst thanks @fagossa !
- [x] path-directives/pathEndOrSingleSlash.rst thanks @fagossa !
- [x] path-directives/pathPrefix.rst thanks @fagossa !
- [x] path-directives/pathPrefixTest.rst thanks @fagossa !
- [x] path-directives/pathSingleSlash.rst thanks @fagossa !
- [x] path-directives/pathSuffix.rst thanks @fagossa !
- [x] path-directives/pathSuffixTest.rst thanks @fagossa !
- [x] path-directives/rawPathPrefix.rst thanks @fagossa !
- [x] path-directives/rawPathPrefixTest.rst thanks @fagossa !
- [x] path-directives/redirectToNoTrailingSlashIfPresent.rst thanks @fagossa !
- [x] path-directives/redirectToTrailingSlashIfMissing.rst thanks @fagossa !
- [ ] range-directives/withRangeSupport.rst
- [x] respond-with-directives/respondWithDefaultHeader.rst thanks @felipefzdz!
- [x] respond-with-directives/respondWithDefaultHeaders.rst thanks @felipefzdz!
- [x] respond-with-directives/respondWithHeader.rst thanks @felipefzdz!
- [x] respond-with-directives/respondWithHeaders.rst thanks @felipefzdz!
- [x] route-directives/complete.rst
- [x] route-directives/failWith.rst
- [x] route-directives/redirect.rst
- [x] route-directives/reject.rst
- [x] scheme-directives/extractScheme.rst thanks @fagossa !
- [x] scheme-directives/scheme.rst thanks @fagossa !
- [x] security-directives/authenticateBasic.rst
- [x] security-directives/authenticateBasicAsync.rst
- [x] security-directives/authenticateBasicPF.rst
- [x] security-directives/authenticateBasicPFAsync.rst
- [x] security-directives/authenticateOAuth2.rst
- [x] security-directives/authenticateOAuth2Async.rst
- [x] security-directives/authenticateOAuth2PF.rst
- [x] security-directives/authenticateOAuth2PFAsync.rst
- [x] security-directives/authenticateOrRejectWithChallenge.rst
- [x] security-directives/authorize.rst
- [x] security-directives/authorizeAsync.rst
- [x] security-directives/extractCredentials.rst
- [x] timeout-directives/withoutRequestTimeout.rst thanks @gosubpl!
- [x] timeout-directives/withRequestTimeout.rst thanks @gosubpl!
- [x] timeout-directives/withRequestTimeoutResponse.rst thanks @gosubpl!
- [x] websocket-directives/handleWebSocketMessages.rst
- [x] websocket-directives/handleWebSocketMessagesForProtocol.rst

**Comment by ktoso** [comment]
<a href="https://github.com/poojadshende"><img src="https://avatars.githubusercontent.com/u/10903248?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [poojadshende](https://github.com/poojadshende)**
_Saturday May 07, 2016 at 00:44 GMT_

----

@johanandren Can I start working on one of the directory or do I have to wait till JavaDSL is merged to master?

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Sunday May 08, 2016 at 18:09 GMT_

----

@poojadshende I'm afraid you will have to wait, we expected to merge the Java DSL during Friday, but things didn't go our way. :( Will update ticket as soon as we have the DSL merged.

**Comment by ktoso** [comment]
<a href="https://github.com/johanandren"><img src="https://avatars.githubusercontent.com/u/666915?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johanandren](https://github.com/johanandren)**
_Wednesday May 18, 2016 at 14:18 GMT_

----

Now this ticket is ready for some contributing!

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Saturday May 21, 2016 at 19:30 GMT_

----

I make a PR for the CookieDirectives example snippet. If that is OK, I will go on for the BasicDirectives.

**Comment by ktoso** [comment]
<a href="https://github.com/patriknw"><img src="https://avatars.githubusercontent.com/u/336161?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [patriknw](https://github.com/patriknw)**
_Saturday May 21, 2016 at 20:23 GMT_

----

Sounds great, thanks

**Comment by ktoso** [comment]
<a href="https://github.com/fagossa"><img src="https://avatars.githubusercontent.com/u/6917738?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fagossa](https://github.com/fagossa)**
_Sunday May 22, 2016 at 17:03 GMT_

----

I made a PR for the [scheme directive](https://github.com/akka/akka/pull/20586)

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Monday May 23, 2016 at 10:50 GMT_

----

Awesome, thanks @fagossa!
1 down, 124 to go...! :-)

:shipit:

**Comment by ktoso** [comment]
<a href="https://github.com/fagossa"><img src="https://avatars.githubusercontent.com/u/6917738?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fagossa](https://github.com/fagossa)**
_Monday May 23, 2016 at 14:02 GMT_

----

@ktoso The `scheme-directives/extractScheme.rst` directive is also shown in [the example](https://github.com/akka/akka/pull/20586/files); so, I think that makes _2 down, 123 to go_!!

BTW I'm working on some other directives

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Monday May 23, 2016 at 14:04 GMT_

----

Hah! You're right, awesome :)
Thanks a lot for your help!

**Comment by ktoso** [comment]
<a href="https://github.com/felipefzdz"><img src="https://avatars.githubusercontent.com/u/369379?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [felipefzdz](https://github.com/felipefzdz)**
_Monday May 23, 2016 at 14:17 GMT_

----

I'll be working on the ones contained in *RespondWithDirectivesExamplesSpec*. `respondWithHeader`, `respondWithDefaultHeader`...

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Monday May 23, 2016 at 15:49 GMT_

----

Great, thanks @felipefzdz !

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Tuesday May 24, 2016 at 11:24 GMT_

----

Working on BasicDirectives now.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Tuesday May 24, 2016 at 11:25 GMT_

----

Awesome, thank you!

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Tuesday May 24, 2016 at 11:53 GMT_

----

Really glad to contribute to Akka. Thanks for providing such a convenient way to contribute to it.

**Comment by ktoso** [comment]
<a href="https://github.com/zhxiaogg"><img src="https://avatars.githubusercontent.com/u/6303886?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zhxiaogg](https://github.com/zhxiaogg)**
_Wednesday May 25, 2016 at 22:55 GMT_

----

I would try `header-directives` if you don't mind.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday May 25, 2016 at 23:04 GMT_

----

Great, thanks a lot :-)

-- 
Konrad `ktoso` Malawski
Akka @ Lightbend

On 26 May 2016 at 00:55:46, John Zhang (notifications@github.com) wrote:

I would try header-directives if you don't mind.

**Comment by ktoso** [comment]
<a href="https://github.com/fagossa"><img src="https://avatars.githubusercontent.com/u/6917738?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fagossa](https://github.com/fagossa)**
_Sunday May 29, 2016 at 16:14 GMT_

----

@ktoso I just made a [PR](https://github.com/akka/akka/pull/20651) on the debugging directives. It covers:

- debugging-directives/logRequest.rst
- debugging-directives/logRequestResult.rst
- debugging-directives/logResult.rst

i'll continue with `path-directives`

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Monday May 30, 2016 at 14:43 GMT_

----

Three more down by @felipefzdz, thanks a lot!

**Comment by ktoso** [comment]
<a href="https://github.com/zhxiaogg"><img src="https://avatars.githubusercontent.com/u/6303886?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zhxiaogg](https://github.com/zhxiaogg)**
_Tuesday May 31, 2016 at 17:19 GMT_

----

I made a PR #20673  for all the header directives together. And will work on `marshalling` if you don't mind.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Tuesday May 31, 2016 at 17:20 GMT_

----

That's great, thank you! :-)

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Friday Jun 03, 2016 at 13:19 GMT_

----

Since basic-directives is finally merged, going to work on execution-directives :)

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 03, 2016 at 13:21 GMT_

----

Thanks a lot :-)
Sorry for the delay, was a bit overwhelmed with so many people contributing last week – nice problem to have :-)

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Friday Jun 03, 2016 at 13:25 GMT_

----

@ktoso Ahh, more and more people are involved to contribute to Akka. That's really a good news :)

**Comment by ktoso** [comment]
<a href="https://github.com/hepin1989"><img src="https://avatars.githubusercontent.com/u/501740?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hepin1989](https://github.com/hepin1989)**
_Friday Jun 03, 2016 at 13:30 GMT_

----

@Hawstein @zhxiaogg Yes,especially guys like you from China:).

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 03, 2016 at 13:31 GMT_

----

Very grateful to have you guys join the efforts indeed :-)

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Saturday Jun 04, 2016 at 07:22 GMT_

----

Start to work on `security-directives`.

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Saturday Jun 04, 2016 at 18:16 GMT_

----

Working on ` coding-directives`.

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Sunday Jun 05, 2016 at 19:12 GMT_

----

Working on `route-directives`.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Sunday Jun 05, 2016 at 19:30 GMT_

----

You're on fire today :-) Thanks a lot!

**Comment by ktoso** [comment]
<a href="https://github.com/Hawstein"><img src="https://avatars.githubusercontent.com/u/2238491?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hawstein](https://github.com/Hawstein)**
_Monday Jun 06, 2016 at 17:28 GMT_

----

Working on ` form-field-directives`.

**Comment by gosubpl** [comment]
Do we know what is the current status of that. Last it was:
- [ ] marshalling-directives @zhxiaogg woking on it
- [ ] misc-directives @fagossa working on it
- [x] websocket-directives @Hawstein did this

Last change, I believe, was @richard-imaoka merging `marshalling-directives/entity` in https://github.com/akka/akka-http/pull/335 . But the rest is probably not done yet. Or am I wrong?
So @fagossa are you working on any of the `misc-directives`? are you planning to submit PR any time? Perhaps just for some of them?
And @zhxiaogg have you by any chance finished either `marshalling-directives/completeWith.rst` or `marshalling-directives/handleWith.rst` ?
Please let us know guys. If you are not planning to continue, someone could pick up this work. Would be good to have this completed around the first stable release.

**Comment by zhxiaogg** [comment]
@gosubpl  I guess I have no time on these issues now.

**Comment by richard-imaoka** [comment]
FYI other than entity, the above two marshalling directives themselves are missing not only examples. I tried to add the missing directives but I could not figure out the right signatures.

**Comment by gosubpl** [comment]
@zhxiaogg thanks for the info
@richard-imaoka I kind of expected this, as doing the file upload stuff required me to write the whole Java side implementation of multipart model, as only Scala implementation and Java interface were present. To this day the Java implementation probably has a couple of unimplemented features, so you have to tread very carefully.

**Comment by gosubpl** [comment]
Ok, a small status update, @jedrekn (new kid on the block, so to speak) seems to be hacking away on the missing `marshalling-directives`. Hope @fagossa gets back soon with the status of `misc-directives` - if he is not working on this, someone else could be :)

**Comment by jlprat** [comment]
If @fagossa is not working on `misc-directives`, I could try to provide some Java examples for them

**Comment by gosubpl** [comment]
Absolutely, @jlprat go ahead. I think that @fagossa did not get back for such a long time that it would be fair to say that `misc-directives` are up for grabs.

**Comment by gosubpl** [comment]
Ah, and `range-directives` are done, please someone with admin rights mark this down. See https://github.com/akka/akka/issues/20466 for details :)

**Comment by ktoso** [comment]
Some more addressed by  @jlprat in #557, thanks!

**Comment by fagossa** [comment]
sorry, but I've been really busy. Won't be able to work on this any time soon 😢 😢 😢 

misc-directives are available for grab

I'll try to advance on other issues starting next year

**Comment by gosubpl** [comment]
I believe this is all done now, and the ticket can be closed :+1:

**Comment by ktoso** [comment]
Awesome, thanks for the ping.

**Comment by gosubpl** [comment]
There is actually one item that was marked as done but is not. It is `rejectEmptyResponse`. There is a PR for it: #558 by @jlprat .
However, I would argue that it is not about providing Java DSL example but more about pinning down what is the required behaviour for the `Optional` during the marshaling process. There is even separate ticket for that: #559 .

**Comment by jlprat** [comment]
Yes, my PR was more about documenting the current behavior and providing an example showing what happens when using `rejectEmptyResponse`. Here I realized `Optional` is not rejecting when `rejectEmptyResponse` is provided

**Comment by ktoso** [comment]
Makes sense to close this one and we'll resolve 559 in the next steps, thanks guys :)
