### ISSUE TITLE
Need a better hook to implement access.log - timeouts, e.g. are handled outside of the user-provided Route/Flow.

### ISSUE THREAD

**Issue by scr-oath** [akka/akka-http#2181]
I spent a good amount of time trying to figure out why sometimes under load I was seeing drops - I blamed the Kubernetes Ingress because our logs were squelched up pretty high and my "access log" directive at the tippy top of the sealed route wasn't catching the timeouts cases which cleaved the connection.

It would be great if there could be some sort of catchall Sink (or Directive?) that could see but not modify the FINAL form of the request/response, if not also (configurably?) debug info like the stack of the call to complete (or the HttpResponse constructor), so that you didn't have to scratch your head about other layers of akka-http and find those pesky settings (idle-timeout in my case) that were outside the logic of the application.

**Comment by scr-oath** [comment]
It might be useful to know about what happened in the TCP layer too - perhaps a valid `HttpResponse` could be stuck on the wire and cleaved from the other side as well…

Ultimately some way to add more hooks to the Flow/BiFlow that's created internally by the bindAndHandle is what I'm looking for - a way to really know what's going on and debug as a user of the library without diving into the guts of it.

**Comment by jrudolph** [comment]
If it's about debugging then you can try `log-unencrypted-network-bytes` to see what's going on at a very low layer. 

If it's about things like monitoring we now also created #2216 which aims to add a hook which should cover all situations.

**Comment by jrudolph** [comment]
Closing this in favor of pursuing the idea in #2216.
