### ISSUE TITLE
Adding Merge Patch MediaType

### ISSUE THREAD

**Issue by Executioner1939** [akka/akka-http#2189]
Hi all, 

I would like to add the following MediaType to the project. We already have `application/json-patch+json`, I would like to include `application/merge-patch+json` as is defined in [RFC 7396](https://tools.ietf.org/html/rfc7396#section-4).

**Comment by jlprat** [comment]
Closed by https://github.com/akka/akka-http/commit/9686ef1f8235b06e75270eb300e30d67975c8baf
