### ISSUE TITLE
Http TLS Client does not disconnect when server fails to send back TLS Encrypted Alert even with EagerClose

### ISSUE THREAD

**Issue by sameerparekh** [akka/akka-http#2239]
We are using Akka HTTP to connect to a streaming server which streams forever, and upon receiving a certain amount of data, our client disconnects. When we connect to a streaming server which doesn't respond to the client's "Encrypted Alert" with another "Encrypted Alert", our client does not disconnect. However, when we connect to a streaming server which *does* respond to the client's "Encrypted Alert" with another "Encrypted Alert" then our client does disconnect the TCP connection.

`EagerClose` is enabled in `akka.stream.scaladsl.TLS#apply`

I'm attached screenshots showing the two "disconnect" scenarios, one which shows the successful disconnect which is preceeded by an Encrypted Alert response from the server, and the second shows the lack of disconnect when there is no Encrypted Alert response from the server.

(Note: I'm using akka-http 10.0.13 because apparently Uri("https://blah:443/") doesn't work in 10.1 -- it gives me a Uri with the port set to 0.. I'll file separate issue for that if one doesn't already exist)

![working](https://user-images.githubusercontent.com/1395413/46373308-e7954880-c64a-11e8-9725-6be99e4167d7.png)
![notworking](https://user-images.githubusercontent.com/1395413/46373309-e82ddf00-c64a-11e8-8794-4472aa45aa7f.png)

**Comment by sameerparekh** [comment]
I'm uploading the code I'm using to repro this to repro.zip. Note that in order to connect to the stream.twitter.com endpoint you will need a consumer key, consumer token, a secret, and a token, which you can get from the Twitter Dev Portal at https://developer.twitter.com/

The failing wireshark screenshot in the original comment is from connecting to a non-public endpoint. The behavior when connecting to stream.twitter.com is slightly different in that when connecting to api.twitter.com (as in the original comment) after the client sends the TLS Encrypted Alert, the server stops sending back data, whereas when connecting to stream.twitter.com the server continues to send back data. In both cases, however, the server does not send back a responding "Encrypted Alert" and the client doesn't send the TCP FIN. 

[wireshark.zip](https://github.com/akka/akka-http/files/2439874/wireshark.zip)

![stream twitter com-notworking](https://user-images.githubusercontent.com/1395413/46379668-c9384880-c65c-11e8-8437-ce01d92bc09b.png)
![finatraserver-working](https://user-images.githubusercontent.com/1395413/46379669-c9384880-c65c-11e8-9f7c-945b1891a011.png)

[repro.zip](https://github.com/akka/akka-http/files/2439868/repro.zip)

**Comment by jrudolph** [comment]
Hi @sameerparekh, thanks for the comprehensive report.

It seems `EagerClose` is not completely specified. In any case, it doesn't mean that the TLS layer closes the TCP connection forcibly.

Up to TLS 1.2 it seems that half-closed TLS connections were not recommended but this definitely [has changed with TLS 1.3](https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#closure-alerts) which removed a sentence that would mandate that peers answer `close_notify` swiftly discarding pending data.

That means that we probably won't change that aspect of the TLS layer.

That leaves us in a somewhat unfortunate state that it might be impossible to close a TLS connection regularly if the peer doesn't play along.

Have you tried failing the connection instead? How is your client trying to disconnect concretely? If nothing else helps, you could create a `ClientTransport` that contains a killswitch that you could use to forcibly close the TCP connection.

**Comment by sameerparekh** [comment]
Thanks @jrudolph for looking into this. I couldn't tell from the section you quoted in the spec.. I see that they are no longer *required* to immediately followup a close_notify with their own close_notify, but do you know if that behavior would be be forbidden due to truncation attacks?

My client is disconnecting simply by doing a take(n) on the stream. Once it gets `n` objects, the client should disconnect. I tried wiring up a KillSwitch to the graph (not to a ClientTransport, just the original graph itself), and that didn't have any impact.

**Comment by jrudolph** [comment]
> Thanks @jrudolph for looking into this. I couldn't tell from the section you quoted in the spec.. I see that they are no longer _required_ to immediately followup a close_notify with their own close_notify, but do you know if that behavior would be be forbidden due to truncation attacks?

Hmm, not sure what you mean? A truncation *attack* would be if a third-party could close the underlying connection and that would regularly close the TLS connection as well without the peer noticing. This is prevented by requiring `close_notify` frames previously and with TLS 1.3 in any case. The thing that was changed, was that a peer that receives a `close_notify` does not have to discard its outgoing buffer (and thus truncate the outgoing data stream) but flush the outgoing side first before sending the `close_notify`. At least, that's how I understand it.

> My client is disconnecting simply by doing a take(n) on the stream. Once it gets `n` objects, the client should disconnect.

I meant that you push a failure up the request side of the connection.

> I tried wiring up a KillSwitch to the graph (not to a ClientTransport, just the original graph itself), and that didn't have any impact.

Which graph? Have you tried `KillSwitch.abort` instead of `KillSwitch.shutdown`?

**Comment by sameerparekh** [comment]
Aha by pushing a failure you mean KillSwitch.abort rather than KillSwitch.shutdown? -- i believe I did try that but there were some other confounding factors at the time as I was experimenting in various ways, so it may not have properly tested it. I'll try that and see. Thanks for your help.

**Comment by jrudolph** [comment]
Old by now. If this is still an issue please reopen.
