### ISSUE TITLE
Implement HPACK - HTTP/2 header parser/cache

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#224]
We can base or take it on Twitter's or Netty's (by now it moved there I believe) efforts 

- https://github.com/akka/akka-http/issues/111
- https://github.com/twitter/netty-http2

Requirement for HTTP/2 https://github.com/akka/akka-http/issues/111

**Comment by jrudolph** [comment]
Twitter hpack implementation: https://github.com/twitter/hpack

**Comment by ktoso** [comment]
Basic version in place, closing ticket to be replaced by more specific ones
