### ISSUE TITLE
Can't set required grpc response header

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-http#2245]
Per the grpc wire format [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)., the response must include an `application/grpc` `Content-Type` header. But when setting this header using akka-gprc, it's rejected by the check [here](https://github.com/akka/akka-http/blob/master/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala#L120).

When I did a local build of akka-http to disable that check, the header was successfully delivered and the [android test client](https://grpc.io/docs/quickstart/android.html) that didn't work without it worked.

How should this be fixed to allow the header for grpc but not for other responses -- apply if IFF the content type isn't `application/grpc`? Or maybe there are other use cases too where the header should be allowed?

The related akka-grpc is [428](https://github.com/akka/akka-grpc/issues/428).

**Comment by raboof** [comment]
The `Content-Type` indeed cannot be set as a regular header, but instead is determined by the `contentType` on the `HttpEntity`. See also https://doc.akka.io/docs/akka-http/current/common/http-model.html#http-headers .

**Comment by ctoomey** [comment]
Thanks @raboof, due to a bug in my code I wasn't properly setting the `contentType` on the `HttpEntity`, once fixed it indeed picked it up properly from there and sent it in the response.
