### ISSUE TITLE
partial consumption of multipart Source does not close underlying connection

### ISSUE THREAD

**Issue by 941design** [akka/akka-http#2246]
**EDIT: Happens only under certain preconditions. See below.**

I am trying to partially consume a multipart http message. Consumption of the entire message works as intended, so does partial consumption if the response entity is read in strict mode and consumed partially thereafter.

However, [documentation](https://doc.akka.io/docs/akka-http/current/client-side/connection-level.html) states, using the `take` combinator would close the underlying connection. That does not seem to be the case here, unless I am missing something important.

Using `Http().singleRequest(..)` produces the same symptoms.

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.{HttpRequest, Multipart, Uri}
import akka.http.scaladsl.unmarshalling.Unmarshal
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Source

import scala.concurrent.ExecutionContext


implicit val sys = ActorSystem()
implicit val mat = ActorMaterializer()
implicit val ec = ExecutionContext.global

val uri = Uri("http://localhost/some_multipart_resource")
val req = HttpRequest(uri = uri)
val conn = Http().outgoingConnection(uri.authority.host.address(), uri.authority.port)

Source.single(req)
    .via(conn)
    .flatMapConcat(response =>
                       Source.fromFutureSource(Unmarshal(response.entity)
                                                   .to[Multipart.General]
                                                   .map(_.parts.flatMapConcat(part => Source.fromFuture(Unmarshal(part.entity).to[String])))))
    .take(1)
    .runForeach(println)
    .flatMap(_ => sys.terminate())
    .onComplete {
        case x =>
            println(x)
            System.exit(0)
    }
```

Might be related to https://github.com/akka/akka-http/issues/2244

B.R.
Markus

**Comment by 941design** [comment]
Apparently, the described behaviour is observable only under certain preconditions (host).
I will clarify, once I have more information.

**Comment by jrudolph** [comment]
Closing for now as we don't have enough information to reproduce. Please reopen or create a new ticket with more information about how to reproduce the issue.
