### ISSUE TITLE
Akka HTTP Java: not override abstract method yeOldeTestNames() in org.scalatest.Suite

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#225]
<a href="https://github.com/harmeetsingh0013"><img src="https://avatars.githubusercontent.com/u/5654656?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [harmeetsingh0013](https://github.com/harmeetsingh0013)**
_Friday Sep 09, 2016 at 19:09 GMT_
_Originally opened as https://github.com/akka/akka/issues/21433_

---

Following are the details for issue with akka http experimental testkit.
http://stackoverflow.com/questions/38864899/akka-http-java-not-override-abstract-method-yeoldetestnames-in-org-scalatest/38895886#38895886

**Comment by jrudolph** [comment]
Probably outdated, please reopen if still a problem.
