### ISSUE TITLE
java.lang.IllegalStateException: Cannot open connection when slot still has an open connection

### ISSUE THREAD

**Issue by chinatangchenhao** [akka/akka-http#2251]
[ERROR] [10/10/2018 18:53:22.563] [Pigeon-akka.actor.default-dispatcher-39] [Pigeon/Pool(shared->http://hook.k8s.bearychat.com:80)] [0 (Unconnected)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.
1947 - 2018-10-10T18:53:22.565Z -java.lang.IllegalStateException: Cannot open connection when slot still has an open connection
1948 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.openConnection(NewHostConnectionPool.scala:285)
1949 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.SlotState$Unconnected$.onNewRequest(SlotState.scala:156)
1950 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$dispatchRequest$1.apply(NewHostConnectionPool.scala:147)
1951 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$dispatchRequest$1.apply(NewHostConnectionPool.scala:147)
1952 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:175)
1953 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:239)
1954 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:248)
1955 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.dispatchRequest(NewHostConnectionPool.scala:147)
1956 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.dispatchRequest(NewHostConnectionPool.scala:114)
1957 - 2018-10-10T18:53:22.565Z -	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.onPush(NewHostConnectionPool.scala:81)
1958 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
1959 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
1960 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
1961 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
1962 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:44)
1963 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:77)
1964 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
1965 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
1966 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
1967 - 2018-10-10T18:53:22.565Z -	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
1968 - 2018-10-10T18:53:22.565Z -	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
1969 - 2018-10-10T18:53:22.565Z -	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
1970 - 2018-10-10T18:53:22.565Z -	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
1971 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
1972 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
1973 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
1974 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
1975 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
1976 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
1977 - 2018-10-10T18:53:22.565Z -	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by chinatangchenhao** [comment]
application.conf is :
akka.http {
  host-connection-pool {
    # 最大打开请求数
    max-open-requests = 1024
    max-connections =  128
  }
}

**Comment by jrudolph** [comment]
Hi @chinatangchenhao, are you on the latest version (currently 10.1.5)? A similar bug was fixed quite a while ago.

**Comment by jrudolph** [comment]
Hi @chinatangchenhao, thanks for that information. Can you clarify if your problem was solved? Or only partly, and you want to come back with more information, once it turns up again?

**Comment by chinatangchenhao** [comment]
The problem has been solved!

**Comment by raboof** [comment]
That is great to hear! Thank you!
