### ISSUE TITLE
Media Type for MS office files should be updated

### ISSUE THREAD

**Issue by TopSpoofer** [akka/akka-http#2264]
Maybe application/mspowerpoint is an older name.

[See MIME](https://www.iana.org/assignments/media-types/media-types.xhtml#application)

**Comment by jlprat** [comment]
Thanks for creating the issue @TopSpoofer 
Dicuss thread: https://discuss.lightbend.com/t/why-ppt-mediatype-is-application-mspowerpoint-but-not-application-vnd-ms-powerpoint/2512/2
