### ISSUE TITLE
No examples for Akka HTTP Custom Java unmarshaller

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2267]
The Scala docs has an example implementation of a custom marshaller, would be nice if the Java docs did as well.

**Comment by johanandren** [comment]
To clarify, it would be on this page of the docs: https://doc.akka.io/docs/akka-http/current/common/marshalling.html#custom-marshallers

**Comment by jlprat** [comment]
I guess this is just one small part of issue https://github.com/akka/akka-http/issues/1367
Shall we close this one in favour of the older one?

**Comment by johanandren** [comment]
Yeah, lets keep that older one. Missed it when looking.
