### ISSUE TITLE
Extracting Empty Params as None

### ISSUE THREAD

**Issue by sidhant92** [akka/akka-http#2268]
If using the parameters directive I am extracting a parameter as an Optional, but while calling the API I pass it blank it gets assigned Some("").  Is there any way to handle this and assign them None.

Example:
```
parameters(
  'name
  'test?
)
```

And If I call the API as:
`some_api?name=abc&test=`

This assigns test Some("") and not None. How do I handle this?

**Comment by jlprat** [comment]
We have a really similar issue already: https://github.com/akka/akka-http/issues/2171
However, from what I understand you'd like a different outcome.

I will close this one, @sidhant92 if you feel this is different from the one I linked, please feel free to come back and re-open it.
