### ISSUE TITLE
feature request: request.wireTap

### ISSUE THREAD

**Issue by dsilvasc** [akka/akka-http#2272]
`request.entity.dataBytes` has a wireTap method now, which is convenient for monitoring traffic and capturing it for replay later (in load tests, for example).

Would it make sense to add a wireTap method to the request as well so that wiretapping code in a server could create a wiretapped request?

**Comment by raboof** [comment]
What would the signature of such a method be? I'm not sure I can imagine one that would add a lot of value.

**Comment by dsilvasc** [comment]
I guess something like

```scala
def wireTap(request: HttpRequest)(f: ByteString => Unit): HttpRequest =
  request.copy(entity = request.entity.transformDataBytes(Flow.fromFunction { bytes =>
    f(bytes)
    bytes
  }))
```

**Comment by jrudolph** [comment]
Thanks for the suggestion, @dsilvasc. I see how it would be useful but it seems that feature is already supported via the slightly more verbose version you suggested. We'd like to keep HttpRequest/HttpResponse free from single purpose functions so we won't add this one right now.
