### ISSUE TITLE
Test with JDK 11

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2285]
In Akka, some issues were found with JDK 11 compatibility. akka-http should be tested with JDK 11 as well. We should start by running tests locally to get an idea about whether there are any bigger problems. When Akka has added more CI testing for JDK 11 it should be easy enough to setup a nightly for akka-http as well.

**Comment by lomigmegard** [comment]
Indeed there seems to be an issue while using Java 11 with Scala 2.12.8
https://github.com/lomigmegard/akka-http-cors/pull/41

**Comment by jrudolph** [comment]
Nightlies are running tests against adoptopenjdk 11.
