### ISSUE TITLE
Failed: GracefulTerminationSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2309]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.11.11/lastCompletedBuild/testReport/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_stop_accepting_new_connections/

Akka has changed the message of a TCP connection refused that this relied on

**Comment by raboof** [comment]
Should be fixed since #2312
