### ISSUE TITLE
encodeResponseWith(GZip) directive uses unnecessary high compression level

### ISSUE THREAD

**Issue by markvandertol** [akka/akka-http#2318]
I profiled the CPU usage on my application using Akka HTTP and I saw it spent a lot of CPU time on compressing responses using GZip. In my opinion that is a waste of CPU cycles if you compare it to the gains. Our server returns relatively large responses, thus the wrong compression level can make a big difference.

The code currently compresses with highest compression level (“Deflater.BEST_COMPRESSION” → 9). The CPU cost of the highest levels are much higher than the levels in the middle, but the compression gains aren’t that large. [An example benchmark](https://www.rootusers.com/gzip-vs-bzip2-vs-xz-performance-comparison/) run by somebody else shows this clearly.  Every level costs a lot more time. There are many benchmarks done and they all show a similar pattern.

For comparison with other HTTP servers: Nginx uses by default level 1 and Apache HTTP uses 6.

My idea would be to make the following two changes:
* Change the (default) compression level to 6 (out of 9) for GZip and Deflate. This is more balanced between compression and speed. This value is used most of the time as a default, even though it still favors compression over speed.
* Create a method withLevel on the GZip and the Deflate object to specify the level yourself. By putting the withLevel method on the object instead of the class, this change can be done in a binary compatible way. The code to use it would then look like: `val route = encodeResponseWith(Gzip.withLevel(1)) { complete("content") }`

If you like the direction of both changes, then I can make a pull request. Simplest change would be to just do the first change only.

**Comment by jrudolph** [comment]
Thanks, @markvandertol. Good observation, indeed, level 9 doesn't make sense. Both suggestion sound good and a PR would be much appreciated.

**Comment by jrudolph** [comment]
Btw. we might want to think about replacing the internal Gzip implementation by now with the one in akka-stream which already allows customizing the compression level. See also #211.
