### ISSUE TITLE
handleExceptions fails when using HttpApp

### ISSUE THREAD

**Issue by martoo6** [akka/akka-http#2325]
When using `HttpApp` handleExceptions(..) fails with: `java.lang.NullPointerException at akka.http.scaladsl.server.directives.ExecutionDirectives.handleException$1`
Adding `handleExceptions` makes fail any request actually.

```
import akka.http.scaladsl.model._
import akka.http.scaladsl.server.{ExceptionHandler, HttpApp, Route}


object WebServer extends HttpApp with App {
  override def main(args: Array[String]): Unit = {
    WebServer.startServer("localhost", 8080)
  }

    val exceptionHandler: ExceptionHandler = ExceptionHandler {
      case _ => complete(HttpResponse(StatusCodes.OK))
    }

  override def routes: Route =
    handleExceptions(exceptionHandler) {
      path("hello") {
        get {
          complete {
            ""
          }
        }
      }
    }
}
```

**Comment by martoo6** [comment]
@jlprat Indeed, splitting  the code into different objects (`WebServer` and `MainApp`, the latter calling the `WebServer`) solved it. Avoiding the use of `def main(args: Array[String])` also solved it.
Thanks!

**Comment by jlprat** [comment]
Great!
