### ISSUE TITLE
Backport a few fixes to 10.0.15

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2329]
It seems we need to do another release for Akka 10.0.x. This is a meta ticket to collect fixes that should/can be backported.

 * [x] TLS closing issue #1822 -> https://github.com/akka/akka-http/pull/2344
 * [x] Collision-resistant hashmaps -> https://github.com/akka/akka-http/pull/2343
 * [x] Dependency updates (at least Jackson databind) -> https://github.com/akka/akka-http/pull/2342
 * [x] Make sure to trigger release-10.0 nightlies on Jenkins for early validation

**Comment by raboof** [comment]
The test failures in the nightly's at first confused me (e.g. https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.0-against-akka-2.4-on-2.11/62/), until I realized these are http2 tests that have been marked as known/expected to be failing, and aren't intended to affect the build result.
