### ISSUE TITLE
Adding woff2 to MediaTypes

### ISSUE THREAD

**Issue by pme123** [akka/akka-http#2330]
Woff2 is not recognized as MediaType, because its entry is missing in MediaTypes.

In:
`akka.http.scaladsl.model.MediaTypes
`

Around Line 333 something like this should be added:

    val `application/font-woff2`  = abin("font-woff2", NotCompressible, "woff2")

**Comment by raboof** [comment]
Shouldn't that be `font/woff2`? (https://dev.w3.org/webfonts/WOFF2/spec/)

A PR adding it would be appreciated, but for the time being you can add it to your application as a custom media type as described in https://doc.akka.io/docs/akka-http/current/common/http-model.html#registering-custom-media-types. Does that work for you?

**Comment by pme123** [comment]
`font/woff2` I am not sure, I just found `application/font-woff2` and it solved my problem.

I use `akka-http` within `play` - Does this description work as well?

**Comment by raboof** [comment]
I'm not sure how this works in Play - that might be a good question for https://discuss.playframework.com?

**Comment by pme123** [comment]
ok, thanks for the support.
