### ISSUE TITLE
FAILED: HttpHeaderParserCRLFSpec The HttpHeaderParser (mode: CRLF) should not show bad performance characteristics when parameter names' hashCodes collide

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2340]
akka.http.impl.engine.parsing.HttpHeaderParserCRLFSpec.The HttpHeaderParser (mode: CRLF) should not show bad performance characteristics when parameter names' hashCodes collide

Similar to #2313?

https://jenkins.akka.io:8498/job/akka-http-nightly/324/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.parsing/HttpHeaderParserCRLFSpec/The_HttpHeaderParser__mode__CRLF__should_not_show_bad_performance_characteristics_when_parameter_names__hashCodes_collide/

```
Error Message

3 was not less than 2

Stacktrace

org.scalatest.exceptions.TestFailedException: 3 was not less than 2
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
	at akka.http.impl.engine.parsing.HttpHeaderParserSpec$$anon$30.<init>(HttpHeaderParserSpec.scala:310)
	at akka.http.impl.engine.parsing.HttpHeaderParserSpec.$anonfun$new$49(HttpHeaderParserSpec.scala:282)
```

**Comment by raboof** [comment]
Probably just too tight an expectation... Again at https://jenkins.akka.io:8498/job/akka-http-nightly/334/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/consoleText

**Comment by jrudolph** [comment]
Happened again:

https://jenkins.akka.io:8498/job/akka-http-nightly/363/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.impl.engine.parsing/HttpHeaderParserCRLFSpec/The_HttpHeaderParser__mode__CRLF__should_not_show_bad_performance_characteristics_when_parameter_names__hashCodes_collide/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/388/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.parsing/HttpHeaderParserCRLFSpec/The_HttpHeaderParser__mode__CRLF__should_not_show_bad_performance_characteristics_when_parameter_names__hashCodes_collide/
