### ISSUE TITLE
GracefulTerminationSpec: Expected exception akka.stream.StreamTcpException to be thrown, but akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1 was thrown

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2349]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3092/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/
```
org.scalatest.exceptions.TestFailedException: Expected exception akka.stream.StreamTcpException to be thrown, but akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1 was thrown
	at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:138)
	at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:312)
	at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:39)
	at akka.http.scaladsl.GracefulTerminationSpec.akka$http$scaladsl$GracefulTerminationSpec$$ensureConnectionIsClosed(GracefulTerminationSpec.scala:193)
	at akka.http.scaladsl.GracefulTerminationSpec$$anon$6.<init>(GracefulTerminationSpec.scala:137)
	at akka.http.scaladsl.GracefulTerminationSpec.$anonfun$new$10(GracefulTerminationSpec.scala:123)
```

**Comment by raboof** [comment]
These tests are testing that after graceful shutdown, requests are not handled.

The test currently expects a `StreamTcpException` from Akka Streams, but when this test failure occurs it gets the `IllegalStateException("Connection was shutdown.") with NoStackTrace` from `SlotState` that is thrown when the connection is completed when in 'busy' state instead. It's not obvious to me that that is wrong, but I'm not 100% sure. The comment for that exception is:

```
      // There's no good reason why the connection stream (i.e. the user-facing client Flow[HttpRequest, HttpResponse])
      // would complete during processing of a request.
      // One reason might be that failures on the TCP layer don't necessarily propagate through the stack as failures
      // because of the notorious cancel/failure propagation which can convert failures into completion.
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3208/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/382/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_provide_whenTerminated_future_that_completes_once_server_has_completed_termination__existing_connection__user_reply__terminate__no_reply_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3298/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_provide_whenTerminated_future_that_completes_once_server_has_completed_termination__existing_connection__user_reply__terminate__no_reply_/

**Comment by jrudolph** [comment]
>       // There's no good reason why the connection stream (i.e. the user-facing client Flow[HttpRequest, HttpResponse])
>       // would complete during processing of a request.
>       // One reason might be that failures on the TCP layer don't necessarily propagate through the stack as failures
>       // because of the notorious cancel/failure propagation which can convert failures into completion.

That comment says it all. We probably need an akka-stream solution for the cancellation problem to fix all these kinds of problems.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/417/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_provide_whenTerminated_future_that_completes_once_server_has_completed_termination__existing_connection__user_reply__terminate__no_reply_/

**Comment by kpritam** [comment]
We are also seeing lot of these issues in our jenkins build causing lot of build failures.
Have raised similar issue here: https://github.com/akka/akka-http/issues/2143

**Comment by johanandren** [comment]
FYI We are planning to get stream cancellation upstream signalling in for Akka 2.6 akka/akka#23908

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.12.8,jdk=AdoptOpenJDK%208/481/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/537/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/532/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/537/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3541/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3628/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_stop_accepting_new_connections/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3638/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/696/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/699/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_stop_accepting_new_connections/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%2011/710/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_provide_whenTerminated_future_that_completes_once_server_has_completed_termination__existing_connection__user_reply__terminate__no_reply_/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/724/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/754/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_provide_whenTerminated_future_that_completes_once_server_has_completed_termination__existing_connection__user_reply__terminate__no_reply_/
