### ISSUE TITLE
MarshallingDirectivesExamplesSpec.scala has a bad import

### ISSUE THREAD

**Issue by ionFreeman** [akka/akka-http#2380]
line 8 of 
        akka-http/docs/src/test/scala/docs/http/scaladsl/server/directives/MarshallingDirectivesExamplesSpec.scala
      should start 'akka', not 'docs'
https://github.com/akka/akka-http/blob/v10.1.7/docs/src/test/scala/docs/http/scaladsl/server/directives/MarshallingDirectivesExamplesSpec.scala

**Comment by jlprat** [comment]
Hi @ionFreeman you are right that if one would like to use this snippets in test code in a real project the right import should be
```
import docs.http.scaladsl.server.RoutingSpec
```
However, to speed up building times the test code under the `docs` sub-project is not really run, but just compiled. This is the reason to import this other version of `RoutingSpec` that doesn't run the tests.

**Comment by jrudolph** [comment]
Seems we can easily remove the `docs` variant to remove confusion a bit. See https://github.com/akka/akka-http/pull/2422.
