### ISSUE TITLE
akka-http testkit seems to run check block before all futures are complete

### ISSUE THREAD

**Issue by blast-hardcheese** [akka/akka-http#2381]
Akka version: v10.1.7
Akka stream version: v2.5.19
Scala Version:
- 2.12.3 👍
- 2.11.12 👎

Problem
===

A custom route that works around https://github.com/akka/akka-http/issues/358 by implementing a custom `exceptionHandler` for `EntityStreamSizeException` that get thrown when attempting to unmarshall `Multipart.FormData`.

When trying to write a test for an [unmarshaller for file uploads](https://github.com/twilio/guardrail/blob/master/modules/codegen/src/test/scala/core/issues/Issue127.scala#L47-L67), I discovered that the test always passes in Scala 2.12.3, but it always fails running in TravisCI in 2.11.12. It doesn't fail locally on my mac. I haven't figured out why.

I've got a branch here that can be used to test this out fairly easily: https://github.com/blast-hardcheese/guardrail/tree/akka-future-bug using
```
sbt '; runScalaExample ; sample/testOnly core.issues.Issue143'
```

Code
===

```scala
    val tempDest = File.createTempFile("guardrail.", ".dat")
    val route = buildRouteWithDest(tempDest)
    req ~> route ~> check {
      status should equal(StatusCodes.RequestEntityTooLarge)
      tempDest.exists() should equal(false) // This always succeeds in Scala 2.12 and always fails in 2.11
    }
    tempDest.exists() should equal(false) // This always succeeds in Scala 2.12 and fails in 2.11, but I haven't tested this nearly as many times as the prior one
    scala.concurrent.blocking {
      Thread.sleep(2000)
      tempDest.exists() should equal(false)  // This always succeeds
    }
```

Workaround
===

This always works:
```scala
    val tempDest = File.createTempFile("guardrail.", ".dat")
    val route = buildRouteWithDest(tempDest)
    val response = Route.asyncHandler(route).apply(req).futureValue
    response.status should equal(StatusCodes.RequestEntityTooLarge)
    tempDest.exists() should equal(false)
```

**Comment by johanandren** [comment]
I couldn't see in the linked class what corresponds to buildRouteWithDest, but if that does the delete that is not in the end transformed to the response, it can happen at any time before or after the testkit sees the response. If this is the problem then the fact that it always fails/completes with with a specific Scala version is a (repeatable) coincidence. To be sure you'd either have to make sure the result _is_ a result of the future, or live with that it is not a sequence of events and just give it some time, you can do this for example with`awaitAssert` from the Akka actor testkit.

**Comment by jrudolph** [comment]
Hi @blast-hardcheese, is that still an issue or has it been resolved or been superseded by now?

**Comment by blast-hardcheese** [comment]
@jrudolph I don't have a way to test this other than to publish to TravisCI. Are you just following up, or do you have some reason to believe this bug has been fixed?

**Comment by raboof** [comment]
> Are you just following up, or do you have some reason to believe this bug has been fixed

Likely just following up.

Unfortunately I couldn't run your reproducer because of `sbt.librarymanagement.ResolveException: unresolved dependency: com.twilio#guardrail_2.11;69fb6db00b73896ddd86a4e763d96daa4fd0242e: not found`. A minimal reproducer might be helpful.

I noticed you are not checking the return value of `dest.delete()`. It might be good to verify it returns 'true'? (if it returns 'false', perhaps there is some race condition causing it to be still in use when you try to delete it?)

**Comment by blast-hardcheese** [comment]
@raboof Yeah -- the challenge is that I find this to be platform dependent, as I indicated in the original comment. I tried the branch I linked above on my mac, and it still passes with flying colors (unsure why it was unable to build on your machine, unfortunately)

My assumptions around the nature of this bug are as follows:

- This doesn't occur outside of the testkit (Thank goodness! 🙌)
- The file is deleted _eventually_
- The testkit itself attempts to expose a very natural and minimal interface for very complex machinery

my thought is that something as simple as `Future.successful` vs `FastFuture.successful` is creating a race condition in the testkit that only impacts a very particular code path (namely, whichever version of the JVM travis was using at that time, the platform I was on, and 2.11.12).

Due to the fact that I foolishly neglected to keep track of the exact version of the JVM this was running on, I suspect this may be dead in the water. As I've dropped focus on 2.11, the original bug was fixed (413s being misreported as 500s), and Travis has aggressively started purging older JVMs, I suspect this may become harder and harder to narrow down.

If you want to close it, I won't object, I just wish there was a more decisive resolution to this issue.

**Comment by raboof** [comment]
> If you want to close it, I won't object

Let's do that for now - though if anyone can come up with a minimal reproducer I'd be happy to have a look

> I just wish there was a more decisive resolution to this issue.

Agreed, though I suspect it's likely something subtle, such as `File#exists()` returning stale values in some situations.
