### ISSUE TITLE
WS().withHeaders removes a required InternalCustomHeader

### ISSUE THREAD

**Issue by joechip504** [akka/akka-http#2400]
(I am not sure if this is a bug or feature request; my apologies if it is categorized incorrectly)

It seems like the akka-http testkit requires an [InternalCustomHeader](https://github.com/akka/akka-http/blob/f57ec755a9107a8c1c25412ecde3149a91261e7c/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/WSTestRequestBuilding.scala#L18) to interpret a request in test as a websocket request.

The general case works great
```scala
WS("/my/websocket/endpoint") // yields a HttpRequest with this InternalCustomHeader
```

When attempting to add an additional custom header to a test request, this InternalCustomHeader disappears. Because of this, the testkit interprets the request as a GET request, and rejects because the route expects a websocket upgrade.

```scala
WS("/my/websocket/endpoint").withHeaders(h1, h2) // yields HttpRequest with only user provided headers h1 and h2 (internal header is removed)
```

If you guys decide this use case should be supported, perhaps the behavior of `WS().withHeaders()`
 could be adjusted to always include this internal header? Or maybe even add something new like `WS().withAdditionalHeaders()`?

Reproducer below

```scala
package ws.reproduce

import akka.http.scaladsl.model.headers.RawHeader
import akka.http.scaladsl.model.ws.Message
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.Route
import akka.http.scaladsl.testkit.{ScalatestRouteTest, WSProbe}
import akka.stream.scaladsl.Flow
import org.scalatest.{Matchers, WordSpec}

class WSHeaderTest extends WordSpec with Matchers with ScalatestRouteTest {

  // For example's sake, this route requires a custom header
  // (Let's assume this websocket endpoint is not accessed via a web browser)
  private val customHeaderRoute: Route = path("ws") {
    headerValueByName("custom-header") { _ =>
      handleWebSocketMessages(Flow[Message])
    }
  }
  private val customHeader = RawHeader("custom-header", "hello")

  "A HTTP Request constructed using WS()" should {
    "be missing an InternalCustomHeader" in {
      val probe = WSProbe()

      // This is rejected with 'ExpectedWebSocketRequestRejection'
      // A request with headers {'Connection': 'Upgrade, 'Upgrade': 'websocket'} manually added is similarly rejected
      //val request = WS("/ws", probe.flow).withHeaders(customHeader)

      // Only with this InternalCustomHeader will the test pass
      // Perhaps it should be added to all WS requests in test, even when .withHeaders() is used?
      val internalCustomHeader = WS("ws", probe.flow).headers.head
      val request = WS("/ws", probe.flow).withHeaders(customHeader, internalCustomHeader)

      request ~> customHeaderRoute ~> check {
        isWebSocketUpgrade shouldEqual true
      }
    }
  }
}
```

**Comment by raboof** [comment]
`withHeaders` is intended to replace the headers. You seem to want to add headers. I think `WS("/my/websocket/endpoint").addHeader(h1).addHeader(h2)` would be the way to do that. I guess we could save some keystrokes by allowing `.addHeaders(h1, h2)`, but I'm not sure it is worth it.

**Comment by joechip504** [comment]
`.addHeader()` is exactly what I was looking for, thanks!
