### ISSUE TITLE
The WebSocket example doesn't work because the “WebSocket settings” are not found

### ISSUE THREAD

**Issue by Storm-Sergey** [akka/akka-http#2401]
If I take the WebSocket example from 
akka-http/docs/src/test/java/docs/http/javadsl/server/WebSocketCoreExample.java
and try to run it then “WebSocket settings” will not be found.

**Comment by raboof** [comment]
Could you paste the exact error message? Do you have `import akka.http.javadsl.settings.WebSocketSettings`?

(this might be more suitable at https://discuss.akka.io - we're compiling this file as part of our testsuite so we're quite confident is has no compile errors itself)

**Comment by TimMoore** [comment]
Related thread https://discuss.lightbend.com/t/i-cant-import-the-websocketsettings-package-in-the-websocket-example-from-the-documentation/3223

**Comment by raboof** [comment]
Ah, answered on discuss

**Comment by Storm-Sergey** [comment]
> Could you paste the exact error message? Do you have `import akka.http.javadsl.settings.WebSocketSettings`?

I'm stupid. I tried to build a project with gradle but there was a maven akka-http-seed-java.iml file inside. After deleting example is perfectly worked.
