### ISSUE TITLE
Scala 2.14 support

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2408]
Once preliminary artifacts for Scala 2.14 are out we would like to try and support it. This would mean:

* [ ] Update the `@pre213` and `@since213` macro's to understand 2.14
* [ ] Add any missing scala-version-specific implementations under `*/src/main/scala-2.14`
* ...?

**Comment by ennru** [comment]
There won't be a Scala 2.14. But Akka HTTP publishes Scala 3 artifacts now.
