### ISSUE TITLE
CachingSettings class hierarchy doesn't follow the usual public/impl classes split

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2415]
For consistency that should be cleaned up. See any of the other settings classes in other modules for a guideline how to do it.

**Comment by heraklos** [comment]
Hello @jrudolph.
I would like to work on this issue if it is still concerned?

I'm going to reference `akka.http.scaladsl.settings.RoutingSettings` and `akka.http.impl.settings` as a guideline if I can take this issue.

**Comment by raboof** [comment]
Go for it! Making sure binary compatibility is not broken is something to take into account here.

**Comment by heraklos** [comment]
I created [#2510](https://github.com/akka/akka-http/pull/2510) for this issue 👍
