### ISSUE TITLE
LogRequest not respecting LogLevel in Java

### ISSUE THREAD

**Issue by dleacock** [akka/akka-http#2418]
Using the LogRequest method with InfoLevel() is sending logs at the Debug level.  Inspecting the code where LogRequest is it appears that nothing is done with the LogLevel. 

DebuggingDirectives.scala in akka/http/javadsl shows this. Nothing is being done with the level variable.

 ```
 def logResult(marker: String, level: LogLevel, inner: Supplier[Route]): Route = RouteAdapter {
    D.logResult(marker) { inner.get.delegate }
  }
```

The only way to make the LogRequest logs show is setting the logLevel to DEBUG in the application.conf file.  That's how I know I'm using it correctly because it shows the message, just at the wrong level.

**Comment by jrudolph** [comment]
Indeed, that seems to be an oversight. Do you want to open a PR to fix that? Should be as simple as using `D.logResult(marker, level) ...` instead.
