### ISSUE TITLE
akka.http.impl.util.StreamUtils#sliceBytesTransformer skip valid data when process more that Int.MaxValue bytes

### ISSUE THREAD

**Issue by sisso** [akka/akka-http#2440]
In the following code

```
   def sliceBytesTransformer(start: Long, length: Long): Flow[ByteString, ByteString, NotUsed] = {
    val transformer = new SimpleLinearGraphStage[ByteString] {
      override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) with InHandler with OutHandler {
        override def onPull() = pull(in)

        var toSkip = start
        var remaining = length

        override def onPush(): Unit = {
          val element = grab(in)
          if (toSkip >= element.length)
            pull(in)
          else {
            val data = element.drop(toSkip.toInt).take(math.min(remaining, Int.MaxValue).toInt)
            remaining -= data.size
            push(out, data)
            if (remaining <= 0) completeStage()
          }

          toSkip -= element.length
        }

        setHandlers(in, out, this)
      }
    }
    Flow[ByteString].via(transformer).named("sliceBytes")
  }
```

For each element received, toSkip is decremented
`toSkip -= element.length`

When is pushing data, first it convert toSkip to int, negative values a ignored by drop
`val data = element.drop(toSkip.toInt).take(math.min(remaining, Int.MaxValue).toInt)`

In the situation that toSkip becomes smaller that Int.MinValue, toSkip.toInt will overflow to a positive value, causing `element.drop` to skip valid data.

A simple solution is just only decrement toSkip if is still bigger that 0L

**Comment by jrudolph** [comment]
Thanks, good catch, @sisso. Your reasoning seems to be almost correct: `toSkip` is a `Long` though, so that it needs to be going below `Long.MinValue`, which seems much less likely. Could you provide a PR with the fix you suggested?

**Comment by sisso** [comment]
@jrudolph  yes, toSkip is a long and it can easly contains `Int.MinValue`, but the overflows happens when it is converted to a int to drop the bytes. `element.drop(toSkip.toInt)`. So we are talking about Int.MinValue, not Long.MinValue.

I can provide a PR in a week if nobody does.

**Comment by jrudolph** [comment]
> @jrudolph yes, toSkip is a long and it can easly contains `Int.MinValue`, but the overflows happens when it is converted to a int to drop the bytes. `element.drop(toSkip.toInt)`. So we are talking about Int.MinValue, not Long.MinValue.

Ah, I see, thanks for correcting me.

**Comment by sisso** [comment]
Btw, let's give credit how deserve, the bug was found by @kstokoz, I just fix it.
