### ISSUE TITLE
Provide full set of HTTP/2 API entrypoints (corresponding to HTTP ones)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#246]
Part of #244 

With this ticket entry-points for an HTTP/2 server should be created similar to `akka.http.scaladsl.Http.bind` etc, so that we can start writing tests against the implementation.

These entrypoint should be added, mimicking the existing Http1 ones:
- [x] bindAndHandleAsync
- [ ] bindAndHandleSync
- [ ] bind
- [ ] bindAndHandle

When HTTP/2 support is considered stable (or even before), the HTTP/2 implementation might be merged into akka-http-core providing HTTP/2 automatically for HTTPS servers if enabled with a flag.

**Comment by ktoso** [comment]
I played around with this for an hour on friday, but nothing useful so far. Backed out from it for now at least.

**Comment by jrudolph** [comment]
For now we don't think that we will support more than `bindAndHandleAsync` / `newServerAt.bind`.

If more low-level access is needed we can revisit this ticket.
