### ISSUE TITLE
Memory leak with Jetty ALPN support

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2462]
With Jetty ALPN, you need to put your ALPN handler inside a global map keyed by the SSLEngine. After our handler is called we remove it from that map again:

https://github.com/akka/akka-http/blob/392742107e3ba98dbeb0d9fca3f9c1a36ef85ebd/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala#L64-L67

When the ALPN handler is never called, though, e.g. because the TLS handshake fails or the connection is closed before the ALPN handshake takes place, we leak the SSLEngine and our handler by keeping it in the global map. Therefore, we somehow have to clean up the ALPN map when a connection is torn down.

Not sure, how we would do it, though, because it's hard to get a handle to the `SSLEngine` after a connection has been closed. Or maybe run a regular clean up task, that runs over all entries and removes the ones where the SSLEngine is already finished?

**Comment by BrijJhala** [comment]
Hi @jrudolph . thank you for pointing this fix. is it same issue as shared below in screen shot ? We are using hive cortex https://github.com/TheHive-Project/Cortex and getting OOM and heap analysis points same class having leak
![image](https://user-images.githubusercontent.com/4096804/95140525-1ca66b00-073d-11eb-938b-0d2bf938a2d5.png)

![image](https://user-images.githubusercontent.com/4096804/95140408-d05b2b00-073c-11eb-83c7-c2ec36697a19.png)
![image](https://user-images.githubusercontent.com/4096804/95140420-dbae5680-073c-11eb-8071-256842f128bb.png)

**Comment by jrudolph** [comment]
Yes, seems similar.
