### ISSUE TITLE
Support HTTP2 from bindAndHandle

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2463]
Currently HTTP2 is only supported for "bindAndHandleAsync", it would be nice to also support it for "bindAndHandle"

**Comment by heraklos** [comment]
Hello @raboof .
Can I work on this issue?

I plan to Implement HTTP2-supporting  "bindAndHandle" and let the function be called from "bindAndHandle" in HttpExt according to passed argument.

**Comment by raboof** [comment]
That sounds great! Balancing readability and performance might be challenging here, I'm looking forward to see what you will come up with!

**Comment by heraklos** [comment]
I've got stuck in how to implement this... 
Please anyone interested in this issue take over it.
Sorry for holding this issue so long 🙇

**Comment by jrudolph** [comment]
Yeah, no worries, let us know if you want to continue at some point and need some pointers.

**Comment by jrudolph** [comment]
The functionality should be simple to add by doing a bit of refactoring in `Http2`. In the `bindAndHandle` API, users will have to propagate the stream id header manually. We should probably that to an attribute before (right now it's internal anyway). If we merge the API idea from the HTTP/2 client PR, we could provide some API in HttpRequest or HttpResponse to make it easier to propagate attributes that are marked as such.

**Comment by raboof** [comment]
This is superseded by the newServerAt API's
