### ISSUE TITLE
Remove/rename strange file and directory with umlaut accents

### ISSUE THREAD

**Issue by LogicalTime** [akka/akka-http#2474]
There is a file and a directory with that gave me errors today when I was trying to build the documentation on centos7. Should they be removed/renamed?
https://github.com/akka/akka-http/blob/master/akka-http-tests/lib/i%20have%20sp%C3%A4ces.jar
https://github.com/akka/akka-http/tree/master/akka-http-tests/src/test/resources/s%C3%BCbdir

**Comment by johanandren** [comment]
They are there specifically to test being able to read uncommon names.

**Comment by raboof** [comment]
Could you share the error you got? would be interesting to get to the bottom of that.

**Comment by LogicalTime** [comment]
java.nio.file.InvalidPathException: malformed input or input contains unmappable characters
sun.nio.fs.UnixPatch.encode(....

**Comment by raboof** [comment]
Could you also share the rest of that stack trace? :smile:

Do you get it immediately when starting sbt, or when running a command? Which command?

Exactly what JVM version are you using?

**Comment by LogicalTime** [comment]
Openjdk. Intellij idea and git we're behaving strange with those filenames as well. I tried to delete the files and then stash that change and it wouldn't stash. Just strange stuff. Anyways, the files were intentionally strange so I'm happy to close this ticket. I have a fresh centos install on my laptop and if I see this issue again I'll bring it up and we can go deeper.

**Comment by jlprat** [comment]
Just a wild guess, @logicaltime what is the locale on your machine?
