### ISSUE TITLE
Setup HTTP/2 conformancy test

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#251]
Part of #244 

See tools recommended here: https://blog.cloudflare.com/tools-for-debugging-testing-and-using-http-2/

**Comment by jrudolph** [comment]
@ktoso in #260:

> There seems to be a TCK-like tool: https://github.com/http2/http2-test/

**Comment by schmitch** [comment]
There is also: https://github.com/summerwind/h2spec (might not be 100% correct from the netty thread: https://github.com/netty/netty/issues/5761)
