### ISSUE TITLE
Failed: ClientServerSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2514]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0-M5,jdk=AdoptOpenJDK%208/468/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_Remote_Address_header_should_be_added_when_using_bind_API/

**Comment by ennru** [comment]
The error log of this failure is not available anymore. Thus this report is too unspecific.

**Comment by jrudolph** [comment]
The job was renamed but it seems this build was just deleted a few days ago, since build 477 is still there: https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/477/.

I updated the configuration to keep failed builds forever. Successful builds are kept for a year as before.

**Comment by jrudolph** [comment]
(we should also include a stack trace at least to make the reports here more useful)
