### ISSUE TITLE
Prefer concat in samples

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2537]
Since `~` can be error prone - easy to miss out that a part of the routing tree was not included I thought we decided a long while ago to favor `concat` in the routing docs. 

A few examples where `~` is still used:
https://doc.akka.io/docs/akka-http/current/routing-dsl/index.html#longer-example
second snippet here https://doc.akka.io/docs/akka-http/current/routing-dsl/overview.html#routing-dsl-overview
https://doc.akka.io/docs/akka-http/current/routing-dsl/routes.html#the-routing-tree
a bunch of small snippets
https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/index.html
https://doc.akka.io/docs/akka-http/current/routing-dsl/rejections.html#rejection-cancellation

Did I remember wrong or did we never decide such a thing?

**Comment by jlprat** [comment]
I think we discussed it some time ago and agreed that we should encourage using `concat` instead of `~`. I don't recall if it was just a gitter discussion or as part of a PR

**Comment by jlprat** [comment]
I will try to find some time to take this one :)

**Comment by jrudolph** [comment]
Thanks @johanandren and @jlprat. I agree we decided to do that.

**Comment by jlprat** [comment]
Closed by https://github.com/akka/akka-http/commit/65bdd3eb00ca04497cb6199d494f5fc9b8afeae3
