### ISSUE TITLE
Remove the ALPN switch for a secure HTTP/2 Always server

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2555]
When selecting `useHttp2 = Always` for a HTTPS binding, we should not go through the ALPN switch, and only allow h2 on that port.

**Comment by raboof** [comment]
See https://github.com/akka/akka-http/pull/2543#discussion_r290701814 for discussion

**Comment by jrudolph** [comment]
I'd also suggest to consider the opposite for simplicity: to remove `Always` (which means we can also remove `UseHttp2`) and accept that there's a slight performance penalty when enabling HTTP/2. The reasoning would be that `Always` servers should be really rare in practice so it wouldn't make sense to optimize for them. Or am I missing an important use case that would also require ultimate performance?

Instead, I'd rather spent time on thinking about how to remove the performance penalty for the switch (which would mean some dynamic rewiring of stages in the GraphInterpreter, might be hard but surely fun :) ).

**Comment by viktorklang** [comment]
@jrudolph Great idea. If we can get rid of UseHttp2 AND have an opportunity to improve Akka Streams in general—that is a good option IMO.

**Comment by jrudolph** [comment]
Closing, we basically removed the `UseHttp2` setting and negotiation is now always on if http2 support is enabled.
