### ISSUE TITLE
SingleRequest behavior when materializer is shutdown during request

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka-http#2571]
We are using an ActorMaterializer tied to a specific ActorContext when making a SingleRequest. When shutting down the actor before the request completes, we see the following behavior:

1. The materializer is shutdown.
2. The streaming part of Akka Http fails with `Trying to materialize stream after materializer has been shutdown`.
3. The Akka Http request now hangs because we did not discard the entity bytes. We see the following warning: `Response entity was not subscribed after 1 second. Make sure to read the response entity body or call discardBytes() on it.`
4. If we cancel a lot of requests at the same time, the 1 second delay can lead to large delays in the system before new requests can go through.

We have been following the discussion around discardEntityBytes, and take care in our code to make sure it happens whatever response we get from the server. But in this specific case of a shutdown of the materializer, is it possible for Akka HTTP to handle the cleanup?

**Comment by jrudolph** [comment]
Thanks @lukas-phaf for the report (and sorry for the delay).

We should make sure that requests are failed when the materializer that runs the pool shuts down. But afaik that should happen. 

> * The Akka Http request now hangs because we did not discard the entity bytes. We see the following warning: `Response entity was not subscribed after 1 second. Make sure to read the response entity body or call discardBytes() on it.`
> 
> * If we cancel a lot of requests at the same time, the 1 second delay can lead to large delays in the system before new requests can go through.

I don't understand that part. If you close down materializer you cannot expect to have any more requests handled by that materializer. It's somewhat weird that `Response entity was not subscribed after 1 second. Make sure to read the response entity body or call discardBytes() on it.` is still shown.

Which part of the pipeline is run with the custom materializer?

Can you show how you run the requests and how the custom materializer comes into play?

(The materializer from ActorContext seems somewhat of a niche feature so we might restrict or remove it in the future. It would be recommended to move away from it if you can.)

**Comment by lukas-phaf** [comment]
Hello @jrudolph, thanks for getting back on this.

If I remember correctly, we had the following setup:
We have two parents, parent1 and parent2. Each has an ActorMaterializer created from its ActorContext, using:
`val materializer = ActorMaterializer()`

Now each parents has a bunch of children, which use this materializer (which is passed in on creation) to do a SingleRequest, all to the same server/endpoint. This works fine.

We now stop the parent1 actor. This stops the materializer, and breaks all SingleRequest in progress by its children, as expected. But they are not immediately removed, instead giving the `Response entity was not subscribed after 1 second. Make sure to read the response entity body or call discardBytes() on it.` warning. This keeps the connections occupied to the server (1s per request) until they timeout, so children of parent2 (which use a different materializer) can not proceed, because of the shared connection pool. Especially when parent1 has a lot of child actors, this can take a significant time delay.

As a workaround, we are now using an ActorMaterializer created in an actor that "never" gets stopped, so all requests under parent1 run to completion (and then the result is ignored).

It is not clear to me why you are referring to a custom materializer, we create if from an actor using:
`val materializer = ActorMaterializer()`
If an actor system is not in scope, I think this is equivalent to:
`val materializer = ActorMaterializer()(context)`

We prefer this over creating it based on the actor system
`val materializer = ActorMaterializer()(context.system)`,
as this avoids leaking the materializer when the actor is restarted.

Do I understand correctly that you recommend not to create the materializer based on the actor context, but to always use the actor system instead? Should I use the Akka actor system that is running my other actors, or create a new actor system for the materializer?

**Comment by jrudolph** [comment]
> because of the shared connection pool

I would have thought, using different materializers would mean different pools. That's a bit surprising and might need some investigation.

> Do I understand correctly that you recommend not to create the materializer based on the actor context, but to always use the actor system instead? Should I use the Akka actor system that is running my other actors, or create a new actor system for the materializer?

The usual recommendation is to use a single materializer that is created at the start of the program and passed around.

**Comment by jrudolph** [comment]
In most cases, we have already deprecated the possibilities to specify custom materializers. That's in line with the Akka 2.6 strategy of deemphasizing Materializers.

So far, we haven't seen very good reasons to use custom materializers, so if you still do, please consider alternative solutions.
