### ISSUE TITLE
[Docs] Add example on how to integrate Akka HTTP with Akka Typed

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#2584]
Currently we have examples that showcase the integration of Akka HTTP with untyped actors. We should offer a new section (probably the same code snipped) that showcases how to use Akka Typed from Akka HTTP.
For example, add a new section here using Akka Typed: https://doc.akka.io/docs/akka-http/current/introduction.html#streaming

**Comment by patriknw** [comment]
@jlprat This is important, would be great if you can help. Has been asked for several times. @chbatey started an example here: https://github.com/chbatey/akka-http-typed
Would be good with something in the core docs too. Don't know if it's trouble with the dependency (there is no akka-actor-typed for Scala 2.11).

**Comment by jlprat** [comment]
I guess it will fail to compile for 2.11, so I guess we might need to do some build magic for the cross Scala version builds.

**Comment by raboof** [comment]
Perhaps as a quick first step we should just turn https://github.com/chbatey/akka-http-typed/blob/master/src/main/scala/info/batey/QuickstartServer.scala#L16 into a regular non-compiled code section (also adding a Java variant)? (and then perhaps postpone moving it to the compiled docs until 10.2.0, #2589)

**Comment by jlprat** [comment]
In fact, I forgot to create the WIP PR, but a month ago I took a stab: https://github.com/akka/akka-http/pull/2650

**Comment by jrudolph** [comment]
Scala example added in #2650. Adding a Java example is tracked in #2664.
