### ISSUE TITLE
Make sure outStreams stream elements cannot be reinstantiated e.g. when PRIORITY frame for already closed stream is received

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2587]
Follow up to #2551.

Aside from `updatePriority` all other calls for `streamFor` could be checked to reproduce/verify this issue if they might resurrect an already closed OutStream.

The easiest way to fix it, is to check the incoming state of a stream before creating a new one in `Http2Multiplexer.streamFor`.

**Comment by johanandren** [comment]
I may have misunderstood this, but if prioritizer would re-prioritize a closed stream id, in `streamFor` we have a check in place when there is no state stored for the stream id: `if (streamId <= largestIncomingStreamId) Closed ` so a stream that was already closed will never resurrect anything as far as I can see.

**Comment by johanandren** [comment]
I discussed this with the team a bit and it seems it was perhaps more of a risk in an earlier design. I think we can close this one then.
