### ISSUE TITLE
feature request: HttpEntity.withDataBytes

### ISSUE THREAD

**Issue by dsilvasc** [akka/akka-http#2603]
The `HttpEntity` trait has a `dataBytes` property -- can it also have a `withDataBytes` method to replace the `Source[ByteString, Any]`?

The stream passed into a response can fail.  When it does, akka-http responds with status 200, sends the header, maybe sends some of the bytes from the stream, then closes the connection without any explanation.  The client just gets a connection reset, and the server logs don't say anything.  This kind of connection reset is difficult to debug.

I'd like to wrap the stream in my server's responses with some logging:

```scala
response.mapEntity(e => e.withDataBytes(e.dataBytes.recover {
  case NonFatal(e) =>
    logger.error("response stream failed:", e)
    throw e
}))
```

**Comment by dsilvasc** [comment]
Related to https://github.com/akka/akka-http/issues/894 and https://github.com/akka/akka-http/issues/848

**Comment by raboof** [comment]
Would [transformDataBytes](https://doc.akka.io/api/akka-http/current/akka/http/scaladsl/model/HttpEntity.html#transformDataBytes(transformer:akka.stream.scaladsl.Flow[akka.util.ByteString,akka.util.ByteString,Any]):akka.http.scaladsl.model.HttpEntity) work for you here?

**Comment by dsilvasc** [comment]
Hmm, yes, this seems to work:

```scala
response.mapEntity(_.transformDataBytes(Flow.fromFunction((x: ByteString) => x).recover {
  case e =>
    logger.error("response stream failed: ", e)
    throw e
}))
```

But it seems odd to recover from errors in the transformation flow instead of errors in the stream.

**Comment by dsilvasc** [comment]
Unfortunate consequence: `ResponseEntity.transformDataBytes` turns a strict or default http entity into a chunked one.

`UniversalEntity` has a transformDataBytes method that takes a content length and doesn't turn strict entities into chunked ones, but `mapEntity` takes a `ResponseEntity => ResponseEntity` instead of `UniversalEntity => UniversalEntity`.

Matching on the different entity cases preserves it though:

```scala
response.entity match {
  case HttpEntity.Strict(_, _) => response
  case HttpEntity.Chunked(contentType, chunks) =>
    response.withEntity(HttpEntity.Chunked(contentType, logStreamFailure(requestContext.requestID, chunks)))
  case HttpEntity.CloseDelimited(contentType, data) =>
    response.withEntity(HttpEntity.CloseDelimited(contentType, logStreamFailure(requestContext.requestID, data)))
  case HttpEntity.Default(contentType, contentLength, data) =>
    response.withEntity(HttpEntity.Default(contentType, contentLength, logStreamFailure(requestContext.requestID, data)))
}

private def logStreamFailure[T, U](requestID: String, stream: Source[T, U]) =
  stream.recover {
    case e =>
      // need to add the request ID by hand because this executes in the server's EC without the request's slf4j MDC
      logger.error(s"response body stream failed for request $requestID: ", e)
      throw e
  }
```

**Comment by raboof** [comment]
Well, for streaming requests the transformation is just appended to the data stream, so thinking of it that way perhaps makes it less odd?

> `Flow.fromFunction((x: ByteString) => x).recover`

Perhaps `Flow[ByteString].recover` would work here

> UniversalEntity has a transformDataBytes method that takes a content length and doesn't turn strict entities into chunked ones, but mapEntity takes a ResponseEntity => ResponseEntity instead of UniversalEntity => UniversalEntity

Interesting, it might make sense to introduce that for more types indeed (though that might need some twiddling to make it binary compatible)

> Matching on the different entity cases preserves it though

Yes that seems like a reasonable approach.

**Comment by jrudolph** [comment]
Seemed simple enough: #2621.

**Comment by jrudolph** [comment]
I just moved that version of `transformDataBytes` from `UniversalEntity` to `HttpEntity`, it will still return a `UniversalEntity` so you should be to use it with `mapEntity`.

**Comment by jrudolph** [comment]
This particular feature has been merged with #2621.

I've also a PR pending for fixing #848 and #894 in #2627.

**Comment by dsilvasc** [comment]
Thank you @jrudolph.  Are there any potential issues with a Strict or CloseDelimited entity becoming a Default one after the call to `transformDataBytes(length, transformer)`?

**Comment by jrudolph** [comment]
> Are there any potential issues with a Strict or CloseDelimited entity becoming a Default one after the call to `transformDataBytes(length, transformer)`?

I would not think so, `Strict` and `Default` have exactly the same rendering on the wire. For `CloseDelimited` it's unlikely that you would know about the content length up front in the first place.

**Comment by dsilvasc** [comment]
Thank you 👍
