### ISSUE TITLE
ConnectionContext.https now (10.1.9) is deprecated, but in docs it is still only one described

### ISSUE THREAD

**Issue by abdolence** [akka/akka-http#2605]
As you can see at https://doc.akka.io/docs/akka-http/current/server-side/server-https-support.html the only one available official example shows how to use the deprecated version of ConnectionContext.https.

Probably the docs should be updated or was it somehow wrongly deprecated?

**Comment by raboof** [comment]
Hmm, looks like I didn't correctly move the default parameters over to the new recommended method in 455a226051, indeed.

**Comment by jrudolph** [comment]
Fixed in #2610.
