### ISSUE TITLE
Multiple subprotocols are not supported in websockets handshake

### ISSUE THREAD

**Issue by RomanBrodetski** [akka/akka-http#2606]
According to the [Websockets RFC](https://tools.ietf.org/html/rfc6455#section-11.3.4), a websocket client can send multiple values in `Sec-WebSocket-Protocol` header. 
However, the [`WebSocketRequest`](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/WebSocketRequest.scala#L22) case class has a `subprotocol` field of type `Option[String]`. Passing subprotocols as comma separated values there doesn't work either, as in this case the handshake fails when the server responds with one of the subprotocols (see https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala#L271).

It seems like this feature is only missing on the `WebSocketRequest` level - the `Option[String]` is then converted to `Seq[String]` with `.toList()` (see [here](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala#L57)). Instead, the `WebSocketRequest` should accept the subprotocols as a `Seq[String]`.

**Comment by jrudolph** [comment]
Fixed in #2607.
