### ISSUE TITLE
Provide TestNGRouteTest.scala in akka-http-testkit

### ISSUE THREAD

**Issue by kanishka-work** [akka/akka-http#2611]

**Comment by raboof** [comment]
We don't have any plans to support different testing frameworks. Perhaps it would be best to have this as a 3rd-party library? Is there anything missing in Akka HTTP to make that possible?

**Comment by kanishka-azimi** [comment]
It sounds possible as is. If you create the repo that houses third party libraries, we may end up contributing TestNGRouteTest to it.

**Comment by jrudolph** [comment]
@kanishka-azimi. we discussed this again in the team and reviewed our current policy wrt testing frameworks. So far, we already support a few frameworks directly under akka-http-testkit (using a `provided` dependency), so adding support for TestNG in the same way seems to make sense after all. If you could PR an initial version that would be much appreciated!
