### ISSUE TITLE
Remove reliance on deprecated akka.stream.actor.ActorPublisher

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2617]
as it is going away entirely in Akka 2.6

It is used in `PoollInterfaceActor`

**Comment by jrudolph** [comment]
We can try first if it is simple and safe to convert to GraphStage directly. Otherwise, we'll have to include a private copy of ActorPublisher for the time being.

**Comment by jrudolph** [comment]
The funny thing about `PoolInterfaceActor` is that it uses its publisher/subscriber-me only to connect itself to the actual pool implementation. I guess it was written when `Source/Sink.queue` wasn't there. So, that might actually be somewhat easy to fix.

**Comment by jrudolph** [comment]
Fixed by reimplementing `PoolInterfaceActor` as a GraphStage in #2630.
