### ISSUE TITLE
Access websocket close frame to control error/close code and reason

### ISSUE THREAD

**Issue by ikempf** [akka/akka-http#2620]
There is currently no way of accessing the closing frame when using akka-http websocket client.
Even though it is a control frame, getting a handle on it as a user is desirable for multiple reasons :
- Accessing the close code and reason which can both be user defined
- Knowing that the connection has been closed properly (closing handshake)
- Acting on non-rfc behaviour (for instance the peer might send data *after* having sent the close frame).

With the current stream model I think that the closing frame should be the last message of the stream. I feel like there should be a `CloseMessage` extending `Message`.
In order to not break compatibility and/or surprise usersm there could be the api modeled as follow :
```scala
sealed trait WebsocketMessage
case class CloseMessage(...) extends WebsocketMessage
sealed trait DataMessage extends WebsocketMessage
case class TextMessage(...) extends DataMessage
case class BinaryMessage(...) extends DataMessage

Http().webSocketClient(Data)Flow(): Flow[DataMessage, DataMessage] // Iso to existing flow
Http().webSocketClientProtocolFlow(): Flow[WebsocketMessage, WebsocketMessage] // Existing flow + close frame
```

The is related to #2458 (requesting user-api for close frame but on the server-side of things)

**Comment by jrudolph** [comment]
Thanks for the suggestion, @ikempf. That seems like a useful feature.

It's hard to change the existing message model in a binary compatible way, though.

> * Accessing the close code and reason which can both be user defined

That would be nice, indeed.
 
> * Knowing that the connection has been closed properly (closing handshake)

That seems like an implementation detail. When you receive the `onComplete` signal you should know that the connection wasn't abruptly terminated.

> * Acting on non-rfc behaviour (for instance the peer might send data _after_ having sent the close frame).

We won't support non-standard behavior. We may consider supporting de-facto standard behavior even if not in the RFC when it has relevant usage but that feature doesn't seem to fit the bill.

**Comment by ikempf** [comment]
> We won't support non-standard behavior. We may consider supporting de-facto standard behavior even if not in the RFC when it has relevant usage but that feature doesn't seem to fit the bill.

I didn't mean for akka-http to support anything other than the RFC.
I was just pointing out the fact that having knowledge of the closing frame allows me/the user to take action against non standard behaviour. In my particular case I wanted to avoid receiving data frames **after** having received a close frame (whether on the server or client side).

**Comment by jrudolph** [comment]
> In my particular case I wanted to avoid receiving data frames **after** having received a close frame (whether on the server or client side).

Ah, thanks for the clarification. That should not happen and would be a bug if it did.

**Comment by mmacfadden** [comment]
Similarly to my comments on #2458, accessing the close code on the server side is of interest to us.

**Comment by jrudolph** [comment]
Let's track that whole feature for server and client side in #2458.
