### ISSUE TITLE
Add flag to log WS frame traffic

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2648]
Similar as done for HTTP/2 a while ago in #2561.

**Comment by nitikagarw** [comment]
Hi @jrudolph, 
Looks like it requires similar changes in `WebSocketSettings.scala`. If yes, Can I please pick this issue?
Thanks, 
Nitika Agarwal

**Comment by jrudolph** [comment]
Yes, please! (sorry for the delay over the change of the year)

**Comment by jrudolph** [comment]
Implemented in #3739
