### ISSUE TITLE
Testkit actor system config file path init

### ISSUE THREAD

**Issue by charlie-world** [akka/akka-http#2658]
Hi, i'm developing web service with `akka-http` which is my favorite web framework and i love scala. 

When i wrote some test codes for route logic with `akka-http-testkit` it has been error with environment variables are not imported.
e.g)
I wrote a `application.conf` file in `/src/main/resources`, and when the program run, system will take env vars from linux machine.
```
/src/main/resources/application.conf

app {
   env = ${APP_ENV}
}
```
However, i think that it doesn't have to insert the env vars at test codes run.
I guess it must be related with this lines.
https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
`at 39 to 44`

So i will suggest some kinds of codes, please check and tell me better idea if you have.
Thx.

**Comment by raboof** [comment]
> i think that it doesn't have to insert the env vars at test codes run.

That is indeed correct

> I guess it must be related with this lines.
https://github.com/akka/akka-http/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala#L39-L44

Indeed you can add configuration specific to your test by overriding `testConfigSource`. I would recommend placing static configuration in youjr test there so your tests no longer have to rely on environment variables.

**Comment by charlie-world** [comment]
@raboof Thanks for feedback !
So, i solved that problem with this codes,
```scala
... In test codes extends TestRoutes

override def testConfigSource: String = "/my-test-config"
```

but, i want to know how many people think this problem should be fixed on framework code level.
or replace default value of `test-config-source` instead of `""`.

**Comment by jrudolph** [comment]
`testConfigSource` doesn't seem to be loaded from the file given but load the config directly from the string. So, you should probably use it like this:

```
override def testConfigSource: String = "app.env = theenv"
```

Right now that's the recommended way to do it. Do you suggest that we add another mechanism to load custom configuration for all of the user's tests?

**Comment by jrudolph** [comment]
Not sure if there's still something to do here, closing for now.
