### ISSUE TITLE
Fail fast when building with jdk9+

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2673]
The Akka HTTP build specifies `-target:jvm-1.8` for the scalac options. However, this is not sufficient to build an Akka HTTP library that works on JDK8: because even with `-target:jvm-1.9`, the code is still linked to the newer standard library. Because of this, this might cause problems like:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer
```
when a downstream project later tries to run with the jdk8 standard library.

In Akka we have fixed the build to produce correct JDK8 classes even when building with a later JDK, because there we need that later JDK anyway for the reactive streams API's. For Akka HTTP, I would suggest just failing fast when accidentally compiling with a newer JDK.

When we drop support for jdk8 we can start using the `-release` flags, but that'll be a while :)

**Comment by jrudolph** [comment]
Maybe we could use the same change as here in here: 

https://github.com/spray/spray-json/commit/5bf165745bc50027f1b6239ad4c7a98dfde25bb5

i.e. guard the addition of the `-release 8` flag looking at Scala and JDK versions.
