### ISSUE TITLE
Fix version in the intro doc

### ISSUE THREAD

**Issue by helena** [akka/akka-http#2675]
Intro doc shows wrong type of version in `$crossString$` paradox property from build.sbt

`"com.typesafe.akka" %% "akka-http"   % "10.1.9+3-8c13e4b3+20190823-1353" `

Doc
https://doc.akka.io/docs/akka-http/current/introduction.html#using-akka-http

Paradox:
```
sbt
:   @@@vars
    ```
    "com.typesafe.akka" %% "akka-http"   % "$project.version$" $crossString$
    "com.typesafe.akka" %% "akka-stream" % "$akka.version$" // or whatever the latest version is
    ```
    @@@
```

**Comment by raboof** [comment]
That must've happened when I manually updated the docs with the Lightbend banner :/

**Comment by raboof** [comment]
(so it should be OK again when we release 10.1.10, but perhaps we want to fix it beforehand)

**Comment by ennru** [comment]
We need to re-deploy 10.1.9 docs so they have the correct version.

**Comment by jrudolph** [comment]
I can do it.

**Comment by jrudolph** [comment]
Fixed in https://github.com/akka/akka-http/compare/10.1.9-docs~2...10.1.9-docs.

**Comment by jrudolph** [comment]
(Removed the 10.1.9-docs branch and created tags instead, let's keep the running branches clean).
