### ISSUE TITLE
HttpEntity.toStrict casts Meterializer blindly to ActorMaterializer causing ClassCastException

### ISSUE THREAD

**Issue by gisql** [akka/akka-http#2679]
`HttpEntity.toStrict` casts `Meterializer` blindly to `ActorMaterializer` causing `ClassCastException`. As far as I can tell, this has been introduced in 10.1.5.

I understand that you need the configured maximum entity length, but surely there must be a better way to get it.

**Comment by jrudolph** [comment]
What kind of materializer do you have? Since there are no significant custom materializers, the distinction between `Materializer` and `ActorMaterializer` is going to fade / be remove with Akka 2.6.

Until then we should document that akka-http only works with an `ActorMaterializer`.

**Comment by gisql** [comment]
I wanted to do some additional stuff when a `task: Runnable` was `scheduled`.  I wrap `Materializer` with my decorator.  I can, obviously, wrap `ActorMaterializer` instead (and just delegate more methods), but since everything requires the base, I thought that it'd be safer to stick with it.

TBH, the `ActorMaterializer` is full of `INTERNAL API` comments which is a bit scary.

**Comment by jrudolph** [comment]
Yep, that's no really supported. Maybe you could use a custom dispatcher or executor instead?
