### ISSUE TITLE
javaunidoc failing

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2692]
Nightly doc job has failed since Aug 28

I think this is the error: `bad option: '-doc-canonical-base-url'`

https://jenkins.akka.io:8498/job/akka-http%20docs/168/consoleFull

**Comment by jrudolph** [comment]
Interesting, forget about that job completely ;) Seems unidoc is otherwise only used during releasing, so good to look at that now.

**Comment by jrudolph** [comment]
The option was added in 2.12.9 but the job was running on 2.12.8. Fixed that, can be closed when https://jenkins.akka.io:8498/job/akka-http%20docs/180/console is successful.

**Comment by raboof** [comment]
> can be closed when https://jenkins.akka.io:8498/job/akka-http%20docs/180/console is successful.

It is
