### ISSUE TITLE
Find less brittle way to test against akka master / release-2.5 in nightlies

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2700]
The nightlies currently include the whole akka/akka build to compile and run tests against those. That seems to break quite a lot of times because of subtle incompatibilities between the two builds (incompatible plugin versions).

Are there better solutions? A better way could be to rely on akka snapshots instead (but how to select the latest with sbt/ivy/coursier?).

**Comment by johanandren** [comment]
Isn't that the whole point of snapshots, that you can depend on a moving target latest snapshot, or have broken that with the snapshot-version-stamp scheme we use for Akka?

**Comment by raboof** [comment]
I think Play have some scripts to depend on our published snapshots - so that should be possible (and if we'd switch to dynver it should [still be](https://github.com/akka/akka/pull/27042#discussion_r290294053) as long as we exclude milestones/rc's

**Comment by ennru** [comment]
Done, CI uses Akka snapshot builds. See https://github.com/akka/akka-http/issues/2994#issuecomment-1323333403
