### ISSUE TITLE
Prepare routing API for deprecation / removal of argument adaption

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2738]
In akka-http routing we make heavy use of adapting arguments into tuples (see http://spray.io/blog/2012-12-13-the-magnet-pattern/#dryness-for-many-similar-overloads for an explanation of why that's needed). The required feature from the Scala compiler is argument adaptation which automatically convert a sequence of arguments of a method to a tuple if the target method takes only a single parameter. This feature is going away with upcoming Scala versions and the consequences can already be experienced by using the `-Yno-adapted-args` compiler flags.

Most importantly the `parameters` and `formFields` directives are affected.

Potential alternatives are:
 * require users to explicitly supply tuples to directives that make use of the magnet pattern (somewhat verbose, all users need to change code, but we might be able to provide scalafix migrations)
 * use a combinator approach to join a set of arguments, i.e. convert `parameters('name, 'age)` to  `parameters('name ~~ 'age)` or similar (still requires users to change code, type inference will be probably be more complex leading to longer compile times and (even) worse error messages)
 * use sbt-boilerplate to generate stubs for all arities and remove / deprecate old variant (same syntax, probably better error messages, straight-forward typing, probably some simplification of the old magnet pattern code, some considerations needed to deal with binary compatibility)

So far, the last option sounds most appealing to me.

**Comment by raboof** [comment]
Let's try the sbt-boilerplate approach first and reconsider if this turns out to blow up

**Comment by jrudolph** [comment]
>     * use sbt-boilerplate to generate stubs for all arities and remove / deprecate old variant (same syntax, probably better error messages, straight-forward typing, probably some simplification of the old magnet pattern code, some considerations needed to deal with binary compatibility)

I had a try at this option. This is hard (impossible?) to pull off because the magnet pattern is inevitable in this place to be able to join the results of to parameter extractions. E.g. to implement the binary

Each param usually will either be equivalent to a Directive1 or a Directive0. Directive1 is the usual case. while using `"name".!(defaultName)" will lead to a `Directive0`. To be able to produce a combined directive here we need to join the result types of `param1` and `param2`. However, that can only be done at the call-site because only there all the parameters and types. The solution with regular implicits (in contrast to magnets) would be to use:

```
def parameters(param1: ParamSpec, param2 ParamSpec)(implicit join: Join[param1.Out, param2.Out]): Directive[join.Out]
```

However, that doesn't work with the Directive API because it is used as `parameters(a,b) { (a, b) => }` where the closure block must not be confused with the implicit parameters. In fact, that was one of the original important reasons to create the magnet pattern in the first place.

I'll also experiment with the second option to see if that makes for a nicer API.

**Comment by jrudolph** [comment]
> Each param usually will either be equivalent to a Directive1 or a Directive0. Directive1 is the usual case while using `"name".!(defaultName)"` will lead to a `Directive0`. To be able to produce a combined directive here we need to join the result types of `param1` and `param2`. However, that can only be done at the call-site because only there all the parameters and types are known. The solution with regular implicits (in contrast to magnets) would be to use:

I realized that required parameters (using `!`) are probably quite rare. So if we can afford a slight source incompatibility in that regard we can make it work, see https://github.com/akka/akka-http/pull/2971.

**Comment by jrudolph** [comment]
Let's consider removing https://github.com/akka/akka-http/pull/3091/files#diff-c275e43e5d4ef31cb36384dbbf818da8R25 again when we manage to fix this.

**Comment by raboof** [comment]
Definitely!

**Comment by jrudolph** [comment]
Auto-tupled arguments can also be used with `complete` (as @raboof reported in https://github.com/akka/akka-http/pull/3114/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR334). They will occur if you use one of the `PredefinedToResponseMarshallers`. But maybe we should just discourage these usages and recommend more-verbose-but-explicit versions for that. E.g. if it's just about text content, it could just be

```scala
complete(HttpResponse(200, entity = "text", headers = ...))
```

Usages that are harder to fix would be those where the entity needs to be marshalled from a different type and content-type negotiation should take place *and* the status code should be provided as well. In that case

```scala
complete(200 -> obj)
```

would still work.

If you need to add headers, you could also use the `respondWithHeader` directive to add that.

**Comment by jrudolph** [comment]
Another instance where adapting args was necessary was for directives that have only implicit parameters like a `ClassTag` (as seen in #3130).
