### ISSUE TITLE
High live object count and GC  of PartialFunction$orElse 

### ISSUE THREAD

**Issue by eugenemiretsky** [akka/akka-http#2742]
Hi, 

I am seeing a lot of PartialFunction$orElse object being allocated and reclaimed in Younge GC - about 14M objects get created and deleted every minute 
My code really doesn't do much. So wanted to see if anybody has encountered this issue before.

Akka HTTP version: 10.1.10
Akka version: 2.5.18

**Comment by jrudolph** [comment]
Hi @eugenemiretsky, I don't think it has been seen before, it's also hard to say if that rate is really significant or not. Could you post some example code or use a profiler to pinpoint the allocation source?

**Comment by eugenemiretsky** [comment]
Hi @jrudolph 
Heap dumps
https://drive.google.com/open?id=1n7YJlFjLjehKQUvCnPR1skPra_6c6oqC
https://drive.google.com/open?id=1EgBqOTYR-OzuRNIfsYNAczQqxlgupvjo 

Heap Trace using Visual VM
https://drive.google.com/open?id=1wczon9dviLE0nmL_awaxTD5ud-vX4lE_

Younge GC: 
https://drive.google.com/open?id=160DRerF6exgKqSlHrNiECcTo1LQ4Mx00

**Comment by jrudolph** [comment]
There are 100k actors of type `StreamSupervisor`. That points to an issue in your code where you create lots of `ActorMaterializer()` without ever shutting them down. The recommendation instead is to create only a single materializer per application and pass this instance around and use it everywhere.

Since this is a common issue, using materializers is optional in the upcoming Akka 2.6 and you can use an `ActorSystem` where you had to use a materializer before.

**Comment by eugenemiretsky** [comment]
You are right, good catch. 
My ActorMaterializer was a def instead of a var. 

Thanks! 

Only reason we are creating an ActorMaterializer is because Unmarshal needs it. And the only reason Unmarshal needs it as a fallback to get an execution context in case there is no implicit execution context. 
This is a bit weird - would it make sense to remove the dependency?

**Comment by eugenemiretsky** [comment]
Btw: Still seeing a lot of PartialFunction$orElse. 
I think it is caused by Json4s
https://www.reddit.com/r/scala/comments/8vj2hv/how_to_optimize_a_long_chain_of/

**Comment by jrudolph** [comment]
Great, seams you figured it out. Thanks for the pointer to the json4s problem.

> Only reason we are creating an ActorMaterializer is because Unmarshal needs it. And the only reason Unmarshal needs it as a fallback to get an execution context in case there is no implicit execution context.
> This is a bit weird - would it make sense to remove the dependency?

It's also passed to the unmarshaller which might need it to read the entity. If you are using akka-http you will have a materializer around anyway so it shouldn't be a big problem to pass it in there.
