### ISSUE TITLE
Multipart form data not behaving properly

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [akka/akka-http#2750]
Hello,

I'm trying to send a multipart request with a file on it,

```
  def createPageEntity(filePath: Path) = {
    val file = new File(filePath.toUri)
    require(file.exists())

    val reqType = Multipart.FormData.BodyPart("RequestType", "TestRequest")

    val ff = Multipart.FormData.BodyPart(
        "test",
        HttpEntity(MediaTypes.`application/xml`.toContentType(HttpCharsets.`UTF-8`),
          file.length(), FileIO.fromPath(filePath)))

    Multipart.FormData(reqType, ff).toEntity()
  }

  def performRequest(fileName:Path):Future[HttpResponse]  = {

      Http().singleRequest(HttpRequest(
        method = HttpMethods.POST,
        uri = serviceUrl,
        entity = createPageEntity(fileName)
      )
      )
  }


```

I get the request on the server, but completely empty. No file, no headers when I put them, and so on. What am I missing?.
Also took a look at the book "Akka Cookbook/Uploading a file using Akka HTTP" tried their code and still the same issue. My versions,

```
  val Akka           	= "2.5.25"
  val AkkaHttp		    = "10.1.10"
```

thanks in advance!

**Comment by jrudolph** [comment]
I haven't tried your code but it seems reasonable.

Can you try with `akka.http.client.log-unencrypted-network-bytes = 1000` and debug logging on (`akka.loglevel = debug`) and see if the file turns up on the wire?

**Comment by albertoandreottiATgmail** [comment]
hello @jrudolph,
thanks for the answer, I changed the code for creating the entity to,

  def createPageEntity(filePath: Path) = {
    val filename = filePath.getFileName.toString
    val file = new File(filePath.toUri)
    val entFut = HttpEntity(MediaTypes.`application/xml`.toContentType(HttpCharsets.`UTF-8`),
      file.length(), FileIO.fromPath(filePath)).toStrict(1.minutes)

    entFut.map { entity =>
      Multipart.FormData(
        Multipart.FormData.BodyPart.Strict(
          filename, entity, Map("filename" -> filename))
      ).toEntity()
    }
  }

and properly handled the resulting future. So could it be the case that in the first version something was failing in the file read that was not properly handled? Some async operation that we didn't wait on?
The thing is that the framework(akka-http) seems to support that type of coding. So maybe if we need the file to be read asynchronously, we shouldn't allow the code to be written like in the first version?

Thank you!

**Comment by jrudolph** [comment]
Sorry, we never answered. Closing for now, if this is still a problem, we can either reopen here or if it's more of a question ask on https://discuss.akka.io.
