### ISSUE TITLE
Failed: Mixed akka versions for nightly 

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2757]
```
Detected possible incompatible versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use [default] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [2.5.23, default] in libraries [akka-protobuf:2.5.23, akka-actor:2.5.23, akka-protobuf-v3:default, akka-stream:2.5.23, akka-stream-testkit:2.5.23]
```

https://jenkins.akka.io:8498/job/akka-http-nightly/655/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.9,jdk=AdoptOpenJDK%208/testReport/junit/akka.http/ConfigSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

When we use the akka version as default (currently 2.5.23), we override but still end up with a 2.6 only dependency (protobuf v3) on the classpath. 

This used to be a warning but now is an error.

**Comment by raboof** [comment]
I can't find the fix but it looks like this is no longer failing? (https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.9,jdk=AdoptOpenJDK%208/) - let's reopen when it occurs again
