### ISSUE TITLE
Keepalive support

### ISSUE THREAD

**Issue by eugenemiretsky** [akka/akka-http#2763]
I was under the impression that keepalive is supported out of the box, and that one needs to sert max-connection-lifetime in order to reset the connections. 
The default keepalive setting on the OS (/proc/sys/net/ipv4/tcp_keepalive_time) is 7200

When running  netstat -ao on my instance I see
Entries like 
tcp6       0      0 ip-172-21-150-108:51874 172.45.2.60:http        ESTABLISHED off (0.00/0/0)

This suggests that keepalive is off. What am I doing wrong?

**Comment by eugenemiretsky** [comment]
For completeness: 
sysctl net.ipv4.tcp_keepalive_time net.ipv4.tcp_keepalive_probes net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_time = 7200
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_intvl = 75

**Comment by jrudolph** [comment]
Hi @eugenemiretsky, could you explain how you would expect TCP keep alive to apply to HTTP? We implement HTTP keepalive which is a different thing.

Do you suggest to add options to allow setting TCP keepalive configuration for HTTP clients / servers?
