### ISSUE TITLE
Http2: outgoing request streams not closed when upstream finished

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2777]
In the Http2 stream multiplexer only `onDownstreamFinish` from the connection is closing down all the `outStreams` but not `onUpstreamFinish` / `onUpstreamFailure`.

That means that for any connection error or completion or the idle-timeout might leave user streams dangling. It depends on how the race between finishing and cancellation plays out. If cancellation is first, then everything is fine, otherwise, the outstreams are left dangling.

This is the root cause of https://github.com/akka/akka-grpc/issues/664.

**Comment by jrudolph** [comment]
#2777 also fixed a related issue for request streams.

**Comment by jroper** [comment]
@jrudolph Thanks for the diagnosis and fix!
