### ISSUE TITLE
SSL failure when using ALPN and http1.1 (not http2)

### ISSUE THREAD

**Issue by jroper** [akka/akka-http#2791]
Here's an example of what happens when you make a request using curl to an https and http2 enabled akka-http server using http1.1. I believe that the problem is that akka-http is returning `h1`, which is incorrect, it should return `http/1.1`, like curl is offering. It should probably also check that http/1.1 is in the list of protocols requested, rather than just returning it.

```
$ curl https://34.74.175.178:8443 -k -v --http1.1
* Expire in 0 ms for 6 (transfer 0x559e1d72e5c0)
*   Trying 34.74.175.178...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559e1d72e5c0)
* Connected to 34.74.175.178 (34.74.175.178) port 8443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS alert, no application protocol (632):
* error:14094460:SSL routines:ssl3_read_bytes:reason(1120)
* Closing connection 0
curl: (35) error:14094460:SSL routines:ssl3_read_bytes:reason(1120)
```

**Comment by jroper** [comment]
This would be a great issue for a new contributor. Here's the registry of ALPN protocol ids:

https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

Here's the code with the bug in it (you can see twice it's selecting `h1`):

https://github.com/akka/akka-http/blob/master/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala

There's also a reference to `h1` here:

https://github.com/akka/akka-http/blob/1d917846529ebf94c99b16ebf4286a8a7c431c38/akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala#L167

Though that one's benign because the place that uses it ignores it:

https://github.com/akka/akka-http/blob/0021aff57b740c704c831a55cf4c8784701fcc94/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ProtocolSwitch.scala#L50-L54

Nevertheless, this code could do with some constants introduced, and if http/1.0 or http/1.1 are selected, they should be returned. And if neither http/1.0, http/1.1 or h2 are selected, then it should not try and return something that the client didn't request. There's a specific error to return:

https://tools.ietf.org/html/rfc7301#section-3.2

Based on the error message from curl above, I guess the JDK is validating what is returned and when it's not one that the client requested, it's doing that appropriately, but presumably the JDK and/or Jetty APIs offer a better way to do that than returning something wrongly (maybe returning null?).

**Comment by jrudolph** [comment]
Great findind and write up, thanks @jroper.
