### ISSUE TITLE
UnsupportedRequestContentTypeRejection formats error messages not in a user-friendly way

### ISSUE THREAD

**Issue by satorg** [akka/akka-http#2804]
If a request is rejected with `UnsupportedRequestContentTypeRejection` and actual `contentType` is provided to the rejection, then the error message for this rejection will look like the following:

> The request's Content-Type [Some(Some(image/gif))] is not supported. Expected:\nimage/jpeg or image/png

which is not user-friendly.

The reason is in these two lines:
https://github.com/akka/akka-http/blob/v10.1.10/akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala#L265-L266

The `unsupportedContentType` value has got type `Option[Option[ContentType]]`.

**Comment by raboof** [comment]
That indeed could be better. Would you be interested in improving this?

**Comment by satorg** [comment]
Yes, for sure. I have shot a tiny PR for this issue (#2807), could you take a look, please?

**Comment by jrudolph** [comment]
Fixed in #2807.
