### ISSUE TITLE
Don't handle TestFailedExceptions in RouteTest ExceptionHandlers

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2818]
That will allow assertions in test routes to fail the test instead of being converted to 500 response.

Seen here: https://guardrail.dev/scala/akka-http/generating-a-server#akka-http

**Comment by raboof** [comment]
Seems reasonable.

Since we don't want to add a dependency on scalatest, I guess we'd recognize them by class name?

**Comment by jrudolph** [comment]
Either that or try to put it into ScalaTestRouteTest where scalatest is available.

**Comment by jrudolph** [comment]
Fixed in #2949.
