### ISSUE TITLE
PR validation not running tests of dependent modules any more

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2831]
#2823 did get through PR validation without running akka-http-tests tests which broke master.

https://jenkins.akka.io:8498/job/pr-validator-akka-http/3854/testReport/

**Comment by raboof** [comment]
Indeed. In https://jenkins.akka.io:8498/job/pr-validator-akka-http/3854/consoleFull it logs `Project [akka-http-core] must be verified, because depends on [akka-http-core]` but for all other modules `Skipping validation of [akka-http], as PR does NOT affect this project...`

**Comment by jrudolph** [comment]
```
[info] Project [akka-http-core] must be verified, because depends on [akka-http-core]
[info] Skipping validation of [akka-parsing], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-caching], as PR does NOT affect this project...
[info] Skipping validation of [akka-http], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-tests], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-jackson], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-marshallers-java], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-spray-json], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-docs], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-xml], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-testkit], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-marshallers-scala], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-root], as PR does NOT affect this project...
[info] Skipping validation of [akka-http-compatibility-tests], as PR does NOT affect this project...
[info] Skipping validation of [akka-http2-support], as PR does NOT affect this project...
```

That's clearly wrong. It could be caused by sbt 1.3.x vs. sbt-dependency-graph, I thought it would work by switching off coursier but maybe not. Checking if that's it and if sbt 1.3.4 has fixed it again.

**Comment by raboof** [comment]
(we had similar problems, except with the pr validator in the separate sbt plugin, in https://github.com/akka/akka/issues/27937)

**Comment by jrudolph** [comment]
> (we have seen similar problems, except with the pr validator in the separate sbt plugin, in [akka/akka#27937](https://github.com/akka/akka/issues/27937))

That's interesting as well but I think it was rewritten to use sbt structures directly compared to what we are doing here with sbt-dependency-graph.

**Comment by jrudolph** [comment]
Going back to sbt 1.2.7 would indeed fix the problem
