### ISSUE TITLE
JDK8/jetty-alpn-agent-2.0.9.jar + akka-http-10.0.11 and Akka 2.6.0 uses HTTP1.1

### ISSUE THREAD

**Issue by surendarchandra** [akka/akka-http#2847]
I'm on JDK and so use jetty-alpn-agent-2.0.9.jar agent to achieve H2.
Upgrading to akka-http-10.0.11 and Akka 2.6.0 only lets me use Http1.1.
Not sure whether its Akka-Http or Akka

**Comment by surendarchandra** [comment]
Reverted to akka-http-10.1.10 and that doesn't fix it. Perhaps its Akka 2.6.0

**Comment by raboof** [comment]
Could you try upgrading ssl-config to 0.4.1? Akka 2.6.0 comes with ssl-config 0.4.0 which [has a known problem](https://github.com/lightbend/ssl-config/pull/220) with the jetty ALPN agent. 

ssl-config 0.4.1 should fix it (and Akka 2.6.1 should [bring in ssl-config 0.4.1](https://github.com/akka/akka/pull/28183))

**Comment by surendarchandra** [comment]
Unfortunately, did not help - it still falls back to HTTP1.1.

**Comment by raboof** [comment]
How do you see that happening?

**Comment by surendarchandra** [comment]
% curl -vv --http2 -k https://10.0.120.43/api/v1/cluster/me/version
*   Trying 10.0.120.43...
* TCP_NODELAY set
* Connected to 10.0.120.43 (10.0.120.43) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=.....
*  start date: Dec  1 09:02:14 2019 GMT
*  expire date: Apr 19 09:02:14 2047 GMT
*  issuer: CN=....
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /api/v1/cluster/me/version HTTP/1.1
> Host: 10.0.120.43
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK

**Comment by raboof** [comment]
Hmm, that is weird. Can you share a (minified version of) the project so we could have a look?

**Comment by surendarchandra** [comment]
NVM, we had switched to Conscrypt and didn't realized the Jetty-ALPN does not support it. Apologies for the false alarm

**Comment by raboof** [comment]
Ahh, thanks for reporting back!
