### ISSUE TITLE
RouteTest cleanUp does not wait for ActorSystem termination

### ISSUE THREAD

**Issue by mmatloka** [akka/akka-http#287]
`RouteTest.cleanup` performs `def cleanUp(): Unit = system.terminate() ` https://github.com/akka/akka/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala#L50 where `  def terminate(): Future[Terminated]`

**Comment by ktoso** [comment]
Thanks for reporting.
None of the afterAlls in Akka HTTP's suite actually wait for the termination.
This seems like a mistake to me...

Would you like to submit a PR fixing this?

// cc @jrudolph

**Comment by rbudzko** [comment]
@ktoso @jrudolph It's merged. Should sth more be prepared to close this one?

**Comment by ktoso** [comment]
Thanks for noticing, yep closing
