### ISSUE TITLE
Failed: no subprojects list 2.11.12

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2885]
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%208/760/console

```
[info] Executing in batch mode. For better performance use sbt's shell
[error] Switch failed: no subprojects list "2.11.12" (or compatible version) in crossScalaVersions setting.
[error] If you want to force it regardless, call ++ 2.11.12!
```

**Comment by johanandren** [comment]
looks like it is all Nightly 2.11 jobs
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%2011/760/console
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%2011/760/

**Comment by raboof** [comment]
Ah yes, we can remove those from the matrix since #2869

**Comment by raboof** [comment]
(done)
