### ISSUE TITLE
Promote Akka 2.6

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2886]
Since the recent Akka 2.5 updates it becomes smoother to use Akka HTTP with Akka 2.6. 

 * [x] Update the docs to show 2.6 usage (#2996)
 * [ ] Streamline usage where Materializer was required before
 * [ ] Review bootstrapping code wrt to Akka 2.6
 * [x] Go through documentation and remove mentions of Materializer

**Comment by raboof** [comment]
What kinds of things should we be looking for before closing this?

**Comment by ennru** [comment]
Another part of this is https://github.com/akka/akka-http/pull/3242

**Comment by ennru** [comment]
I believe we've covered this now. Closing.
