### ISSUE TITLE
Getting net::ERR_HTTP2_COMPRESSION_ERROR from Chrome

### ISSUE THREAD

**Issue by surendarchandra** [akka/akka-http#2888]
This is a followup to https://discuss.lightbend.com/t/akka-http-10-1-9-for-http2-getting-net-err-http2-compression-error/5209.

Okay, there are multiple issues here:
  - I think there is a issue in Twitter hpack library (https://github.com/twitter/hpack/issues/34): because of this, even headers such as Content-Length that should come from static table are now coming from Dynamic tables. 
  - Chrome requests a larger dynamic table than the default 4K and we grant them. However, I think there s a bug in how we communicate that to large table to Chrome. I am not familiar with H2. In Quiche (which is the Google/ThirdParty QUIC/H2 library that Chome uses, we are in
http2/hpack/decoder/hpack_decoder_state.cc: 

```
void HpackDecoderState::OnIndexedHeader(size_t index) {
...
  allow_dynamic_table_size_update_ = false;
  const HpackStringPair* entry = decoder_tables_.Lookup(index);
  if (entry != nullptr) {
    listener_->OnHeader(entry->name, entry->value);
  } else {
    std::cout << "SPDY_DECOMPRESS_FAILURE index=" << index << "\n";
    ReportError("Invalid index.");
  }
```

and we get a Invalid index error. Not sure how the update is received. I added some printfs and this is what I see from Chromium:

```
SPDY_DECOMPRESS_FAILURE dynamic i=0 value = HpackStringPair(name=content-length, value=71874)
SPDY_DECOMPRESS_FAILURE dynamic i=1 value = HpackStringPair(name=content-type, value=font/woff)
SPDY_DECOMPRESS_FAILURE dynamic i=2 value = HpackStringPair(name=etag, value="2b60016f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=3 value = HpackStringPair(name=content-length, value=1748)
SPDY_DECOMPRESS_FAILURE dynamic i=4 value = HpackStringPair(name=etag, value="4778016f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=5 value = HpackStringPair(name=content-length, value=7906)
SPDY_DECOMPRESS_FAILURE dynamic i=6 value = HpackStringPair(name=content-length, value=11)
SPDY_DECOMPRESS_FAILURE dynamic i=7 value = HpackStringPair(name=content-length, value=37)
SPDY_DECOMPRESS_FAILURE dynamic i=8 value = HpackStringPair(name=content-length, value=32)
SPDY_DECOMPRESS_FAILURE dynamic i=9 value = HpackStringPair(name=content-length, value=1680)
SPDY_DECOMPRESS_FAILURE dynamic i=10 value = HpackStringPair(name=content-length, value=1710)
SPDY_DECOMPRESS_FAILURE dynamic i=11 value = HpackStringPair(name=content-length, value=279)
SPDY_DECOMPRESS_FAILURE dynamic i=12 value = HpackStringPair(name=content-length, value=1276)
SPDY_DECOMPRESS_FAILURE dynamic i=13 value = HpackStringPair(name=content-length, value=7)
SPDY_DECOMPRESS_FAILURE dynamic i=14 value = HpackStringPair(name=content-length, value=0)
SPDY_DECOMPRESS_FAILURE dynamic i=15 value = HpackStringPair(name=content-length, value=3087)
SPDY_DECOMPRESS_FAILURE dynamic i=16 value = HpackStringPair(name=content-length, value=281)
SPDY_DECOMPRESS_FAILURE dynamic i=17 value = HpackStringPair(name=content-length, value=251)
SPDY_DECOMPRESS_FAILURE dynamic i=18 value = HpackStringPair(name=content-length, value=98)
SPDY_DECOMPRESS_FAILURE dynamic i=19 value = HpackStringPair(name=content-length, value=15)
SPDY_DECOMPRESS_FAILURE dynamic i=20 value = HpackStringPair(name=content-length, value=1259)
SPDY_DECOMPRESS_FAILURE dynamic i=21 value = HpackStringPair(name=content-length, value=1261)
SPDY_DECOMPRESS_FAILURE dynamic i=22 value = HpackStringPair(name=content-length, value=402)
SPDY_DECOMPRESS_FAILURE dynamic i=23 value = HpackStringPair(name=content-length, value=89)
SPDY_DECOMPRESS_FAILURE dynamic i=24 value = HpackStringPair(name=content-length, value=598)
SPDY_DECOMPRESS_FAILURE dynamic i=25 value = HpackStringPair(name=etag, value="dfa4816f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=26 value = HpackStringPair(name=content-length, value=75259)
SPDY_DECOMPRESS_FAILURE dynamic i=27 value = HpackStringPair(name=etag, value="62a4816f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=28 value = HpackStringPair(name=content-length, value=75078)
SPDY_DECOMPRESS_FAILURE dynamic i=29 value = HpackStringPair(name=etag, value="5b18296f87f4b940")
SPDY_DECOMPRESS_FAILURE dynamic i=30 value = HpackStringPair(name=content-length, value=1317082)
SPDY_DECOMPRESS_FAILURE dynamic i=31 value = HpackStringPair(name=content-type, value=image/jpeg)
SPDY_DECOMPRESS_FAILURE dynamic i=32 value = HpackStringPair(name=etag, value="20e4816f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=33 value = HpackStringPair(name=content-length, value=75524)
SPDY_DECOMPRESS_FAILURE dynamic i=34 value = HpackStringPair(name=content-type, value=application/x-font-truetype)
SPDY_DECOMPRESS_FAILURE dynamic i=35 value = HpackStringPair(name=content-length, value=22)
SPDY_DECOMPRESS_FAILURE dynamic i=36 value = HpackStringPair(name=etag, value="c450016f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=37 value = HpackStringPair(name=content-length, value=2595)
SPDY_DECOMPRESS_FAILURE dynamic i=38 value = HpackStringPair(name=etag, value="4d88016f87f4b558")
SPDY_DECOMPRESS_FAILURE dynamic i=39 value = HpackStringPair(name=last-modified, value=Thu, 09 Jan 2020 01:39:19 GMT)
SPDY_DECOMPRESS_FAILURE dynamic i=40 value = HpackStringPair(name=content-length, value=4530)
SPDY_DECOMPRESS_FAILURE dynamic i=41 value = HpackStringPair(name=content-type, value=image/svg+xml)
SPDY_DECOMPRESS_FAILURE dynamic i=42 value = HpackStringPair(name=content-length, value=53)
SPDY_DECOMPRESS_FAILURE dynamic i=43 value = HpackStringPair(name=content-length, value=18)
SPDY_DECOMPRESS_FAILURE dynamic i=44 value = HpackStringPair(name=content-length, value=14)
SPDY_DECOMPRESS_FAILURE dynamic i=45 value = HpackStringPair(name=warning, value=199 - This API Resource is subject to ongoing development. The endpoint and the parameters may change in the future. Only use this API when necessary. USE AT YOUR OWN RISK.)
SPDY_DECOMPRESS_FAILURE dynamic i=46 value = HpackStringPair(name=content-length, value=29)
SPDY_DECOMPRESS_FAILURE dynamic i=47 value = HpackStringPair(name=content-type, value=text/plain; charset=UTF-8)
SPDY_DECOMPRESS_FAILURE dynamic i=48 value = HpackStringPair(name=:status, value=401)
SPDY_DECOMPRESS_FAILURE dynamic i=49 value = HpackStringPair(name=cache-control, value=max-age=0, private)
SPDY_DECOMPRESS_FAILURE dynamic i=50 value = HpackStringPair(name=content-length, value=28)
SPDY_DECOMPRESS_FAILURE dynamic i=51 value = HpackStringPair(name=content-type, value=application/json)
SPDY_DECOMPRESS_FAILURE dynamic i=52 value = HpackStringPair(name=etag, value="75ad956f87f4b940")
SPDY_DECOMPRESS_FAILURE dynamic i=53 value = HpackStringPair(name=content-length, value=2733486)
SPDY_DECOMPRESS_FAILURE dynamic i=54 value = HpackStringPair(name=content-type, value=application/javascript; charset=UTF-8)
SPDY_DECOMPRESS_FAILURE dynamic i=55 value = HpackStringPair(name=etag, value="722c416f87f4b940")
SPDY_DECOMPRESS_FAILURE dynamic i=56 value = HpackStringPair(name=content-length, value=144462)
SPDY_DECOMPRESS_FAILURE dynamic i=57 value = HpackStringPair(name=content-type, value=text/css; charset=UTF-8)
SPDY_DECOMPRESS_FAILURE dynamic i=58 value = HpackStringPair(name=date, value=Tue, 14 Jan 2020 18:10:06 GMT)
SPDY_DECOMPRESS_FAILURE dynamic i=59 value = HpackStringPair(name=accept-ranges, value=bytes)
SPDY_DECOMPRESS_FAILURE dynamic i=60 value = HpackStringPair(name=etag, value="fe40016f87f4b940")
SPDY_DECOMPRESS_FAILURE dynamic i=61 value = HpackStringPair(name=last-modified, value=Thu, 09 Jan 2020 01:39:20 GMT)
SPDY_DECOMPRESS_FAILURE dynamic i=62 value = HpackStringPair(name=content-encoding, value=gzip)
SPDY_DECOMPRESS_FAILURE dynamic i=63 value = HpackStringPair(name=cache-control, value=max-age=31536000, public, immutable)
SPDY_DECOMPRESS_FAILURE dynamic i=64 value = HpackStringPair(name=x-xss-protection, value=1; mode=block)
SPDY_DECOMPRESS_FAILURE dynamic i=65 value = HpackStringPair(name=x-permitted-cross-domain-policies, value=none)
SPDY_DECOMPRESS_FAILURE dynamic i=66 value = HpackStringPair(name=x-frame-options, value=SAMEORIGIN)
SPDY_DECOMPRESS_FAILURE dynamic i=67 value = HpackStringPair(name=x-content-type-options, value=nosniff)
SPDY_DECOMPRESS_FAILURE dynamic i=68 value = HpackStringPair(name=strict-transport-security, value=max-age=31536000)
SPDY_DECOMPRESS_FAILURE index=131
```

Basically all the strings that I'd expect to be serviced from static tables clogging up dynamic tables and us not sending the dynamic table update. 

One quick fix was to ignore the dynamic table size update: in
**akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala**

```diff
--- a/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
+++ b/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
@@ -73,10 +73,10 @@ private[http2] object HeaderCompression extends GraphStage[FlowShape[FrameEvent,
         s foreach {
           case Setting(SettingIdentifier.SETTINGS_HEADER_TABLE_SIZE, size) =>
             log.debug("Applied SETTINGS_HEADER_TABLE_SIZE({}) in header compression", size)
-            // 'size' is strictly spoken unsigned, but the encoder is allowed to
-            // pick any size equal to or less than this value (6.5.2)
-            if (size >= 0) encoder.setMaxHeaderTableSize(os, size)
-            else encoder.setMaxHeaderTableSize(os, Int.MaxValue)
+          // 'size' is strictly spoken unsigned, but the encoder is allowed to
+          // pick any size equal to or less than this value (6.5.2)
+          // if (size >= 0) encoder.setMaxHeaderTableSize(os, size)
+          // else encoder.setMaxHeaderTableSize(os, Int.MaxValue)
           case _ => // ignore, not applicable to this stage
         }
     }
```

We are allowed to pick sizes smaller than what is requested; we will loose some compression. 

With the bug, cnce Chrome sees this error/any error in h2 process, it marks all of the channels as invalid and so we loose all the interleaved H2 pages in flight. So, can we remove support for accepting larger dynamic pages until we fix this issue?

The relevant comment from Chromium/Quiche is:

```
  // This instance can't be reused after an error has been detected, as we must                                                                                              
  // assume that the encoder and decoder compression states are no longer                                                                                                    
  // synchronized.
```

**Comment by jrudolph** [comment]
Thanks for the report @surendarchandra.

Can you provide a self-contained example and instructions that can be used to reproduce the behavior?

> Basically all the strings that I'd expect to be serviced from static tables clogging up dynamic tables and us not sending the dynamic table update.

That's a decision to be made by the encoder if it wants to put stuff into the dynamic table or not. The reasoning could be that not only the header name is common and reused but also the value, so initially you take the name from static table and add a literal value and put it into the dynamic table. In another request that uses the same header and value, this dynamic table entry could then be used for an even shorter encoding.

Whether or not `Content-Length` should ever be put into that table is another question (because the value has high entropy). It seems HPACK always puts it into the dynamic table if enabled statically (see line 114 of Encoder.java: `IndexType indexType = useIndexing ? IndexType.INCREMENTAL : IndexType.NONE;` where `useIndexing` is a static configuration).

All that said, in no case should we end up sending indices that are (not yet?) filled. But we will need a reproducer to find out what's going on.

**Comment by jrudolph** [comment]
```
SPDY_DECOMPRESS_FAILURE dynamic i=68 value = HpackStringPair(name=strict-transport-security, value=max-age=31536000)
SPDY_DECOMPRESS_FAILURE index=131
```

The index is into the combined table (static + dynamic). The static table has 61 entries, so `dynamic i=68` should correspond to 68+61=129, so it seems as if at least 2 entries are missing (maybe evicted already?).

I think the chrome issue and your discovery about not calling `setMaxHeaderTableSize` are spot on. When chrome announces a higher dynamic table ability that doesn't mean that the encoder has to use it. But if it does it has to announce it by including a [Dynamic Table Size Update](https://tools.ietf.org/html/rfc7541#section-6.3) in the next HEADERS frame. It seems, `setMaxHeaderTableSize` is creating that message but we never put it on the wire.

**Comment by jrudolph** [comment]
Can you try if this simple change would fix the issue for you:

```diff
diff --git a/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala b/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
index a9871b17d8..da690b9819 100644
--- a/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
+++ b/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
@@ -42,12 +42,12 @@ private[http2] object HeaderCompression extends GraphStage[FlowShape[FrameEvent,
           push(eventsOut, ack)
 
         case ParsedHeadersFrame(streamId, endStream, kvs, prioInfo) =>
-          os.reset()
           kvs.foreach {
             case (key, value) =>
               encoder.encodeHeader(os, key.getBytes(HeaderDecompression.UTF8), value.getBytes(HeaderDecompression.UTF8), false)
           }
           val result = ByteString(os.toByteArray)
+          os.reset()
           if (result.size <= currentMaxFrameSize) push(eventsOut, HeadersFrame(streamId, endStream, endHeaders = true, result, prioInfo))
           else {
             val first = HeadersFrame(streamId, endStream, endHeaders = false, result.take(currentMaxFrameSize), prioInfo)
```

**Comment by surendarchandra** [comment]
Thanks @jrudolph - that simple change fixed it - it works great now.

Sorry, couldn't isolate it to a simple sample code from our system, its too complex.

I think Twitter HPACK library should behave differently but it is what it is. With your fix, we would be fine. You might consider removing content-length, date etc. (I think the Encoder case sensitive behaves that way - it doesn't cache them if that flag is set).

When is the earliest release that would have this fix!!!

Thanks much for your help

**Comment by jrudolph** [comment]
> I think Twitter HPACK library should behave differently but it is what it is. With your fix, we would be fine. You might consider removing content-length, date etc. (I think the Encoder case sensitive behaves that way - it doesn't cache them if that flag is set).



> When is the earliest release that would have this fix!!!

We'll include it in 10.2.0 and also in 10.1.12 but there's no planned release date yet. When #2891 is merged a new snapshot will be built automatically which you can use to test the fix.

**Comment by surendarchandra** [comment]
Naive question: we use Maven central to pull released versions. However, I need this fix before 10.1.12 is released. How do you build a single jar similar to what maven central hosts? I haven't used Travis (and don't have creds anyway). sbt package seems to generate a bunch of jars. Thanks

**Comment by jrudolph** [comment]
Just merged the fix. A new snapshot version will be published to https://dl.bintray.com/akka/snapshots/. You can see this Travis task to see when it's done and what version number it got: https://travis-ci.org/akka/akka-http/jobs/639402208?utm_medium=notification&utm_source=github_status

**Comment by jrudolph** [comment]
> How do you build a single jar similar to what maven central hosts?

Btw. to build the project and publish locally use `sbt publishLocal`.

**Comment by crisamdegracia** [comment]
net::ERR_HTTP2_COMPRESSION_ERROR - WORDPRESS

Okay, I hope this will help many. I have been experiencing this for many weeks. My apology because I am using WordPress.

net::ERR_HTTP2_COMPRESSION_ERROR only occurs on Chrome:Incognito.

I have Cloudflare for my CDN and caching HTML - and W3 Total Cache - for minify js, css and Page Cache, OP-Cache, Object Cache, Browser Cache.

now, after countless of trouble shooting, I detected the issue when disabling the "Browser Cache" after that, I fixed the problem when

I modified the Browser Cache ( go to side panel )

find the ("HTTP Strict Transport Security policy") make sure its checked. under that is ("Directive") set the value to - max-age=EXPIRES_SECONDS; includeSubDomain: preload

take note that I am using sub-domain.

**Comment by jrudolph** [comment]
> net::ERR_HTTP2_COMPRESSION_ERROR - WORDPRESS

Not sure what you mean. Is this actually related to akka-http in any way or just about the browser error message?

**Comment by crisamdegracia** [comment]
> > net::ERR_HTTP2_COMPRESSION_ERROR - WORDPRESS
> 
> Not sure what you mean. Is this actually related to akka-http in any way or just about the browser error message?

Hello, My answer is for the browser error message. only on incognito-Chrome.
