### ISSUE TITLE
Incorrect Parsing of Content-Type Header

### ISSUE THREAD

**Issue by avanu** [akka/akka-http#2910]
Parsing a `Content-Type` header seems to incorrectly detect the media type if the word "charset" is capitalized.

When parsing `text/html; charset=utf-8` everything works fine but for `text/html; Charset=utf-8` (capital C) I get the media type `text/html; Charset=utf-8` instead of just `text/html`; the resulting content type is then also `ContentTypeWithMissingCharset` instead of `ContentTypeWithCharset`

### How to Reproduce
```
scala> import akka.http.scaladsl.model.HttpHeader, akka.http.scaladsl.model.headers.`Content-Type`
import akka.http.scaladsl.model.HttpHeader
import akka.http.scaladsl.model.headers.Content$minusType

scala> val goodHeader = HttpHeader.parse("content-type", "text/html; charset=utf-8")
goodHeader: akka.http.scaladsl.model.HttpHeader.ParsingResult = Ok(Content-Type: text/html; charset=UTF-8,List())

scala> goodHeader match { case HttpHeader.ParsingResult.Ok(`Content-Type`(c), _) => c.mediaType }
res0: akka.http.scaladsl.model.MediaType = text/html

scala> val badHeader = HttpHeader.parse("content-type", "text/html; Charset=utf-8")
badHeader: akka.http.scaladsl.model.HttpHeader.ParsingResult = Ok(Content-Type: text/html; Charset=utf-8,List())

scala> badHeader match { case HttpHeader.ParsingResult.Ok(`Content-Type`(c), _) => c.mediaType }
res1: akka.http.scaladsl.model.MediaType = text/html; Charset=utf-8
```

Looking at the  [RFC](https://tools.ietf.org/html/rfc7231#section-3.1.1.1) it seems that `text/html; Charset=utf-8` should be a valid content type:

> For example, the following examples are all equivalent, but the first is preferred for consistency:
> text/html;charset=utf-8
> text/html;charset=UTF-8
> Text/HTML;Charset="utf-8"
> text/html; charset="utf-8"

Hope the issue explanation is clear enough, let me know if I can answer additional questions. I tried looking through the current issues but couldn't find a similar one.

**Comment by jrudolph** [comment]
Thanks, @avanu. We also have a related issue for other headers (#2136) but since `Content-Type` is handled specially (and also quite important), we should make sure it works here in particular.
