### ISSUE TITLE
Default entity size limit for client

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#2961]
The current client size limit is inherited from the default parser settings, where it is set to 8 Mb. Isn't that an unreasonably low limit for a client? (I can see how it makes sense on the server side)

I propose we increase it quite a bit or perhaps even disable it by default.

**Comment by jrudolph** [comment]
I agree it is probably more important on the server. In the past, we debated whether those limits were useful in a streaming setting at all. In the end, you will probably be also be guarded by the `toStrict` limits before loading stuff into memory. The original reasoning was to have limits for everything for more defense in depth but I can see how people would be confused about that on the client side. Maybe we should just disable it there? WDYT, @raboof?

**Comment by raboof** [comment]
Sounds reasonable to me!

**Comment by seglo** [comment]
I would vote to remove it on the client side.  This issue has come and and been worked around several times in Alpakka by disabling the default limit.

References (GCS and S3)
* https://github.com/akka/alpakka/issues/2084
* https://github.com/akka/alpakka/issues/303
