### ISSUE TITLE
Akka HTTP 10.2 plans

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#2970]
The Akka HTTP 10.2 will build on top of Akka 2.6.

- This means Scala 2.12 or later is required.
- It enables some cleanup of internals and to leverage improvements with Akka 2.6.

We expect to release Akka HTTP 10.2 during Q2 2020.

See the [milestone](https://github.com/akka/akka-http/milestone/50) for what is currently scheduled for 10.2.0

**Comment by jrudolph** [comment]
The release notes cover the scope of the release https://doc.akka.io/docs/akka-http/10.2/release-notes/10.2.x.html.
