### ISSUE TITLE
Add style guide for Akka HTTP route structure

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#2980]
And add section how that compares to play route files + extra logic in handlers. More info about that here: https://www.google.com/url?q=https://www.playframework.com/documentation/2.8.x/ScalaRouting%23The-routes-file-syntax&sa=D&ust=1582537250637000&usg=AFQjCNFOSZ17O-__XqjVJHiyHGkf15FoBA

**Comment by ennru** [comment]
Fixed with #3079 and #3099. Can be improved ofc...
