### ISSUE TITLE
HttpEntity.toStrict timed out after x seconds while still waiting for outstanding data 

### ISSUE THREAD

**Issue by PierreKieffer** [akka/akka-http#2981]
I encounter a problem randomly without SSL(sometimes it works without issue), and each time with SSL, and I don't understand why. 
It's a time out during HttpEntity.toStrict. 

```
    extractRequest{payload =>
                 
                  val futureRequestEntity = payload.entity.toStrict(5.seconds).map(_.data.utf8String)
                  val requestEntity = Await.result(futureRequestEntity, 10.seconds)

    ... }
```

I tried to set longer waiting times, but doesn't solve the issue. 

```
    java.util.concurrent.TimeoutException: HttpEntity.toStrict timed out after 5 seconds while still waiting for outstanding data
	at akka.http.impl.util.ToStrict$$anon$1.onTimer(package.scala:138)
```

I need to use extractRequest for my path because I extract the entity and the header further in the code. 

Thank's in advance

**Comment by jrudolph** [comment]
It could mean that the entity just hasn't been received in those 5 seconds. A likely alternative explanation is that your use of `Await` will block a dispatcher thread which can lead to thread starvation if there's enough work so the `Await` here might deadlock the background work receiving data from the network.

If you need access to the request entity as string, you can use

```scala
entity(as[String]) { requestEntity =>

}
```

instead.

**Comment by PierreKieffer** [comment]
Thank you for this. 
I tried and It works  with entity(as[string]), 
But how can I do if i need to extract the header at the same time as the entity ? 

The only way I found is the use of Await to get the entity, and you're right, I think it leads to  thread starvation. 

`extractRequest{payload =>
                  val headValue = payload.headers.filter(x => x.is("context")).map(x => x.value()).head
                  val futureRequestEntity = payload.entity.toStrict(5.seconds).map(_.data.utf8String)
                  val requestEntity = Await.result(futureRequestEntity, 10.seconds)
                }`

**Comment by jrudolph** [comment]
You can nest those directives:

```scala
entity(as[String]) { requestEntity =>
  headerValueByName("context") { contextHeaderValueAsString =>
    ...
  }
}
```
