### ISSUE TITLE
Is building with Akka as a source dependency still useful?

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#2994]
There is some machinery to make developing Akka HTTP against Akka as a source dependency possible.

Now that the split between Akka and Akka HTTP has stabilized, and Akka is publishing snapshot artifacts to test against (which is also simple, though somewhat slow, locally), perhaps we should remove this machinery?

**Comment by jrudolph** [comment]
If we can find a way to consume the published snapshots, then I'm for it. If we just publish them locally, we still occur a big part of the cost (though maybe not all of the complexity).
