### ISSUE TITLE
BasicHttpCredentials can't deal with no password

### ISSUE THREAD

**Issue by elm-** [akka/akka-http#302]
While working on the Zendesk API I noticed that it is not possible to use the BasicHttpCredentials without password. Some APIs use only a username that encodes the username / token instead of splitting it up into username and password (besides Zendesk the Google Docker Registry has a similar approach I think).

The difference is that the ":" between username and empty password is not part of the encoded string.

My suggestion therefore is to either create a new header or extend the BasicHttpCredentials to support this case.

```
BasicHttpCredentials(username: String, password: Option[String])
```

I created my own type for now to reflect it (BasicHttpUserCredential(username: String)) that handles this.

Does it make sense to work something into the HTTP model to support this?

**Comment by jrudolph** [comment]
It seems that [RFC 2617](https://tools.ietf.org/html/rfc2617) defines the grammar like this:

```
      basic-credentials = base64-user-pass
      base64-user-pass  = <base64 [4] encoding of user-pass,
                       except not limited to 76 char/line>
      user-pass   = userid ":" password
```

which wouldn't allow such a usage. So, for this non-standard usage I'd suggest to use workarounds until there's more convincing arguments to change parsing here where it could have security-related consequences.

So, if the workaround works for you so far, I'd like to close this as "won't fix" for now.

**Comment by elm-** [comment]
I did a check of this case a bit more under this RFC and other libraries have similar discussions if it should be included or not. e.g. [1]. According to the RFC it's quite clear, so I think the behaviour makes sense. I'll raise an issue with the API implementor how they see this, looks like they should be able to deal with the empty password and encoded ":".
