### ISSUE TITLE
Please document how to generate/report server-side WebSocket errors

### ISSUE THREAD

**Issue by leo-da** [akka/akka-http#3023]
Akka HTTP [Server WebSocket Support](https://doc.akka.io/docs/akka-http/current/server-side/websocket-support.html) documentation does not explain how to generate/report server-side errors that client can receive and process.

Please add an example and document how to generate an error that can be received on the client-side with `ws.on("error", ...)`:

```javascript
const ws = new WebSocket("ws://localhost:...", [subprotocol])

ws.on("open", function open() {
  ws.send(`...`)
})

ws.on("error", function incoming(error) {
  console.log(`error: ${JSON.stringify(error)}`)
})
```

**Comment by leo-da** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/error_event

> The error handler is fired when a connection with a WebSocket has been closed due to an error (some data couldn't be sent for example).

Given `akka.http.scaladsl.model.ws.UpgradeToWebSocket`, how can I close the connection with an error that gets propagated to the client?

**Comment by leo-da** [comment]
See [1.4. Closing Handshake](https://tools.ietf.org/html/rfc6455#section-1.4) and [7.1.6. The WebSocket Connection Close Reason](https://tools.ietf.org/html/rfc6455#section-7.1.6)

**Comment by jrudolph** [comment]
Hi @leo-da, thanks for opening the issue. There is currently no API to control error codes and reasons. We use #2458 to track adding such an API. I'm going to close this one as a duplicate but feel free to continue the discussion over there.
