### ISSUE TITLE
FrameEvent should expose flags: Byte and take ByteFlags

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#305]
i wrote it like that in artery, so maybe just FYI https://github.com/akka/akka/pull/21378/files#diff-82dac4787416496563ec7e2e6c3fe8ecR72
usage https://github.com/akka/akka/pull/21378/files#diff-82dac4787416496563ec7e2e6c3fe8ecR414

This allows for better packing of the values (less booleans in each case class) while keeping typesafety

**Comment by jrudolph** [comment]
Closing as done even if it was finally implemented a bit differently: parsing/rendering uses ByteFlag but actual classes use Booleans for now.
