### ISSUE TITLE
Make sure to read the response entity body or call `discardBytes()` on it

### ISSUE THREAD

**Issue by robstoll** [akka/akka-http#3050]
I get the following error:
```
Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. POST
```
I am using `Http.singleRequest(...).map(response => response.discardEntityBytes())` but the warning shows up nonetheless. I see that there is a difference in the warning and my implementation. I use `discardEntityBytes` and the warning suggest `discardBytes()`. However, discardBytes() does not exist on HttpResponse. 

*Edit:* I spotted the error on my side. Thus the remaining issue here is that the warning should most likely be updated.

**Comment by jrudolph** [comment]
Thanks for the report @robstoll and sorry for not getting to it any sooner.

`.discardEntityBytes()` is a shortcut for `.entity.discardBytes()`, the error message is referring to the entity so it seems to be correct. Do you have a suggestion how to make it clearer?

**Comment by robstoll** [comment]
I see, how about 
```
Response entity was not subscribed after 1 second. Make sure to read the response `entity` body or call `entity.discardBytes()`
```

**Comment by robstoll** [comment]
Or
```
Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` (`discardEntityBytes()` if you deal with a `HttpResponse` directly)
```

**Comment by jrudolph** [comment]
Yes, would make sense, can you open a PR?

**Comment by robstoll** [comment]
I can, which one do you prefer?

**Comment by jrudolph** [comment]
Maybe a mixture of both showing both `entity.discardBytes` and `response.discardEntityBytes`.
