### ISSUE TITLE
Update docs about new actor API use

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#3073]
eg. https://doc.akka.io/docs/akka-http/current/routing-dsl/index.html#interaction-with-akka-typed

**Comment by jrudolph** [comment]
#3077 was merged, anything else needed?

**Comment by ennru** [comment]
Eg. #2664 is part of this.

**Comment by raboof** [comment]
#2664 is closed via #3078. Anything else?

**Comment by ennru** [comment]
Eg. https://doc.akka.io//docs/akka-http/snapshot/introduction.html#routing-dsl-for-http-servers could show the new actors API.
But it requires #3223 to go in first.

**Comment by ennru** [comment]
I believe we've covered this. Closing.
