### ISSUE TITLE
Routing DSL: Parameter enhancement `.*` clashes with `predef.StringOps`

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#3081]
To enable the `"parameter".*` notation to capture a list of values for an URL parameter, the `ToNameReceptacleEnhancements` contains an implicit conversion of `String` to `NameReceptacle[String]`.

This implicit is ambiguous with `Predef`s `augmentString` which adds the `*` (times) method on Strings:

```
 found   : String("city")
 required: ?{def *: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method augmentString in object Predef of type (x: String)scala.collection.immutable.StringOps
 and method _string2NR in trait ToNameReceptacleEnhancements of type (string: String)akka.http.scaladsl.common.NameReceptacle[String]
 are possible conversion functions from String("city") to ?{def *: ?}
      parameters(("color", "city".*)) { (color, cities) =>
```

The conversion works fine as long as Scala symbols are used, which is what the docs show.

References #2738, #3079

**Comment by jrudolph** [comment]
Good catch, interesting that no one noticed yet. I guess using `.*` is somewhat obscure anyway.
