### ISSUE TITLE
One consumerActor per Websocket connection

### ISSUE THREAD

**Issue by youenough** [akka/akka-http#3116]
```kotlin
    /** actorRef need a actor ref */
    val actorSink = Sink.actorRef(consumerActor, ...)
    val flow = Flow.fromSinkAndSourceMat(actorSink, actorSource) { sinkMat, sourceMat ->
          // ......
          NotUsed.getInstance()
    }
    Directives.handleWebSocketMessages(flow)
```
I use fromSinkAndSourceMat to create a flow handle websocket message. If the consumerActor is the only one ( single actor instance ) doing the actual processing with messages, managing connects/disconnects and acting like a router for sockets which may be the bottleneck for this design as the messages are always processed sequentially for an actor. I doubt if the sample was meant for scalability but rather a simple demonstration for websockets.

How to create new consumerActor when new websocket connect?
create actor need ActorContext, But in the Doc:

ActorContext Thread Safety
* Many of the methods in ActorContext are not thread-safe and
* Must not be accessed by threads from scala.concurrent.Future callbacks
* Must not be shared between several actor instances
* Must only be used in the ordinary actor message processing thread

**Comment by raboof** [comment]
We tend to use the github issues only for bugs and features, so you might have more luck at https://discuss.akka.io .

Depending on the rest of your progra, `system.actorOf` might work for you?

**Comment by youenough** [comment]
@raboof 
Sorry about that. And thanks for reply.

I use akka typed. I found some info about system.actorOf from the outside on typed ActorSystem with custom user guardian:
[Stream materialization and custom guardian in typed](https://github.com/akka/akka/issues/24298)

Thanks again for your reply. I will try other ways
