### ISSUE TITLE
Example in docs uses deprecated call

### ISSUE THREAD

**Issue by dorians** [akka/akka-http#3128]
When compiling [the first example](https://github.com/akka/akka-http/blob/v10.1.11/docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala#L318-L348) from Akka HTTP docs I got warning that `ActorMaterializer` is deprecated.

Akka HTTP version: 10.1.11
Akka stream version: 2.6.4

**Comment by raboof** [comment]
Thanks for the heads-up!

Indeed while they should work with Akka 2.6, the docs are currently still rather 2.5-centric.

We're intending to fix this in Akka HTTP 10.2.0 (with #2996 and others). You can see the new version of the example at https://github.com/akka/akka-http/blob/master/docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala#L309 , though you likely need a development snapshot of Akka HTTP for it to work like that.

In the mean time you could replace `ActorMaterializer` with `SystemMaterializer(system).materializer` to get rid of the deprecation warning.

**Comment by dorians** [comment]
Cool, thanks a lot for a replacement code!
