### ISSUE TITLE
HTTP 2 travis compilation fails on master

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#3135]

**Comment by raboof** [comment]
ah, seems like it's a matter of akka-http using a version of jdk8 that is no longer supported by HTTP 10.2.0 since 94ad70d145831c354d03963c29c14c80d1a86a5a

**Comment by johanandren** [comment]
Also non javadoc on JDK 11: https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/120/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-http-docs/425/console

**Comment by raboof** [comment]
> https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/120/consoleFull

I suspect this is due to jdk11 needing to be upgraded on `johannes`, since this version of jdk11 does not expose the backported API when running with `-release 8`

> https://jenkins.akka.io:8498/job/akka-http-docs/425/console

This is due to jdk8 needing to be upgraded on the moxie servers. This will make other builds fail (like akka-grpc because of https://github.com/akka/akka-grpc/issues/946), but I don't think that should hold up the upgrade.

**Comment by jrudolph** [comment]
> > [jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/120/consoleFull](https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/120/consoleFull)
> 
> I suspect this is due to jdk11 needing to be upgraded on `johannes`, since this version of jdk11 does not expose the backported API when running with `-release 8`

Do you know if there is such an JDK 11 version yet?

**Comment by jrudolph** [comment]
http://hg.openjdk.java.net/jdk-updates/jdk11u/file/d37f3b2d0da9/make/data/symbols/java.base-8.sym.txt doesn't seem to have been changed recently.

**Comment by jrudolph** [comment]
I guess the simplest solution would be to go back to the reflective version for now. I'll PR.

**Comment by ennru** [comment]
Refective access merged in #3150

**Comment by jrudolph** [comment]
akka-http-nightly and akka-http-docs are green again.
