### ISSUE TITLE
Excessive logging in 10.2.0-M1 at INFO level

### ISSUE THREAD

**Issue by alexmnyc** [akka/akka-http#3147]
INFO [c.g.m.a.AkkaHttpClient$] [] - Try to parse content type from application/x-amz-cbor-1.1

**Comment by jrudolph** [comment]
This doesn't seem to come from akka-http itself? What is this `c.g.n.a.AkkaHttpClient` class that is referenced in the log line?

**Comment by alexmnyc** [comment]
It seems like it is coming from Alpakka 2.0. More explicitly, from
```
com.lightbend.akka:akka-stream-alpakka-kinesis_2.12:2.0.0
|    +--- org.scala-lang:scala-library:2.12.10 -> 2.12.11
|    +--- com.github.matsluni:aws-spi-akka-http_2.12:0.0.8
```

**Comment by raboof** [comment]
> I logged an issue there matsluni/aws-spi-akka-http#52 as well

That seems right, let's close it here - thanks for the follow-up!
