### ISSUE TITLE
Failed: Multiple ClientServerSpec tests fail in JDK 11

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3159]
https://jenkins.akka.io:8498/job/akka-http-nightly/126/

**Comment by jrudolph** [comment]
Probably caused by #3151

**Comment by jrudolph** [comment]
This seems to be a genuine TLS stage leak (at least until the idle timeout kicks in).

https://jenkins.akka.io:8498/job/akka-http-nightly/126/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%2011/consoleFull

It seems that `closeTransport = false` in this line prevents a shutdown of the TLS stage in JDK 11:

https://github.com/akka/akka/blob/9a1d5191b96c21b135bd18687132b180290c943e/akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala#L302

I wonder if that's related to other JDK 11 issues like the one mentioned in #2614.

For now it might be fixed by setting down the idle timeout.

**Comment by jrudolph** [comment]
> I wonder if that's related to other JDK 11 issues like the one mentioned in #2614.

Interesting enough it seems the failing test case is testing the opposite behavior (client HTTPS, server HTTP)as the one observed in #2614 (client HTTP, server HTTPS).

The reason it now popped up is that before #3151 `ClientServerSpec` created another materializer (through `AkkaSpecWithMaterializer`) that was checked using `assertAllStagesStopped` than the `SystemMaterializer` which is now used for most stuff accessed through `Http()`.

**Comment by ennru** [comment]
We need an issue for the "real" problem.

**Comment by jrudolph** [comment]
Filed another issue in #3286. The behavior is actually fixed in combination with Akka 2.6.6 and not-yet-released 2.5.32.
