### ISSUE TITLE
Suggested documentation improvements after migration of docs to Paradox

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#318]
A list of documentation improvements as mentioned in #313 which should be addressed before the first release.

- [ ] @@snip for most scala directives do not work and this PR:
   -  `git grep FIXME@@snip | wc -l` shows 154
   - Might involve copy/pasting or use the `includecode2.py` script to extract API elements until #11 is completed

- [x] Cross-references to akka/akka documentation
   - `git grep 'FIXME: unresolved link reference' | wc -l` shows 12

- [x] Replace `@github@` variables
   - Paradox does not replace vars in links, e.g. `[Server.scala](@github@/akka-http/.../Server.scala)`.

- [x] Replace `@version@` variables with `$project.version$`

- [x] Use tabbed @@snip markup for configuration pages listing `reference.conf`
    ```
    akka-http-core
    : @@snip [reference.conf](...)
    ```

**Comment by jonas** [comment]
PR to propose an external link directive in Paradox: lightbend/paradox#27
This could both help fix links to GitHub sources and cross-references to akka.io documentation.

**Comment by ktoso** [comment]
Only "fancy snip" remaining
