### ISSUE TITLE
Is there any way to customize 501 responses to be 400's?

### ISSUE THREAD

**Issue by alexmnyc** [akka/akka-http#3191]
AWS ALB 5xx alarms get polluted when software vulenrability scanners throw bad requests and trigger false positive alarms. I am looking to override that behavior

i.e.

```
curl -X REMOTE -D - http://server
HTTP/2 501 
```

I've tried adding ParserException to the exceptionhandler but it never gets invoked to be able to override the response.

**Comment by jrudolph** [comment]
There currently is no way to override this behavior (which, incidentally, is according [to the spec](https://tools.ietf.org/html/rfc7231#section-4).

That said, as also observed in #1622, this assignment of returning a 5xx server error code for unsupported methods seems questionable.

There was a recent discussion about customizing parser error behavior but just now I cannot find it.

**Comment by alexmnyc** [comment]
That is unfortunate. One would think the exception should bubble up to the exception handler and let the end user decide what to do with it. I understand that the default behavior is correct but it should be customizable

**Comment by alexmnyc** [comment]
Perhaps there should be a way to have a ParserExceptionHandler and seal a route with it similarly to what we do for for exceptionhandler

**Comment by jrudolph** [comment]
Turns out we did provide a way to override that just recently in #3049. So starting with the upcoming 10.2.0 you will be able to do just that.

Can you try out if the solution in 10.2.0-M1 would be good enough for you?

(Btw. the original issue where this capability was raised was in #210).

**Comment by alexmnyc** [comment]
That is great news. Thank you!

**Comment by jrudolph** [comment]
Closing for now, let us know if something is missing the 10.2.0 solution.

**Comment by alexmnyc** [comment]
Thank you!
