### ISSUE TITLE
ServerSettings NPE exception when using Http.bindAndHandle()

### ISSUE THREAD

**Issue by Christewart** [akka/akka-http#3221]
This is happening when using defaults 
```scala
    
val serverSettings = ServerSettings(ActorSystem("my-system"), ConfigFactory.empty()))

```

Stack trace: 
>[info] java.lang.NullPointerException: null
[info]  at akka.http.scaladsl.model.HttpEntity$Strict.isKnownEmpty(HttpEntity.scala:334)
[info]  at akka.http.scaladsl.model.HttpResponse.<init>(HttpMessage.scala:457)
[info]  at akka.http.scaladsl.model.HttpResponse$.apply(HttpMessage.scala:529)
[info]  at akka.http.impl.settings.ServerSettingsImpl$.terminationDeadlineExceededResponseFrom(ServerSettingsImpl.scala:110)
[info]  at akka.http.impl.settings.ServerSettingsImpl$.fromSubConfig(ServerSettingsImpl.scala:105)
[info]  at akka.http.impl.settings.ServerSettingsImpl$.fromSubConfig(ServerSettingsImpl.scala:61)
[info]  at akka.http.impl.util.SettingsCompanionImpl.apply(SettingsCompanionImpl.scala:51)
[info]  at akka.http.scaladsl.settings.ServerSettings$.apply(ServerSettings.scala:134)
[info]  at akka.http.scaladsl.settings.ServerSettings$.apply(ServerSettings.scala:122)
[info]  at akka.http.scaladsl.settings.SettingsCompanion.apply(SettingsCompanion.scala:19)
[info]  at akka.http.scaladsl.settings.SettingsCompanion.apply$(SettingsCompanion.scala:19)
[info]  at akka.http.scaladsl.settings.ServerSettings$.apply(ServerSettings.scala:122)
[info]  at org.bitcoins.server.Server.start(Server.scala:85)
[info]  at org.bitcoins.server.Main$.$anonfun$startFut$9(Main.scala:109)

This is on akka 2.6.5, back i tried downgrading all the way to 2.6.0 and it still applies. It seems fine on akka 2.5.x

**Comment by raboof** [comment]
Thanks for sharing! It looks like the `data` field of the `HttpEntity.Strict` is null, which is invalid.

On gitter you shared this is from https://github.com/bitcoin-s/bitcoin-s, that might help narrow this down. Are you on master?

**Comment by raboof** [comment]
Since I'm pretty confident this is a problem in the usage of the library and not in Akka HTTP itself, let's close this here and discuss it further in an upstream ticket, at https://discuss.akka.io or elsewhere

**Comment by Christewart** [comment]
It's reproducible here with `appServer/run` in sbt 

https://github.com/Christewart/bitcoin-s-core/commit/dc7e5e7b0f41db2836557ec54f932b2a2fbab99f#diff-bf2179f99ebbeac78b82b72bf890c199R84

**Comment by Christewart** [comment]
So this is where the error occurs exactly: https://github.com/Christewart/bitcoin-s-core/commit/b82c9a37b84f915a5d08fd8a7dc9eecc97e18982#diff-bf2179f99ebbeac78b82b72bf890c199R88

It's when we construct a HttpResponse with a with an empty entity 
```scala
    val response = HttpResponse(status = 503,
      entity = entity)

```

the invariant that fails because of a NPE is baffling to say the least 

```
require(entity.isKnownEmpty || status.allowsEntity, "Responses with this status code must have an empty entity")
  r
```

**Comment by raboof** [comment]
> val serverSettings = ServerSettings(ActorSystem("my-system"), ConfigFactory.empty()))

That can't be right, ServerSettings doesn't have a constructor that takes a system and a configuration?

> It's reproducible here with appServer/run in sbt
> Christewart/bitcoin-s-core@dc7e5e7#diff-bf2179f99ebbeac78b82b72bf890c199R84

Thanks! That doesn't reproduce it for me though:

```
sbt:bitcoin-s> appServer/run
[info] running (fork) org.bitcoins.server.Main
[info] [INFO] [akkaDeadLetter][06/08/2020 09:21:49.633] [bitcoin-s-akka.actor.default-dispatcher-6] [akka://bitcoin-s/user/P2PClient$-1591608109600] Message [akka.io.Tcp$CommandFailed] from Actor[akka://bitcoin-s/system/IO-TCP/selectors/$a/0#-700418540] to Actor[akka://bitcoin-s/user/P2PClient$-1591608109600#273072512] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] 2020-06-08T09:21:55 ERROR [P2P] Failed to connect with peer=Peer(localhost/127.0.0.1:18444) with err=org.bitcoins.rpc.util.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with 100 milliseconds waiting periods
[info] 2020-06-08T09:21:55 ERROR [P2P] Cannot start Neutrino node
[info] org.bitcoins.rpc.util.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with 100 milliseconds waiting periods
[info] at org.bitcoins.node.Node.$anonfun$start$4(Node.scala:123)
```

I guess something needs to be running on port 18444? What?

**Comment by Christewart** [comment]
> java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)

If you are willing to work with me I'll simplify the startup logic to get a minimal reproducible example (on my machine).

**Comment by raboof** [comment]
I noticed you're using GraalVM, does the problem also occur when using AdoptOpenJDK?

**Comment by Christewart** [comment]
I get the same behavior as described above using

> java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**Comment by raboof** [comment]
> I get the same behavior as described above using

Very strange, I don't see the problem with that JDK (or any other I tried). Could you perhaps package up a reproducer as a Dockerfile?

**Comment by raboof** [comment]
Interestingly https://github.com/akka/akka-grpc/issues/1014 has very similar symptoms.

**Comment by jrudolph** [comment]
Here's another case from the past which was in the vicinity but not quite the same: akka/akka-http#1564

**Comment by jrudolph** [comment]
One difference between 2.12 and 2.13 is that object `val`s are instance fields in 2.12 and final static fields in 2.13. But all of that might be a red herring.

**Comment by raboof** [comment]
@Christewart we managed to reproduce the problem in akka/akka-grpc#1014. It turns out to be an upstream Akka problem, which can now be tracked at akka/akka#29244. If you want a short-term workaround, it looks like touching `ByteString.empty` early in your application startup should avoid the issue. Let us know if that indeed does the trick for you as well!

**Comment by Christewart** [comment]
That sounds right to me, we fixed it by doing this early in application startup: https://github.com/bitcoin-s/bitcoin-s/pull/1522/files#diff-84af26f45275ce285f45cf7de3aa559eR34

**Comment by Christewart** [comment]
Thank you for your help @raboof , it seems like things are working on our end now :tada: :tada:

**Comment by jrudolph** [comment]
Great! Akka 2.6.7 should have the fix.
