### ISSUE TITLE
HTTP/2 client: review rendering parsing

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3229]
And see if things can be DRY'd with server implementations

**Comment by johanandren** [comment]
Hmm, can't see any obvious repetition in the rendering and the parsing. Am I missing something?

**Comment by jrudolph** [comment]
> Hmm, can't see any obvious repetition in the rendering and the parsing. Am I missing something?

Rendering has somewhat duplicated logic wrt `content-length` and substream creation. Maybe that was the main thing I had in mind.

**Comment by ignasi35** [comment]
@jrudolph, with #3520 merged is there anything else pending for this issue?

**Comment by jrudolph** [comment]
These four lines could still be dry'd up between client and server:

```
      addContentHeaders(headerPairs, response.entity)
      renderHeaders(response.headers, headerPairs, serverHeader, log, isServer = true)

      val headers = ParsedHeadersFrame(streamId, endStream = response.entity.isKnownEmpty, headerPairs.result(), None)
      substreamFor(response.entity, headers)
```

but it's somewhat low priority do go this step as well.

**Comment by ignasi35** [comment]
> These four lines could still be dry'd up between client and server:

Done in #3657 :-)
