### ISSUE TITLE
`discardEntityBytes` should allow `ClassicActorSystemProvider`

### ISSUE THREAD

**Issue by ennru** [akka/akka-http#3241]
`discardEntityBytes` should be usable without a materializer and allow usage with the system's materializer instead.

https://github.com/akka/akka-http/blob/6b79bfec6e536da20fa6fb3d8e15a9aa75a35540/akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java#L100

**Comment by jrudolph** [comment]
Just as a clarification: this is for the java-side where there is no implicit doing that conversion from `ClassicActorSystemProvider` to `Materializer`.

**Comment by jrudolph** [comment]
Fixed in #3361
