### ISSUE TITLE
Downstream connection failure is not propagated into WebSockets flow

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#3247]
Even when using Akka 2.6, when a request is handled using a websocket flow, and the connection is aborted by the outgoing TCP connection, this failure is not propagated to the websocket flows' `watchTermination`.

I suspect this is because the `ProtocolSwitchStage` completes the stage when downstream finishes,  (https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L602), without taking into account any cancellation reason.

Setting a cancellation strategy of `AfterDelay` (to make sure we pick up the upstream failure before handling the downstream cancellation) didn't appear to help, but perhaps I added it in the wrong way.

**Comment by jrudolph** [comment]
Is that about the server or the client side?

**Comment by raboof** [comment]
This is about the server side

**Comment by jrudolph** [comment]
Seems this is fixed in some regards in 10.2.0-M1. I guess the reason is that we only backported the client-side cancellation race fixes to 10.1.12 but not the server-side fix which came later and also fixed it on the server-side.

Also we still need a fix for the ProtocolSwitchStage to materialize the inner flow with the cancellation delay enabled, also for 10.2.x.

**Comment by jrudolph** [comment]
@raboof this should be fixed in master and with #3258 also in release-10.1. Could you convert your test repro into a test to make sure it's really fixed?

**Comment by raboof** [comment]
> and with #3258 also in release-10.1

Yes, verified

> Could you convert your test repro into a test to make sure it's really fixed?

I'll have a look.

**Comment by jrudolph** [comment]
Test added in #3276.

**Comment by jrudolph** [comment]
10.1 backport of test in #3288.
