### ISSUE TITLE
Http2ServerSpec.The Http/2 server implementation should support stream for request entity data should close the stream when we receive a RST after we have half-closed ourselves as well

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3264]
https://jenkins.akka.io:8498/job/akka-http-nightly/166/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%2011/

Note: this is a detailed failure report. See [this](https://github.com/akka/akka-http/issues?q=is%3Aopen+label%3Afailed+Http2ServerSpec) other failures in `Http2ServerSpec` 

```
sbt.ForkMain$ForkError: java.lang.AssertionError: received 1 excess messages on WarningFilter(None,Left(),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:121)
	at akka.http.impl.engine.http2.Http2ServerSpec$$anon$12.<init>(Http2ServerSpec.scala:317)
	at akka.http.impl.engine.http2.Http2ServerSpec.$anonfun$new$17(Http2ServerSpec.scala:308)
```

**Comment by jrudolph** [comment]
Failed three times in a single nightly matrix build here: 

https://jenkins.akka.io:8498/job/akka-http-nightly/169/testReport/

Unfortunately, the warning isn't shown in the error message. But likely it is some illegal state in `Http2StreamHandling`. I've seen a few of those, maybe related to the recent Http2 client side merge. If that's the case, it's actually a bug.

**Comment by jrudolph** [comment]
Reproduces very reliably for me, it's:

```
| [WARN] [06/22/2020 11:23:38.306] [Http2ServerSpec-akka.actor.default-dispatcher-2] [Http2ServerDemux(akka://Http2ServerSpec)] handleOutgoingCreated received unexpectedly in state Open. This indicates a bug in Akka HTTP, please report it to the issue tracker.
```
