### ISSUE TITLE
UpgradeToWebSocket as Attribute

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#3278]
UpgradeToWebSocket is a 'virtual' header, perhaps we should start introducing an attribute for this and deprecate the header?

**Comment by jrudolph** [comment]
> UpgradeToWebSocket is a 'virtual' header, perhaps we should start introducing an attribute for this and deprecate the header?

Yes, agreed, would be nice, but not sure if it should block 10.2.0. In any case, we could already do the deprecation without the alternative because it's public API but mostly hidden higher-level abstractions.

**Comment by jrudolph** [comment]
Deprecation done in #3280. Leaving open until attribute is done.
