### ISSUE TITLE
Test compatibility of 10.2.0 with related projects

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3290]
Even if those projects do not yet update to 10.2.0 themselves they should work out-of-the-box if a project pulls up dependencies.

 * [ ] akka-management
 * [ ] alpakka (The [CRON builds](https://travis-ci.com/github/akka/alpakka/builds) use Akka 2.6 and HTTP RC1)
 * [x] play (at least, the latest version) (Runs a scheduled build on Akka and Akka HTTP snapshots)
 * [ ] telemetry

**Comment by ennru** [comment]
- [ ] Create a 10.2 branch in https://github.com/akka/akka-http-quickstart-scala.g8
- [ ] Create a 10.2 branch in https://github.com/akka/akka-http-quickstart-java.g8

**Comment by ennru** [comment]
- [ ] Akka gRPC https://github.com/akka/akka-grpc/pull/937 (hits some deprecations for `bindAndHandleAsync`)

**Comment by raboof** [comment]
To test akka-management, perhaps run https://github.com/akka/akka-sample-cluster-kubernetes-scala with updated dependencies?

**Comment by jrudolph** [comment]
> To test akka-management, running [akka/akka-sample-cluster-kubernetes-scala](https://github.com/akka/akka-sample-cluster-kubernetes-scala) with updated dependencies: [travis-ci.com/github/akka/akka-sample-cluster-kubernetes-scala/builds/175535368](https://travis-ci.com/github/akka/akka-sample-cluster-kubernetes-scala/builds/175535368)

Done and working here: https://travis-ci.com/github/akka/akka-sample-cluster-kubernetes-scala/builds/178400077

**Comment by jrudolph** [comment]
Created an update for the scala quickstart here: https://github.com/akka/akka-http-quickstart-scala.g8/pull/76

**Comment by jrudolph** [comment]
Should we keep this open?

**Comment by raboof** [comment]
I think this was here to do pre-release tests, if we find any issues now after the release we can open specific tickets for those
