### ISSUE TITLE
Weird copyright date in docs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3304]
![image](https://user-images.githubusercontent.com/9868/85795798-2af5eb80-b739-11ea-957e-9a7734105daa.png)

**Comment by jrudolph** [comment]
Seems to be a recent regression, 10.1.11 and 10.2.0-M1 still showed it correctly.

**Comment by raboof** [comment]
This was a problem on my system. I've fixed it here, but ofc the real fix is to publish the docs from CI.
