### ISSUE TITLE
http server stops responding requests

### ISSUE THREAD

**Issue by javierpajaro** [akka/akka-http#3322]
I am using: 

akka-http_2.12 
10.1.5
akka-stream_2.12
2.5.26
openjdk version "1.8.0_252"

akka-http is configured with:

```
http.server.max-connections = 100     
http.server.backlog = 100  
http.server.pipelining-limit = 1
http.caching.lfu-cache.max-capacity = 100
```

After a while, the http simply stops processing requests. CPU load, GC activity, memory, etc. is ok.

In Main the http server is created in the following way:

```java
     	final ActorMaterializer lMaterializer = ActorMaterializer.create(lSystem);
		final ConnectHttp lConnection = ConnectHttp.toHost(AppContext.getConfig().getHttpHost()
														 , AppContext.getConfig().getHttpPort());
		final Flow<HttpRequest, HttpResponse, NotUsed> lRouteFlow = new HttpConsumer(lSystem.startTime())
																					.routes()
																					.flow(lSystem, lMaterializer);

		Http.get(lSystem).bindAndHandle(lRouteFlow, lConnection, lMaterializer);
		AkkaManagement.get(lSystem).start();`
```

Requests are handled in 

[HttpConsumer.txt](https://github.com/akka/akka-http/files/4853723/HttpConsumer.txt)

Please help, I am getting crazy :) trying to find a solution.

**Comment by jrudolph** [comment]
Hi @javierpajaro,

that seems more like a question suitable for the forums at `https://discuss.akka.io`.

I'd first try updating to the latest versions of Akka and Akka-Http, e.g. 10.1.12 and 2.5.31 and see if the same happens there as well. Next step would be to use `jstack <pid>` to see if any threads are doing anything unexpected when the issue occurs. Then you could also check how many connections already are established to the server (e.g. with `netstat` or `ss`).
