### ISSUE TITLE
Docs publish failed

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#3333]
```
[error] Expected ';'
[error] deployRsync akkarepo@gustav.akka.io
[error]  
```

https://jenkins.akka.io:8498/job/akka-http-docs/454/console

**Comment by chbatey** [comment]
Looks like it is this: https://github.com/akka/akka-http/commit/f3fe3481a7bdc2645f9cbc969e629565df5e0583

I'll change the Jenkins job to publishRsync instead

**Comment by chbatey** [comment]
@raboof do we need the jenkins job still or does travis do it all now?

**Comment by chbatey** [comment]
Closing as the build passes now, but maybe we want to delete the build

**Comment by raboof** [comment]
> @raboof do we need the jenkins job still or does travis do it all now?

Since #3328 (which seems to work, https://travis-ci.org/github/akka/akka-http/jobs/704209011) I think we can retire the jenkins job. I'll just disable it for now, to be on the safe side.
