### ISSUE TITLE
Add post-render, regex-based request / response modification

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka-http#334]
Hi folks,

I've been wrestling with a bug in IIS (see https://groups.google.com/d/msg/akka-user/7iW5-HlshZk/S75Wgxg_AwAJ).  It seems that I'm going to have to deal with the problem myself, because either IIS can't be fixed or the guys I'm dealing with aren't willing to try.

I've used Akka to build a Reverse HTTP Proxy and, while Akka is doing nothing wrong, it is rendering an HTTP request that IIS fails to parse properly.  Yes, it's their fault, but this has become my problem, and I need to implement the solution.

As such, I've thrown together a simple (and highly inelegant, at the moment) mechanism for being able to rewrite the `Content-Type` header after rendering, as this is the header that is currently causing me problems.  See the single test case for a specific example.

I'd very much appreciate someone taking a look at it and critiquing the approach.  I tried a number of ways of shoehorning this feature into the code, implicits on the render method, a template-method pattern for wiring in a user-defined transformer and they were all pretty cumbersome.  This was the "simplest" method I could find for the moment but if someone knows of a better way, well... that's why I'm asking :)

Does anyone think the idea has any possibility of being considered as a PR?  Such a feature (although not necessarily using my current design) is actually quite vital to my success, so I need to have it regardless, but I'd much rather not keep a perpetual fork of Akka, and I'd also like to add to the toolkit, if possible.

I just threw this together today so it's not exactly up to the Akka coding guidelines, but will work toward that as the days progress and eventually present a PR.

https://github.com/derekwyatt/akka/commit/1b279bc426be352a1d204e45e855451acaac58e3

**Comment by jrudolph** [comment]
I understand that such a hook would nice to have sometimes but I'm not sure it would warrant the extra complexity right now. As we identifies the underlying issue let's focus on fixing that one.

Closing for now...

**Comment by derekwyatt** [comment]
Understood. The potential for this feature to empower the operations team to, for lack of a better phrase, not bug me at 2am in order to provide a patch to work around some critical issue, gives me the same warm feeling as a glass of single malt.

So, I may bug you again someday :)
