### ISSUE TITLE
Make SyntheticHeader public

### ISSUE THREAD

**Issue by chetanmeh** [akka/akka-http#3349]
In our project we need to log details related to request and response as part of access log. Such logs should also include the header details. While dumping all request header the logs also include the `timeout-access` header which is a synthetic header used internally by Akka HTTP.

Currently there is no easy way to distinguish which header is a user provided one and which one is generated by Akka HTTP. One way would be to make `akka.http.scaladsl.model.headers.SyntheticHeader` trait public. Then we can easily filter out such synthetic header via type check.

**Comment by raboof** [comment]
Hmm, I'm not sure we want to expose this, since we're (slowly) moving away from synthetic headers and using 'Attributes' instead.

Perhaps a compromise might be to remove the `private` modified but add an `@InternalApi` so you can 'peek' but we don't promise keeping it intact going forward?

**Comment by chetanmeh** [comment]
> Perhaps a compromise might be to remove the private modified but add an @InternalApi so you can 'peek' but we don't promise keeping it intact going forward

+1. That would work for me in the interim

**Comment by chetanmeh** [comment]
> using 'Attributes' instead

Any reference to this Attribute support?

**Comment by raboof** [comment]
#1500 / https://doc.akka.io/docs/akka-http/snapshot/common/http-model.html#attributes

**Comment by jrudolph** [comment]
Let's close this as attributes seem like the way forward.
