### ISSUE TITLE
[failed] BindException in ClientServerSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3372]
(looks like #2953) 

Twice in seldom jobs of a matrix in single build:

https://jenkins.akka.io:8498/job/akka-http-nightly/197/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.11,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_log_materialization_errors_in__bindAndHandle__which_stop_stages_on_failure/

and

https://jenkins.akka.io:8498/job/akka-http-nightly/197/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_properly_complete_a_chunked_request_response_cycle/

**Comment by ignasi35** [comment]
It happened again (twice in separate jobs of the same build matrix)

https://jenkins.akka.io:8498/job/akka-http-nightly/198/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.12.11,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_prevent_more_than_the_configured_number_of_max_connections_with_bindAndHandle/

and

https://jenkins.akka.io:8498/job/akka-http-nightly/198/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_complete_a_request_response_when_request_has__Connection__close__set/

**Comment by jrudolph** [comment]
Fixed in the meantime, see #3460 and a later change to go back to the Akka version.
