### ISSUE TITLE
Release failed while publishing docs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3392]
https://travis-ci.org/github/akka/akka-http/jobs/711079586

```
$ eval "$(ssh-agent -s)" && echo $SCP_SECRET | base64 -d > /tmp/id_rsa && chmod 600 /tmp/id_rsa && ssh-add /tmp/id_rsa && sbt -jvm-opts .jvmopts-travis -Dakka.genjavadoc.enabled=true publishRsync

Agent pid 5427

Enter passphrase for /tmp/id_rsa: 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by raboof** [comment]
Huh, I think we should just populate SCP_SECRET with a key that doesn't require a password.

**Comment by jrudolph** [comment]
Done manually this time.

**Comment by jrudolph** [comment]
Would be nice if you could look into that when you're back, @raboof.

**Comment by raboof** [comment]
Weird - this is the same configuration that publishes the 'snapshot' docs to https://doc.akka.io/docs/akka-http/snapshot/ - so perhaps some kind of transient error?

https://travis-ci.org/github/akka/akka-http/jobs/731256312#L240

**Comment by jrudolph** [comment]
I think we partly figured it out at some point in time. The problem was somehow that the SCP_SECRET key was only added to master builds but is missing for the tag builds or something like that.

**Comment by raboof** [comment]
Ah of course. Uploaded the secret available to all branches, tested that it still works for master, hopefully that also does the trick for the next release.
