### ISSUE TITLE
nightly builds fail with scalafmt-related sbt errors

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#3395]
e.g. https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/962/console

This is failing since https://github.com/akka/akka/pull/29378 because we're using source references but the set of sbt plugins in akka is different from akka-http.

**Comment by jrudolph** [comment]
This cannot be the full story as the nightly builds are still working and only release-10.1 is affected?

**Comment by jrudolph** [comment]
We moved to use snapshots for nightlies for akka-http master but not for release-10.1 so far.

**Comment by jrudolph** [comment]
Fixed in #3401. Test builds not quite finished but looking good in https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-release-10.1/968/.
