### ISSUE TITLE
Port FrameOutHandler and FrameEventRenderer as graph stages from `akka/akka`

### ISSUE THREAD

**Issue by gosubpl** [akka/akka-http#341]
This story is for porting PR #21360 from `akka/akka` to `akka/akka-http`. Third time is the charm!

**Comment by gosubpl** [comment]
Please see https://github.com/akka/akka/issues/19361 and https://github.com/akka/akka/pull/21360 .

**Comment by ktoso** [comment]
We'll see it merged this time around :)
Thanks a lot!

**Comment by gosubpl** [comment]
This is merged now, closing.
