### ISSUE TITLE
Allow customizing materializer with ServerBuilder API

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3410]
The ServerBuilder API currently doesn't support a custom materializer but will always use the SystemMaterializer. Would be good to retain that functionality for now.

When doing that, also think about updating the scalafix rule.

**Comment by ennru** [comment]
Duplicate of #3388.

**Comment by jrudolph** [comment]
Fixed in #3414.

**Comment by jrudolph** [comment]
> Duplicate of #3388.

Short-term memory seems to be gone...
