### ISSUE TITLE
Failed: org.pegdown.ParsingTimeoutException while building paradox documentation on travis

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3429]
Often happens on master builds.

E.g. here: https://travis-ci.org/github/akka/akka-http/jobs/716500980

This might just be a too tight timeout. I've seen it at least twice today.

**Comment by jrudolph** [comment]
Still happening afterwards: https://travis-ci.org/github/akka/akka-http/jobs/724154843

**Comment by jrudolph** [comment]
This time it was for "custom-directives.md".

In #3430 the timeout was changed to 10 seconds and I think that's per file (?) which seems reasonable. I think we haven't understood why the processing times would be so long or so volatile.

**Comment by jrudolph** [comment]
path-directives.md

https://travis-ci.org/github/akka/akka-http/jobs/725277631

marshalling.md

https://travis-ci.org/github/akka/akka-http/jobs/725253509

http2.md

https://travis-ci.org/github/akka/akka-http/jobs/725254337

Seems not really correlated to the file so far.

**Comment by jrudolph** [comment]
This still happens regularly. I wonder now if there are just too many things running in parallel when that happens? Or a GC / memory problem?

**Comment by raboof** [comment]
Good question.

What should we do to find out? Enable GC logging and show a stack dump when we see this exception?
