### ISSUE TITLE
Doc: Linked Website "The Magnet Pattern" not available - broken link

### ISSUE THREAD

**Issue by domdorn** [akka/akka-http#3447]
https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/debugging-directives/logRequest.html links to http://spray.io/blog/2012-12-13-the-magnet-pattern/ which is not able to be opened in my current firefox on mac os. 

Essential information about the library should be included in the documentation.
The only way I could access this blog post was through using the google-cache: 
http://webcache.googleusercontent.com/search?q=cache:SmzyAu7YuOgJ:spray.io/blog/2012-12-13-the-magnet-pattern/%3Fsource%3Dpost_page---------------------------+&cd=1&hl=en&ct=clnk&gl=at&client=firefox-b-d

**Comment by raboof** [comment]
hmm, I think we should bring back the spray website :) - @sirthias do you know how/where this is hosted?

**Comment by sirthias** [comment]
Sorry about that, gentlemen, that was my mistake.
An upgrade to Java 11 brought the site down.
Now everything should be running smoothly again...

**Comment by raboof** [comment]
Thanks!
