### ISSUE TITLE
how can I get the post request data with low api?

### ISSUE THREAD

**Issue by Lovecxgood** [akka/akka-http#3451]
hello! 
for some reason  I use akkahttp without route api but lower server api
but I meet  a question with akka-http post request 
I know how to use http get request by your example on your official as follow
(https://doc.akka.io/docs/akka-http/current/server-side/low-level-api.html#streams-and-http)
String name = uri.query().get("name").orElse("Mister X");
but how can i fetch the http post request body and use it,no example on your official and with your api
 Source<ByteString, Object> bytes = request.entity().getDataBytes();
I can only get a Source object  and use it with bytes.runForeach() with a async way;
if any way to acquire the data with a sync way? just like get request??
thank you very much!

**Comment by raboof** [comment]
`entity.toStrict()` might be useful to you, there's an improvement to the docs on the client side coming up in #3446, but perhaps it might be helpful to mention that on that page as well (perhaps near the 'Streaming Request/Response Entities' section?).

The downside of using 'toStrict' instead of streaming asychronously is that it will collect the whole entity in memory, which is not necessarily the case with streams.

**Comment by Lovecxgood** [comment]
aha! thanks for your answer~
I have try your answer in my project, but it  looks like another async way to acquire the request data

it's ok if I use the request data with a actor and return a asyn HttpResponse just like 
```
 @Override
			public CompletionStage<HttpResponse> apply(HttpRequest request) {//return a CompletionStage<HttpResponse>

				if (request.method() == HttpMethods.GET) {//get is ok
					if (request.getUri().path().equals("/")) {
						String name = request.getUri().query().get("name").orElse("Mister X"); // this is a sync way

						CompletionStage<RespCmd> rst1 = null; // interact with a actor with parameter name and return a
																// async HttpResponse;

						return rst1.thenApply((r) -> {
							return HttpResponse.create().withEntity(ContentTypes.TEXT_PLAIN_UTF8, r.toString());
						});
					} else {
						return CompletableFuture.completedStage(NOT_FOUND);
					}
				} else if (request.method() == HttpMethods.POST) {//post 
					CompletionStage<Strict> strictEntity = request.entity().toStrict(20000, system);
					return strictEntity.thenApply((r) -> {
						if (request.getUri().path().equals("/")) {
							String data = r.getData().utf8String();
							CompletionStage<RespCmd> rst1 = null; // interact with a actor with parameter data and
																	// return a async HttpResponse;

							return rst1.thenApply((r2) -> {
								return HttpResponse.create().withEntity(ContentTypes.TEXT_PLAIN_UTF8, r2.toString());
							}); //it's error here 

							//return SUCCESS;  //it's ok here
						} else {
							return NOT_FOUND;
						}
					});
				} else {
					return CompletableFuture.completedStage(NOT_FOUND);
				}
			}
```
so  how can i use post data and interact  with actor then return a  CompletionStage<HttpResponse> correctly?
thank you very much!

**Comment by raboof** [comment]
That is a general `CompletionStage` question - I think this would fit better in a discussion thread on https://discuss.akka.io . (perhaps you want `strictEntity.thenCompose` rather than `strictEntity.thenApply`)

**Comment by Lovecxgood** [comment]
aha! thanks for your answer~
I have try your answer in my project, but it looks like another async way to acquire the request data

it's ok if I use the request data with a actor and return a asyn HttpResponse with get request   
but it's error if I use the request data with a actor and return a asyn HttpResponse with post request  beacuse of the way of the request parameters
 ```
@Override
public CompletionStage<HttpResponse> apply(HttpRequest request) {//return a CompletionStage<HttpResponse>

				if (request.method() == HttpMethods.GET) {//get is ok
					if (request.getUri().path().equals("/")) {
						String name = request.getUri().query().get("name").orElse("Mister X"); // this is a sync way

						CompletionStage<RespCmd> rst1 = null; // interact with a actor with parameter name and return a
																// async HttpResponse;

						return rst1.thenApply((r) -> {
							return HttpResponse.create().withEntity(ContentTypes.TEXT_PLAIN_UTF8, r.toString());
						});
					} else {
						return CompletableFuture.completedStage(NOT_FOUND);
					}
				} else if (request.method() == HttpMethods.POST) {//post 
					CompletionStage<Strict> strictEntity = request.entity().toStrict(20000, system);
					return strictEntity.thenApply((r) -> {
						if (request.getUri().path().equals("/")) {
							String data = r.getData().utf8String();
							CompletionStage<RespCmd> rst1 = null; // interact with a actor with parameter data and
																	// return a async HttpResponse;

							return rst1.thenApply((r2) -> {
								return HttpResponse.create().withEntity(ContentTypes.TEXT_PLAIN_UTF8, r2.toString());
							}); //it's error here 

							//return SUCCESS;  //it's ok here
						} else {
							return NOT_FOUND;
						}
					});
				} else {
					return CompletableFuture.completedStage(NOT_FOUND);
				}
			}
```
so how can i use post data and interact with actor then return a CompletionStage correctly?
thank you very much!

**Comment by Lovecxgood** [comment]
I have solved my problem  with your  suggestions，
Thanks very much!
