### ISSUE TITLE
Parameters with defaults don’t compile

### ISSUE THREAD

**Issue by andyczerwonka** [akka/akka-http#3466]
[x-posted on Akka HTTP discourse](https://discuss.lightbend.com/t/parameters-with-defaults-dont-compile/7125) in case this is just a misunderstanding on my part.

Upgrading Akka HTTP to 10.2.0, I am getting compilation errors using default parameters. The following code using non-defaulted parameters compiles just fine:
```scala
import akka.http.scaladsl.server.Directive
import akka.http.scaladsl.server.Directives._
```

```scala
val page = 'page.as[Int] // <-  NameReceptacle[Int]
val perPage = 'per_page.as[Int] // <-  NameReceptacle[Int]
parameters(page, perPage) // <- Directive[(Int, Int)]
```
but adding default behaviour fails with `Cannot resolve overloaded method 'parameters'`
```scala
val page = 'page.as[Int] ? 1 // <-  NameDefaultReceptacle[Int]
val perPage = 'per_page.as[Int] ? 20 // <-  NameDefaultReceptacle[Int]
parameters(page, perPage) // <- Cannot resolve overloaded method 'parameters'
```
If the migration documentation is missing, could we turn this ticket in a `add documentation` ticket.

**Comment by andyczerwonka** [comment]
This is not a bug. Initially, I have an import problem, and once I corrected it, IntelliJ still highlights this as a problem. Closing.
![image](https://user-images.githubusercontent.com/138898/92390504-3326bb80-f0d8-11ea-9646-0af96eb6ba40.png)

**Comment by raboof** [comment]
:+1: thanks for reporting back!
