### ISSUE TITLE
Square brackets no longer appear to be supported

### ISSUE THREAD

**Issue by huntc** [akka/akka-http#3504]
It appears that query parameters using the ["sparse field set" convention](https://jsonapi.org/format/#fetching-sparse-fieldsets) are no longer permitted when processing query parameters within a route.

For a given URI represented as a `curl` command:

```
curl 'some-host/path?recordingsOffset\[electric-fence-data-up-json\]=79637283602489&recordingsOffset\[gust-speed-data-up-json\]=79637283602454'
```

Our log files report:

```
 WARN  ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '[', expected query-char, pct-encoded or 'EOI' (line 1, column 152)...
```

We have recently upgraded to akka-http `10.2.0` from `10.1.11`, where the latter appeared to tolerate brackets being present. We are using the `parameterSeq` directive for parsing as follows:

```scala
  private def namedQueryParameterMap[A](name: String): Directive1[Map[String, String]] =
    parameterSeq.map { params =>
      val prefix = s"$name["
      val suffix = "]"

      params
        .filter {
          case (key, _) => key.startsWith(prefix) && key.endsWith(suffix)
        }
        .map {
          case (key, value) =>
            key.drop(prefix.length).dropRight(suffix.length) -> value
        }
        .toMap
    }
```

**Comment by huntc** [comment]
It seems that the following configuration for relaxing the parsing fixes things:

```
akka.http {
  parsing {
    uri-parsing-mode = relaxed
  }
}
```

Closing this, as [the RFC](https://tools.ietf.org/html/rfc3986#page-23) does indeed indicate that square brackets are not permitted.

**Comment by jrudolph** [comment]
Indeed, there was a short migration note entry about the change: https://doc.akka.io/docs/akka-http/current/migration-guide/migration-guide-10.2.x.html#strict-query-strings

**Comment by huntc** [comment]
> Indeed, there was a short migration note entry about the change: https://doc.akka.io/docs/akka-http/current/migration-guide/migration-guide-10.2.x.html#strict-query-strings

I probably should have read that. :-) I applied many upgrades to our code base. Lots of catching up! Thanks.
