### ISSUE TITLE
HttpExt.singleRequest() Future fails very late when host was not found or connection was refused

### ISSUE THREAD

**Issue by mirzov** [akka/akka-http#3533]
The issue is present in Akka HTTP 10.2.1 and Akka 2.6.10, but I believe it is not new and has been there for quite some time. Here is a snippet to isolate and showcase the problem:

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.HttpRequest
import com.typesafe.config.ConfigFactory
import scala.concurrent.Await
import scala.concurrent.duration.Duration

object AkkaBugReport {

	def run(): Unit = {
		val uriStr = "http://akka.io:2345/"

		val system = ActorSystem("bug_report", ConfigFactory.empty())

		val startTime = System.currentTimeMillis()

		println(s"Sending single HTTP GET request to $uriStr ...")
		val fut = Http(system).singleRequest(HttpRequest(uri = uriStr))

		val resp = Await.ready(fut, Duration.Inf).value.get

		val elapsed = System.currentTimeMillis() - startTime

		println(s"Elapsed $elapsed ms, result was:\n$resp")
		system.terminate()
	}

}
```

I observe the following output:
```
Sending single HTTP GET request to http://akka.io:2345/ ...
Elapsed 64360 ms, result was:
Failure(akka.stream.StreamTcpException: Tcp command [Connect(akka.io:2345,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired)
```

So, it takes the `Future` more than 1 minute to fail, whereas the connecting-timeout is only 10 seconds. Here is output of my `java -version`:
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

**Comment by jrudolph** [comment]
Thanks for the report, @mirzov. The connection pool backing `singleRequest` retries a request for a few time with a backoff interval between attempts. The exception will only show the error message during the last attempt.

If you enable `debug` logging you should see what the pool is doing.

**Comment by mirzov** [comment]
Hi @jrudolph, thank you very much for the prompt and informative response! I could achieve the behavior that was needed by setting `max-retries` in the connection-pool settings to zero (the use case in question was actually access to a localhost -- not very idiomatic Akka).
