### ISSUE TITLE
`DELETE` method with Accept:application/json header fails with `NotAcceptable` but still get underlying function called

### ISSUE THREAD

**Issue by stremlenye** [akka/akka-http#356]
Hi

to enclose the problem I've wrote that test you see here:

```scala
implicit val actorSystem = ActorSystem()
    implicit val materializer = ActorMaterializer(ActorMaterializerSettings(actorSystem))
    var triggered = false
    val route =
      path("blah") {
        delete {
          complete {
            triggered = true
            StatusCodes.OK
          }
        }
      }

    Await.ready(Http().bindAndHandle(route, "0.0.0.0", 11022), 10 seconds)

    val request = HttpRequest(HttpMethods.DELETE, Uri("http://localhost:11022/blah"), immutable.Seq[HttpHeader](Accept(MediaRange(MediaTypes.`application/json`))))
    val result = Await.result(Http().singleRequest(request), 10 seconds)

    assert(result.status == StatusCodes.NotAcceptable)
    assert(triggered == false)

    actorSystem.terminate()
```

The test is failing, and according to the [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616.txt) thats not 100% clear is that behaviour is a strainght forward or not, but it feels wrong to receive and error and get endpoint to be triggered at the same time.

**Comment by jrudolph** [comment]
Hi @stremlenye,

yes, that's expected. The acceptance test only happens "inside" of the `complete` directive because only when it knows what to serialize (`StatusCodes.OK` in this case) the marshalling knows which requests to reject. Try this code instead:

```scala
delete {
  complete {
     triggered = true
     StatusCodes.ok
  }
}
```

This is a general advice: if you execute side-effects, don't do it during routing (i.e. somewhere in the routing structure) but only inside the `complete` which is only executed if all of the routing succeeded.

**Comment by stremlenye** [comment]
Hi @jrudolph,
Thanks for answer and for advice. Now its clear for me.
Just to make it clear: the case is 'as far as there is no way to marshall StatusCode to the `application/json` response, the request will have `NotAcceptable` status", is it so?

**Comment by jrudolph** [comment]
Yes, basically. The predefined marshaller for status codes ([source](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala#L33)) creates a `text/plain` response including the "default message" for that status code as the entity. This will be rejected with `NotAcceptable` if the client expects an `application/json` response, instead. You can use `complete(HttpResponse(StatusCodes.OK))` to stay clear of such problems.

**Comment by stremlenye** [comment]
Thank you!
I guess that one should be closed.
