### ISSUE TITLE
http2: support for receiving response trailers

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3563]
Trailers are received as a second and final HEADERS frame on a stream.

This is probably needed for the gRPC client as sending response trailers was needed for the server-side. (correct, @raboof?)

One difficulty is, that in the HTTP model we can encode trailers only with HttpEntity.Chunked. Currently, we create chunked entities when a stream comes in which doesn't have a `Content-Length` header set.

We could also expand that for receiving request trailers on the server (but only if required).

It seems, we cannot support trailers for responses with a `Content-Length` set (or we will have to generated Default entities in all cases).

**Comment by raboof** [comment]
> This is probably needed for the gRPC client as sending response trailers was needed for the server-side. (correct, @raboof?)

Yes, the grpc status code and other metadata are sent in the trailing header, so we'd need to be able to get to those.

> We could also expand that for receiving request trailers on the server (but only if required).

I'm not aware of use cases for that (though I could think of them I guess ;) )

> It seems, we cannot support trailers for responses with a `Content-Length` set

`Strict` is `final`, so I guess we're free to add methods to that... but perhaps there is a nicer way.

**Comment by jrudolph** [comment]
> > It seems, we cannot support trailers for responses with a `Content-Length` set
> 
> `Strict` is `final`, so I guess we're free to add methods to that... but perhaps there is a nicer way.

I think we should only do it if there's a use case with gRPC. Do gRPC requests ever have a `Content-Length` set for streamed channels?

**Comment by raboof** [comment]
> Do gRPC ~requests~ responses ever have a `Content-Length` set for streamed channels?

I'm sure Akka gRPC never sends a Content-Length for a gRPC response, but I'm not sure what other frameworks do. I don't think the [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses) forbids it (you can have 'custom metadata' in the response headers and content-length could be one of those AFAICS)

**Comment by jrudolph** [comment]
So, the conclusion could be to emit a chunked entity in all cases where no `Content-Length` header was received, so we can publish the trailer as a `LastChunk`. This should work for gRPC which doesn't seem to use `Content-Length` commonly.

What would we do if we receive a `Content-Length` and also get a trailer? We could either just ignore the trailer or fail or warn.

**Comment by raboof** [comment]
> the conclusion could be to emit a chunked entity in all cases where no `Content-Length` header was received, so we can publish the trailer as a `LastChunk`. This should work for gRPC which doesn't seem to use `Content-Length` commonly.

We could try that and see if that leads to problems for anyone, sure.

> We could either just ignore the trailer or fail or warn.

This is tricky. Failing seems too harsh, since it's not wrong spec-wise and the user might not even care about those trailing headers. I'm not sure about logging, since the user can't always prevent the server from sending those trailing headers, so then it's not really actionable. Perhaps just silently drop them? A user that is interested in them will notice they're missing from the API anyway...

**Comment by jrudolph** [comment]
>  Perhaps just silently drop them? A user that is interested in them will notice they're missing from the API anyway...

Yep, that's a good point (and also the current behavior).
