### ISSUE TITLE
Java DSL cannot create ContentTypeResolver

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#360]
The docs say _Implement this interface to provide a custom mapping _, but implementing just `akka.http.javadsl.server.directives.ContentTypeResolver` makes the target class not be a scala `ContentTypeResolver`, causing `JavaMapping` to error out with

```
Illegal custom subclass of akka.http.scaladsl.server.directives.ContentTypeResolver. Please use only the provided factories in akka.http.javadsl.model.Http
```

I think the simplest solution may be to have a factory around a lambda, rather than an interface, i.e. 

```
def create(java.util.function.Function[String,ContentType]): ContentTypeResolver
```

**Comment by ktoso** [comment]
Good catch, and the proposed solution is good as well. Should be `ContentTypeResolver.create(....)`
