### ISSUE TITLE
Java PathDirectives.pathSuffixTest uses Scala Function instead of Java

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#361]
line [221](https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/javadsl/server/directives/PathDirectives.scala#L221) should be 
```
def pathSuffixTest[T1](pm: PathMatcher1[T1], inner: JFunction[T1, Route]): Route = RouteAdapter {
```
instead of 
```
def pathSuffixTest[T1](pm: PathMatcher1[T1], inner: Function[T1, Route]): Route = RouteAdapter {
```

There are more erroneous usages of `scala.Function` in there.

**Comment by ktoso** [comment]
Thanks for spotting! Go ahead and mark as bug right away :)

**Comment by ktoso** [comment]
We should fix those before we release from this repo a stable version, would you be able to submit a PR, checking related issues about JFunction around there?

**Comment by jypma** [comment]
ah, completely forgot I have POWER on the repo these days :)

I'm a bit pressed for time at the moment, working on a demo, so unfortunately can't promise anything.

**Comment by ktoso** [comment]
Right, but I don't think we'll release a stable tomorrow, so we still have a bit of time here. :)
