### ISSUE TITLE
complete(StatusCodes.NoContent) fails with UnacceptedResponseContentTypeRejection for Accept(MediaTypes.`application/json`) request

### ISSUE THREAD

**Issue by leachbj** [akka/akka-http#366]
When a route completes with `StatusCodes.NoContent` the marshalling will fail with `StatusCodes.NotAcceptable` if the request doesn't accept text/plain.

The following test fails with `Request was rejected with rejection UnacceptedResponseContentTypeRejection(Set(MediaType(text/plain)))`

```scala
import akka.http.scaladsl.model.headers.Accept
import akka.http.scaladsl.model.{MediaTypes, StatusCodes}
import akka.http.scaladsl.server.{Directives, Route}
import akka.http.scaladsl.testkit.ScalatestRouteTest
import org.scalatest.{Matchers, WordSpecLike}

class NoContentSpec extends WordSpecLike with Matchers with ScalatestRouteTest with Directives {

  val noContentRoute: Route = complete(StatusCodes.NoContent)

  "The noContentRoute" should {
    "return HTTP NoContent for accept header `application/json`" in {
      Get("/").withHeaders(Accept(MediaTypes.`application/json`)) ~> noContentRoute ~> check {
        status shouldBe StatusCodes.NoContent
      }
    }
  }
}
```

As a work-around `complete(HttpResponse(StatusCodes.NoContent, entity = HttpEntity.Empty))` can be used instead.

**Comment by jrudolph** [comment]
This seems like a duplicate of https://github.com/akka/akka/issues/20793. Can you see if it has been fixed for you in 2.4.11, @leachbj?

**Comment by jrudolph** [comment]
Actually, it might be hard to see why it is a duplicate but I think we still have it fixed in the latest version.

**Comment by leachbj** [comment]
Works for me in 2.4.11.

**Comment by ktoso** [comment]
Cool :) Thanks for checking!

**Comment by leachbj** [comment]
Sorry my test scenario was flawed as I used `complete(HttpResponse(StatusCodes.NoContent))` instead of `complete(StatusCodes.NoContent)`.  The test case at the start of the ticket still fails with 2.4.11.

**Comment by jrudolph** [comment]
Thanks, confirmed, it is related to akka/akka#20793 but isn't exactly the same.

**Comment by jrudolph** [comment]
I'm considering preventing content type negotiation for the status code marshallers. A server is not strictly required to participate in "Proactive content-type negotiation":

From [RFC 7231 3.4.1](https://tools.ietf.org/html/rfc7231#section-3.4.1):

```
   A user agent cannot rely on proactive negotiation preferences being
   consistently honored, since the origin server might not implement
   proactive negotiation for the requested resource or might decide that
   sending a response that doesn't conform to the user agent's
   preferences is better than sending a 406 (Not Acceptable) response.
```

Especially for status code responses which usually won't contain any "resource" at all, it makes more sense to return the status code and a `text/plain` response instead of requiring the client to add `text/plain` just to support receiving status information.
