### ISSUE TITLE
HttpCookie copy method calling itself recursively.

### ISSUE THREAD

**Issue by rleibman** [akka/akka-http#3669]
In:
https://github.com/akka/akka-http/blob/0edbcafab114a3a5fcdaf08bb7c91f49ecb53916/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpCookie.scala#L83
The copy method calls itself recursively. This is affecting akka-http-session, which uses that method.

**Comment by jrudolph** [comment]
Fixed in #3670
