### ISSUE TITLE
h2 server: complete the stage gracefully

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#3687]
The Http2ServerDemux stage currently completes the stage when the server has finished sending frames to the client.

It would likely be neater if it completed the 'incoming' and 'outgoing' sides independently, notably cancelling the incoming stream of substreams as soon as the last relevant substream has been accepted.

**Comment by jrudolph** [comment]
> as the last relevant substream has been accepted.

Not sure what you mean with that.
