### ISSUE TITLE
An Either ToResponseMarshaller is needed

### ISSUE THREAD

**Issue by rrodseth** [akka/akka-http#369]
Konrad provided an Either unmarshaller.
https://github.com/akka/akka/pull/20274

Spray also has an Either marshaller. Needs to be included in Akka HTTP.

**Comment by rrodseth** [comment]
I may be mistaken
GenericMarshallers has the following.
`
  implicit def eitherMarshaller[A1, A2, B](implicit m1: Marshaller[A1, B], m2: Marshaller[A2, B]): Marshaller[Either[A1, A2], B] =
    Marshaller { implicit ec ⇒
      {
        case Left(a1)  ⇒ m1(a1)
        case Right(a2) ⇒ m2(a2)
      }
    }
`

**Comment by ktoso** [comment]
Yep indeed, seems we do provide it in `GenericMarshallers`.
So it'd seem we can close this ticket - esp since Marshaller extends generic marshallers, so it should resolve properly. 

Where did it not work for you?

**Comment by rrodseth** [comment]
Sorry, I'm thoroughly confused, but I get an error if I just do
val prm = implicitly[ToResponseMarshaller[Either[Int,String]]]
`
[ERROR] /Users/rrodseth/dev/repos/notifications/notifications-service-lib/src/main/scala/com/gridpoint/energy/notifications/api/NotificationsAPIRouting.scala:103: error: could not find implicit value for parameter e: akka.http.scaladsl.marshalling.ToResponseMarshaller[Either[Int,String]]
[INFO] val prm = implicitly[ToResponseMarshaller[Either[Int,String]]]
`

**Comment by ktoso** [comment]
Right, but that's since you don't have a marshaller from Int, isn't it?
Use intellij and cmd+shift+p to see implicit parameters and which ones are missing

**Comment by rrodseth** [comment]
I use ScalaIDE, but you correct. Perhaps it's the tuple then.
This succeeds:
`
val prm = implicitly[ToResponseMarshaller[Either[APIError,NotificationsStatusDTO]]]
`
This does not
`
val prm = implicitly[ToResponseMarshaller[(String,Either[APIError,NotificationsStatusDTO])]]
`
The error in Maven is
`
[ERROR] /Users/rrodseth/dev/repos/notifications/notifications-service-lib/src/main/scala/com/gridpoint/energy/notifications/api/NotificationsAPIRouting.scala:104: error: could not find implicit value for parameter e: akka.http.scaladsl.marshalling.ToResponseMarshaller[(String, Either[com.gridpoint.energy.notifications.apisupport.APIError,com.gridpoint.energy.notifications.dto.NotificationsStatusDTO])]
[ERROR] val prm = implicitly[ToResponseMarshaller[(String,Either[APIError,NotificationsStatusDTO])]]
`
In ScalaIDE
`
could not find implicit value for parameter e: akka.http.scaladsl.marshalling.ToResponseMarshaller[(String, Either[com.gridpoint.energy.notifications.apisupport.APIError,com.gridpoint.energy.notifications.dto.NotificationsStatusDTO])]
not enough arguments for method implicitly: (implicit e: akka.http.scaladsl.marshalling.ToResponseMarshaller[(String, Either[com.gridpoint.energy.notifications.apisupport.APIError,com.gridpoint.energy.notifications.dto.NotificationsStatusDTO])])akka.http.scaladsl.marshalling.ToResponseMarshaller[(String, Either[com.gridpoint.energy.notifications.apisupport.APIError,com.gridpoint.energy.notifications.dto.NotificationsStatusDTO])]. Unspecified value parameter e.
`
