### ISSUE TITLE
HTTP/2: support graceful termination

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#3708]
For Http/1.1 every server flow will contain a `GracefulTermination` stage, materializing a `ServerTerminator` that will allow shutting down all connections through `ServerBinding.terminate`.

This does not work for HTTP/2.

HTTP/2 includes the `MasterTerminator` to support the `ServerBinding` API but does not add the `GracefulTermination` stage to connections or register each connection with the `MasterTerminator`.

**Comment by johanandren** [comment]
Potentially a duplicate of #3580

**Comment by jrudolph** [comment]
Let's use the other ticket.
