### ISSUE TITLE
Support for responses with multiple Content-Type headers

### ISSUE THREAD

**Issue by armanbilge** [akka/akka-http#3712]
Today while testing my Alpakka connector akka/alpakka#2548 against the Google BigQuery REST API I was very frustrated to encounter `HTTP message must not contain more than one Content-Type header`. Unfortunately, it seems that one of the endpoints responds with two `Content-Type` headers making it impossible to use from Akka. 

Similarly to #3112, is it possible to make the Akka HTTP client more lenient with regard to this? If this is agreeable, I'm happy to make the PR. Thanks in advance for your thoughts.

**Comment by raboof** [comment]
> Unfortunately, it seems that one of the endpoints responds with two `Content-Type` headers

Ouch, so conflicting ones?

> Similarly to #3112, is it possible to make the Akka HTTP client more lenient with regard to this? If this is agreeable, I'm happy to make the PR. Thanks in advance for your thoughts.

I think I'd be OK with allowing this this (perhaps as an option?) in principle, but it's not so trivial to decide how to do it: the content type is not kept in the list of headers, but as a field on the entity - so there's no obvious way to keep both and let the user decide how to deal with them. Do you have ideas on how to approach that? I guess we could just drop one of the values, but that seems questionable enough that it should perhaps be opt-in.

**Comment by armanbilge** [comment]
> Ouch, so conflicting ones?

Yup, `application/json; charset=UTF-8` and `text/plain; charset=utf-8`. To add insult to injury the response body is empty anyway (pure-header response). FWIW I've filed an issue on their end as well.

> I guess we could just drop one of the values, but that seems questionable enough that it should perhaps be opt-in.

This was my first instinct too. As far as I can tell a response with more than one `Content-Type` is already questionable and while a warning is more than appropriate supporting this is a necessary evil for me. Perhaps while opting-in the user can specify whether to keep the first or last? And maybe include the "dropped" headers in the header list?

**Comment by armanbilge** [comment]
Sorry to bump, but I'm badly in need of a fix for this. I'm going to draft a PR along the lines of my previous comment unless there are any other suggestions for how to handle this. Thanks!

**Comment by jrudolph** [comment]
Fixed in #3727
