### ISSUE TITLE
Prevent the serialization of header containing a line terminator

### ISSUE THREAD

**Issue by gontard** [akka/akka-http#3717]
akka-http should throw an `Exception` when an header value containing a line terminator (LF) is sent in a response

For example

```scala
package com.example

import akka.actor.typed.ActorSystem
import akka.actor.typed.scaladsl.Behaviors
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.http.scaladsl.model.headers.{ModeledCustomHeader, ModeledCustomHeaderCompanion}
import akka.http.scaladsl.server.Directives._

import scala.util.Try

object HttpServerRoutingMinimal {
  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem(Behaviors.empty, "my-system")
    implicit val executionContext = system.executionContext
    val route =
      path("hello") {
        get {
          complete(StatusCodes.OK, Seq[HttpHeader](
            MyHeader("abc\ndef")
          ), "<h1>Say hello to akka-http</h1>")
        }
      }

    Http().newServerAt("localhost", 8080).bind(route)
  }

  final class MyHeader(token: String) extends ModeledCustomHeader[MyHeader] {
    override def renderInRequests = true
    override def renderInResponses = true
    override val companion = MyHeader
    override def value: String = token
  }
  object MyHeader extends ModeledCustomHeaderCompanion[MyHeader] {
    override val name = "my-header"
    override def parse(value: String) = Try(new MyHeader(value))
  }
}

```

We spotted this issue because our[ envoy](https://www.envoyproxy.io/) reverse proxy complains of an `Invalid HTTP header field was received`.

**Comment by jrudolph** [comment]
Good point, thanks for reporting (and sorry for the delay), @gontard.

I don't have a good idea how to check this cheaply. I don't think we want that check for our own modeled headers. It would certainly make sense for `RawHeader` but not sure where to put this for more generic user-defined modeled headers. Any ideas?

**Comment by gontard** [comment]
Thanks for your answer.

>  I don't think we want that check for our own modeled headers

Is it a performance concern? 

> Any ideas?

IDK the akka-http internals, but naively i would check that systematically.

**Comment by nitikagarw** [comment]
Hi @jrudolph, 
How about adding the check [here][1] and [here][2]?

[1]: https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala#L101
[2]: https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala#L776

**Comment by jrudolph** [comment]
>  How about adding the check [here](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala?rgh-link-date=2021-02-05T17%3A15%3A22Z#L101) and [here](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala?rgh-link-date=2021-02-05T17%3A15%3A22Z#L776)?

It should go into the constructor of `ModeledCustomHeader` (instead of its companion). We can put a verification method into `object HttpHeader` to call from the constructors.

**Comment by nitikagarw** [comment]
Hi @jrudolph, I have created a PR https://github.com/akka/akka-http/pull/3763 to discuss the fix.

**Comment by jrudolph** [comment]
#3922 adds a general solution that checks headers for invalid characters while rendering and if occurred drops those headers.
