### ISSUE TITLE
[failed] Server returned HTTP response code: 521 for URL:

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3756]
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/1167/console

It looks like the akka snapshots repo is refusing the connections from Cloudflare.

[521 Web Server Is Down - The origin server has refused the connection from Cloudflare.](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by jrudolph** [comment]
Seems someone restarted the webserver later the morning this happened, so maybe something was broken around that time.

Let's close it here.
