### ISSUE TITLE
[failed] akka-http-bench-nightly general failure (silencer_lib:1.7.3 in scala 2.12.12)

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-http#3783]
https://jenkins.akka.io:8498/job/akka-http-bench-nightly/264/

Problem is `silencer_lib:1.7.3` doesn't exist for scala 2.12.12 (`HEAD` already declares using scala 2.12.13 but the jenkins job insists on using 2.12.12)

**Comment by jrudolph** [comment]
I ran a quick test run successfully here: https://jenkins.akka.io:8498/job/akka-http-bench-nightly/266. The next regular one will run nightly after the next commit.
