### ISSUE TITLE
requestEntityPresent doesn't reject with RequestEntityExpectedRejection

### ISSUE THREAD

**Issue by leachbj** [akka/akka-http#379]
The `requestEntityPresent` scaladoc says it rejects with `RequestEntityExpectedRejection` (as it used to do with spray) but actually just rejects with an empty rejection list.

**Comment by leachbj** [comment]
Wrong project - opened as https://github.com/akka/akka-http/issues/379

**Comment by ktoso** [comment]
Marking as bug, though have not verified yet. Will get to it during our cleanup days.

**Comment by ktoso** [comment]
thanks for reporting!

**Comment by jrudolph** [comment]
Fixed by #385.
