### ISSUE TITLE
Paradox introduces extra line breaks

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#382]
Markdown usually ignores line breaks, so that the md source files can be arranged in a way that is readable without an editor that wraps long lines. It seems the current documentation workflow inserts `<br/>` instead leading to somewhat ugly formatting:

![screenshot from 2016-10-11 16 57 16](https://cloud.githubusercontent.com/assets/9868/19275377/247730e6-8f99-11e6-9f8f-b359fabd14b9.png)

Any idea, how to change that @jonas?

**Comment by jrudolph** [comment]
Added lightbend/paradox#31 to review whether HARDWRAPS was intended or an accidental parsing option.

**Comment by jonas** [comment]
I believe the original Markdown flavour specifies to honour line breaks, mainly to support proper formatting in block quotes. GFM which Paradox "embraces" does not I was also planning to submit a patch to fix it in Paradox.

Any Lightbend docs that already uses Paradox will have to explicitly format haiku poems and what not. ;)

**Comment by jrudolph** [comment]
> I believe the original Markdown flavour specifies to honour line breaks

Don't think so. See http://daringfireball.net/projects/markdown/basics:

```
Now is the time for all good men to come to
the aid of their country. This is just a
regular paragraph.
```

is converted into

```
<p>Now is the time for all good men to come to
the aid of their country. This is just a
regular paragraph.</p>
```

That's also how CommonMark defines paragraphs (http://spec.commonmark.org/0.25/#paragraphs):

> A sequence of non-blank lines that cannot be interpreted as other kinds of blocks forms a paragraph. The contents of the paragraph are the result of parsing the paragraph’s raw content as inlines. The paragraph’s raw content is formed by concatenating the lines and removing initial and final whitespace.

> mainly to support proper formatting in block quotes

This is unrelated. Blockquotes are parsed / output differently.

> Any Lightbend docs that already uses Paradox will have to explicitly format haiku poems and what not. ;)

Yes, this is a valid concern. Forcing Haikus between blockquotes might seem like an overly harsh restriction on creative freedom.

**Comment by jonas** [comment]
Yes, you are right. Hope the PR gets merged soon.

**Comment by jrudolph** [comment]
Paradox has been fixed. Waiting for a new version...
