### ISSUE TITLE
Multipart-Form-Data in akka-http, missing quotes in Content-Disposition field

### ISSUE THREAD

**Issue by KrzyMucha** [akka/akka-http#387]
When we use akka-http for http request with following code:
```
Multipart
            .FormData(Multipart.FormData.BodyPart("file",
                HttpEntity.Strict(MediaTypes.`image/jpeg`, ByteString("test")), Map("filename" -> "somefile.jpeg"))).toEntity()
```
Then Http request is as follows
```
User-Agent: [akka-http/2.4.8]
Transfer-Encoding: [chunked]
Host: [localhost:8089]
Content-Type: [multipart/form-data; boundary=xWtacaNwjOWLKFExaR8fOv6Q; charset=UTF-8]

--xWtacaNwjOWLKFExaR8fOv6Q
Content-Type: image/jpeg
Content-Disposition: form-data; filename=somefile.jpeg; name=file

test
--xWtacaNwjOWLKFExaR8fOv6Q--
```
Parameters **filename** and **file** are without quotation marks. However following HTTP specification this params should be quoted. As result some servers (ex. "django" app) are not able to see attached files.

**Comment by KrzyMucha** [comment]
Information about requirement I found here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html, paragraph **19.5.1 Content-Disposition**
```
filename-parm = "filename" "=" quoted-string
disp-extension-parm = token "=" ( token | quoted-string )
```

**Comment by ktoso** [comment]
Opened this ticket already, closing as duplicate.
Please post here: https://github.com/akka/akka-http/issues/386
