### ISSUE TITLE
Rejections with empty list even that request is procesing

### ISSUE THREAD

**Issue by sebarys** [akka/akka-http#3897]
Hello,

In our application (REST API exposed by akka-http server) we're using `logRequestResult` directive to log on debug successful responses, on info error responses and rejections:
```
  private def requestBasicInfoAndResponseStatus(req: HttpRequest): RouteResult => Option[LogEntry] = {
    case RouteResult.Complete(res) if res.status.isFailure() => Some(
      LogEntry(s"Request ${req.method} to ${req.uri} resulted in failure with status ${res.status}", Logging.InfoLevel)
    )
    case RouteResult.Complete(res) => Some(
      LogEntry(s"Request ${req.method} to ${req.uri} resulted in response with status ${res.status}", Logging.DebugLevel)
    )
    case RouteResult.Rejected(rejections) => Some(
      LogEntry(s"Request ${req.method} to ${req.uri} was rejected with rejections: $rejections", Logging.InfoLevel)
    )
  }
```
in logs I see very often:
```
Request HttpMethod(POST/GET/PATCH) to http://URL/PATH was rejected with rejections: List()
```
I’ve read in docu that empty rejection list could be related to no routing for given path, but that is not the case - provided (path, method) is covered by Route - I see logs from proper resolving and processing of requests from mentioned endpoints. Is there any way to determine why it happens?

Library versions:
- akkaVersion = "2.6.14"
- akkaHttpVersion = "10.2.4"

Connected issue on forum. https://discuss.lightbend.com/t/how-can-i-establish-root-cause-of-rejection-when-empty-list-is-provided/8593

**Comment by jrudolph** [comment]
The forum is indeed the right place for these kind of questions. Closing here and see you over there.
