### ISSUE TITLE
HTTP idle-timeout encountered, no bytes passed in the last 60 seconds after updating to 10.2.6 

### ISSUE THREAD

**Issue by sergionoviello** [akka/akka-http#3900]
After updating to 10.2.6 version I started seeing the following error in my application for every request
`HTTP2 connection failed with error [HTTP idle-timeout encountered, no bytes passed in the last 60 seconds. This is configurable by akka.http.[server|client].idle-timeout.]. Sending INTERNAL_ERROR and closing connection.`
I believe it comes from
this method https://github.com/akka/akka-http/blob/1088de3468cb3e488a8a4334226e8562cd3f10c5/akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala#L161

I’m using the default value 60s for `akka.http.server.idle-timeout`. Is there a way to mute/handle this exception?

**Comment by jrudolph** [comment]
Indeed, that's a bit annoying. We should either move the idle connection handling there directly or just ignore that particular error.

It shouldn't happen for every request, though, only once every 60 seconds (per target host)?

**Comment by sergionoviello** [comment]
> Indeed, that's a bit annoying. We should either move the idle connection handling there directly or just ignore that particular error.
> 
> It shouldn't happen for every request, though, only once every 60 seconds (per target host)?

I'm not sure if it's for every request, in my test I was using a ruby grpc client and noticed the exception every time I sent a request with a delay of 60s (my akka.http.server.idle-timeout setting)

**Comment by alexanderkyte** [comment]
When using akka-grpc and streaming, I'm seeing this error appear on every request. Adding a killswitch to the request and response streams doesn't change the failure status. (And watchTermination does trigger on the request input `Source[_, _]`)

If I ctrl+C the client for the request, it doesn't print this idle-timeout message. This makes me think that akka-http or akka-grpc are leaving open a connection, and an actor to watch the connection, even if the request `Source[_, _]` is being terminated.

**Comment by jrudolph** [comment]
> If I ctrl+C the client for the request, it doesn't print this idle-timeout message. This makes me think that akka-http or akka-grpc are leaving open a connection, and an actor to watch the connection, even if the request `Source[_, _]` is being terminated.

Yes, gRPC clients usually use a connection pool, so connections are not directly mapped to requests.

Anyway, the logging is really annoying so here's a fix: https://github.com/akka/akka-http/pull/4044
