### ISSUE TITLE
Allow parsing.max-content-length = 0

### ISSUE THREAD

**Issue by strelec** [akka/akka-http#3903]
java.lang.IllegalArgumentException: requirement failed: if set max-content-length must be > 0

This should simply require all requests to have empty bodies (for example, a server that only serves GET requests.)

**Comment by jrudolph** [comment]
Thanks, @strelec, that might make sense (but there might be some reasons it was done the way it is). Would you like to create a PR for that feature?

**Comment by GKuldeepak-Knoldus** [comment]
Hi Everyone, 
Has the issue been resolved? Also, lemme know if I'm wrong, we just need to change the value of `akka.http.client.parsing.max-content-length` to `0` from `20m` and if the issue is still open so, I would like to pick this issue.

**Comment by jrudolph** [comment]
Thanks, @GKuldeepak-Knoldus. Yes, this issue is still up for grabs, so please go ahead!

**Comment by GKuldeepak-Knoldus** [comment]
Thanks @jrudolph ,
I have raised a PR for the same. I have set the value to 0 for now, please lemme know, if it required anything further.

**Comment by soo-underground** [comment]
Hi Everyone!
Since the linked PR has been rejected, can I try to fix this issue?

**Comment by strelec** [comment]
Sure, have a crack at it.
