### ISSUE TITLE
Incorrect SSL session for first request on a connection

### ISSUE THREAD

**Issue by brharrington** [akka/akka-http#3920]
Occasionally we are seeing issues where the SSL session accessed via the `Tls-Session-Info` header or the attribute is not valid and shows `SSL_NULL_WITH_NULL_NULL` instead of something like `TLS_AES_128_GCM_SHA256`. I found a report of a similar issue for Jetty ([Jetty question](https://stackoverflow.com/questions/18080996/ssl-null-with-null-null-cipher-suite-in-in-jetty-logs)) where it appears it would access the SSL session before the SSL handshake was complete. I suspect something similar is happening with Akka-HTTP as I have only seen this problem on the first request for a given connection. 

The main problem is that I need to be able to access the X509 certificates for the request, but they are not available from the session even though the request otherwise works fine.

**Comment by jrudolph** [comment]
Thanks, @brharrington. I guess this is about the client side?

**Comment by jrudolph** [comment]
Which JDK is that? TLS implementations are quite different between versions.

**Comment by brharrington** [comment]
The JDK in this test was:

```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.22-SA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.22-SA-linux64) (build 25.302-b08, mixed mode)
```

It was an Akka server with a non-Akka client.

**Comment by sharpwriter** [comment]
Is there any news on this : I am facing a similar issue.

Testing from Postman, mutual TLS with a configured Client Certificate.

The first call always fails, after that everything is fine.

**Comment by johanandren** [comment]
We have merged an upstream fix, it will be included in the next Akka release (https://github.com/akka/akka/issues/31419)

**Comment by johanandren** [comment]
Would be great if you could try a snapshot of Akka 2.8 and verify that it helps.

**Comment by johanandren** [comment]
Details about using a snapshot here: https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository

**Comment by johanandren** [comment]
Thanks for confirming, I'll close this issue now since there is nothing in Akka HTTP that needs a change.
