### ISSUE TITLE
Akka-Http custom rejections doesn't work in the latest version

### ISSUE THREAD

**Issue by johnykoshy** [akka/akka-http#3938]
Custom `RejectionHandler` as given in the [docs](https://doc.akka.io/docs/akka-http/current/routing-dsl/rejections.html#customizing-rejection-handling) doesn't work. Following is a minimal working code of what I was trying.

```
object MyApp extends App {
    implicit def myRejectionHandler = RejectionHandler.newBuilder()
      .handle {
        case m: MethodRejection =>
          complete((StatusCodes.NotFound, "Not here!"))
      }.result()`
  implicit val system = ActorSystem()

  val route: Route =
    path("index") {
      post {
        complete(StatusCodes.OK)
      }
    }

    Http().newServerAt("localhost", 8080).bind(route)
}
```

If I try `http://localhost:8080/index`, the response is

> HTTP method not allowed, supported methods: POST

with status code `405`, instead of

> Not here!

with status code `404`

My `build.sbt`

```
scalaVersion := "2.13.6"

lazy val akkaVersion = "2.6.17"
lazy val akkaHttpVersion = "10.2.7"

libraryDependencies ++=
  Seq(
    "com.typesafe.akka" %% "akka-actor" % akkaVersion,
    "com.typesafe.akka" %% "akka-stream" % akkaVersion,
    "com.typesafe.akka" %% "akka-http" % akkaHttpVersion
  )

```

The snippet given in doc for `10.1.x` works.

Note: This is a question that I had asked in [stackoverflow.com](https://stackoverflow.com/questions/69923510/akka-http-custom-rejections-doesnt-work-in-the-latest-version), so most of the content is copy-pasted from there. But looks like a possible bug or documentation error.

**Comment by jrudolph** [comment]
That might be an oversight, indeed. By now, we prefer explicit declarations of `RejectionHandler`. Try

```scala
val route = handleRejections(myRejectionHandler) { ... }
```

**Comment by johnykoshy** [comment]
Yes, handleRejections do work. Thought raising this issue might warrant either a change in documentation or code.

Thanks.

**Comment by nitikagarw** [comment]
Hi @jrudolph, Does this issue requires the documentation to be updated? If yes, Can I please pick this?

**Comment by jrudolph** [comment]
@nitikagarw sure, thanks for picking this up!
