### ISSUE TITLE
Akka HTTP single requests hang forever when host is invalid/unreachable

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#397]
<a href="https://github.com/bfil"><img src="https://avatars.githubusercontent.com/u/660513?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bfil](https://github.com/bfil)**
_Sunday Oct 16, 2016 at 13:09 GMT_
_Originally opened as https://github.com/akka/akka/issues/21679_
---

I've managed to strip down the core issue to the following snippet:

``` scala
import akka.http.scaladsl.Http
import akka.http.scaladsl.client.RequestBuilding._
0 to 10 map { i =>
  Http().singleRequest(Get("http://someinvaliddomain.com")) map {
    res => println(s"Got Response: $i")
  }
}
```

This looks relatively straightforward, I would expect to get all my 10 responses back, but after 4 responses due to the invalid host no more requests will ever be sent to the specific host.

```
Got Response: 0
Got Response: 3
Got Response: 1
Got Response: 2
```

I've noticed this behaviour when trying to hit a slow service which times out from time to time, after 4 gateway timeouts sent from nginx no more requests were sent to the host. I'm not 100% sure in what case this would get stuck though, some clarification on the matter would be useful.

I've noticed a few related issues like this one: https://github.com/akka/akka/issues/21098

That have been closed and linked to akka meta: https://github.com/akka/akka-meta/issues/27

But I would expect such trivial example and `Http().singleRequest` to take care of the corner cases for me since it returns a `Future[HttpResponse]` rather than a stream.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Sunday Oct 16, 2016 at 13:13 GMT_

----

What's the response though?
Have you read
http://doc.akka.io/docs/akka/2.4.8/scala/http/implications-of-streaming-http-entity.html
?

**Comment by ktoso** [comment]
<a href="https://github.com/bfil"><img src="https://avatars.githubusercontent.com/u/660513?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bfil](https://github.com/bfil)**
_Sunday Oct 16, 2016 at 13:17 GMT_

----

@ktoso don't think so, I'll have a read.

The response of the above is:

```scala
HttpResponse(200 OK,List(Server: nginx, Date: Sun, 16 Oct 2016 13:00:46 GMT, Connection: close, Expires: Sun, 16 Oct 2016 13:10:46 GMT, Cache-Control: max-age=600),HttpEntity.Chunked(text/html; charset=UTF-8),HttpProtocol(HTTP/1.1))
```

Gets stuck after 4, but if I change the host to let's say `http://google.com` then it doesn't get stuck and processes all 10. Can't see the difference there.

**Comment by viktorklang** [comment]
You still need to consume the response body.

-- 
Cheers,
√

**Comment by bfil** [comment]
@viktorklang I get that, is the only difference in behaviour here then that the above snippet would not get stuck if the `HttpResponse` entity comes back as `Strict` instead of `Chunked`? Or is there anything else happening under the hood?

I think my initial gateway timeout and the above snippet's response were both coming back from nginx, both as chunked I assume.

Using `discardEntityBytes` does solve the issue. I would argue it would help to show that it's needed in the relevant Spray to Akka HTTP migration docs, there's nothing there that points this out:

http://doc.akka.io/docs/akka/current/scala/http/migration-from-spray.html#Changes_in_HTTP_Client

And that page imo should also link to http://doc.akka.io/docs/akka/current/scala/http/implications-of-streaming-http-entity.html

**Comment by jrudolph** [comment]
Shouldn't all the entity substreams have timeouts attached, so that the connections would be automatically failed after some time?

**Comment by jrudolph** [comment]
Thanks, @bfil. The suggestion about putting pointers about entity stream handling into the migration guide is a good one. I created a pull request that adds a section to the spray migration guide:

https://github.com/akka/akka-http/pull/456

**Comment by jrudolph** [comment]
Fixed by adding more info to the migration guide in #456.
