### ISSUE TITLE
Bump Jackson libraries to 2.8.x

### ISSUE THREAD

**Issue by guidomedina** [akka/akka-http#4]
There are not breaking changes in Jackson 2.8.x compared to 2.7.x, only new features, it is even still compatible with Java < 8

That said I see no harm on just bumping to 2.8.x, I have upgraded a POJO project to it _-legacy code-_ and I haven't found any issue so far which with annotated POJOs is even more complicated to migrate.

**Comment by ktoso** [comment]
Thanks for the ticket, we certainly can upgrade it right now during the move.

To be clear though, "have not found issue" is not strong enough once we're stable.
It has to be binary compatible, this is how we roll.

**Comment by guidomedina** [comment]
I know, I was only giving my testimony for what's it can be worth.

**Comment by ktoso** [comment]
Got it, thanks! :) Soon we should see code in this repo and then do the change :)

**Comment by patriknw** [comment]
Jacksson has a good track record. +1
