### ISSUE TITLE
`PoolMaster.shutdown` hangs indefinitely

### ISSUE THREAD

**Issue by t3hnar** [akka/akka-http#4003]
Hello, 

I found a bug that leads to shutdown process hanging indefinitely.

`PoolMaster.shutdown(…)` call does not complete `shutdownCompletedPromise` for connection pool that has been shutdown because of `idle-timeout`

```
case Shutdown(poolId, shutdownCompletedPromise) =>
      statusById.get(poolId).foreach {
```

is never executed, because nothing is found in the `map`

**Comment by jrudolph** [comment]
Thanks, @t3hnar, good catch.
