### ISSUE TITLE
Streamed text message never ends with a Futter WebSocket client for a specific TCP sequence

### ISSUE THREAD

**Issue by maximeburri** [akka/akka-http#4015]
Hello,

I adapted a bit the Websocket chat example https://github.com/jrudolph/akka-http-scala-js-websocket-chat and implemented a Flutter application using this WebSocket server.

I checked the packets network, and in contrast to the Play frontend: the web socket flutter is quite strange because he sends the WebSocket mask in a a single PUSH/ACK TCP packet before sending the payload.

**Flutter WebSocket client (64661) sending a mask before sending payload**
![image](https://user-images.githubusercontent.com/5551924/151844442-030724f1-c724-46d8-a878-ffe0807dc880.png)

This flow works correctly and are handled by the server.

BUT when more message are sent (~5 messages per seconds) the server will sometimes send an ACK of the first PUSH packet (the mask packet):

**Server ACK the mask**

![image](https://user-images.githubusercontent.com/5551924/151847077-7e2e2e87-303c-40ff-b3a9-6c66e82f0f3b.png)

I guess that seems ok regarding to the TCP specification. But when that happens, `akka-http` seems to change the message to a `TextMessage.Streamed` that never ends:

- If the `TextMessage.Streamed` is not collected in the flow, the channel is blocked and normal `TextMessage.Strict`s are not processed  for ~5 seconds.
- If the `TextMessage.Streamed` is collected and tried to await and transformed to a strict message (`Await.result(streamed.toStrict(1.second), 1.second).text`): the timeout is thrown.

Printing the messages of the stream (`stream.runForeach(msg => println(s"Streamed: $msg"))`) print the whole correct payload.

It looks like the server is still waiting for a packet that never comes or don't ACK correctly. After some other packet exchanges a _Spurious Retransmission_ packet is sent from the flutter client to the server:

![image](https://user-images.githubusercontent.com/5551924/151848625-19b765d5-9718-4019-98af-84ed59a495c0.png)

Thanks a lot for you help

**Comment by jrudolph** [comment]
HI @maximeburri, the reason is probably that your `Await.result` blocks any further processing of the stream (because the infrastructure and your handling code share the same stream). You can try to adapt the solution that @johanandren posted a while ago on the forum: https://discuss.lightbend.com/t/help-akka-http-websocket-messages-disorder/9316/5.

**Comment by maximeburri** [comment]
Hi @jrudolph 
Thanks a lot that was the reason.
