### ISSUE TITLE
10.3.0 planning

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#4016]
Milestone:

https://github.com/akka/akka-http/milestone/57

Work items:

 * [ ] Drop Akka 2.5 support
 * [ ] Drop Scala 2.12?
	 * [ ] Get rid of pre213 / post213 logic (+ extra warts needed for Scala 3)
 * [ ] Support cancellation cause propagation everywhere
 * Update dependencies to potentially breaking versions
	 * [ ] scala-xml https://github.com/akka/akka-http/pull/3995)
	 * [ ] scala-test
	 * [ ] perhaps even update jackson beyond the version Akka is on?
 * [ ] Deprecations / Removals

**Comment by patriknw** [comment]
obsolete, even though some of these tasks will come back later
