### ISSUE TITLE
Client-side SSE (Server-Sent Events) source does not emit server-side's default heartbeats

### ISSUE THREAD

**Issue by imRentable** [akka/akka-http#4017]
Hello, 

I am using Akka HTTP `v10.2.7` and trying to consume Server-Sent Events with an Akka HTTP client that are emitted by an Akka HTTP server similar to [this official example](https://doc.akka.io/docs/akka-http/10.0/sse-support.html). This works fine for events that have a non-empty string as value in their data field but not for events whose data field's value is an empty string. This happens to be the case when the default heartbeat provided by Akka HTTP is used: `akka.http.scaladsl.model.sse.ServerSentEvent#heartbeat`. The client source simply won't emit anything. Is this supposed to be like this? According to the examples given in the [specification](https://html.spec.whatwg.org/multipage/server-sent-events.html), a data field that has no value should trigger a client source to emit an event.

AFAIU, the cause for this behaviour lies within the `akka.http.scaladsl.unmarshalling.sse.ServerSentEventParser` in line 115 where data must not be empty. Otherwise, nothing is appended and a push won't happen in line 108.

There is also a comment stating that "Events without data are ignored according to the spec" but I have not been able to verify this within the aforementioned specification.

I wrote a minimal [client/server example](https://gist.github.com/imRentable/6be8ca9e8b2ee555090411bfef244257) that shows the aforementioned behaviour.

I am afraid that this could cause other client implementations to act weirdly since I think it does not work exactly as specified. That being said, please correct me if I am mistaken.

**Comment by jrudolph** [comment]
Thanks for the report, @imRentable.

I'd say in section [9.2.6 Interpreting an event stream](https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation), the list of steps can be interpreted as skipping empty data events:

> 2. If the data buffer is an empty string, set the data buffer and the event type buffer to the empty string and return.

so that the processing never gets to actually dispatching the event.

Have you verified that browsers would show a different behavior?

**Comment by imRentable** [comment]
@jrudolph: I agree, it is not very clear.

I tested it with Google Chrome `Version 97.0.4692.71 (Official Build) (x86_64)` and there I can see heartbeats in the form of `data:<empty string>`.

**Comment by claasic** [comment]
There are three things I am reading differently.

1. The specification also lists an example with events that only consist of data fields with empty strings. These events are described as firing:
> The following stream fires two events:
> 
> data
> 
> data
> data
> 
> data:
> The first block fires events with the data set to the empty string, as would the last block if it was followed by a blank line. 
> The middle block fires an event with the data set to a single newline character. The last block is discarded because it is not followed by a blank line.

2. The specification also states that whenever a data field is read a LF character is appended to the buffer. This implies to me that on the happy path there is empty string and that step no. 2 is a kind of NULL-check to ensure the correctness.

3. The ABNF also allows for `data` and `data:` without any following value. If these are considered valid events why would the interpretation return?

**Comment by imRentable** [comment]
> The following stream fires two events:
> 
> data
> 
> data
> data
> 
> data:
> The first block fires events with the data set to the empty string, as would the last block if it was followed by a blank line.
> The middle block fires an event with the data set to a single newline character. The last block is discarded because it is not followed by a blank line

This is the example I referred to in the issue description. Additionally, all the other points @claasic mentioned lead me to believe that the current parsing logic does not adhere to the specification in this case. 

Thank you for your detailed input.

**Comment by jrudolph** [comment]
I see, I agree the example makes it pretty clear. Thanks for clearing that up!

> 2\. The specification also states that whenever a data field is read a LF character is appended to the buffer. This implies to me that on the happy path there cannot be an empty string and the previously quoted step acts as a check to ensure the correctness.

Either that, or you might have received an event without any `data` field at all, in which case it would be ignored. Would anyone be willing to provide a PR for that fix?

**Comment by imRentable** [comment]
I'll do it. In the next few days or so.

**Comment by jrudolph** [comment]
Great, thanks!

**Comment by jrudolph** [comment]
This broke existing code where akka-http client and server played together and automatically emitted empty events as heartbeats. I added another PR to change the default back to the old value. We now still have a possibility to explicitly offer those empty events to applications that want to interpret empty events differently.

https://github.com/akka/akka-http/pull/4043
