### ISSUE TITLE
gzip decoding fails with Scala 3

### ISSUE THREAD

**Issue by nvollmar** [akka/akka-http#4040]
- Akka: 2.6.18
- Akka-HTTP: 10.2.7
- Scala 3.1.1

Requests fail mid parsing when `gzip` is in `Accept-Encoding` using Scala 3. Compiled with Scala 2 or using deflate or none works fine.

```
Unknown error in http request: HttpRequest(HttpMethod(GET),http://xxx, List(Accept-Encoding: gzip, deflate,HttpEntity.Strict(none/none,0 bytes total),HttpProtocol(HTTP/1.1)) with failure: spray.json.JsonParser$ParsingException: Unexpected end-of-input at input index 32768 (line 1, position 32769), expected ':':
```
(Interesting to note, it fails at Short.MAX_VALUE)

**Comment by jrudolph** [comment]
Interesting, thanks for the report, @nvollmar. Which version of spray-json do you use? Could you share a reproducer?

**Comment by nvollmar** [comment]
The same one that is provided by akka-http-spray-json, 1.3.6

To note, the system called (within the same k8s cluster) is implemented in Go.
We also just encountered it on another system deployed with Scala 2. While testing on a small cluster I could not reproduce this with Scala 2.

**Comment by nvollmar** [comment]
We've identified the issue in the Go gzip middleware - closing the issue.

**Comment by jrudolph** [comment]
> We've identified the problem resulting from the Go gzip middleware - closing the issue as it isn't related to akka-http.

Thanks for the follow-up!
