### ISSUE TITLE
Bumping from 10.2.7-10.2.8 causes crash on launch

### ISSUE THREAD

**Issue by CalumMcCall** [akka/akka-http#4045]
When I bumped to the latest release, I get the following exception on launch:

```
'cinnamon.instrument.akka.http.AkkaHttpInstrumentation akka.http.scaladsl.HttpExt.cnmInstrumentation()'
<snip>
Caused by: java.lang.NoSuchMethodError: 'cinnamon.instrument.akka.http.AkkaHttpInstrumentation akka.http.scaladsl.HttpExt.cnmInstrumentation()'
```

Given that this is a minor release, I don't expect any API changes were made. Can anyone provide any clues as to what might be going wrong here?

**Comment by raboof** [comment]
Thanks for the report, that indeed doesn't look like it should happen - looking into it.

**Comment by CalumMcCall** [comment]
No problem, let me know if you need anything else from me.

**Comment by JustinPihony** [comment]
Hi @CalumMcCall would you mind opening a support case in the Lightbend portal so that we can track this there? I ask because the error you are getting is from an interaction with our commercial product, Cinnamon. We are aware of this breakage and will be working on a fix, however understanding which companies are specifically affected will help, also.

**Comment by CalumMcCall** [comment]
> Hi @CalumMcCall would you mind opening a support case in the Lightbend portal so that we can track this there? I ask because the error you are getting is from an interaction with our commercial product, Cinnamon. We are aware of this breakage and will be working on a fix, however understanding which companies are specifically affected will help, also.

I don't have an account on the lightbend portal, and there doesn't seem to be an obvious way to make one.

**Comment by jrudolph** [comment]
Reverted the conflicting part so 10.2.9 should work again with the current Telemetry versions.
