### ISSUE TITLE
There are any plan that integrate CORS in akka http?

### ISSUE THREAD

**Issue by xusliebana** [akka/akka-http#4067]
Please use https://discuss.akka.io or https://gitter.im/akka/akka for questions instead of posting them to the issue tracker.

**Comment by raboof** [comment]
Please use https://discuss.akka.io/ or https://gitter.im/akka/akka for questions instead of posting them to the issue tracker ;)

You can use https://github.com/lomigmegard/akka-http-cors to get that behavior, though.
