### ISSUE TITLE
Performance issue with HttpHeader parsing initilization

### ISSUE THREAD

**Issue by sdehors-ibm** [akka/akka-http#4110]
The initial call for parsing of header values can take a very long time:
for example 
`HttpHeader.parse("Content-disposition", "attachment; filename=\"filename.jpg\"" );`
takes up to 500 ms on a powerful local machine running java8. 

Then parsing of incorrect headers takes between 1 and 2 ms which has a visible impact on response time.
For example: `HttpHeader.parse("Content-disposition", "attachment; \"filename.jpg\"" );`

**Comment by jrudolph** [comment]
> takes up to 500 ms on a powerful local machine running java8.

Yes, cold JVMs are slow, it will need all kinds of class-loading to get there. For me the first invocation is ~ 250ms, the second one is already below 1 ms.

> Then parsing of incorrect headers takes between 1 and 2 ms which has a visible impact on response time.
> For example: `HttpHeader.parse("Content-disposition", "attachment; \"filename.jpg\"" );`

It will get much faster after warmup. For me those ones will go down to ~30 us after 1000 invocations (compared to ~4us for correct headers).

I'd say these are reasonable numbers, you can parse 30000 / s of broken headers or 300000/s of correct ones per thread after warmup.

Of course, we could discuss JVM warmup times, but why do it here?

**Comment by hepin1989** [comment]
You need do some warm up？

**Comment by sdehors-ibm** [comment]
ok got it for the warm-up. The broken case is a bit surprising and annoying. We'll have to prevent that beforehand in the application code.

**Comment by hepin1989** [comment]
warmup and then publish the service should be ok.
