### ISSUE TITLE
New lines in RawHeader

### ISSUE THREAD

**Issue by imclem** [akka/akka-http#4136]
Hi 👋

We're using akka http client (10.1.9) to perform http requests to a remote server.

In the process we build the following http request:
```scala
    val request =
      Post(
        Uri(s"$rootUrl/stats"),
        stats
      ).withHeaders(RawHeader("Authorization", s"Bearer $token"))
```

Which ended up failing server side because the token contained a trailing `\n`.

We debugged by building and performing the request manually with a java `HttpsUrlConnection`, in this case when we set the header Authorization with a token containing a new line, a runtime exception is thrown:
```java
java.lang.IllegalArgumentException: Illegal character(s) in message header value: Bearer
```

For now we fixed by manually removing `\n` characters:
```scala
      Post(
        Uri(s"$rootUrl/stats"),
        stats
      ).withHeaders(RawHeader("Authorization", s"Bearer ${token.replace("\n", "")}"))
```

I'm not sure what's the best solution here, throwing an exception, cleaning it up for us but IMHO there is something to do to avoid this issue.

Thanks !

**Comment by jrudolph** [comment]
This seems to be a duplicate of https://github.com/akka/akka-http/issues/3717 which has been fixed in 10.2.7 by discarding those headers while rendering.

**Comment by imclem** [comment]
@jrudolph does #3717 also fix http client ? Will it completely remove the header from the request ?

**Comment by imclem** [comment]
Thanks we'll just upgrade to the newer version then
