### ISSUE TITLE
Now that Route.asyncHandler is deprecated, there is now no way to avoid the default ExceptionHandler

### ISSUE THREAD

**Issue by blast-hardcheese** [akka/akka-http#4142]
Previously, with `Route.asyncHandler`, I would describe an `ExceptionHandler({ case t => _ => Future.failed(t) })` for use with ScalaTest, to permit bubbling failure assertions out.

It would be nice to have a variant of `Route.toFunction` that avoids this catch-all that turns exceptions into `StatusCodes.InternalServerError`, even if it is just for testing.

Guidance here would be appreciated, I am happy to do the work. Thank you!

**Comment by johanandren** [comment]
Long time with no reply here, sorry for that.

The RouteTest from the testkit does bubble failures out to the test, is that insufficient?

Example from our test suite:
```
    "failing the test inside the route" in {

      val route = get {
        fail()
      }

      assertThrows[TestFailedException] {
        Get() ~> route
      }
    }
```

**Comment by blast-hardcheese** [comment]
Unfortunately no, as this is for [guardrail](https://github.com/guardrail-dev/guardrail) (openapi-driven codegen) "round trip" tests (both in our own repo as well as in end user consuming repos), the requests and responses are not generated using the testkit methods and builders.

The way I'd like to have tests work (and the way they've been able to work in the past) is to say:

```scala
val client = FooClient.httpClient(
  Route.toFunction(FooResource(new FooHandler {
    def doBar(respond: ...)(arg: Int) = {
      arg shouldBe (42) // Test in server
      Future.successful(respond.Ok(234))
    }
  })))
client.doBar(123).futureValue shouldBe (42) // Test in client
```

`FooClient` accepts a `Request => Future[Response]`
`FooResource` is a `FooHandler => Routes`
`FooHandler` is an interface that permits users to provide business logic completely abstracted from HTTP internals.

While "Test in client" would emit a test failure exception, as desired, the "Test in server" exception gets eaten by `toFunction` and turned into a `HttpResponse(500,...)`

The reason I can't easily switch over to using the testkit stuff is because the generated servers and generated clients are all the production versions of those classes, emitting testkit-targeted classes would leave part of the production codebase untested.

I believe an escape hatch should be added to `toFunction` to permit bypassing the sink-to-500 issue, it doesn't need to be exactly like `asyncHandler`'s implementation, but removing this functionality would prevent testing in environments that can't use testkit.

I did quite a bit of digging, all the internals that I could use to get around this are private, and would invariably have me just writing my own `toFunction` with a single line changed.

**Comment by johanandren** [comment]
I'm hesitant to open the main api back up for custom exception handling, would a `def toFunctionPassThroughExceptions(route: Route)(implicit system: ClassicActorSystemProvider): HttpRequest => Future[HttpResponse]` in the testkit be a workable solution?

**Comment by blast-hardcheese** [comment]
I believe that satisfies all my use cases, somebody else may be using this functionality in a non-test environment but I am not.

Thank you!
