### ISSUE TITLE
Automatic keep-alive WebSocket Ping support doesn’t work in PLAY FRAMEWORK.

### ISSUE THREAD

**Issue by atyutin90** [akka/akka-http#4147]
Hello everyone,

I found strange behavior in akka-http 10.2.9 that automatic keep-alive Ping the server-side WebSocket support  doesn’t work  when creating WebSocket in PLAY FRAMEWORK. (https://github.com/playframework/playframework/issues/3861)

I created simple Play example project, using [documentation](https://www.playframework.com/documentation/2.8.x/ScalaWebSockets). 

My server configuration is the following:

```
akka {
  http {
    server {
      websocket {
         periodic-keep-alive-mode = ping
         periodic-keep-alive-max-idle = 3s
      }
    }
  }
}
```

As a result, I got that the ping/pong mechanism seems doesn't work as expected, I didn't see in Wireshark that the data being sent from the server every 3 seconds to client or returned back.

After, I decided to create project using clean [akka-http](https://doc.akka.io/docs/akka-http/current/server-side/websocket-support.html) with above config, and got that the ping/pong mechanism seems to work as expected.

I researched point when both examples start to work differently and found that differences executing the method https://github.com/akka/akka-http/blob/294eb5d86568bb42851adff3f07d435d691d3083/akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala#L154-L159

Play example worked in case Left and sent ready FrameEvent, but Akka Http worked in case Right and sent Message.

If you look at the implementation of the WebSocket.stack method https://github.com/akka/akka-http/blob/294eb5d86568bb42851adff3f07d435d691d3083/akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala#L37-L46 it's not hard to see that automatic keep-alive Ping support in this function https://github.com/akka/akka-http/blob/294eb5d86568bb42851adff3f07d435d691d3083/akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala#L61-L75

Why is automatic keep-alive Ping support exist only in case Right (only Message)? Is it special feature or mistake?

P.S. I continued research library and made some modify which allowed Play example work correctly.

```scala
def buildResponse(key: `Sec-WebSocket-Key`, handler: Either[Graph[FlowShape[FrameEvent, FrameEvent], Any], Graph[FlowShape[Message, Message], Any]], subprotocol: Option[String], settings: WebSocketSettings, log: LoggingAdapter): HttpResponse = {
      val frameHandler = handler match {
        case Left(frameHandler) => WebSocket.stack(serverSide = true, settings).join(frameHandler)
        case Right(messageHandler) =>
          WebSocket.stack(serverSide = true, settings, log = log).join(messageHandler)
      }

def stack(
    serverSide:        Boolean,
    websocketSettings: WebSocketSettings): BidiFlow[FrameEvent, FrameEvent, FrameEvent, FrameEvent, NotUsed] =
    BidiFlow.fromFlows(
      maskIf(!serverSide, websocketSettings.randomFactory),
      periodicKeepAlive(serverSide, websocketSettings)
    )

def periodicKeepAlive(serverSide: Boolean, settings: WebSocketSettings): Flow[FrameEvent, FrameEvent, NotUsed] = {
    settings.periodicKeepAliveMaxIdle match {
      case maxIdle: FiniteDuration =>

        val noCustomData = WebSocketSettingsImpl.hasNoCustomPeriodicKeepAliveData(settings)
        val mkFrame = settings.periodicKeepAliveMode match {
          case "ping" if noCustomData => () => PingFullFrame // sending Ping should result in a Pong back
          case "ping" => () => FrameEvent.fullFrame(Opcode.Ping, None, settings.periodicKeepAliveData(), fin = true)

          case "pong" if noCustomData => () => PongFullFrame // sending Pong means we do not expect a reply
          case "pong" => () => FrameEvent.fullFrame(Opcode.Pong, None, settings.periodicKeepAliveData(), fin = true)

          case other => throw new IllegalArgumentException(s"Unsupported periodic-keep-alive-mode. " +
            s"Found: [$other] however only [ping] and [pong] are supported")
        }
        maskIf(!serverSide, settings.randomFactory).keepAlive(maxIdle, mkFrame)
      case _ =>
        Flow[FrameEvent]
    }
  }
```

@jrudolph What do you think about this?

**Comment by ihostage** [comment]
Hi, Johan @johanandren! 👋 
While Johannes @jrudolph is busy, maybe you are able to share your opinion?
It very needs for us, because if you think that it isn't a problem of Akka HTTP, we will try to fix that on the Play side 😄

**Comment by johanandren** [comment]
I'm guessing the low level (and even marked with internal API) `UpgradeToWebSocketLowLevel.handleFrames` may not be expected to automatically do higher level stuff like keep alive but leave implementing such to the consuming end. 

It's not super clear though, is play using the low level API to provide its own API corresponding to Message or why is it using the low level one?

**Comment by ihostage** [comment]
@johanandren I really don't know why Play uses low level and prepares frames himself 🤷‍♂️ 
Maybe James @jroper remembers, but It was a long time ago 😄 
As my hypothesis, maybe for simplification of support two backend (Netty/AkkaHTTP) 🤔 
But needs to note, that for Netty users is all fine and problem with `keep-alive` only for Akka HTTP users 😞

I think that current question sounds something like this:

> Will we are able to implement `keep-alive` mechanics for case `case Left(frameHandler) => frameHandler` like already implemented for `case Right(messageHandler) => WebSocket.stack(...).join(messageHandler) `. Or you think that it's impossible by some reasons. And If impossible, tell us what reasons?

**Comment by johanandren** [comment]
I think it is safe to implement that on the play side, and that it would be less safe to introduce it here (even if it is marked internal).

**Comment by mkurz** [comment]
I implemented ping/pong support for Play and plan to release that with the next Play 2.8.x version: https://github.com/playframework/playframework/pull/11521

**Comment by johanandren** [comment]
Good to hear, let's close this then.
