### ISSUE TITLE
Content-Type header disappears with custom content type value

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#418]
<a href="https://github.com/Vadi"><img src="https://avatars.githubusercontent.com/u/218148?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Vadi](https://github.com/Vadi)**
_Wednesday Oct 19, 2016 at 14:36 GMT_
_Originally opened as https://github.com/akka/akka/issues/21702_

---

Given I've a route like this -- 

```
path("sid" / IntNumber) { id =>
    post { ctx =>
      ctx.complete(ctx.request.headers.mkString(","))
    }
}
```

When I execute -

```
> curl -H "Content-Type: application/json" -d'{}' -XPOST http://0.0.0.0:8080/sid/123
```

It returns -

```
Host: 0.0.0.0:8080,User-Agent: curl/7.49.1,Accept: */*,Timeout-Access: <function1>%
```

Notice that `Content-Type` header is not returned. However, check this request &mdash;

```
curl -H "Blah: Blue" -H "Content-Type: moon" -d'{}' -XPOST http://0.0.0.0:8080/deployment/123
```

This one returns `content-type: moon` as expected.

```
Host: 0.0.0.0:8080,User-Agent: curl/7.49.1,Accept: */*,Blah: Blue,content-type: moon,Timeout-Access: <function1>%
```

Not sure what the issue is -- How content type value is disappearing when a valid value is sent out. I am using `headerValueByName` directive to implement a custom content type.

**Comment by ktoso** [comment]
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Oct 19, 2016 at 14:38 GMT_

----

ContentType gets special treatment and is stored in `request.entity.contentType`.
I agree though it can be confusing, perhaps we can simplify this so it's the same for all cases

**Comment by jrudolph** [comment]
`moon` is not a valid media-type which needs to contain a slash e.g. like `application/moon`. That's the reason why akka-http cannot parse it and creates a `RawHeader` as a fallback.

Can you explain what you want to achieve? To support multiple content-types for incoming entities you usually need to create a custom `Unmarshaller` using `Unmarshaller.firstOf`.

**Comment by lloydmeta** [comment]
> [<img alt="" width="48" height="48" src="https://avatars.githubusercontent.com/u/120979?v=3">](https://github.com/ktoso) **Comment by [ktoso](https://github.com/ktoso)**
> _Wednesday Oct 19, 2016 at 14:38 GMT_
> 
> ContentType gets special treatment and is stored in `request.entity.contentType`.
> I agree though it can be confusing, perhaps we can simplify this so it's the same for all cases

Currently in the middle of porting a large-ish Spray app and got bit by this. IMHO, it should not be removed from the list of headers. In our case, we have an endpoint that needs to demarshall `application/zip`(just unmarshall the body as bytes) and `multipart/form-data` (look up the `file` form data, treating body as a form).

**Comment by eugeniyk** [comment]
Face this as well, very confusing since Content-Type is one of the main http header and if you're implementing traffic forwarding tool you need to know this "feature" of akka http.
