### ISSUE TITLE
FAILED: HttpExtensionApiSpec - Tcp command [Connect(...)] failed

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#419]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/160/consoleFull

```
[info] - should properly bind and handle a server with a flow (with seven parameters) *** FAILED ***
[info]   java.util.concurrent.ExecutionException: akka.stream.StreamTcpException: Tcp command [Connect(localhost:42995,None,List(),Some(10 seconds),true)] failed
[info]   at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[info]   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1907)
[info]   at scala.concurrent.java8.FuturesConvertersImpl$CF.scala$concurrent$java8$FuturesConvertersImpl$CF$$super$get(FutureConvertersImpl.scala:84)
[info]   at scala.concurrent.java8.FuturesConvertersImpl$CF$$anonfun$get$2.apply(FutureConvertersImpl.scala:84)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.package$.blocking(package.scala:123)
[info]   at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[info]   at akka.http.javadsl.HttpExtensionApiSpec.akka$http$javadsl$HttpExtensionApiSpec$$waitFor(HttpExtensionApiSpec.scala:474)
[info]   at akka.http.javadsl.HttpExtensionApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(HttpExtensionApiSpec.scala:155)
[info]   at akka.http.javadsl.HttpExtensionApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(HttpExtensionApiSpec.scala:145)
[info]   ...
[info]   Cause: akka.stream.StreamTcpException: Tcp command [Connect(localhost:42995,None,List(),Some(10 seconds),true)] failed
```

**Comment by callicles** [comment]
Is there some more Information on this? I got a similar error when trying to use https://github.com/akka/alpakka for s3

Thanks

**Comment by 2m** [comment]
`Tcp command [Connect(localhost:42995 ...] failed` indicates that a connection to `localhost:42995` could not be established. @callicles have you specified the correct URL for the s3 to connect to?

**Comment by jonas** [comment]
This test failure could be the same as what was observed for #824, namely that the port returned by `TestUtils.temporaryServerHostnameAndPort` is grabbed by another process between the probe and bind.

**Comment by callicles** [comment]
I found the issue on alpakka it is not related to that.

**Comment by JPrakashM** [comment]
I face same issue previously,  for me it is working as expected.

val httpClient: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] = Http().outgoingConnection(host,port,None,connSetts)
Problem place 👍  Source.single(request).via(httpClient)

It is unable to connect my host so i use proxy server for this.

val httpsProxyTransport : ClientTransport = ClientTransport.httpsProxy(InetSocketAddress.createUnresolved("proxyservicesHost", 90))
  val connSetts: ClientConnectionSettings = ClientConnectionSettings(system).withTransport(httpsProxyTransport).withIdleTimeout(Duration(180, "second"))
  val httpClient: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] = Http().outgoingConnection(host,port,None,connSetts)

Then i pass the httpclient in .vai(httpclient ), It work
