### ISSUE TITLE
Failed: OutOfMemoryError

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4193]
JDK 8, Scala 2.13 in the nightlies: https://github.com/akka/akka-http/actions/runs/3475885488/jobs/5810584292#step:7:928

Reached UriTest before running out. Could be something with the recent CI JDK bumps.

**Comment by johanandren** [comment]
Three different flows got JDK 8 OOM last night: https://github.com/akka/akka-http/actions/runs/3484847544

**Comment by ennru** [comment]
Fixed with #4200
