### ISSUE TITLE
[10.5.0-M1] Using Scala-3 artefacts crash the compiler

### ISSUE THREAD

**Issue by mushtaq** [akka/akka-http#4194]
Even though M1 artefacts are published for scala-3, they are not usable.
This one liners crashes the compiler:

```scala
$ echo demo.sc
//> using scala "3.2.1"
//> using lib "com.typesafe.akka::akka-http:10.5.0-M1"

println(akka.http.scaladsl.model.HttpEntity)

$ scala-cli compile demo.sc
Compiling project (Scala 3.2.1, JVM)
exception occurred while compiling /Users/mushtaqahmed/projects/scala3/scripts/.scala-build/project_0676cca331-7fb9ff8688/src_generated/main/akka-http-compiler-crash.scala
Error compiling project (Scala 3.2.1, JVM)
Error: Unexpected error when compiling project_0676cca331-7fb9ff8688: 'assertion failed'
Compilation failed
```

**Comment by johanandren** [comment]
Creating a new project from the g8 template akka/akka-http-scala-quickstart.g8 with Scala 3.2.1 compiles/tests and runs without problems, could it be related to single-file-scripting like that somehow perhaps?

**Comment by mushtaq** [comment]
Even with the g8 template, one can [reproduce it](https://github.com/mushtaq/akka-http-4194).

But, if you uncomment the `akka-stream` dependency `build.sbt` (or add the dependency in the script above), the issue gets fixed.

No idea why!

**Comment by johanandren** [comment]
When does it fail for you with the template? Compiling, running, issuing a specific request?

**Comment by johanandren** [comment]
Aha, so with the dependency in place it works, only when it is pulled in transitively. We should investigate this but then there is at least a very easy workaround (and that explains why the template works out of the box).

**Comment by mushtaq** [comment]
Fails during compilation.

Yes, the workaround is great for now.

If fact, `akka-stream` is a provided dep of `akka-http`, hence the [doc mention](https://doc.akka.io/docs/akka-http/current/introduction.html#using-akka-http) that it has to be explicit. 

But compiler crash is still unexplainable.

**Comment by johanandren** [comment]
I actually do not get a compiler crash but an error saying that classes are not available:

```
[info] compiling 4 Scala sources to /Users/johan/Code/my-akka-http-project/target/scala-3.2.1/classes ...
[error] undefined: new
[error]   akka.stream.stage.GraphStage[
[error]     akka.stream.FlowShape[akka.util.ByteString,
[error]       akka.http.impl.engine.parsing.BodyPartParser.Output
```

Curious that it would be different between environments with the same Scala version.

**Comment by johanandren** [comment]
I think this is more of an issue with the compiler than something specifically with our artifacts, so please report upstream to the Scala 3 project (https://github.com/lampepfl/dotty).

**Comment by johanandren** [comment]
Thanks, closing this then, I don't think there is anything to do on our side.
