### ISSUE TITLE
Un-preview http2 server

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4218]
The HTTP/2 server has been production ready for quite a while but the setting is still `akka.http.server.preview.enable-http2`, can we remove the setting completely, default to true, or at least make it `akka.http.server.enable-http2`?

**Comment by patriknw** [comment]
> or at least make it akka.http.server.enable-http2

For compatibility we can still keep the `preview.enable-http2` and read from both or make the new an alias
```
akka.http.server.enable-http2 = ${akka.http.server.preview.enable-http2}
```
