### ISSUE TITLE
`handleRejections` directive rebuilds route hierarchy

### ISSUE THREAD

**Issue by GeluOltean** [akka/akka-http#4223]
The `handleRejections` directive seems to re-evaluate and rebuild its entire inner route hierarchy when the routes are chained/concatenated inline, within the `handleRejections` block directly, e.g:

```scala
val routes: Route =
  handleRejections(rejectionHandler) {
    Controllers.Controller1(dep1).routes ~
      Controllers.Controller2(dep1, dep1).routes
  }

// or
  handleRejections(rejectionHandler)(Controllers.Controller1(dep1).routes ~
    Controllers.Controller2(dep1, dep1).routes)
```

However, when moving out the routes into a value in an outer scope, everything works as expected:

```scala
val chainedRoutes: Route =
  Controllers.Controller1(dep1).routes ~
    Controllers.Controller2(dep1, dep1).routes

val routes: Route =
  handleRejections(rejectionHandler) {
    chainedRoutes
  }
// or
  handleRejections(rejectionHandler)(chainedRoutes)
```
Once a request is received, the definition in first block will cause the inner routes to be rebuilt before said request is served.

Demo of this happening is [available here](https://github.com/GeluOltean/akka-http-route-chain-eval).

**Comment by johanandren** [comment]
This is true for all directives, as they at the core are `T => Route` (`T` being `Unit` in the case of `Directive0`), the route tree is lazily built on request, not fully on route root construction or server bind.
