### ISSUE TITLE
Get timeout for `RouteTestTimeout` from the configuration file

### ISSUE THREAD

**Issue by MiguelMarcelino** [akka/akka-http#4238]
`RouteTestTimeout` uses a default timeout of 1 second. This can cause test failures when there is heavy use of testing or if many tests run in parallel in a CI environment. This causes the requests not to be completed within the expected 1 second window.

`RouteTestTimeout` should get the timeout from the configuration file. I have seen some [similar changes](https://github.com/akka/akka-http/issues/2127) done to `MarshallingTestUtils`. We could maybe add this feature to `RouteTestTimeout` as well.

**Comment by johanandren** [comment]
Sounds like a good idea to allow config. 👍
