### ISSUE TITLE
Failed: Http2PersistentClientTlsSpec when waiting for a response

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4243]
https://github.com/akka/akka-http/actions/runs/4474855377/jobs/7863714930#step:7:1976

```
2023-03-21T02:22:42.2809273Z [info]   - should when waiting for a response *** FAILED *** (306 milliseconds)
2023-03-21T02:22:42.2840797Z [info]     java.lang.AssertionError: No severe log messages should be emitted during test run but got [1] warnings and [0] errors (see marked lines above)
2023-03-21T02:22:42.2841595Z [info]     at akka.http.impl.util.WithLogCapturing.withFixture(WithLogCapturing.scala:77)
```

[http2persistentclientfail.txt](https://github.com/akka/akka-http/files/11039501/http2persistentclientfail.txt)

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/4580764617/jobs/8089764590#step:7:2190

**Comment by octonato** [comment]
**Compile and test (3.2, 1.8, main)**
https://github.com/akka/akka-http/actions/runs/4943244959/jobs/8837533393#step:7:2364

**Compile and test (3.2, 1.7, main)**
https://github.com/akka/akka-http/actions/runs/4943244959/jobs/8837533762#step:7:2275

**Comment by octonato** [comment]
**Compile and test (3.2, 1.8, main)**
https://github.com/akka/akka/actions/runs/4953727716/jobs/8861506809#step:5:2673

Failed on same job as above, but on a different build.

**Comment by octonato** [comment]
https://github.com/akka/akka-http/actions/runs/5029876815/jobs/9021892632#step:7:2239

**Comment by johanandren** [comment]
I have a fix waiting for review in https://github.com/akka/akka-http/pull/4260

**Comment by octonato** [comment]
fixing in #4260
