### ISSUE TITLE
scaladsl HttpRequest provides no means to lookup non built-in headers

### ISSUE THREAD

**Issue by jroper** [akka/akka-http#4268]
If I want to look up a header from a scaladsl `HttpRequest` that isn't built-in to Akka HTTP, there's no means for me to do this, other than manually search through the headers, making sure that I do a case insensitive match when I do this, and being very careful to avoid the Turkish i bug, ie:

```scala
val req: HttpRequest = ...
val headerName = "Different-Header".toLowerCase(Locale.ROOT) // <-- almost everyone forgets this and then the code breaks in Turkey
val header = req.headers.find(_.is(headerName))
```

It doesn't matter whether you try to model it yourself using `ModelledCustomHeader`, or if you just want to get a `RawHeader`, there simply doesn't exist any API in the scaladsl to do either. There does exist a `Optional<String> getHeader(String name)` in the Java API, but no equivalent in the Scala API.

There needs to be at least some convenient method to lookup custom headers from `HttpRequest` in the Scala API. Some options include:

* Provide a `rawHeader(name: String): Option[String]` method that does the same as the Java `getHeader` method.
* Modify the existing `header` method, so that if the initial lookup fails, and perhaps, if the incoming type implements `CustomHeader`, parse it using that types companion. The main problem here is that I don't think there's any way to implicitly get the modelled companion of a header type, we'd have to modify it to provide this everywhere, not sure if that could be done in a parent class somewhere or not. I'm pretty sure that this could be done in a both binary and source compatible way - binary compatible by keeping the existing `header` method to accept a non implicit `ClassTag`.
* Add a new overloaded `header` method that accepts the Modelled companion as a non implicit field, and does the above logic.

**Comment by johanandren** [comment]
I think a `header(name: String): Option[sm.Header]` matching the Java DSL sounds good, or if that is somehow conflicting with the existing `header` method `rawHeader` sounds like a reasonable name.
