### ISSUE TITLE
Replace Akka with Akka-http in Contributing file

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#429]
Currently the Contributing file is the same one from the main Akka project.
Instructions still refer to the Akka project instead of the akka-http project in some points. For example:

- [ ] Branches summary
- [ ] Project name under Tags
- [ ] Contributing guidelines headline
- [ ] General workflow project name to fork
- [ ] TL;DR; section under General workflow refers to fork akka project
- [ ] Pull Request project mention
- [ ] JavaDoc project mention
- [ ] Reference to akka-contrib

I know it's still understandable, but maybe it's worth fixing it.

**Comment by ktoso** [comment]
Would you be able to help us out on this please?
We're trying to polish other things needed for the as-soon-as-possible release right now, thus any help would be very welcome - thanks!

**Comment by jlprat** [comment]
I'm on it

**Comment by ktoso** [comment]
Awesome, thanks a lot :)

**Comment by jlprat** [comment]
Didn't modify the Test section, as I don't know which are the guidelines for it

**Comment by ktoso** [comment]
Thanks, testing I think does not really change hm
