### ISSUE TITLE
host-connection-pool.min-connections property with positive value

### ISSUE THREAD

**Issue by waagnermann** [akka/akka-http#4294]
Here is the quote from docs of akka-http [configurartion](https://doc.akka.io/docs/akka-http/current/configuration.html):

> # If the number of connections is falling below the given threshold, new ones are being spawned.

My question is connections with WHO are spawned at the moment of server's start if I specify host-connection-pool.min-connections setting's value to 5, for instance?
if at the start server doesn't know if there will be any hosts establishing connections with it

**Comment by johanandren** [comment]
Cross post of question in forum https://discuss.lightbend.com/t/host-connection-pool-min-connections-property-with-positive-value/10439, so closing this for now.
