### ISSUE TITLE
Apache Access Log directive appears to close the connection

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka-http#432]
I seem to have some offending code. If I (essentially) comment out the block of code at https://github.com/derekwyatt/ahalog/blob/master/src/main/scala/org/derekwyatt/ahalog/AhaLogDirectives.scala#L49 then connections appear to be used efficiently.

I use the `AhaLogDirectives` to wrap my HTTP route in `accessLog()`, which gives me an apache-style log in my server. It's a great log to have around and I love it, but... there's something about that `map` that is causing the connections to die.

If I leave that code in, my Akka test client is continually making new connections, but if I take it out, the connections are nicely persistent.

I've tried to spot my flaw but have failed to do so.  Can anyone see what's going on here?

**Comment by jrudolph** [comment]
I don't see anything at first glance. Can you try to find out what exactly causes the connection to be closed and in which way? Maybe use some tools like http://httpbin.org/ or ngrok to capture a broken request - response cycle and report it here. E.g. does it still work if you remove the `transformDataBytes` bit?

**Comment by jrudolph** [comment]
Closing. Feel free to reopen if the problem persists and you have more information.
