### ISSUE TITLE
Improve docs structure for stable release

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#436]
Tasks:

 * [x] Go through page tree and see if it makes sense and otherwise add tasks here
 * [x] Clean up document structure as shown in the top-level TOC
 * [x] Figure out where to put migration notes per version (release notes or somewhere else?)

**Comment by jonas** [comment]
Paradox uses the title of the top level page as the site title, thus docs/src/main/Paradox/index.md should be titled "Akka HTTP".

**Comment by jrudolph** [comment]
First steps have been done in #1638. I guess we'll keep on the look for further improvements.
