### ISSUE TITLE
Configure cross version build for Scala 2.12

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#437]
Akka 2.4.11 was released for 2.12.0-RC2 so Akka HTTP should also provide artifacts for Scala 2.12.

**Comment by ktoso** [comment]
Very true, let's make it ship for 12 on release :)
We checked 2.12.0-RC2 on Akka 2.4.11 and it works, so this should not run into any weird issues, just a matter of setting up dependencies.

**Comment by jonas** [comment]
@ktoso Was the tests run for 2.12? I am seeing several failures likely linked with differences between 2.11 and 2.12

**Comment by jonas** [comment]
OK, sanity restored.

**Comment by patriknw** [comment]
There is also an issue with scaladoc due to `sealed abstract class HttpCredentials`.

We have many other sealed abstract class in the http-core model, but maybe it's only this HttpCredentials that is extended from java?

This was originally reported by @SethTisue in https://github.com/akka/akka/issues/21543

**Comment by jrudolph** [comment]
Interesting, I somehow missed the old issue. I'll have a look...

**Comment by jonas** [comment]
Does this issue affect publishing of the 2.12 artifacts or can we put it in a separate ticket and mark as a future improvement.

**Comment by jrudolph** [comment]
Yes, we won't be able to release a docs artifact as long as this is not fixed.

We decided that removing the `sealed` modifier is ok and shouldn't break anything. It should be replaced by a comment that extending these classes with third-party implementations is not supported right now.

**Comment by ktoso** [comment]
Just saw https://github.com/akka/akka-http/pull/447#issuecomment-257530888 so... are we ready to publish 2.12 or not yet? (not sure which comment was written first ;-))

**Comment by jonas** [comment]
We need to validate scaladex generation for 2.12 and it would be nice to configure at least nightly builds for 2.12 unless we do that as part of the Travis ticket.

**Comment by wsargent** [comment]
Play also has a dependency on akka-http https://github.com/playframework/playframework/issues/6110

**Comment by ruippeixotog** [comment]
So, are there any updates about this? As more and more libraries release artifacts for 2.12.0, akka-http is starting to become the last blocker in many of the projects I work with.

Is there anything I can do to help? Thanks in advance for your effort on this :)

**Comment by adamw** [comment]
@ruippeixotog There's 10.0.0-RC2 which is cross-built for 2.12 (see e.g. akka-http-session build). I don't know the timeline, but I suspect a final release to be available soon.

**Comment by ktoso** [comment]
Yeah 10.0.0-RC2 is available, we didn't announce - will do so on this monday.
And I hope to release a stable as soon as we can (been trying to since last week).

Sorry for the wait, but we're very close.

**Comment by ktoso** [comment]
This task is blocking the stable release for example: https://github.com/akka/akka-http/issues/517
So for Akka HTTP the thing that's slow is making the first stable release from the new repo, 2.12 we're ready (and did release 10.0.0-RC2 for it already).

**Comment by ktoso** [comment]
Cross building solved in https://github.com/akka/akka-http/pull/544
RC2 was already for 2.12.0, and so will 10.0.0 👍

**Comment by SethTisue** [comment]
@ktoso if this is done, could you submit an update to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md ?

**Comment by SethTisue** [comment]
@ktoso is this done?

**Comment by ktoso** [comment]
Yes, and we're released against 2.12 as well :-)
http://search.maven.org/#artifactdetails%7Ccom.typesafe.akka%7Cakka-http_2.12%7C10.0.0%7Cjar
