### ISSUE TITLE
The akka.http.cors package is not exist

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [akka/akka-http#4374]
I am using Java and my akka http dependency is as follows:  xml    <dependency>       <groupId>com.typesafe.akka</groupId>       <artifactId>akka-http_3</artifactId>       <version>10.6.0-M1</version>   </dependency> On the official website, I read that "The directive uses config defined under akka.http.cors, or an explicitly provided CorsSettings instance." However, I cannot find the akka.http.cors package. How can I resolve the CORS issue?

**Comment by johanandren** [comment]
The CORS support was introduced with the 10.6.1 release so you need to upgrade to use it. You should see what version of the library the docs are for by the version number up top left on the documentation navigation bar.
