### ISSUE TITLE
Consider @Experimental / @ApiMayChange markers on APIs - LOOKING FOR NAMES

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#438]

**Comment by patriknw** [comment]
Experimental means so many different things for different people. Shall we try another name?

`@ApiMayChange` ?

**Comment by ktoso** [comment]
Yeah, absolutely let's talk about the names to use here.
I think the Hadoop ecosystem has started using various annotations like that years ago as well, let's see if naming there could inspire us. Names that have good meaning would be best here than the `experimental` which in Akka up until this day even people are confused about

**Comment by ktoso** [comment]
One I'd like to add is something among the lines of `@NotMeantToBeExtended` - specifically for the HTTP model.

**Comment by jonas** [comment]
Here's a link to Spark's API annotations some of which looks to be overlapping: https://github.com/apache/spark/tree/master/common/tags/src/main/java/org/apache/spark/annotation

As for name Spark use `InterfaceStability`.

**Comment by patriknw** [comment]
Something like that looks good. I think we should use same in Akka core. Perhaps Stable is the default if no annotation is given.

**Comment by jlprat** [comment]
@ktoso for the "Not meant to be extended", I know JBoss Drools packs all those classes under the `internal` package. It's pretty clear that if you depend on something under the `internal` package, you can't expect stability, or actually relay in any way on this.

**Comment by ktoso** [comment]
Due to the design of our HTTP Model it is "not meant to be extended" however it is very much public API. It can not be final, due to scaladsl is-a javadsl - this saves impl complexity and allocations :)

Will think and propose names soon, feel free to propose some :)

**Comment by jlprat** [comment]
I see... then the internal makes no sense

**Comment by ktoso** [comment]
Let's start simple:

- `@InternalAPI` - equivalent of current `/** INTERNAL API*/` comments, we'll work on MiMa to be aware of these (!) so no filtering out when touching such classes/methods will be needed
- `@APIMayChange` - To mark new "experimental" APIs, such as the #662 API

These annotations will land immediately in akka.actor, we'll use them from there in Akka HTTP.

Hope this sounds good, cheers!

**Comment by ktoso** [comment]
This will be sovled in Akka itself .
PR for annotations in Akka: https://github.com/akka/akka/pull/22110
