### ISSUE TITLE
X-Forwarded-For includes the port

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka-http#440]
`X-Forwarded-For` contains a sequence of `RemoteAddress` objects, but they contain the port and the render doesn't seem to take this into account.  If I create this on the client side:

``` scala
HttpRequest(headers = List(`X-Forwarded-For`(addr)))
```

Then I see this when the same request is seen by an Akka server:

```
Illegal request header: Illegal 'x-forwarded-for' header: Invalid input ':', expected HEXDIG, h8, listSep or 'EOI' (line 1, column 16): 0:0:0:0:0:0:0:1:60052
```

**Comment by jrudolph** [comment]
Thanks, @derekwyatt. Does that only happen with IPv6 addresses?

**Comment by derekwyatt** [comment]
@jrudolph It's both.  I added a couple of tests to verify it, but fixing it is a bit of problem.  I can easily change the `RemoteAddress` instances just-in-time for rendering but the test fails with:
```
Ok(X-Forwarded-For: 1:2:3:4:5:6:7:8,List()) did not equal Ok(X-Forwarded-For: 1:2:3:4:5:6:7:8,List()) (HttpHeaderSpec.scala:693)
```
Changing them prior to construction would be better, but that's tricky due to the duplicate signatures.  e.g.
``` scala
def apply(addrs: immutable.Seq[RemoteAddress]): `X-Forwarded-For` = // transform here
...
final case class `X-Forwarded-For`(addresses: immutable.Seq[RemoteAddress]) 
```
I could create `RemoteIPAddress` to make a truly type-safe way of doing it, but that might be overkill.

Thoughts?

**Comment by jonas** [comment]
I played around with this and the bug also affects `X-Real-Ip`.

@jrudolph What is the reason for failing tests if the round-trip fails? (i.e. `parsedHeader != origHeader`)?

If this constraint cannot be lifted we need to make the main constructor private for those headers so the port can be removed from `RemoteAddress.IP` before passed to `X-Forwarded-For` or `X-Real-Ip`. Not sure what options are available if we want to ensure bincompat.

**Comment by jrudolph** [comment]
> @jrudolph What is the reason for failing tests if the round-trip fails? (i.e. parsedHeader != origHeader)?

WDYM? The round-trip is required so that we test both the parsing and the rendering. You can turn off checking the rendering if that's not what you want.

**Comment by jonas** [comment]
The easiest way to fix X-Forwarded-For and X-Real-Ip is to change their
rendering to not print the port. Right now the tests ensures that the
initial value given can be constructed by first rendering and then parsing.
If you say this constraint can be relaxed for these two headers I can make
a PR.

**Comment by jrudolph** [comment]
> The easiest way to fix X-Forwarded-For and X-Real-Ip is to change their
> rendering to not print the port.

Would that mean that if we would emit the header the port would just be missing?

**Comment by jonas** [comment]
Yes.

**Comment by jrudolph** [comment]
Fixed by https://github.com/akka/akka-http/pull/974.
