### ISSUE TITLE
Failed: compiling against Akka main because scala java 8 compat dropped 

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#4417]
Fall out from https://github.com/akka/akka/pull/32435

Failing nightlies Akka HTTP was relying on a transitive dependency.

Fyi @sebastian-alfers this would be nice to fix next since CI is failing.

**Comment by sebastian-alfers** [comment]
Taking a look.

**Comment by sebastian-alfers** [comment]
https://github.com/akka/akka-http/pull/4418
