### ISSUE TITLE
S3 doesn't interpret URI paths with `+` signs correctly vs. Akka HTTP normalizing URIs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#451]
According to an [AWS forum post](https://forums.aws.amazon.com/thread.jspa?messageID=722673), S3 mistakenly interprets `+` signs in the *path* portion of an URI as a space character. Instead, a file with a `+` sign in its path needs to be accessed by using the percent encoded representation of the plus sign, `%2b`. This is in violation of [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.3) which mandates that a literal plus sign or its percent encoded form are to be treated as equivalent. (Note, how this is different from the interpretation of the query portion of an http uri in which `+` signs actually *are* to be interpreted as a space character.)

Akka HTTP will never send out the `+` sign as percent encoded because it normalizes URIs on creation. This means that it isn't possible to access a file in S3 that contains a `+` sign in its path using Akka HTTP's URIs. 

As a workaround, you can use the synthetic `Raw-Request-Uri` header to render the URI yourself and force Akka HTTP to send a plus sign in its percent encoded form like this:

```scala
HttpRequest(uri = "/ignored", headers = List(Raw-Request-URI("/a/b%2Bc/")))
```

I put the issue here to help people who also run into this problem. To resolve it we should document the issue more prominently.

**Comment by ktoso** [comment]
Agree that this is something we can put into docs, thanks for the writeup.

**Comment by easel** [comment]
For reference, the working incantation is actually this:

      import akka.http.scaladsl.model.headers.`Raw-Request-URI`
      val x = HttpRequest(uri = "/ignored", headers=List(`Raw-Request-URI`("/a/b%2Bc")))
