### ISSUE TITLE
Follow Same Content Structure for Java and Scala Documentation

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#453]
Currently under http://doc.akka.io/docs/akka-http/current/ Scala and Java documentation have different order in their sections. It would be beneficial to follow the same content order for both languages.

Current Java's content order is:
* Low-Level Server-Side API
* Server-Side WebSocket Support
* High-level Server-Side API
* Consuming HTTP-based Services (Client-Side)
* Common Abstractions (Client- and Server-Side)
* Implications of the streaming nature of Request/Response Entities
* Configuration
* Server-Side HTTPS Support
* Migration Guides (Java)

Current Scala's content order is:
* Introduction
* Configuration
* Common Abstractions (Client- and Server-Side)
* Implications of the streaming nature of Request/Response Entities
* Low-Level Server-Side API
* High-level Server-Side API
* Consuming HTTP-based Services (Client-Side)
* Server-Side HTTPS Support
* Handling blocking operations in Akka HTTP
* Migration Guides

**Comment by jlprat** [comment]
More issues will come for missing points on missing sections for Java content

**Comment by ktoso** [comment]
Good observation, thanks - would you please submit a PR addressing as much
as possible given the current written content? Thanks a lot.

-- 
Konrad Malawski

**Comment by jlprat** [comment]
Related issues #454 and #455

**Comment by jlprat** [comment]
I think I can do a PR with this resorting later today

**Comment by jlprat** [comment]
Just realized these following sections are not as a main topic in the Scala index:
* Server-Side WebSocket Support <-- this is part of the High-level Server-Side API section for the Scala docs
* HTTP Model <-- this is part of the Common Abstractions (Client- and Server-Side) section for the Scala docs

**Comment by ktoso** [comment]
Thanks for your help here!

**Comment by jlprat** [comment]
Does it make sense to add `Server-Side WebSocket Support` and `HTTP Model` as main topic in Scala docs?
Some people miss it from the docs as it can be seen here: https://groups.google.com/forum/#!topic/akka-user/D0Tg8txHGIk

**Comment by ktoso** [comment]
Yeah, please split it out if you have some time - would be awesome.

**Comment by jlprat** [comment]
Created #465
