### ISSUE TITLE
Add Introduction is Akka-Http documentation section for Java

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#454]
Scala documentation contains a section called introduction where the project is introduced, this section is missing in the Java counterpart.

**Comment by ktoso** [comment]
Thanks, good point - could up submit a PR adding it? Thanks in advance.
Can be a copy adjusted eith java wording.

**Comment by jlprat** [comment]
I guess also with Java code snippets, right?

**Comment by ktoso** [comment]
Yes if it has samples those should be made java. Should be fairly simple with the new javadsl it's very similar to the scala one.

Thanks a lot!

**Comment by jlprat** [comment]
For the code samples that involve some `case class`, should I add them as inner classes?

**Comment by ktoso** [comment]
Yeah, precisely :) Thanks!

**Comment by jlprat** [comment]
I have 3 out of 6 snippets translated to Java, do you want me to do a WIP pull request, so those files can already be checked if you have any comment?

**Comment by ktoso** [comment]
Sure :) might as well catch something early :)
Thanks a lot!
