### ISSUE TITLE
Integrate with akka-http-core under a flag

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#463]
Advantages of merging into akka-http-core:
 * no code changes necessary to use HTTP/2 (when already using HTTPS)
 * this showcases our claim that HTTP/2 can be supported transparently
 * so, everyone can try HTTP/2 just by flipping a switch
 * "feature switches" are a best practice and seem to be successful in other large projects like the Linux kernel

Disadvantages:
 * people might get confused about what it means that stable akka-http-core contains an experimental implementation
 * for production-level HTTP/2 support users might want to add third-party components anyway using netty-openssl as an alternative, faster TLS backend

**Comment by ktoso** [comment]
It's also a timing question. We can always "merge it in" once we're somewhat confident in it.
For now let's continue as separate experimental module, and once happy with it we can merge it in.

@patriknw once mentioned that releasing with `-experimental` was in general not that useful. Do you think we should not have the marker in the artifact name?

**Comment by viktorklang** [comment]
If the feature is completely transparent to the end user, I see no issue having an experimental feature flag.

**Comment by ktoso** [comment]
There's two things:

- flag in code to enable this (possibly not needed)
- marking the feature as experimental (and how to best go about this)

**Comment by patriknw** [comment]
It's not about useful, it's about that we can't promote an experimental feature without releasing a new major version. The typical example is akka-distributed-data-experimental that has been ready for promotion for ages, but we can't do it until Akka 2.5.

The reason it can't/shouldn't be done in a patch release is that it's too easy to end up with multiple jar files (transitive dependencies) with the same classes and accidentally use the wrong version.

**Comment by patriknw** [comment]
I think experimental should be in documentation and in opt-in config feature flag if that makes sense. The annotation we talked about elsewhere is also useful.

**Comment by jrudolph** [comment]
> flag in code to enable this (possibly not needed)

The idea of directly merging it into akka-http-core is not to provide any extra entrypoints. The flag would be the only thing needed to enable Http/2 on HTTPS server bindings. It would be switched off by default and would come with documentation (e.g. in `reference.conf`) that the feature is still experimental.

Apart from that I think there's another dimension that we need to decide about when we actually maintain that code inside of the master branch. Maintaining an extra branch has some cost as well as maintaining code in the master branch (where PR validation runs all the time and it will be included in releases).

But maybe let's start with making it useful at all and then come back here ;)

**Comment by ktoso** [comment]
> > flag in code to enable this (possibly not needed)
> The idea of directly merging it into akka-http-core is not to provide any extra entrypoints. The flag would be the only thing needed to enable Http/2 on HTTPS server bindings. It would be switched off by default and would come with documentation (e.g. in reference.conf) that the feature is still experimental.

Yeah I know, in code I meant in our code :)

I forgot we have it on a separate branch right now.
I propose we merge it to `master`, and continue our work in the separate module - then revisit this issue once it's actually usable. We can always start from separate module and "merging" the module into akka-http-core

**Comment by ktoso** [comment]
We've merged to master and continued work, we'll have the upgrade mechanism in place so it could be opt in via "enable allowing to upgrade" eventually. But it's not at that level yet, closing this ticket though.

**Comment by ktoso** [comment]
Or no... I only read the last comments, not the initial one - the finally merging into `core` or not is undecided yet.

**Comment by jrudolph** [comment]
There's also a third alternative:

 * keep the project structure
 * still provide a flag under akka-http-core and use reflection to access Http2 entry points when the flag is set (and document that the extra artifact is needed for http2 support)
