### ISSUE TITLE
HTTP/2: implement upgrade switch between Http/2 Http/1 based on TLS ALPN

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#464]
Currently, we have the Http/2 stack hard-wired regardless of whether a client actually support Http/2. We need to support fallback to the Http/1.1 stack depending on what the client sends out via ALPN.

**Comment by ktoso** [comment]
I refer to this as "ALPN Upgrade support", wrong wording in my vocabulary?

**Comment by jrudolph** [comment]
Yep, agree will change the title.

**Comment by 2beaucoup** [comment]
Would this make it possible to have generic `bindAndHandleX` and friends?

**Comment by jrudolph** [comment]
Generic `bindAndHandle` could be the next step. The change here is a mandatory requirement to be able support Http/2 and Http/1 clients on a single port.

**Comment by ktoso** [comment]
This is in progress right?
