### ISSUE TITLE
Publish Akka-http Java and Scala API docs

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#475]
Maybe this ticket already existed, but I couldn't find it.
Currently the Java and Scala docs are published under http://doc.akka.io/docs/akka-http/current/
However, the Java and Scala API is nowhere to be find for the 3.0.0-RC1

**Comment by ktoso** [comment]
Thanks for the ticket, yes this needs to be done.

**Comment by jlprat** [comment]
I would say this is done

**Comment by ktoso** [comment]
True, thanks for cleaning up!
