### ISSUE TITLE
PathMatcher documentation is broken

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#476]
See http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/path-matchers.html

![screenshot from 2016-11-03 14 54 10](https://cloud.githubusercontent.com/assets/9868/19968563/6aefa67c-a1d5-11e6-9703-6e277010b893.png)

**Comment by jlprat** [comment]
How can I generate the paradox output locally, so I can check the output?

**Comment by ktoso** [comment]
Thanks for the help!
This is documented here https://github.com/akka/akka-http/blob/master/CONTRIBUTING.md#documentation

**Comment by jlprat** [comment]
Fixed what I saw:
* Empty lines on operators
* Table Render
* unary_! as title
