### ISSUE TITLE
Improve logging in the GraphStages

### ISSUE THREAD

**Issue by gosubpl** [akka/akka-http#482]
This is something that went as a part of story around hardening the connection pool to protect against pool failures due to failed futures propagating from single slots. During the review the improved logging in PoolConductor was removed from the PR as not being in the scope. I would still like to include those changes.
This task changes the entries in the logs to use a more consistent style prevalent in other GraphStages. I will attach a PR to this. If you don't find this useful, please close this issue.

**Comment by ktoso** [comment]
Sounds good, thanks!

**Comment by gosubpl** [comment]
As per @2beaucoup 's comment:
```
val thingIn = Inlet[ThingClass]("MyClass.thingIn")
val thingOut = Outlet[ThingClass]("MyClass.thingOut")
```
all the things :)

**Comment by jrudolph** [comment]
Solved by #483 IIUC.

**Comment by 2beaucoup** [comment]
#483 just fixed `PoolConductor`. We might want to keep this open for the remaining graph stages.

**Comment by gosubpl** [comment]
Wait for me wait for me :) I am on track to submit a PR with all stages this weekend...

**Comment by jrudolph** [comment]
Oh sorry. Reopening... Thanks for tackling this, @gosubpl.
