### ISSUE TITLE
Provide access to matched path

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka-http#496]
This could be either added to the request context or extracted with a special directive.

See #6.

**Comment by 2beaucoup** [comment]
We could extract this from the [`FileAndResourceDirectives` impl](https://github.com/akka/akka-http/blob/555a31f0c7e6782267e9123ae7465ea88ae8b6db/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L151-L156).

**Comment by rbudzko** [comment]
@jrudolph Shall we close?

**Comment by ktoso** [comment]
Yes, thanks.
If a ticket contains "Resolves #...." it would auto close btw :)
