### ISSUE TITLE
Feedback of assertHeaderExists can be improved

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#5]
Currently, `akka.http.javadsl.testkit.TestRouteResult.assertHeaderExists(expectedHeader)`, when the header has a different value, will simply say `"Header $expected was missing."`. That's not very useful if you're trying to diagnose what's wrong with your actual returned header

Much more useful would be `"Expected $expected, but instead got $actualHeadersWithThatName"`

**Comment by rbudzko** [comment]
@ktoso Shall we close?

**Comment by 2beaucoup** [comment]
Done. Thanks again Robert!
