### ISSUE TITLE
Where to publish scaladoc/javadoc

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#517]
We should put them on doc.akka.io and it should be part of the release script.

I think @2m mentioned it's possible to put those into the tech hub as well...?

**Comment by 2m** [comment]
Yes, techhub can consume jars with scaladoc and serve them.

**Comment by ktoso** [comment]
Could you set this up here next week?

**Comment by ktoso** [comment]
Resolved by https://github.com/akka/akka-http/pull/534
