### ISSUE TITLE
Document how to reply with 404 when Source completing request is empty

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#525]
Normally empty source will be rendered as `[]` etc, which is valid.
We could document how to render 404 in that case

**Comment by jrudolph** [comment]
But you could only do this for a known empty source, right? Seems like a potentially confusing feature to me.

**Comment by ktoso** [comment]
Well is a source completes without any elements sent then it could be interpreted as 404.
It's more of a docs thing how to build such thing than a feature.

**Comment by jrudolph** [comment]
The objection here is that you might have sent out response status and headers before you detect a source to be empty. So, I don't see how you could solve this reliably. Closing for now because of lack of interest or solutions.
