### ISSUE TITLE
Http2: Ignore trailing headers for now

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#531]
Before we get to supporting trailing headers (#530) we might just want to ignore them.

However, trailing HEADERS frames need to be "actively ignored" because they change the state of the header compression so we need to receive and decompress the headers even if we don't push them to the user.

**Comment by ktoso** [comment]
I'll just add this now, should be simple.

**Comment by ktoso** [comment]
Actually wasn't, leaving for now.

**Comment by jrudolph** [comment]
Fixed by #531.
