### ISSUE TITLE
ByteStringParser doesn't backpressure

### ISSUE THREAD

**Issue by drewhk** [akka/akka-http#532]
It uses emit which will buffer outgoing elements and will instantly call pull in a loop. It should instead properly propagate backpressure from the outgoing side to the input (with buffering input data as much needed).

(ported from https://github.com/akka/akka/issues/21838)

**Comment by drewhk** [comment]
Meh, ByteStringParser is in Akka-Stream :(

**Comment by viktorklang** [comment]
@drewhk I guess your plan will be: Create a copy in akka-http, deprecate/remove the one in akka.stream and fix the issue in the "new" version?

**Comment by drewhk** [comment]
Well, turns out that we want to make this public at some point so it was moved from *there* to *here*. So I fix it here then

**Comment by viktorklang** [comment]
@drewhk Ok
