### ISSUE TITLE
MediaRange.matches ignores parameters while matching

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#535]
At the moment, `MediaRange` ignores parameters while matching (and trying to find an unmarshaller). This makes it hard to implement things like `application/json; apiVersion=1` and `application/json; apiVersion=2` being handled by separate unmarshallers.

On the other hand, it's of course also a common scenario to say "accept this media type and any parameters". But since none of the built-in media types have any parameters, could we just extend the default implementations of `MediaRange.matches` to _also_ check if all of the defined props are present in the candidate?

e.g. for `Custom` (see `MediaRange.scala`):
```scala
    def matches(mediaType: MediaType) = 
      (mainType == "*" || mediaType.mainType == mainType) &&
      (params -- mediaType.params).isEmpty
```

and for `One`:
```scala
    def matches(mediaType: MediaType) =
      this.mediaType.mainType == mediaType.mainType && 
      this.mediaType.subType == mediaType.subType && 
      (this.mediaType.params -- mediaType.params).isEmpty
```

**Comment by jrudolph** [comment]
Hmm not sure if that wouldn't have any unexpected consequences. Can you check if marshalling is spec'd somewhere wrt parameters?

I would probably try to be conservative and let the parameters only influence the ordering of potential marshallings without excluding not-matching ones for now.

**Comment by jypma** [comment]
Yes that's probably nicer. I'll look into how easy that'd be.

**Comment by jypma** [comment]
It's not going to be easy: `Unmarshaller`'s signal that it doesn't like the incoming content type is to throw `UnsupportedContentTypeException` (which is then caught in `Unmarshaller.firstOf`). So there's no way to "interrogate" the unmarshaller alternatives, other than actually have them try.

Javadoc on `MediaRange` says _A media-range either matches a single media-type
or it matches all media-types of a given main-type._, which CAN be read as "yes, properties should be ignored".

How about creating a `MediaRange` subclass that does validate/require properties?

**Comment by jrudolph** [comment]
This was duplicated by #963 which has been fixed by now.
