### ISSUE TITLE
Replace internal completeAfter with takeUntil(..., inclusive) once on Akka 2.4.13

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#536]
It's used in `HttpRequestHeaderHpackDecompression`, and was implemented in Akka now for 2.4.13

**Comment by jlprat** [comment]
Is this only replacing `completAfter` with `takeUntil` in this file `HttpRequestHeaderHpackDecompression`?

**Comment by ktoso** [comment]
Yes, but can only be done after 2.4.13 is released – takeUntil has gained the `inclusive` mode now.

**Comment by jrudolph** [comment]
I think this won't be needed any more when we move the order of the stages around to make sure we can handle more complex cases of trailing HEADERS frames.

So, maybe let's keep it here but don't start working on it before we have made the switch.

**Comment by jlprat** [comment]
Then, does it make sense to remove the "2 - pick next" label?

**Comment by ktoso** [comment]
@jrudolph true, I can remove the custom completeAfter impl in 2 minutes though once Akka is out today :)
Both valid things to do I guess

**Comment by ktoso** [comment]
Realised it was already in 2.4.12, fixed.

**Comment by jonas** [comment]
HttpRequestHeaderHpackDecompression was removed in a4eeded40c872253ca227ffd2c7b2f2ed53abe57 along with all traces of `completeAfter` so closing.

**Comment by ktoso** [comment]
Excellent catch, thanks

**Comment by ktoso** [comment]
Please assign to latest milestones or as invalid when closing tickets :)

**Comment by jonas** [comment]
OK, will do.
