### ISSUE TITLE
Migration guide refers to non existing version 3.0.0

### ISSUE THREAD

**Issue by m-sp** [akka/akka-http#578]
The migration guide at http://doc.akka.io/docs/akka-http/current/scala/http/migration-guide/migration-guide-2.4.x-3.0.x.html still uses the version 3.0.0

**Comment by m-sp** [comment]
same for the java version of the guide http://doc.akka.io/docs/akka-http/current/java/http/migration-guide/index.html

**Comment by jrudolph** [comment]
Thanks good point.

Am 22.11.2016 17:48 schrieb "Matthias Sperl" <notifications@github.com>:
