### ISSUE TITLE
possible inconsistency in conditional directive when If-Modified-Since header is in the future

### ISSUE THREAD

**Issue by wlk** [akka/akka-http#579]
Hi,
I stumbled on a possible inconsistency (or just annoying behavior) when value of `If-Modified-Since` header is in the future, when using `conditional` directive, I'd like to get feedback if this is a real problem and I'm happy to provide a fix.

Here: https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/CacheConditionDirectives.scala#L98

we have following function:
```scala
def unmodified(ifModifiedSince: DateTime) =
          lastModified.get <= ifModifiedSince && ifModifiedSince.clicks < System.currentTimeMillis()
```

It seems to me that this `ifModifiedSince.clicks < System.currentTimeMillis()` condition is unnecessary.

Current behavior:
If `If-Modified-Since` is in the future we return 200 code and full body, the `unmodified` evaluates to false

IMO it's this is better:
If client provides `If-Modified-Since` in the future, it should be treated by returning `304` without body assuming all other conditions are valid.

```scala
def unmodified(ifModifiedSince: DateTime) = lastModified.get <= ifModifiedSince
```

I have read section of https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html `14.25 If-Modified-Since` and it seems to me that this is not defined behavior, and I don't see any value in treating dates that are in the future as invalid

UPDATE:

The only thing in the RFC I found was this:
> or if the passed If-Modified-Since date is invalid

IMO the date in the future is still a valid date, but I suppose different people can have different opinions here

**Comment by ktoso** [comment]
It also has the bit about:

>   Note: If a client uses an arbitrary date in the If-Modified-Since
>   header instead of a date taken from the Last-Modified header for
>   the same request, **the client should be aware of the fact that this**
>   **date is interpreted in the server's understanding of time**. The
>   client should consider unsynchronized clocks and rounding problems
>   due to the different encodings of time between the client and
>   server. This includes the possibility of race conditions if the
>   document has changed between the time it was first requested and
>   the If-Modified-Since date of a subsequent request, and the
>   possibility of clock-skew-related problems if the If-Modified-
> 
>   Since date is derived from the client's clock without correction
>   to the server's clock. Corrections for different time bases
>   between client and server are at best approximate due to network
>   latency.

What do other web servers do? I'd rather be simply consistent with the most prominent ones.

**Comment by wlk** [comment]
I have tested few websites:

Nginx and github pages (which seems to be using nginx)

`304` is only returned when `If-Modified-Since` == `Last-Modified ` - they disallow `If-Modified-Since` to be between `Last-Modified` and `current date`

Apache (the https://httpd.apache.org/ webstie)

Same as nginx, but allows `If-Modified-Since` to be between `Last-Modified` and `current date`


Akka-http allows `If-Modified-Since` to be anywhere between `Last-Modified ` and `current date` which is the same behavior as Apache web server, but different than nginx. I think the current behavior implemented in Akka-http is OK

Closing issue as irrelevant, thanks for suggestion to look at other web servers
