### ISSUE TITLE
Java Docs. Add Missing examples for Routing DSL index page

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#592]
On the Index page for the [Routing DSL](http://doc.akka.io/docs/akka-http/current/java/http/routing-dsl/index.html) there 2 missing Java examples under the File Uploads section.

**Comment by jlprat** [comment]
I'll like to provide those :)

**Comment by ktoso** [comment]
Great, thank you!

**Comment by jlprat** [comment]
In order to provide those examples, I'll do first #604
