### ISSUE TITLE
Java Docs. Update rejections page to Java APIs

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#593]
As stated on the page itself, [rejections](http://doc.akka.io/docs/akka-http/current/java/http/routing-dsl/rejections.html), needs to be adapted to Java API's and provide examples for it.

**Comment by jlprat** [comment]
https://github.com/akka/akka-http/pull/744 addressed partially this issue by adding one example for it

**Comment by ktoso** [comment]
Yeah I noticed more was missing. Didn't add the other one though... up for taking!

**Comment by jlprat** [comment]
I might take this one, but I'd like to finish the HttpApp PR first

**Comment by ktoso** [comment]
Yup, makes sense 👍

**Comment by jlprat** [comment]
I will try to tackle this issue now :)

**Comment by ktoso** [comment]
Thanks a ton!
