### ISSUE TITLE
Consider adding "respondWithLocation" directive

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#6]
I needed a way to incorporate nested `pathPrefix` directives when setting a `Location:` header, so its value became nicely relative to the root of the server. Parking the code here, to discuss whether to make an official directive out of it.

Relates to https://github.com/akka/akka/issues/15839 since it does calculate the "matchedPath".

Test:

``` java
    describe("Directives.addLocationHeader", () -> {
        when("nested inside a pathPrefix directive", () -> {
            Function<String,Route> route = relativePath -> 
                pathPrefix("foo", () -> 
                    pathPrefix("bar", () -> 
                        Directives.addLocationHeader(relativePath, () -> 
                            complete("OK"))));

            it("should take nested path prefixes into account when building a URL for a relative path segment", () -> {
                runRoute(route.apply("hello"), HttpRequest.GET("/foo/bar")).assertHeaderExists(Location.create("/foo/bar/hello"));
                runRoute(route.apply("hello"), HttpRequest.GET("/foo/bar/")).assertHeaderExists(Location.create("/foo/bar/hello"));
                runRoute(route.apply("hello"), HttpRequest.GET("/foo/bar/baz")).assertHeaderExists(Location.create("/foo/bar/hello"));
            });

            it("should return the location relative to the root if the relative path segment starts with /", () -> {
                runRoute(route.apply("/hello"), HttpRequest.GET("/foo/bar")).assertHeaderExists(Location.create("/hello"));
                runRoute(route.apply("/hello"), HttpRequest.GET("/foo/bar/")).assertHeaderExists(Location.create("/hello"));
                runRoute(route.apply("/hello"), HttpRequest.GET("/foo/bar/baz")).assertHeaderExists(Location.create("/hello"));                
            });

            it("should return the location relative to the parent if the relative path segment starts with ..", () -> {
                runRoute(route.apply("../hello"), HttpRequest.GET("/foo/bar")).assertHeaderExists(Location.create("/foo/hello"));
                runRoute(route.apply("../hello"), HttpRequest.GET("/foo/bar/")).assertHeaderExists(Location.create("/foo/hello"));
                runRoute(route.apply("../hello"), HttpRequest.GET("/foo/bar/baz")).assertHeaderExists(Location.create("/foo/hello"));                
            });            
        });

        when("invoked on the root", () -> {
            Function<String,Route> route = relativePath -> 
                Directives.addLocationHeader(relativePath, () ->
                    complete("OK"));
            it("should use the given string as absolute url", () -> {                
                runRoute(route.apply("hello"), HttpRequest.GET("/")).assertHeaderExists(Location.create("/hello"));
                runRoute(route.apply("/hello"), HttpRequest.GET("/")).assertHeaderExists(Location.create("/hello"));
            });
        });
    });

```

Implementation:

``` java
    public static Route addLocationHeader(String relativePath, Supplier<Route> inner) {
        return extractRequestContext(ctx -> {
            String path = ctx.getRequest().getUri().path();
            String base = path.substring(0, path.length() - ctx.getUnmatchedPath().length());
            if (!base.endsWith("/")) {
                base = base + "/";
            }
            URI uri = URI.create(base).resolve(relativePath);
            return respondWithHeader(Location.create(uri.toString()), inner);
        });
    }
```

**Comment by ktoso** [comment]
Needs some checking with the spec IMO.
Not sure `relativePath` is correct, would be `absolutePath` right?
Perhaps require it should start with `/` (or protocol) then?

**Comment by 2beaucoup** [comment]
We can add the matched path logic to `RequestContext` as requested in #15839. What would be left is a simple `respondWithHeader(Location(...))` which doesn't warrant its own directive IMO.

**Comment by 2beaucoup** [comment]
FTR: Extracting the matched path is already implemented and [hidden](https://github.com/akka/akka-http/blob/555a31f0c7e6782267e9123ae7465ea88ae8b6db/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L151-L156) inside `FileAndResourceDirectives#listDirectoryContents`.

**Comment by rbudzko** [comment]
@ktoso @2beaucoup  I could dance with this one, but it seems obsolete - based on akka/akka#15839. Can we establish if `respondWithLocation` is to be added?

**Comment by 2beaucoup** [comment]
IMO: No. What do others think?

**Comment by jypma** [comment]
Well my use case still exists: we want to send a server-root relative `Location:` back as part of a "_POST to create resource_" pattern, i.e.
```
POST /resources

200 OK
Location: /resources/42
```
without needing to repeat `"/resources"` in the routing logic.

**Comment by 2beaucoup** [comment]
@jypma What do you think about https://github.com/akka/akka-http/issues/6#issuecomment-242042604?

**Comment by jypma** [comment]
You'd still need to combine two directives. Assuming `ctx.getMatchedPath()` returns `Uri`:
```
extractRequestContext(ctx ->
  respondWithHeader(Location.create(ctx.getMatchedPath().addPathSegment(myId)), () -> 
    complete(...)
  )
) 
```
It would reduce the custom code for sure, so it would be a definite improvement.

I'd personally still push it down into a `respondWithLocation` directive in my own code though... but if I'm the only one having this API style, it's obviously not much of a pattern :)

**Comment by jrudolph** [comment]
I'm with @2beaucoup on this one. Adding `matchedPath` to `RequestContext` (only necessary if we want to keep it as a field in RequestContext) or as a directive would be a definite win.

For which kind of responses do you want to add `Location` headers, @jypma? The redirection ones or `201` or something else?

**Comment by jypma** [comment]
@jrudolph It's a 201 Created. Sorry, edited 2 comments ago to reflect that. So client POSTs a new resource to us, with the content in the body, server then makes up an identifier for that new resource, and returns its new location in the `Location:` header, which happens to always be directly underneath the URI that the original POST goes to.

Either way, just getting `matchedPath` would be an improvement, so by all means let's go forward with that. As long as `Uri.addPathSegment` would properly handle the current `matchedPath` ending or not ending in a slash.

**Comment by 2beaucoup** [comment]
I added #496 to track the matched path feature. Let's close this for now.
