### ISSUE TITLE
AllDirectives cannot be resolved to a type

### ISSUE THREAD

**Issue by thewolf** [akka/akka-http#601]
akka.http.javadsl.server.AllDirectives cannot be resolved to a type in latest version of akka-http 10.0.0 (java version)

can someone help please?

**Comment by ktoso** [comment]
You need to depend on akka-http, not only akka-http-core :) I guess that was it.

**Comment by thewolf** [comment]
it was an issue with my maven cache, all worked fine after deleting it manually. thanks :)
