### ISSUE TITLE
JavaDSL Unmarshaller is leaking ScalaDSL classes

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#604]
The current `akka.http.javadsl.unmarshalling.Unmarshaller` is leaking some scaladsl as return types. The current examples I found are:
* `entityToMultipartByteRanges()` that is returning `Unmarshaller<http.javadsl.model.HttpEntity, akka.http.scaladsl.model.Multipart.ByteRanges>`
* `entityToUrlEncodedFormData()` that is returning `Unmarshaller<http.javadsl.model.HttpEntity, akka.http.scaladsl.model.FormData>`

**Comment by ktoso** [comment]
Thanks for catching it, that's a bug / missing API that needs ot be fixed.
It is possible that we're missing those datatypes in javadsl... :/

Would you give it an attempt to fix?

**Comment by jlprat** [comment]
Sure!

**Comment by ktoso** [comment]
Thanks @jlprat !
