### ISSUE TITLE
regression: current master doesn't compile against akka master

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-http#606]
this turned up in the Scala 2.12 community build:

```
[akka-http] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/akka-http-7e987c846a164652c9cdd2faa53bb7eb0e6fb7a8/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala:18: object Context is not a member of package akka.stream.stage
[akka-http] [error] import akka.stream.stage.{ Context, GraphStage, SyncDirective, TerminationDirective }
[akka-http] [error]        ^
```

@ktoso this might have to do with https://github.com/akka/akka/pull/21919 ?

**Comment by SethTisue** [comment]
fyi @lrytz (this came up in your community build run)

**Comment by SethTisue** [comment]
I thought this might be because we have akka-http frozen at 3217cbf417817ca03421439af6aa2587dd418e8c, because https://github.com/scala/community-builds/issues/400, but I see the same import in RenderSupport.scala even in akka-http master

**Comment by jrudolph** [comment]
@SethTisue thanks for catching. akka-http is now built against released akka versions and we haven't set up our own integrated build infrastructure to catch things like this. 

You are right, it's probably because of https://github.com/akka/akka/pull/21919. The import seems to be left over from a previous version.

**Comment by ktoso** [comment]
We want to set up our own mini-dbuild for this reason and would need some help on how to get started with that... let's continue about that in the email thread @2m started.

**Comment by ktoso** [comment]
Thanks a lot again for reporting @SethTisue !
