### ISSUE TITLE
Scala/Java Docs: Example code for actor interaction incorrect

### ISSUE THREAD

**Issue by aksiksi** [akka/akka-http#612]
I initially submitted a PR fixing this directly, but I closed that after reading `CONTRIBUTING.md`.

### Problem

The actor interaction example on the Introduction page (the last code snippet) on both the Java and Scala docs is written incorrectly. In its current state, the example will **not** compile.

Pages in question:

- http://doc.akka.io/docs/akka-http/current/java/http/introduction.html#routing-dsl-for-http-servers
- http://doc.akka.io/docs/akka-http/current/scala/http/introduction.html#routing-dsl-for-http-servers

The example does not compile for two reasons. Firstly, the `Auction` actor itself is not defined at all in the snippet. And secondly, `Props` is not used correctly in the `actorOf` call.

### Proposed Fix

1. `import akka.actor.ActorSystem` => `import akka.actor.{Actor, ActorSystem, Props}`
2. Write a simple `Auction` actor that prints a message on receiving a `Bid`.
3. `system.actorOf(Auction.props, "auction")` => `system.actorOf(Props[Auction], "auction")`

**Comment by ktoso** [comment]
The PR was fine, no reason to close it :)
Thanks for noticing.

**Comment by ktoso** [comment]
Merged, thanks!
