### ISSUE TITLE
Substream Source cannot be materialized more than once failure in either unmarshaller

### ISSUE THREAD

**Issue by leachbj** [akka/akka-http#618]
Using a `Either[Type1, Type2]` unmarshaller where the two types have spray-json unmarshallers available failed with;
 
`Failed to unmarshal Either[Type1, Type2] (attempted Type2 first). Right failure: Object is missing required member 'foo', Left failure: Substream Source cannot be materialized more than once`

**Comment by jrudolph** [comment]
Yes, I agree, it seems the logic for Either unmarshallers does not work with non-strict entities.

**Comment by ktoso** [comment]
Thanks for reporting! Bug indeed.

**Comment by jrudolph** [comment]
Fixed by making it explicit that the marshaller only works for strict entities in #2632.
