### ISSUE TITLE
Add links to ScalaDoc and JavaDoc to main documentation site

### ISSUE THREAD

**Issue by eswenson1** [akka/akka-http#623]
It is currently difficult (with Google) to locate the ScalaDoc (and JavaDoc) for Akka HTTP. Without much effort, you can find the documentation here:  http://doc.akka.io/docs/akka-http/current/, but neither that page, or the subordinate Scala or Java pages, include links to http://doc.akka.io/api/akka-http/current/akka/http/scaladsl/index.html and http://doc.akka.io/api/akka-http/current/akka/http/javadsl/index.html. 

These pages should include links to the Scala/JavaDoc for Akka HTTP.

**Comment by ktoso** [comment]
Thanks for the ticket :)
