### ISSUE TITLE
Docs. Missing snippet in Extract Directive (ScalaDSL)

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#636]
The [extract](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/basic-directives/extract.html) directive in ScalaDSL documentation is missing a snippet (typo in `@@snip` id)

**Comment by jlprat** [comment]
Created an issue in Paradox, asking for support of numeric-prefixed-ids: https://github.com/lightbend/paradox/issues/79

**Comment by jonas** [comment]
Fixed via be6e176
