### ISSUE TITLE
Extract a header value or return default

### ISSUE THREAD

**Issue by zettelmj** [akka/akka-http#639]
I some situation it would be handy to for the headerValue* directives to allow to specify a default value that is used if the header is not present.

for headerValueByName this could look like this:

`def headerValueByName(headerName: String, default: String): Directive1[String] =
    headerValue(optionalValue(headerName.toLowerCase)) | provide(default)`

**Comment by zettelmj** [comment]
Hi @jrudolph,

that looks way better than what i tried over the weekend. Passing a function down through the directives makes all of the look very convoluted. Additionally it changes a bunch of signatures. 
I'll give the "provide" directive a try. 

Cheers
Jens

**Comment by ktoso** [comment]
Would you have some time to add this pattern to our documentation, in 

- http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/header-directives/headerValue.html
- https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/java/http/routing-dsl/directives/header-directives/headerValue.md

That would be very nice of you :) A way of saying thanks in a way :-)

**Comment by zettelmj** [comment]
@ktoso i will after implementing.

**Comment by jlprat** [comment]
I would say for the Java DSL is not that straight forward, unless https://github.com/akka/akka-http/issues/620 is done

**Comment by jrudolph** [comment]
@jlprat agreed.

**Comment by zettelmj** [comment]
@ktoso just putting it into headerValue feels a bit strange cause it is effectively just an application of http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/index.html#composing-directives.

There are some examples in composing-directives but they aren't covering this scenario.
Maybe a sub page of examples what can be done by composing patterns would be good?!

Thank you
Jens

**Comment by ktoso** [comment]
Page with patterns would also be good, but this one I think is basically a headerValue "or else..." which is why I think it makes sense to add to its page. We have examples of directives which have such additional documentation (simply as section inside their docs) :)

**Comment by jrudolph** [comment]
In #666, @zettelmj added the example to the Scala documentation. Would make sense to add something similar to the Java documented, not least for consistency.
