### ISSUE TITLE
Java `complete` directive(s) should take arguments of type `ResponseEntity` instead of `RequestEntity`

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-http#641]
This extends to `Marshaller[T, RequestEntity]`.

Notice that a `RequestEntity` is a `ResponseEntity` and not the other way round!

With the current implementation, it's not possible to write a marshaller which marshals to `CloseDelimited`, because that's nole a `ResponseEntity` and not a `RequestEntity`.

**Comment by jrudolph** [comment]
Looks like an oversight to me, left over from the Java port.

**Comment by btomala** [comment]
If no one working on it I will take a look on it. Looks pretty simple.

**Comment by jlprat** [comment]
Just wondering, isn't this change a potential breaker for users of those classes? Basically, is it binary and source compatible?

**Comment by btomala** [comment]
@jlprat It is source compatible but isn't binary. And it is very simple change. Do you want this change even though?

**Comment by jlprat** [comment]
Yes, the ticket is up to be picked. It would be cool if you could provide a PR! :smiley:

**Comment by jrudolph** [comment]
Fixed in #982.
