### ISSUE TITLE
Outdated warning in https docs

### ISSUE THREAD

**Issue by note** [akka/akka-http#645]
At http://doc.akka.io/docs/akka-http/current/scala/http/client-side/client-https-support.html we can see a warning stating `Akka HTTP 1.0 does not completely validate certificates when using HTTPS`. I tested it according to `https://tersesystems.com/2014/03/31/testing-hostname-verification/` and seems like hostname verification is performed. When trying to access server with certificate lacking subjectAltName or with incorrect subjectAltName I am getting `java.security.cert.CertificateException: No subject alternative DNS name matching san.app found.` which is correct.

Also I tracked down the change and it was done in `ac9bcebb901a06a4ddcbdac70414a040f20de06a` (November 2015) in akka repository. In previous commits there were some remarks on Java 6 but as akka since 2.4 is targeted to Java 8 I think any need for warning vanished.

Would be nice to remove this warning if it's in fact outdated because it does not look well to use library with "security warning" on production.

**Comment by ktoso** [comment]
As you notice, the note is ancient - referring to 1.0 whereas we're on 10.0. It indeed was implemented, esp. with Java 8 it is built into the engine/
Would you be kind enough to submit a PR removing this warning?
Thanks
