### ISSUE TITLE
Document missing Scala DSL directives

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#656]
As shown in #613 several scaladsl directives are not documented:

- [x] BasicDirectives.extractParserSettings
- [ ] CodingDirectives.withPrecompressedMediaTypeSupport
- [ ] WebSocketDirectives.extractUpgradeToWebSocket
- [ ] WebSocketDirectives.extractOfferedWsProtocols
- [ ] WebSocketDirectives.handleWebSocketMessagesForOptionalProtocol

**Comment by ktoso** [comment]
Marked extractParserSettings as done.

**Comment by jonas** [comment]
Thanks, unified the to-do list. GitHub does seem to support broken up todo items.
