### ISSUE TITLE
Java API for bindAndHandle does not allow port 0

### ISSUE THREAD

**Issue by akara** [akka/akka-http#660]
We use port 0 during tests extremely frequently. As we do parallel tests, this allows Akka-HTTP to find me an open ephemeral port and bind there. We then read the actual port back from the resulting ServerBinding.

When writing Java API tests, we just found out it does not accept 0 for `bindAndHandle`. To be more specific, The `ConnectHttp.toHost("localhost", 0)` throws an exception - not the bindAndHandle itself. The culprit is in this code in `ConnectHttp`:

```scala
  def toHost(host: String, port: Int): ConnectHttp = {
    require(port > 0, "port must be > 0")
    val start = if (isHttpOrHttps(host)) host else s"http://$host"
    toHost(Uri.create(start).port(port))
  }
```

I think the second line should rather spell:

```scala
    require(port >= 0, "port must be 0 or higher")
```

**Comment by akara** [comment]
Apparently there is another place that wants `port > 0` in `ConnectHttp`:

```scala
  private def effectivePort(scheme: String, port: Int): Int = {
    val s = scheme.toLowerCase(Locale.ROOT)
    if (port > 0) port
    else if (s == "https" || s == "wss") 443
    else if (s == "http" || s == "ws") 80
    else throw new IllegalArgumentException("Scheme is not http/https/ws/wss and no port given!")
  }
```

**Comment by jonas** [comment]
Thanks for reporting this. I've proposed a PR to remove this inconsistency.

**Comment by akara** [comment]
Thanks for accepting! Looked at #803. Looks good!
