### ISSUE TITLE
Handle exceptions with request context

### ISSUE THREAD

**Issue by tyth** [akka/akka-http#668]
Currently there is no way to handle an exception based on `RequestContext`.
So for example. if I want to have a localized ("Accept-Language" request header) error message for some exception I need to put this localization logic here and there in my business logic.

A temporal solution I wrote is:

```
import akka.http.scaladsl.util.FastFuture._
def handleExceptionsWithContext(handler: (RequestContext) => ExceptionHandler): Directive0 =
  Directive { innerRouteBuilder ⇒ ctx ⇒
    import ctx.executionContext
    def handleException: PartialFunction[Throwable, Future[RouteResult]] =
      handler(ctx) andThen (_(ctx.withAcceptAll))
    try innerRouteBuilder(())(ctx).fast.recoverWith(handleException)
    catch {
      case NonFatal(e) ⇒ handleException.applyOrElse[Throwable, Future[RouteResult]](e, throw _)
    }
  }
```

Surely it can be done without creation of a new `ExceptionHandler` instance on every `handleException` call. 

I can submit a pull request, if such functionality is needed.
If there is some good workaround, please tell me.

**Comment by jonas** [comment]
An `ExceptionHandler` is a partial function from `Throwable` to `Route` so you can use `headerValue` to  get the request's `Accept-Language` and `extractRequestContext` to access the request context inside the handler. I wonder if you tried that?

The [exception handling docs](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/exception-handling.html) has an example using `extractUri`:
```
val myExceptionHandler = ExceptionHandler {
  case _: ArithmeticException =>
    extractUri { uri =>
      println(s"Request to $uri could not be handled normally")
      complete(HttpResponse(InternalServerError, entity = "Bad numbers, bad result!!!"))
    }
}
```

**Comment by tyth** [comment]
My bad, thank you.
