### ISSUE TITLE
Add support for Server-Sent Events by including Akka SSE

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-http#669]
Please discuss.

**Comment by hseeberger** [comment]
Akka SSE: https://github.com/hseeberger/akka-sse

**Comment by hseeberger** [comment]
I have just released Akka SSE 2.0.0. The idea is that it could be moved in as is (except for shuffling package names and adding non-Scaladoc documentation), so please take a look at the design and implementation.

**Comment by ktoso** [comment]
Great, thanks a lot Heiko. I'll get to it next week I think, attempting to stay offline for a few days now :)
In general I'm in favour of pulling it in, seems you worked on javadsl as well so let's see if we're all good there. Will comment there or here somehow hm hm

**Comment by ktoso** [comment]
Hope to get to it this week, we're still halfed with much of the team on holidays. Sorry for the delay.

**Comment by hseeberger** [comment]
Any progress here?

**Comment by ktoso** [comment]
Could you make a PR with it? Would make reviewing much easier hm.

**Comment by hseeberger** [comment]
Sure, I could create a PR. But that's a lot of work and therefore I'd like to see a general thumbs up to the idea of including SSE first.

**Comment by ktoso** [comment]
As you know since a long time, there is a thumbs up ;-)

**Comment by hseeberger** [comment]
Sounds great! Will make a PR as soon as I can find some time.

**Comment by hseeberger** [comment]
(didn't check the thumbs-up, now there are four ;-))

**Comment by ktoso** [comment]
Excellent, thanks 👍

**Comment by OverlyExcessive** [comment]
@hseeberger Any chance you could submit that PR soon? Looking to use this for a project and I admit it would be easiest if this was bundled directly with akka-http. Also makes sense as they are already supporting WebSockets :)  .

**Comment by hseeberger** [comment]
@OverlyExcessive I'm too busy, but using akka-sse should be a no-brainer.
