### ISSUE TITLE
Investigate how akka.pattern ends up in ScalaDoc

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#684]
See http://doc.akka.io/api/akka-http/10.0.1/akka/pattern/index.html

**Comment by jonas** [comment]
Regarding the investigation, I'll let you decide if it merits a ticket against Scaladoc itself.

**Comment by jonas** [comment]
I'll update this Scaladoc ticket with my observations: https://issues.scala-lang.org/browse/SI-10028

**Comment by jrudolph** [comment]
Great thanks.
