### ISSUE TITLE
Uri("//") generates empty path in Uri

### ISSUE THREAD

**Issue by devsprint** [akka/akka-http#690]
If the string passed to Uri constructor is an escaped path (or generated by mistake in a path builder for example..), Uri path will be empty (akka-http 10.0.0). 

scala> import akka.http.scaladsl.model.Uri
import akka.http.scaladsl.model.Uri

scala> val uri = Uri("//")
uri: akka.http.scaladsl.model.Uri =

scala> uri.path
res2: akka.http.scaladsl.model.Uri.Path =

**Comment by ktoso** [comment]
AFAIR such handling of path is exactly what the RFC dictates though. Do you
have a real use case where this poses a problem? Did you reference check
the Uri RFC spec to see how path is defined there?

**Comment by devsprint** [comment]
@ktoso The only real use case is the linked PR, where AWS Signature 4 based test suite, requires a path normalization. In the test suite I have implemented this normalization before the Uri constructor is called, but I though that maybe it will be useful to become part of the Uri implementation itself.
I'm aware about the RFC, in section [4.2](https://tools.ietf.org/html/rfc3986#section-4.2) is describing the "//" as being rarely used.

**Comment by ktoso** [comment]
Thanks, I missed that the issue was linked to the signature thing. Thanks,
will have to investigate it seems :)

**Comment by jrudolph** [comment]
@devsprint doing the normalization before the Uri constructor is called seems quite brittle as you rely on generating and parsing strings to the same values. Uri already contains normalization so it could make sense to just rely on `Uri`'s normalization.

In any case the string `//` is not an absolute path, so if that should be a result of normalization, there's a bug in the normalization implementation.

As [section 3.3](https://tools.ietf.org/html/rfc3986#section-3.3) says:

```
[...]
   If a URI
   does not contain an authority component, then the path cannot begin
   with two slash characters ("//").  In addition, a URI reference
   (Section 4.1) may be a relative-path reference, in which case the
   first path segment cannot contain a colon (":") character.  The ABNF
   requires five separate rules to disambiguate these cases, only one of
   which will match the path substring within a given URI reference.  We
   use the generic term "path component" to describe the URI substring
   matched by the parser to one of these rules.

      path          = path-abempty    ; begins with "/" or is empty
                    / path-absolute   ; begins with "/" but not "//"
[...]
```

**Comment by devsprint** [comment]
@jrudolph there is not problem with the normalization implementation. I think, the work around that I used in the test suite it is good enough to use the test scenario. AWS 4 signature in alpakka is using the HttpRequest that is using a Uri, where there is no way to instantiate such Uri. So from this point of view we are safe. It is just a matter of Amazon test suite.

**Comment by jrudolph** [comment]
Seems this wasn't an issue in the end.
