### ISSUE TITLE
track the latency of techempower round 13

### ISSUE THREAD

**Issue by hepin1989** [akka/akka-http#698]
https://www.techempower.com/benchmarks/#section=data-r13&hw=cl&test=plaintext

**Comment by ktoso** [comment]
We're aware of those benchmarks 😉 
I don't think this ticket is actionable, we're working on performance in more specific tickets, like materialization etc. 

Closing this one.

**Comment by kajia** [comment]
Do you have any hints  why akka-http performance so poor in their benchmarks?

**Comment by jonas** [comment]
When I looked at some of the implementations my impression was that they target different levels of abstraction. One was using the low-level Jackson API to generate JSON, the Spray implementation is using Spray JSON's AST API, while the Akka HTTP one is using the case class encoder API. So I wonder how much they actually benchmark JSON encoding and database access versus HTTP serving.

**Comment by shafqatevo** [comment]
Shouldn't there be an officially reviewed implementation for this widely cited benchmark?
