### ISSUE TITLE
The parser fails to parse some RFC compliant URI's

### ISSUE THREAD

**Issue by kosii** [akka/akka-http#700]
`Uri("http://example.com/path?a=b?c=d").query()` throws an exception:

> Exception in thread "main" akka.http.scaladsl.model.IllegalUriException: Illegal query: Invalid input '=', expected '+', query-char, 'EOI', '&' or pct-encoded (line 1, column 6): a=b?c=

The relevant parts from the RFC: 

> query         = *uric
> uric          = reserved | unreserved | escaped
> reserved      = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" | "$" | ","

Also: 
> The characters slash ("/") and question mark ("?") may represent data
   within the query component. [[ref]](https://tools.ietf.org/html/rfc3986#section-3.4)

**Comment by viktorklang** [comment]
It's not complaining about the `?`, it's complaining about the second `=` (i.e. an equals-sign inside a value.)

**Comment by kosii** [comment]
oh, right , thanks!
