### ISSUE TITLE
PathMatcher of Map[String, T] is not working when nested

### ISSUE THREAD

**Issue by shachr** [akka/akka-http#701]
PathMatcher of Map[String, T] is not working when nested as such:
use case 1:
`
  def test = path("test") {
    path(Map("a"->1)) {
      val =>
        pathEndOrSingleSlash {
          get {
            complete(val)
          }
        }
    }
  }
`

use case 2:
`
  def test1 = path(Map("a"->1)) {
      val =>
        path("test") {
          pathEndOrSingleSlash {
            get {
              complete(val)
            }
          }
        }
  }
`

it is working when it is not nested e.g.:
`
  def test = path(Map("a"->1)) {
      val =>
        pathEndOrSingleSlash {
          get {
            complete(val)
          }
        }
  }
`

**Comment by ktoso** [comment]
Please read about path and pathPrefix in the docs. They work differently,
which is what you are seeing here.

**Comment by shachr** [comment]
@ktoso You are correct, though it seems to not work also cause in one of my tests a tried a Map[String, MyClass] , MyClass a case class with 3 parameters, the 3rd is another complex type which has many functions, it seems to completely ignore the mapping in this case, when i changed it to be a Map[String, Int] it worked.

**Comment by ktoso** [comment]
That's a different question than in the title of the ticket though.
Could you share the real reproducer and open a new ticket please?

**Comment by shachr** [comment]
@ktoso I will try to create a clean isolated test first, thanks.
