### ISSUE TITLE
List of directives (alphabetically) should be more prominent in TOC.

### ISSUE THREAD

**Issue by analytically** [akka/akka-http#712]
![image](https://cloud.githubusercontent.com/assets/254434/21653332/7779597a-d2a8-11e6-8e65-ecb43116a2c2.png)

Some serious scrolling just to get to the directives list :-)

**Comment by analytically** [comment]
http://doc.akka.io/docs/akka-http/current/scala/http/

**Comment by ktoso** [comment]
Will be mostly resolved by search which we're working on adding. It depends how quick algolia is able to set us up though.
Happy to accept PR though, if it doesn't break ToC :)

**Comment by jrudolph** [comment]
It's now directly under a reference top-level TOC entry.
