### ISSUE TITLE
Document missing Java DSL directives

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#717]
As @jonas found out in #656 several scaladsl directives are not documented, this documentation is also missing for the javadsl:

- [x] BasicDirectives.extractParserSettings
- [x]  CodingDirectives.withPrecompressedMediaTypeSupport
- [x]  WebSocketDirectives.extractUpgradeToWebSocket
- [x]  WebSocketDirectives.extractOfferedWsProtocols
- [x]  WebSocketDirectives.handleWebSocketMessagesForOptionalProtocol

**Comment by jonas** [comment]
I'll take this @jlprat and put you as reviewer when it is ready.

**Comment by jlprat** [comment]
Cool!

**Comment by jonas** [comment]
Done in 4fbc87a
