### ISSUE TITLE
Constantly increasing default dispatcher thread count running on AWS

### ISSUE THREAD

**Issue by spoolphiz** [akka/akka-http#722]
This is a repost of http://stackoverflow.com/questions/41402501/akka-http-server-dispatcher-number-constantly-increasing/41467091

I am testing an akka http service running on AWS ECS behind an application load balancer. New containers spin up fine and register with the load balancer's target group. However as health check requests come into the service I see the default dispatcher thread number constantly increasing. It grows well beyond what I would expect:

```
[DEBUG] [01/03/2017 22:33:03.007] [default-akka.actor.default-dispatcher-41200] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [01/03/2017 22:33:29.142] [default-akka.actor.default-dispatcher-41196] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [01/03/2017 22:33:33.035] [default-akka.actor.default-dispatcher-41204] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [01/03/2017 22:33:59.174] [default-akka.actor.default-dispatcher-41187] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [01/03/2017 22:34:03.066] [default-akka.actor.default-dispatcher-41186] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [01/03/2017 22:34:29.204] [default-akka.actor.default-dispatcher-41179] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [01/03/2017 22:34:33.097] [default-akka.actor.default-dispatcher-41210] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
```

My health check router currently looks like this:

```
import akka.http.scaladsl.model.StatusCodes.OK
import akka.http.scaladsl.model.headers.Connection
import akka.http.scaladsl.server.Directives._
import com.thebouqs.services.bridge.utils.LogHelper
import de.heikoseeberger.akkahttpjackson.JacksonSupport._

import scala.concurrent.ExecutionContext

class HealthCheckRoutes()(implicit executionContext: ExecutionContext)
  extends LogHelper {

  val routes = pathPrefix("health-check") {
    pathEndOrSingleSlash {
      respondWithHeader(Connection("close")) {
        complete(OK -> "Ok")
      }
    }
  }
}
```

~I cannot reproduce this behavior locally so it feels abnormal.~

I am able to reproduce this locally if I run the server as a docker container. Running the server on the host system however does not result in the same behavior.

Any idea what may be causing this? Should I be concerned or is this considered normal in some contexts?

**Comment by viktorklang** [comment]
That's not the thread count, that's the thread id sequence number. ForkJoin decommissions threads if there is no work to be done.

**Comment by jrudolph** [comment]
Hi @spoolphiz, as @viktorklang says the range of thread ids is not necessarily a bad sign.

Depending on how long your service has been running when you see this it could be an issue if the overall thread churn is high, though. So, are you running other things on this dispatcher? If you have blocking calls somewhere running in `blocking` calls (like `Await.result`) it might spawn an temporary extra thread.

There's hasn't been any sign that this is related to akka-http so far, so closing here.

**Comment by spoolphiz** [comment]
@jrudolph to be clear this is a test environment and that service does nothing but serve GET requests to the health check route. I'm also able to reproduce this issue outside of docker by running the server in elastic beanstalk. If this is a thread churn issue, should I be concerned about going to production? What could be causing this thread churn in the absence of any async of blocking calls?

**Comment by jrudolph** [comment]
Hmm, ok if you think this is a bug / problem, could you describe how to reproduce it with docker and nothing else?

**Comment by spoolphiz** [comment]
Ill set up a repo with instructions on how to reproduce and post it here in the next day or two.

**Comment by spoolphiz** [comment]
@jrudolph here is the repo: https://github.com/spoolphiz/akka-http-dispatcher-test

**Comment by jrudolph** [comment]
@spoolphiz I tried your reproducer. It doesn't seem to exhibit different behavior with or without docker for me. As far as I checked there's nothing special going on. As @viktorklang said, the pool underlying akka's dispatcher (ForkJoinPool) will start and stop threads according to the current load. Per default it is configured with a max factor of 3 times the number of processors (cores / hyperthreads). Even a single request can make use of several thread so if requests are infrequent enough, previous threads will have been stopped already and several new ones might be created per request. This is nothing special. The number in the thread name is just an monotonically increasing number to identify the current thread.

I added a bit to your code to monitor the currently active threads like this:

```scala
class CheckThreadsRunner extends Thread {
  override def run(): Unit =  while(true) {
    import scala.collection.JavaConverters._
    val dispThreads =
      Thread.getAllStackTraces.keySet.asScala.filter(_.getName startsWith "default-akka.actor.default-dispatcher")

    dispThreads.toVector.map(_.getName).sorted.foreach(println)
    println()
    println(s"Currently ${dispThreads.size} threads")

    Thread.sleep(10000)
  }
}
```

and then start this monitor thread with

```scala
  val checker = new CheckThreadsRunner
  checker.setDaemon(true)
  checker.start()
```

which will print out the names of all currently existing dispatcher threads every 10 seconds.

After a while this looks for me e.g. like this:

```
Currently 1 threads
default-akka.actor.default-dispatcher-8

Currently 1 threads
[DEBUG] [01/30/2017 08:47:20.986] [default-akka.actor.default-dispatcher-8] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12
default-akka.actor.default-dispatcher-8

Currently 4 threads

default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12
default-akka.actor.default-dispatcher-8

Currently 4 threads
default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 3 threads
default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 3 threads
default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 3 threads
default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 3 threads
default-akka.actor.default-dispatcher-10
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 3 threads
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 2 threads
default-akka.actor.default-dispatcher-11
default-akka.actor.default-dispatcher-12

Currently 2 threads
```

So, before a health request there's only a single thread in the pool (the minimum to keep the pool alive). Afterwards there are 4 alive. After some time threads are decommissioned one after the other.

I'm closing this for now. If you still think this is an issue or if you can show that the thread churn is bigger than expected in docker, please add more info and reopen.
