### ISSUE TITLE
Cannot construct json root format

### ISSUE THREAD

**Issue by Jegp** [akka/akka-http#729]
Hi all and many thanks for a great project!

I've got an issue with creating a simple deserializer. I've got a simple case class ``LogEntry`` with a single parameter which I'd like to deserialize from a request. I've followed your docs and adapted your example to this:

    trait JsonSupport extends SprayJsonSupport with DefaultJsonProtocol {
        implicit val entryFormat = jsonFormat1(LogEntry)
    }

Only, I get the exception:

    Error:(75, 41) could not find implicit value for evidence parameter of type JsonSupport.this.JF[Map[String,Any]]
    Error:(75, 41) not enough arguments for method jsonFormat1: (implicit evidence$1: JsonSupport.this.JF[Map[String,Any]], implicit evidence$2: ClassManifest[com.repocad.logging.LogEntry])spray.json.RootJsonFormat[com.repocad.logging.LogEntry].
        Unspecified value parameters evidence$1, evidence$2.

I'm using version 10.0.1 for both ``akka-http`` and ``akka-http-spray-json``.

Cheers!

**Comment by jonas** [comment]
The error message is indicating that Spray JSON cannot find an implicit format mapping for `Map[String, Any]`. One solution would be to use a more specific type than `Any` or alternatively provide a custom JSON format for `Any`.

I would also suggest to use the akka/akka Gitter channel or stackoverflow for this sort of Q&A question in the future.

**Comment by Jegp** [comment]
Ok, gotcha. Is this in the docs?
Thanks for helping out!

**Comment by ktoso** [comment]
Happy to accept docs improvements on this if you'd like to send in a PR.

Generally everything is documented in spray-json since that's what we're using as default. 
If you'd use something else then that something else's docs would be the thing to read https://github.com/spray/spray-json
