### ISSUE TITLE
An opcode of a websocket response becomes "", so browsers execute callbacks without response data.

### ISSUE THREAD

**Issue by elseorand** [akka/akka-http#730]
* scala: 2.11.8
* akka-http: 2.4.16

I write a simple sample like 
[Akka HTTP Scala Documentation Akka HTTP Server-Side WebSocket Support](http://doc.akka.io/docs/akka-http/current/scala/http/websocket-support.html)

But every opcode in server response becomes empty string "", though finBit is true, 
probably browsers(Edge, Firefox, Chrome) don't think of the response as TextMessage.

* a response observed by a browser
```
finBit	true
rsvBit1	""
rsvBit2	""
rsvBit3	""
opCode	""
maskBit	true
mask	""
payload	"Hello test!"
OPCODE_CONTINUATION	""
OPCODE_TEXT	1
OPCODE_BINARY	2
OPCODE_CLOSE	8
OPCODE_PING	9
OPCODE_PONG	10
webSocketSerialID	311
```

* Server code

```
import scala.io.StdIn

import collection.mutable

import akka.actor._
import akka.stream._
import akka.stream.scaladsl._
import akka.http.scaladsl._
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.model.ws._

object WebServer extends App {
  // args
  implicit val system = ActorSystem("sample")
  implicit val materializer = ActorMaterializer()
  // needed for the future flatMap/onComplete in the end
  implicit val executionContext = system.dispatcher

  implicit val serverPort = 18080

  val route = get {
    pathPrefix("sample") {
      pathSingleSlash {
        getFromResource("html/main.html")
      } ~
      pathPrefix("jscss"){
        getFromResourceDirectory("jscss") // TODO search recursive
      } ~
      pathPrefix("jscss" / "jquery-ui-1.11.4") {
        getFromResourceDirectory("jscss/jquery-ui-1.11.4")
      }
    }
  } ~
  pathPrefix("sample" / "ws") {
    Console println "pass : "
    // TODO 誰が捨てたかが、必須のため、受領を意味するHttpレスポンスも返す
    handleWebSocketMessages(wsFlow)// TODO wsFlowの生成にHttpRequestの情報を用いる
  }

  val wsFlow: Flow[Message, Message, _] = Flow[Message].mapConcat {
    case tm: TextMessage =>
      TextMessage(Source.single("Hello ") ++ tm.textStream ++ Source.single("!")) :: Nil
    case bm: BinaryMessage =>
      // ignore binary messages but drain content to avoid the stream being clogged
      bm.dataStream.runWith(Sink.ignore)
      Nil
  }

  val bindingFuture = Http().bindAndHandle(route, "192.168.11.3", serverPort)

  // EnterでSeverを終了
  println(s"Server online at http://localhost:$serverPort\nPress RETURN to stop...")
  StdIn.readLine() // let it run until user presses return
  bindingFuture
    .flatMap(_.unbind()) // trigger unbinding from the port
    .onComplete(_ => system.terminate()) // and shutdown when done

}
```

**Comment by jrudolph** [comment]
Hi @elseorand, where do you get the browser output from? It contains the payload, so maybe you are reading from the wrong field?

**Comment by elseorand** [comment]
Thank you @jrudolph .
I use a firefox addon "WebSocket Moniter". 
![screenshot from 2017-01-11 01-44-14](https://cloud.githubusercontent.com/assets/11012337/21815587/9addf086-d7a0-11e6-8449-55b955fc7762.png)

Today I've observed by Wireshark, and I've just found that akka-http sends a response "opcode: 1 and payload 0" first. 
![screenshot from 2017-01-11 01-59-13](https://cloud.githubusercontent.com/assets/11012337/21815989/d3258a0c-d7a1-11e6-9c6c-c0c828b23e2e.png)
But probably my browsers on Windows10 and Ubuntu16.04 don't recognize it.

I'll observe what cause this problem.

**Comment by jrudolph** [comment]
A single websocket message can be broken down into several frames without any semantic difference. That's what's happening here. As your websocket monitor shows, the frame has been successfully received. (It shows "Hello test!" as the payload as expected.)

So, it looks to me as if everything is working as expected. Maybe I'm missing something?

**Comment by elseorand** [comment]
Excuse me.
I release this sample to another server, and this sample works well.
Probably I took some mistakes.

Thank you for replying. @jrudolph

**Comment by jrudolph** [comment]
Cool, can we close this then?

Btw. in your dump I've seen a thing that, although semantically correct, could be optimized. I created https://github.com/akka/akka-http/issues/748 to track this.

**Comment by elseorand** [comment]
Yes. Please close.
I'm glad to contribute a little.
