### ISSUE TITLE
Bump ssl-config for new version

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#752]
To include https://github.com/typesafehub/ssl-config/issues/46

**Comment by jrudolph** [comment]
Is it really required? Whoever needs it would be able to update to the new version at any time, right?

**Comment by ktoso** [comment]
Yeah well, more of a todo-list-reminder-like-required. Can remove from title.
Thing is we need to release the new ssl-config anyway for anyone to be able to do that.

**Comment by ktoso** [comment]
Solved in https://github.com/akka/akka-http/commit/9de1b67e0c8d5b7f88162035cb7513bfa732efef
