### ISSUE TITLE
Http2: provide the same behavior wrt to automatically generated headers as Http/1

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#753]
Some headers are handled specially in akka-http or are being autogenerated for every response.

Http/2 should use the same logic as the existing implementation. In the best case, some code could be (refactored to be) reused.

Existing implementation:

https://github.com/akka/akka-http/blob/5932237a86a432d623fafb1e84eeeff56d7485fe/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala#L137-L137

**Comment by ktoso** [comment]
FYI @akka/akka-http-team / @gosubpl this would be a very helpful one to pick up if you'd like to.

**Comment by gosubpl** [comment]
@ktoso @jrudolph I felt full on synergy when I just saw this :) enthusiastically picking this up

**Comment by johanandren** [comment]
@gosubpl fyi I'll leave the modeled headers to you but "steal" this ticket

**Comment by gosubpl** [comment]
@johanandren go ahead, a few days vacation and man, how out-of-sync I am :)

**Comment by jrudolph** [comment]
Fixed by #791.
