### ISSUE TITLE
Http2: parse headers into modeled headers

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#755]
Right now the Http/2 parser generates only RawHeaders. Instead, it should provide modeled headers by running the headers through the header parser.

This might need a bit of massaging to run the (ByteString-based) `HttpHeaderParser` on the String-based key/value header pairs coming out of the HPACK decoder. One possibility could be changing `ParsedHeadersFrame` to take `(ByteString, ByteString)` pairs and defer the actually string decoding to the later `RequestParsing` stage.

**Comment by gosubpl** [comment]
Picking up this one too, as it seems related to #753

**Comment by jrudolph** [comment]
Great, thanks, @gosubpl.

This one is about the request side, #753 is more about the response side.

**Comment by johanandren** [comment]
@gosubpl Any progress on this? If not I might want to take it over, so please let us know, thanks!

**Comment by gosubpl** [comment]
@johanandren I have started working on this item, but in the meantime left for short vacation. I'll be back on Thursday (19th) and would be very happy to continue working on it. If you cannot wait that long, please take over.

**Comment by johanandren** [comment]
Thanks for letting us know, I think I'll let you work on it then!
