### ISSUE TITLE
HTTP2: Respect SETTINGS_MAX_FRAME_SIZE

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#757]
SETTINGS_MAX_FRAME_SIZE (0x5):
Indicates the size of the largest frame payload that the sender is willing to receive, in octets.

The initial value is 214 (16,384) octets. The value advertised by an endpoint MUST be between this initial value and the maximum allowed frame size (224-1 or 16,777,215 octets), inclusive. Values outside this range MUST be treated as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

**Comment by ktoso** [comment]
That's the setting I started working with yesterday, so marking as in progress.

**Comment by ktoso** [comment]
Part of https://github.com/akka/akka-http/issues/757

**Comment by ktoso** [comment]
We're respecting the setting if sent from the client, the server is not sending it / limiting incoming frames yet,
