### ISSUE TITLE
Http2: Allow PRIORITY frames for streams in idle state

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#758]
Right now we send a GOAWAY frame because the frames are not yet in our map.

As firefox will use the first few streams as a priority tree to hang later resource requests into.

http://bitsup.blogspot.de/2015/01/http2-dependency-priorities-in-firefox.html

**Comment by jrudolph** [comment]
This blog post from akamai shows it in a bit more detail what firefox does: https://blogs.akamai.com/2016/04/http2-enables-more-intelligent-resource-loading-via-stream-dependencies-but-its-not-as-simple-as-you.html

**Comment by gosubpl** [comment]
I will look into that.

**Comment by ktoso** [comment]
Hey @gosubpl, this is something we want to have in the release in this week so I'll start working on it. Hope you don't mind :-)

**Comment by gosubpl** [comment]
Absolutely, please hack away. In the meantime - anything of a bit lower priority for me?

**Comment by ktoso** [comment]
Various settings handlings would be good https://github.com/akka/akka-http/labels/t%3Ahttp2

**Comment by ktoso** [comment]
I'll mark this one as resolved, actually handling them is a separate story, will add a ticket
