### ISSUE TITLE
Java Docs. Document workaround for S3 not interpreting URI paths with `+` signs correctly vs. Akka HTTP normalizing URIs

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#759]
This was already addressed in issue #451 for the Scala documentation. However, the Java one is still missing. Please document the proper workaround for this in the Java documentation with the proper Java snippet.

**Comment by jlprat** [comment]
For reference, the Scala documentation was added in this PR: https://github.com/akka/akka-http/pull/654

**Comment by jonas** [comment]
Fixed with additional improvements to Scala doc version.
