### ISSUE TITLE
JavaDSL Docs. Http client decoding response example in docs

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#760]
As a result of issue #685 there is now a Scala example of client decoding response. Please provide a similar example and documentation for the Java DSL.

**Comment by jlprat** [comment]
PR for reference 
https://github.com/akka/akka-http/pull/686

**Comment by ktoso** [comment]
Can be closed, was done 👍

**Comment by jlprat** [comment]
Well, there is this PR... https://github.com/akka/akka-http/pull/771

**Comment by ktoso** [comment]
Ah ok missed the relation between those :~
