### ISSUE TITLE
HTTP2: Respect SETTINGS_INITIAL_WINDOW_SIZE

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#773]
SETTINGS_INITIAL_WINDOW_SIZE (0x4):
Indicates the sender's initial window size (in octets) for stream-level flow control. The initial value is 216-1 (65,535) octets.

This setting affects the window size of all streams (see Section 6.9.2).

Values above the maximum flow-control window size of 231-1 MUST be treated as a connection error (Section 5.4.1) of type FLOW_CONTROL_ERROR.

**Comment by jrudolph** [comment]
This setting is already handled. The only thing to do here is to check the received value against the maximum size.

**Comment by jrudolph** [comment]
Remaining part fixed by #816.
