### ISSUE TITLE
HTTP2: Respect SETTINGS_MAX_CONCURRENT_STREAMS

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#774]
SETTINGS_MAX_CONCURRENT_STREAMS (0x3):
Indicates the maximum number of concurrent streams that the sender will allow. This limit is directional: it applies to the number of streams that the sender permits the receiver to create. Initially, there is no limit to this value. It is recommended that this value be no smaller than 100, so as to not unnecessarily limit parallelism.

A value of 0 for SETTINGS_MAX_CONCURRENT_STREAMS SHOULD NOT be treated as special by endpoints. A zero value does prevent the creation of new streams; however, this can also happen for any limit that is exhausted with active streams. Servers SHOULD only set a zero value for short durations; if a server does not wish to accept requests, closing the connection is more appropriate.

**Comment by johanandren** [comment]
Setting added but not enforced so we can keep this ticket open

**Comment by jrudolph** [comment]
This has been better specified in #3228. Closing this as a duplicate.
