### ISSUE TITLE
PR validation: fix tagging after failed runs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#779]
It seems PRs are still tagged `validating` instead of `needs-attention` when PR validation fails. We should fix that in the pr validation task configuration.

**Comment by jrudolph** [comment]
I wonder how that ever worked. The script was executed against the wrong repo (akka/akka). So now, some old akka PRs there got wrong tags ;). E.g. here: https://github.com/akka/akka/pull/771

Anyway, probably nothing to worry about too much. Fixed the script on jenkins.

**Comment by ktoso** [comment]
lol wat, weird that it targetted wrong repo...
Thanks for fixing
