### ISSUE TITLE
Scala Docs. Fix broken `snip` link in source streaming support

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#797]
Paradox docs can't be generated due to a wrong link in source streaming support page.

**Comment by ktoso** [comment]
Sounds like we're not including it in PR validation then?
To close this ticket we should fix the issue and fix pr validation

**Comment by jlprat** [comment]
I'm submitting now the fix for the page itself

**Comment by jlprat** [comment]
I would say the test code is checked, but the `paradox` task is not run

**Comment by jlprat** [comment]
For reference, the PR valdiation ticket: #801

**Comment by jonas** [comment]
Fixed via 5e78867
