### ISSUE TITLE
Http2: implement priority tree and use it for prioritizing requests

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#806]
As specified here: http://httpwg.org/specs/rfc7540.html#StreamPriority

**Comment by gosubpl** [comment]
Interesting tests for `PRIORITY`: https://github.com/netty/netty/blob/4.1/codec-http2/src/test/java/io/netty/handler/codec/http2/WeightedFairQueueByteDistributorTest.java

**Comment by jrudolph** [comment]
First version of this was merged with #818.
