### ISSUE TITLE
withoutSizeLimit should not be recommended to people

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#814]
withoutSizeLimit obviously turns off the too large payload protection (that's exactly what it does), so we should not recommend it directly but instead advertise picking the right values for the size limit more consciously.

**Comment by jlprat** [comment]
Would it make sense to also extend this recommendation to Scaladic/Javadoc?

**Comment by ktoso** [comment]
Yes, we usually/everywhere explain those things but with size limit we're too eager to tell people to use it. scaladoc should also recommend thinking about a good limit instead
