### ISSUE TITLE
Run tests also against Akka 2.5 (milestone for now)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#826]
Akka 2.5 should be compatible enough to run with akka-http compiled against 2.4. We should run our tests against the current 2.5 binary to make sure everything is compatible.

**Comment by ktoso** [comment]
I think this works now right? Anything else we need to do here @jrudolph ?

**Comment by jrudolph** [comment]
No, the idea was to run it against the *binaries*, the nightly tests runs it against the

**Comment by jrudolph** [comment]
We can also postpone this for a while until 2.5 was released. We can then update to 2.5 but would want to run tests against 2.4 binaries instead.

**Comment by ktoso** [comment]
(Not yet done, just merged a PR preparing for it)

**Comment by sourcekick** [comment]
We have some services using Akka HTTP 10.0.p with p > 8 on top of Akka 2.4 and also some on top of Akka 2.5

It would be nice to know we can completely migrate to Akka 2.5.x without caring too much about potential issues.

**Comment by jrudolph** [comment]
We are building and running tests against 2.5 every night so we are pretty confident that it is working well. We just don't run extra binary compatibility checks right now. So, you should be fine.

**Comment by jrudolph** [comment]
As explained above we run against Akka master every night, so we have that covered for now. We could also add another nightly run that runs against the latest released version if that's necessary.

We'll track the next steps for 10.1.x in #1645. Closing this ticket.
