### ISSUE TITLE
encodeResponse with gzip is very slow

### ISSUE THREAD

**Issue by arjantop** [akka/akka-http#841]
Example project:
https://github.com/arjantop/akka-http-gzip

No matter the text size the throughput is at least halved when using gzip (from examples I ran), original observation was with some actual logic in the service comparing Akka HTTP and Finagle. I did not experience such slowdowns when using Finagle with compression level 9.

Some very rough numbers:
Akka HTTP: ~14k req/s -> ~6k req/s
Finagle: ~14k req/s -> ~10k req/s

**Comment by jrudolph** [comment]
Thanks for the report @arjantop. What units are those numbers?

**Comment by arjantop** [comment]
Req/s, I updated the comment.

**Comment by jrudolph** [comment]
I think there are two things at play here:

 * Stream materialization is slow, so a non-strict entity will be much slower than a strict one. We are currently working on improvements to materialization speed in akka-stream (akka/akka#22264) which will hopefully reduce the cost.
 * Gzip compression itself seems to be somewhat slow. We do nothing fancy here but using the JDK `Deflater`, not sure how finagle would be able to serve things still as fast.

I used this route to compare things:

```scala
    path("large") {
      complete(textLarge)
    } ~
    path("large-gzip") {
      encodeResponseWith(Gzip) {
        complete(textLarge)
      }
    } ~
    path("large-gzip-strict") {
      complete(Gzip.encode(ByteString(textLarge)))
    } ~
    path("large-streamed") {
      complete(HttpEntity(ContentTypes.`text/plain(UTF-8)`, Source.single(ByteString(textLarge))))
    }
```

I see these numbers with `wrk -t 2 -c 64 -d 120 <url>`:

 * large: 75k req/s
 * large-gzip-strict: 21k req/s
 * large-streamed: 18k req/s
 * large-gzip: 9k req/s

So, for me the difference is far bigger with both materialization and gzip both contribution a factor of ~ 3x of slowdown.

**Comment by jrudolph** [comment]
FWIW, for `large-gzip-strict` here are the top things in the profile:

```
Overhead  Shared Object       Symbol                                                                                                                                                                                                          
  22.94%  libzip.so           [.] longest_match
  22.46%  libzip.so           [.] deflate_slow
   7.60%  libzip.so           [.] compress_block
   2.55%  libzip.so           [.] pqdownheap
   1.97%  libzip.so           [.] build_tree
   1.47%  perf-8183.map       [.] Lsun/nio/cs/UTF_8$Encoder;::encode
   1.00%  libc-2.19.so        [.] memset
   0.96%  perf-8183.map       [.] updateBytesCRC32
   0.81%  [kernel]            [k] flush_tlb_func
   0.69%  libzip.so           [.] send_tree
   0.55%  perf-8183.map       [.] Lakka/dispatch/Mailbox;::processMailbox
   0.50%  perf-8183.map       [.] itable stub
   0.44%  perf-8183.map       [.] Lakka/io/SelectionHandler$ChannelRegistryImpl$$anon$3;::tryRun
   0.41%  perf-8183.map       [.] itable stub
   0.39%  libzip.so           [.] scan_tree
   0.39%  perf-8183.map       [.] Lakka/io/Tcp
```

**Comment by arjantop** [comment]
I can confirm that `large-gzip-strict` endpoint is practically equivalent to finagle in performance. I updated the repo and added finagle (https://github.com/arjantop/akka-http-gzip). Finagle also uses `Deflater`.

If I look at the profile in Flight Recorder (ignoring native code) `Fusing` comes as one of the top methods. Is this that "Stream materialization" stuff that you are talking about?

**Comment by jrudolph** [comment]
Yes, Fusing is stream materialization. Faster materialization will come with Akka 2.5.

**Comment by jrudolph** [comment]
I don't think we will act on this any time soon. Try using Akka 2.5 if you care about better materialization performance.
