### ISSUE TITLE
Failure to materialize response entity from server goes up in smoke

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#848]
This sample: https://github.com/johanandren/akka-stream-samples/blob/8ff72a06a11a78a66fa7d58d7f42328f8b277193/src/main/java/com/lightbend/akka/johan/stream/samples/java/Sample3.java

Throws an exception when materializing (because the range is converted to a Seq and they cannot contain that many elements), the exception is nowhere to be seen, client get connection error:
```
$ curl http://127.0.0.1:8080/numbers
curl: (56) Recv failure: Connection reset by peer
```

Would be nice if it resulted in Http 500, or at least the exception got logged on the server.

**Comment by jrudolph** [comment]
I can reproduce this issue. It is logged on DEBUG level as 

```
[info] [DEBUG] [07/31/2019 10:50:44.766] [default-akka.actor.default-dispatcher-2] [akka://default/system/StreamSupervisor-0/flow-1-0-detacher] Aborting tcp connection to /127.0.0.1:56120 because of upstream failure: java.lang.IllegalArgumentException: 0 to 2147483647 by 1: seqs cannot contain more than Int.MaxValue elements.
[info] scala.collection.immutable.Range.fail(Range.scala:143)
[info] scala.collection.immutable.Range.length(Range.scala:140)
[info] scala.collection.IndexedSeqLike$class.iterator(IndexedSeqLike.scala:90)
[info] scala.collection.immutable.Range.iterator(Range.scala:61)
[info] akka.stream.javadsl.Source$$anon$2.create(Source.scala:173)
[info] akka.stream.javadsl.Source$$anon$2.create(Source.scala:171)
[info] akka.stream.javadsl.Source$$anonfun$fromIterator$1.apply(Source.scala:103)
[info] akka.stream.javadsl.Source$$anonfun$fromIterator$1.apply(Source.scala:103)
[info] akka.stream.scaladsl.Source$$anon$1.iterator(Source.scala:261)
[info] akka.stream.impl.fusing.StatefulMapConcat$$anon$30.onPush(Ops.scala:2035)
[info] akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
[info] akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:510)
[info] akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
```

so, it isn't throwing while materializing but only after. That means, we already have sent out the headers when the error occurs, so we have no chance to report anything to the client. We should give an error with ERROR level though because it is an application-level error.

**Comment by jrudolph** [comment]
As commented before, there's little possibility to notify the client of the error but in #2627 materialization and stream errors are now logged properly.
