### ISSUE TITLE
README has a broken image for Scaladex link

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#853]
The image that links to Scaladex is broken.
Currently image points to: https://camo.githubusercontent.com/4ecfd7f2cbcd4cd9eb91164b704f16ede8a34ba3/68747470733a2f2f696e6465782e7363616c612d6c616e672e6f72672f636f756e742e7376673f713d646570656e64656e636965733a616b6b612f616b6b612d687474702a267375626a6563743d7363616c616465783a26636f6c6f723d626c7565267374796c653d666c61742d737175617265
which returns a 504

**Comment by jlprat** [comment]
Nevermind, it looks Scaladex is experiencing some troubles (it first started with the image, and now the whole site is down.

**Comment by jrudolph** [comment]
Yep, seems to be working again, so maybe some intermediate troubles.

**Comment by ktoso** [comment]
Cool, please mark as invalid when closing

**Comment by jlprat** [comment]
Sorry, as it was me who closed it, I couldn't add any milestone or label

**Comment by ktoso** [comment]
Ah I see, we should do something about that 😉 😉

**Comment by jlprat** [comment]
😉  😉
