### ISSUE TITLE
Provide link to api doc in main page

### ISSUE THREAD

**Issue by kmcheung12** [akka/akka-http#859]
The link to [api doc](http://doc.akka.io/api/akka-http/current/)  seems to be missing from the akka-http [documentation](http://doc.akka.io/docs/akka-http/current/index.html)

In contrast, it can be easily found on http://akka.io/docs/

It took me some guess work to find out the link to the api doc page.
Or perhaps I am missing the obvious?

**Comment by jrudolph** [comment]
It's on this page, so two levels deeper: http://doc.akka.io/docs/akka-http/current/scala/http/index.html

We are planning to restructure docs in the future (#436) to simplify finding things like that. Let's keep it open until then.

**Comment by kmcheung12** [comment]
Didn't expect to have response that quick! Thanks a lot!

**Comment by jonas** [comment]
As part of #1638, the API docs are now listed in the reference section on the main page.
I suggest closing this ticket.

**Comment by kmcheung12** [comment]
@jonas Thanks, indeed!
