### ISSUE TITLE
FAILED: ResponseRendererSpec -> The response preparation logic should properly render The 'Connection' header should be rendered correctly

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#864]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/743/testReport/junit/akka.http.impl.engine.rendering/ResponseRendererSpec/The_response_preparation_logic_should_properly_render_The__Connection__header_should_be_rendered_correctly/

**Comment by jrudolph** [comment]
Probably a follow-up to https://github.com/akka/akka-http/issues/332

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/799/testReport/junit/akka.http.impl.engine.rendering/ResponseRendererSpec/The_response_preparation_logic_should_properly_render_The__Connection__header_should_be_rendered_correctly/

**Comment by note** [comment]
Happened again here: https://jenkins.akka.io:8498/job/pr-validator-akka-http/1092/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1136/testReport/junit/akka.http.impl.engine.rendering/ResponseRendererSpec/The_response_preparation_logic_should_properly_render_The__Connection__header_should_be_rendered_correctly/

**Comment by jlprat** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1350/testReport/junit/akka.http.impl.engine.rendering/ResponseRendererSpec/The_response_preparation_logic_should_properly_render_The__Connection__header_should_be_rendered_correctly/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1448/testReport/junit/akka.http.impl.engine.rendering/ResponseRendererSpec/The_response_preparation_logic_should_properly_render_The__Connection__header_should_be_rendered_correctly/
