### ISSUE TITLE
Accept LF as line ending in body part parser

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#868]
Follow up to #106.

**Comment by satansk** [comment]
Hi @jrudolph , since the problem has been fixed for HTTP messages and headers, so I guess it will be easier to get right with body part. I want to have a try!

**Comment by jrudolph** [comment]
Currently unmerged https://github.com/akka/akka-http/pull/585 already contained an implementation for this feature.

**Comment by satansk** [comment]
@jrudolph oh, so maybe it's better to chose another one.
