### ISSUE TITLE
Update MiMa and Fix binary incompatibilities

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#870]
MiMa doesn't have entries for releases `10.0.2` and `10.0.3` this implies that all PR's since then were not properly checked by MiMa, causing some binary incompatibilities.
Currently these are:
* ~~akka-http-spray-json:~~
  * ~~`method sprayJsValueByteStringUnmarshaller()akka.http.scaladsl.unmarshalling.Unmarshaller in trait akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport is present only in current version filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.sprayJsValueByteStringUnmarshaller")`~~
* ~~akka-http:~~
  * ~~`method fromEntityStreamingSupportAndEntityMarshaller(akka.http.scaladsl.common.EntityStreamingSupport,akka.http.scaladsl.marshalling.Marshaller,scala.reflect.ClassTag)akka.http.scaladsl.marshalling.Marshaller in trait akka.http.scaladsl.marshalling.LowPriorityToResponseMarshallerImplicits is present only in current version filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.marshalling.LowPriorityToResponseMarshallerImplicits.fromEntityStreamingSupportAndEntityMarshaller")`~~
  * ~~`method andThen(akka.http.scaladsl.unmarshalling.Unmarshaller)akka.http.scaladsl.unmarshalling.Unmarshaller in trait akka.http.scaladsl.unmarshalling.Unmarshaller is present only in current version filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.unmarshalling.Unmarshaller.andThen")`~~
* ~~akka-http-core:~~
  * ~~`method parsingRendering(akka.http.scaladsl.settings.ServerSettings,akka.event.LoggingAdapter)akka.stream.scaladsl.BidiFlow in object akka.http.impl.engine.server.HttpServerBluePrint does not have a correspondent in current version filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.http.impl.engine.server.HttpServerBluePrint.parsingRendering")`~~
  * ~~`method apply(akka.http.scaladsl.settings.ServerSettings,akka.event.LoggingAdapter)akka.stream.scaladsl.BidiFlow in object akka.http.impl.engine.server.HttpServerBluePrint does not have a correspondent in current version filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.http.impl.engine.server.HttpServerBluePrint.apply")`~~
  * ~~`method parsing(akka.http.scaladsl.settings.ServerSettings,akka.event.LoggingAdapter)akka.stream.scaladsl.Flow in object akka.http.impl.engine.server.HttpServerBluePrint does not have a correspondent in current version filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.http.impl.engine.server.HttpServerBluePrint.parsing")`~~

I guess the proper `10.0.*.backwards.excludes` files must be added for those projects

**Comment by jlprat** [comment]
After putting the right `.backwards.excludes` files in place these are the current binary incompats:
akka-http-core: found 2 potential binary incompatibilities while checking against com.typesafe.akka:akka-http-core_2.11:10.0.3  (filtered 7)
* class akka.http.impl.util.StreamUtils#AbsorbCancellationStage does not have a correspondent in current version filter with: ProblemFilters.exclude[MissingClassProblem]("akka.http.impl.util.StreamUtils$AbsorbCancellationStage")
* method absorbCancellation()akka.stream.scaladsl.Flow in object akka.http.impl.util.StreamUtils does not have a correspondent in current version filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.http.impl.util.StreamUtils.absorbCancellation")

**Comment by jrudolph** [comment]
Fixed by #871.
