### ISSUE TITLE
Fix redirectToNoTrailingSlashIfPresent not to go into redirect loop for root path

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#878]
In Http, the root path cannot be empty and must be at least a single slash. So, if you remove the slash for the root URL and redirect, it will automatically be added leading to the redirect loop.

/cc @lihaoyi

**Comment by kubukoz** [comment]
Seems easy enough - I'd like to tackle this. ;)

**Comment by ktoso** [comment]
Please assign milestones when closing issues, we lost quite a few from 10.0.5 that I now backtrack and add milestones to. @akka/akka-http-team
