### ISSUE TITLE
Make default ExceptionHandler logging message more informative

### ISSUE THREAD

**Issue by tkroman** [akka/akka-http#887]
I've seen people wondering about the messages logged from the default [`ExceptionHandler`](https://github.com/akka/akka-http/blob/691a56cfbb8460fc93f890706bd88a9d6e9bb8ff/akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala#L45) more than once, especially when exception's message is null (we get something like this: 

`Error during processing of request: 'null'. Completing with InternalServerError response
`

which is not very helpful.)

Since there's no stack trace logging, I assume it's due to performance considerations and don't suggest simply adding an exception object as a `log.error` argument, but rather 

a) printing a class name for exceptions with `e.getMessage == null`
b) log message with a link to the 'Exception Handling' section of the docs and a short error description.

I've tried to do this in a local branch, so if you think this is worth a PR or further discussion, [here's the change I propose](https://github.com/akka/akka-http/compare/master...tkroman:explain-500-error?expand=1#diff-a3c2fe9da784b62492e0c89750710e93).

**Comment by jrudolph** [comment]
Thanks, @tkroman. I like this suggestion. I wonder if it could even make sense to log the exceptions as exceptions so that the logger can directly log the stack traces.

Please open a PR with your suggestion for further discussion.
