### ISSUE TITLE
Stage for access logging and other full response handling

### ISSUE THREAD

**Issue by vendamere** [akka/akka-http#892]
I was working on providing an access logger and ran into a few problems. Other examples I've seen rely on working within the routing layer and may not be accurate. So far for me this has lead to two log messages one when `withRequestTimeout`'s handler gets the message and then one when the Future completes after timeout and logs successfully. I've also tried adding a BidiFlow stage between my routes and the server, but this leads to the server's timeouts dissolving my stream and my logging never happens. It seems to me that the ability to put a layer [here](https://github.com/akka/akka-http/blob/b474e394e83a46ecdda97db70af505c074b4d1a7/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L60-L61) between  the `requestTimeoutSupport` and `requestPreparation` would be the ideal way to do access logging or any other analysis of the request/response before serialization. Is there a better way I'm missing? Is this something that would be accepted?

**Comment by vendamere** [comment]
I did find that by using both a BidiFlow on top of my routes to handle successful request and `withRequestTimeout` to handle timeouts did remove the issue of getting duplicate log messages when mapping on the route result. Though I think having access to the layer mentioned would be a better solution since this still leads to possibly logging a success and a timeout when they are very close in time.

**Comment by raboof** [comment]
That seems accurate but I'm not sure there's anything reasonable we could do to prevent this...
