### ISSUE TITLE
Mixed completion types(future/immediate) block (high level api)

### ISSUE THREAD

**Issue by kag0** [akka/akka-http#897]
I've encountered this with the java api, but it may be applicable to scala as well.
It's well understood [and documented](http://doc.akka.io/docs/akka-http/10.0.3/java/http/handling-blocking-operations-in-akka-http-routes.html) that blocking the dispatcher, or the dispatcher's thread pool is bad news. Methods like `completeWithFuture` address this issue. However I've encountered a case where `completeWithFuture` still blocks the dispatch thread. I'm not sure if this is a bug, or intended behavior that's a bit non-obvious to the developer. Anyway:

```java
// outer route stuff here
() -> { // inner route here
  if(condition){
    // assume that someCompletionStage is not blocking dispatcher or ForkJoinPool.commonPool() in any way 
    return completeOKWithFuture(someCompletionStage);
  } else {
    return (RouteAdapter) complete(BAD_REQUEST);
  }
}
```

The assumed behavior would be that in the if case the response is returned on the completion of `someCompletionStage` and other requests are not impacted, and in the else case a response is returned immediately. 
The actual behavior is that in the if case later requests are not handled until `someCompletionStage` has completed.

If this intended behavior, I'd be happy to open a little PR to add a note in the docs if it would help.

**Comment by jrudolph** [comment]
Hi @kag0, thanks for the report.

In which way have you experienced this problem? Can you show stack traces that show the blocking of the dispatcher thread? (E.g. gather stack traces using `jstack <pid>` on the shell).

How do you create requests?

**Comment by kag0** [comment]
Let me get back to you with some jstack

I've experienced it by sending multiple requests one after another in postman, and observing that the response time is roughly r*n where r is the time the request takes to complete, and n is the number of requests made before the one in question. So when sending 3 requests where the async part is just a 5s sleep, I'd see response times of roughly 5s for the first request, 10s for the second, 15s for the third.
To investigate more I ran the application in IDEA's debugger and observed the threads I created for each sleep never existed at the same time, but rather were created and destroyed one after another.

```

**Comment by jrudolph** [comment]
Hmm, I cannot reproduce it with the route given. If I issue 3 concurrent requests they are handled concurrently. Also the times don't get longer from time to time for me.

**Comment by jrudolph** [comment]
That's the code I tried: https://github.com/akka/akka-http/compare/master...jrudolph:jr/w/897-CompletionStage-hanging-reproducer?expand=1

**Comment by kag0** [comment]
I've built out a more advanced test setup... and now I can't reproduce for myself :smile::gun:.
I suspect the issue was with the application I was using to make the requests (seems it only runs requests to the same path serially).

Thanks for your time, and sorry for wasting it.
