### ISSUE TITLE
Docs actor-interaction example not complete

### ISSUE THREAD

**Issue by fancellu** [akka/akka-http#898]
https://github.com/akka/akka-http/blob/master/docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala#L564

won't work

as actor Auction.receive doesn't handle GetBids

Was worked on previously, https://github.com/akka/akka-http/pull/610

but not completely

**Comment by jlprat** [comment]
The Java example has the same problem, here is the code: https://github.com/akka/akka-http/blob/master/docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java#L114

**Comment by jlprat** [comment]
Thanks for reporting! Would you like to provide a PR to fix this issue?

**Comment by btomala** [comment]
@jlprat @fancellu If you don't mind I could fix it.

**Comment by jlprat** [comment]
I don't know if @fancellu did something already or wanted to provide a PR for this issue. Let's see if he replies.
Otherwise, you could take it, yes :)

**Comment by fancellu** [comment]
Feel free to fix it, I'm a bit busy at the moment.

**Comment by jlprat** [comment]
@btomala it's all yours! :smiley:

**Comment by btomala** [comment]
Thanks, I will rise PR soon
