### ISSUE TITLE
Change link to issue tracker in CONTRIBUTING

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#899]
I just noticed the link to the issue tracker in CONTRIBUTING is pointing to akka docs.
It should point to https://github.com/akka/akka-http/issues/

Extra mile (open to discussion): Provide an issue template, with all the necessary comments like: 
* Check that this issue doesn't already exist
* Specify your akka-http-version (if applies)
* Specify if it's Java or Scala DSL (if applies)
* This issue tracker is not the intended place to ask questions

Information on how to add templates here: [Issue Template](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by ktoso** [comment]
Fixing the link - absolutely!

I'm not a big fan of the issue templates though... People end up just ignoring them and the issue template remains not filled out :~ I don't know what others think about it.

**Comment by jlprat** [comment]
That's why I marked it as `new` and not as `triaged`.
I have mixed feelings about templates, they are welcoming for new users, but repetitive for usual ones.

**Comment by jlprat** [comment]
PR for link created.
If people like the template issue, can be addressed in a different PR

**Comment by jlprat** [comment]
Link already merged by #902.

**Comment by johanandren** [comment]
I think it would be good if we could put a few bullets, and links to gitter/akka-user in the header, the things you describe, but I don't like the idea of default template contents - I think Konrad is right about that just being ignored/noise/deleted.

Can't find anything on such a github feature though.
