### ISSUE TITLE
Discuss: where should akka-http-core live

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#9]
This depends somewhat on #3, as "core" is already a stable module.
We have not, and should not do breaking changes in it.

"Akka HTTP", *this repo*, shall contain the directives and other high level stuff.
These high level things *MAY* need to do slightly more binary compatibility trade-offs.
The *MAY* originates from the the very user-facing-dsl aspect of this DSL.

Akka HTTP Core is already a stable module and should not change.

We have 2 options:

- 1) akka-http-core stays in akka/akka as it is the "stable slower moving thing".
- 2) akka-http-core, as it is a core part of Akka HTTP, moves along into this place. This would still be a compatible thing I believe.

I originally started with the idea 1) however recently started leaning to 2), since if someone wants to file a bug, they'd come over to "the akka http repo" of course so it would be confusing to tell them that they should report "oh that thing" in akka/akka.

I propose we move the akka-http-core code into this repo as well (opposite as I was proposing a long time ago).
Opinions?

**Comment by patriknw** [comment]
The more I think about it the more I think it's necessary to keep those together, i.e. move akka-http-core also.

**Comment by ktoso** [comment]
It seems that the more one thinks about the more one leans to keeping them together - I had the same thought process 😉 

Keeping open for @akka/akka-http-team to chime in, but I think this will be good to move together.

**Comment by 2beaucoup** [comment]
+1

**Comment by ktoso** [comment]
To be fair I think it was @2beaucoup that talked me into moving together 😄

**Comment by 2beaucoup** [comment]
:sunglasses:

**Comment by hepin1989** [comment]
+1

**Comment by ktoso** [comment]
It shall live here.
