### ISSUE TITLE
Link to example doesn't work on custom directive page.

### ISSUE THREAD

**Issue by ridox** [akka/akka-http#900]
I got 404 when clicking on "optionalHeaderValue" link in "map and tmap" section of custom directive page of documentation. [http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/custom-directives.html](http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/custom-directives.html)

**Comment by jlprat** [comment]
Thanks for reporting, the link is indeed broken. Would you like to provide a PR for this?

**Comment by ktoso** [comment]
Thanks @ridox !
