### ISSUE TITLE
Default HttpApp shuts down immediately in sbt-revolver

### ISSUE THREAD

**Issue by shishkin** [akka/akka-http#914]
The default shutdown signal in `HttpApp`, the `ENTER` key, is apparently getting triggered immediately after start when running in [sbt-revolver](https://github.com/spray/sbt-revolver).

Maybe `HttpApp` should be shutdown on `SIGTERM` by default? Something like this might work:

```scala
override def waitForShutdownSignal(actorSystem: ActorSystem)(implicit executionContext: ExecutionContext): Future[Done] = {
  val promise = Promise[Done]()
  sys.addShutdownHook {
    promise.complete(Success(Done))
  }
  promise.future
}
```

If it does make sense, I could make PR.

**Comment by jrudolph** [comment]
I agree that HttpApp should work properly with sbt-revolver.

The reason it instantly completes is that there is no stdin when run with sbt-revolver. Couldn't we just check if `stdin` has already been closed, i.e. if `readLine` returns `null` and then log a message and keep the ActorSystem alive?

**Comment by ktoso** [comment]
Sounds good - we definitely want to work well with revolver. 
Would you try to detect this and submit a PR @shishkin ?

**Comment by jlprat** [comment]
Bonus point would be that it also works from the sbt console, so dummy demos are still possible

**Comment by jrudolph** [comment]
What's the blocker with the sbt console?

**Comment by jlprat** [comment]
Oh, no, just thinking about the convenience of hitting ENTER and shutting down the server without quitting the console.

**Comment by shishkin** [comment]
> Would you try to detect this and submit a PR @shishkin ?

I will. Thanks for the suggestions everyone, will incorporate them into the PR.
