### ISSUE TITLE
Support for pluggable transports on the client-side

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#916]
Right now it's possible to use `Http().clientLayer` to implement all kinds of transports below HTTP on a single connection level. However, in the pool infrastructure the transport is currently hard-wired.

It would be nice to be able to define a new custom transport and configure it for the pool so the pool will use it when creating pooled connections.

This could be used to implement transports for running directly over SOCKS proxies (https://github.com/akka/akka-http/issues/916), HTTPS proxies (#192), or over SSH tunneled connections.

(Note that, normal HTTP proxies need to be implemented differently as these are implemented on the HTTP layer, not on the transport layer.)

**Comment by ktoso** [comment]
This was solved, please close / assign milestones when done with a PR :)
