### ISSUE TITLE
Allow Content-Range as a Request HttpHeader

### ISSUE THREAD

**Issue by desmondyeung** [akka/akka-http#932]
There are a number of popular APIs that use the `Content-Range` header to facilitate resumable or chunked uploads features. However, the header is currently not allowed as a request Header. 
See: `akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala`

There appears to be some general confusion about this topic. See 2nd comment & discussion. http://stackoverflow.com/questions/716680/difference-between-content-range-and-range-headers

**Comment by jrudolph** [comment]
Agreed. Should be as simple as changing the type of `Content-Range` from `ResponseHeader` to `RequestResponseHeader`. Could you open up a PR for that?

**Comment by desmondyeung** [comment]
Sure! I'll open up a PR today.

**Comment by ktoso** [comment]
Solved (please note that when closing the right milestone must be assigned) :)
