### ISSUE TITLE
NPE when acessing scaladsl.model.headers.HttpOriginRange.`*`

### ISSUE THREAD

**Issue by jonas** [akka/akka-http#936]
While testing #929 I looked into akka/akka@2aa3d7bb1dc9099d00243047b6cdf4597fd570a0 and found that it is still possible to reproduce the java initialization issue using the test case given in https://github.com/akka/akka/issues/20403#issuecomment-215356663

Here's a test version:
```scala
class JavaInitializationSpec extends WordSpec with Matchers {

  implicit class HeaderCheck[T](self: T) {
    def =!=(expected: String) = self.toString shouldBe expected
  }

  "LanguageRange" should {

    "initializes the right field" in {
      // Uncommenting the following line fixes the NPE
      // akka.http.javadsl.model.headers.HttpOriginRange.ALL =!= "*"
      akka.http.scaladsl.model.headers.HttpOriginRange.`*` =!= "*"
    }
  }
}
```

Based on https://gist.github.com/jonas/6ccec6a28a105c89e3793b9f410b71ef

**Comment by jrudolph** [comment]
Thanks, great reproducer.
