### ISSUE TITLE
Routes parsing doesn't work?

### ISSUE THREAD

**Issue by jmcardon** [akka/akka-http#937]
I've tried the following:

```
..
~ pathPrefix("someRoute" / "get_metadata") {
    pathEnd {
        ...
      }
    }
~ pathPrefix("someRoute" / "list") {
   pathEnd {

   }
}
```

or

```
~ pathPrefix("someRoute") {
      pathSingleSlash {
         pathPrefix("get_metadata) {
              ...
           }
        }
    }

```
or
```

pathPrefix("someRoute"){
 pathSingleSlash {
         pathPrefix("get_metadata) {
              pathEnd {
                       ...
                 }
           }
        }
    }
  }
```

or 

```
pathPrefix("someRoute"){
 pathSingleSlash {
         path("get_metadata) {
                       ...
           }
        }
    }
  }
```

None of these work very intuitively. In the first example, the second route gets a "not absolute uri" exception. In the other three, it doesn't match the "get_metadata" route at all.

What Am I missing here for nesting routes? If I wanted a route say "/api/{x}" where x may vary in value, every option I've tried has failed.

This is on the current 10.0.1 version of akka-http btw.

**Comment by jlprat** [comment]
Regarding the `/api/{x}` have you read the examples in the documentation? http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/path-matchers.html#examples

For composing directives, you can also take a look at http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/index.html#composing-directives

**Comment by ktoso** [comment]
In general, you're over-doing it - there is no need for the pathSingleSlash right in the middle of nested routes, and there is no need for pathEnd (you could just say `path("bla" / Segment) { seg =>` etc.

Please read the docs @jlprat linked.
I'm closing this as it's not an issue but a question really, please use https://groups.google.com/forum/#!searchin/akka-user/ or http://gitter.im/akka/akka for questions on using akka, issues are for reporting bugs :)

Thanks and hope this helps!

**Comment by jrudolph** [comment]
I still wonder what's going on with the first example. If you see the "not absolute uri" exception again, please feel free to post it here, @jmcardon.

And we should take this as (another) indication that basic information how to do path matching needs to be one of the first things that people should learn from the documentation.

**Comment by jmcardon** [comment]
@jrudolph, @ktoso , @jlprat  I apologize. Working until 6am breeds insanity, especially while working with a system you're just learning. I simply did the bad habit of not goign to sleep until my bug was fixed.

I tried nested routes initially and it wasn't working and I was getting the "Not absolute URI" error as nesting routes was the first thing I tried. 

After I tried example 1, but it threw the exact same exception, thus I figured the issue was with the routing, not the HTTP request within the child actor. The bug was in the HTTP request to the foreign service I was passing (it was missing a URI but the compiler didn't throw errors) Everything else was working as intended. I should've been more thorough in my debugging efforts.

Still, I find the routing system, while it's extremely nice for parsing regular expressions, can be non-intuitive for nesting and composing routes. I've been neck deep in your docs and have gotten most of what I want to work, but there just isn't an example for pattern matching say `/api/{x}{y}{z}` within /api/ when x, y and z have different behavior.. See for example:

```
~ pathPrefix("someRoute") {
      path("hello") {
        (post & entity(as[SomeMarshalledMetadata])) {
          request =>
            complete(
             ...
            )
        }
      } ~ path("hi") {
        (post & entity(as[SomeListFolder])) {
          request =>
            complete(
             ...
            )
        }
      }
    }
```

Doesn't work, even after making sure the aforementioned entity unmarshalling is working, but given the docs this is the intuitive way to match routes.

**Comment by jlprat** [comment]
Hi @jmcardon,
I hakked some tiny dummy example that is doing more or less what you want to achieve, you can find it here:
https://gist.github.com/jlprat/7195f6cfd68ad5ce133e252157a6060c

To test it for example run:
```
$> curl localhost:8080/someRoute/hello -d "{\"foo\": \"foz\"}" -H "Content-Type: application/json"
hey! foz
```

```
$> curl localhost:8080/someRoute/hi -d "{\"foo\": \"foz\"}" -H "Content-Type: application/json"
ho! FOZ
```

**Comment by jmcardon** [comment]
@jlprat thank you for the example. That worked!!!!!!

..But why? The only difference is the route is being surrounded in brackets {}

So basically, my original code was like this: 

```
val route: Route = path("somepath1") {
... // some acitons
    } ~ pathPrefix("someRoute") {
      path("hello") {
        (post & entity(as[SomeMarshalledMetadata])) {
          request =>
            complete(
             ...
            )
        }
      } ~ path("hi") {
        (post & entity(as[SomeListFolder])) {
          request =>
            complete(
             ...
            )
        }
      }
    }
```

This didn't work as intended. However: 

```
val route: Route = {
   path("somepath1") {
... // some acitons
    } ~ pathPrefix("someRoute") {
      path("hello") {
        (post & entity(as[SomeMarshalledMetadata])) {
          request =>
            complete(
             ...
            )
        }
      } ~ path("hi") {
        (post & entity(as[SomeListFolder])) {
          request =>
            complete(
             ...
            )
        }
      }
    }
}
```

Works just fine. Is this intended behavior? I'm rather new to routes composition. I had the right idea from the get go but it wasn't working simply because it wasn't scoped in brackets.

**Comment by jmcardon** [comment]
@jlprat @jrudolph I reproduced, what (may) be a bug? Maybe it's intended but I didn't see anything anywhere regards this scoping.

See: https://gist.github.com/jmcardon/14f2e7ae7e358a5ee8c36b96c1e9686c

Now try:
`$> curl localhost:8080/someRoute/hi -d "{\"foo\": \"foz\"}" -H "Content-Type: application/json"
The requested resource could not be found.`

OS: Ubuntu 16.04 (xenial)

**Comment by jlprat** [comment]
Hi,
There is at least a missing `~` (concat operator) between the `kappa` route
and the `someRoute` one. It's a common thing.

I would encourage you to head to the gitter channel or use the mailing list
(google groups), it's better to discuss over there. You can find them in
the README file.
