### ISSUE TITLE
Small Error in Akka HTTP Introduction Doc

### ISSUE THREAD

**Issue by wgx731** [akka/akka-http#950]
Dear `akka-http` team,

While I am reading the introduction documentation, I notice a small error in [Routing DSL for HTTP servers](http://doc.akka.io/docs/akka-http/current/scala/http/introduction.html#routing-dsl-for-http-servers) example.

Basically, I think [this line](https://github.com/akka/akka-http/blob/master/docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala#L559) is missing a `~`, the current example, will only allow `GET` method but not `PUT` method for `/auction` path. 

Wish this can be fixed to benefit other readers.

Thank you very much.

**Comment by ktoso** [comment]
You;rehanks fo spotting th mistake :)
Would you want to contribute the fix? It's as simple as editing it online: https://github.com/akka/akka-http/edit/master/docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala#L559

**Comment by wgx731** [comment]
@ktoso, thx for getting back to me, my fix is at #951. 

Thank you very much.

**Comment by jlprat** [comment]
Solved via #951
