### ISSUE TITLE
HttpApp.route perhaps should be called routes?

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#953]
I somehow feel `routes` would be more natural.

As one would say "and here we define the routes".

WDYT?

**Comment by ktoso** [comment]
https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala#L149

**Comment by jlprat** [comment]
I have no strong opinion, I agree `routes` is more natural and `route` maybe is closer to the type. But I tend to agree with you.

We could maybe just deprecate the `route` method, instead of removing it, just to keep some source compatibility.

**Comment by viktorklang** [comment]
routesTo?

-- 
Cheers,
√

**Comment by jlprat** [comment]
Any further opinions? just rename it to `routes`?

**Comment by ktoso** [comment]
Yes, just add a method `routes` and make the `route` deprecated I guess
