### ISSUE TITLE
HttpMethod.custom doesn't work, Unsupported HTTP method

### ISSUE THREAD

**Issue by didlich** [akka/akka-http#954]
I need to extend the http methods, so I used HttpMethod.custom to register my own http method.
```
val BOLT = HttpMethod.custom(
"BOLT", 
safe = false, 
idempotent = true, 
requestEntityAcceptance = Expected
)
```

It shows me the message:
```
Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: BOLT
```

I prepared a working Scala/Akka app in this repo, which shows the problem:
https://github.com/didlich/akka-http-custom-method

**Comment by jrudolph** [comment]
@didlich custom HttpMethods need to be registered in `ParserSettings` to apply. Basically the same procedure as shown [in the documentation for status codes](http://doc.akka.io/docs/akka-http/current/scala/http/common/http-model.html#registering-custom-status-codes) needs to be used to register a custom http method. You need to change one line to

```
val parserSettings = ParserSettings(system).withCustomMethods(BOLT)
[...]
```

It seems this haven't yet been documented properly, so let's keep this ticket open to improve the documentation.

**Comment by ktoso** [comment]
We have it documented here: http://doc.akka.io/docs/akka-http/10.0.4/scala/http/routing-dsl/directives/method-directives/extractMethod.html#custom-http-method

So either linking or duplicating the example in that part of the docs would be a good idea it seems

PR very welcome to clean this up!

**Comment by didlich** [comment]
@jrudolph, @ktoso thanks for the hint, google was not able to find the proper text in the doc :-)

**Comment by richard-imaoka** [comment]
I can work on this if @didlich is not submitting a Pull Request?

**Comment by ktoso** [comment]
Yes please Richard :-)

**Comment by ktoso** [comment]
Thanks a ton @richard-imaoka !
