### ISSUE TITLE
How to get Content-Length from response of HEAD request

### ISSUE THREAD

**Issue by cheerx** [akka/akka-http#959]
I'm using Akka-Http 10.0.3.
I always get 0 by the method `contentLengthOption` from the reponse entity of HEAD request with empty response body, but I can see that `Content-Length` is not 0 with curl. I found that akka-http scala document says how to deal with this case, but I'm not very clear

**Comment by jlprat** [comment]
I guess it's better to ask such questions on the gitter channel or the user list. Unless this ticket is to express that documentation is wrong or not clear enough. If it is the latter case, could you please reformulate the issue?

**Comment by cheerx** [comment]
Sorry, I will ask by other ways, thanks

**Comment by jrudolph** [comment]
I think this is a duplicate of https://github.com/akka/akka-http/issues/377 (and I've seen you found that ticket, @cheerx).

**Comment by cheerx** [comment]
Yes, but nobody answered me after a long time, so I asked again here.

**Comment by jrudolph** [comment]
Yes, no worries. It's an expected condition in an open source project that some issues just lie around until someone cares enough to fix them. So, to speed things up, offering to help out will help more than nagging people ;)

**Comment by cheerx** [comment]
Yeah, I will have a try, but it's pretty hard for me, I'm a newbie. Thanks ^_^
