### ISSUE TITLE
ActorSystem and dispatcher access in HttpApp

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#960]
Currently `HttpApp` is not really friendly to use when it comes to create complex routes that might need a `dispatcher`, `materializer` or the `ActorSystem` itself.
It will be helpful if `HttpApp` would offer better ways to access them making it more suitable for real world usage.

**Comment by ktoso** [comment]
So on this ticket let's talk about what people should do if they want to start new actors or use futures in HttpApp.

This also relates to how people usually compose services, using a thin-cake pattern

**Comment by jrudolph** [comment]
You can always use

`extractMaterializer { implicit mat =>`

and

`extractExecutionContext { implicit ec =>`

and

`extractActorSystem { implicit system =>`

if you need to access those in a route.

**Comment by ktoso** [comment]
Hmm, right this could be the answer here indeed. I'll ponder it a bit more, perhaps that's fine.

**Comment by jlprat** [comment]
Another option would be getting rid of the `AtomicReference` for the system and pass it as an implicit parameter to all methods the user can extend. Obviously this only works for Scala, for the Java one they would need to be real parameters.

**Comment by hepin1989** [comment]
https://github.com/playframework/playframework/issues/6168
Just a link,seems like same issue.

**Comment by jlprat** [comment]
Do we want to do something with this? is @jrudolph suggestion good enough @ktoso ?

**Comment by schrepfler** [comment]
I kicked off a HttpApp class which I wanted to use for a quick test of the web-socket server support code samples, however even with the most basic websocket code sample I got this error:
```
Error:(20, 30) could not find implicit value for parameter materializer: akka.stream.Materializer
        bm.dataStream.runWith(Sink.ignore)
Error:(20, 30) not enough arguments for method runWith: (implicit materializer: akka.stream.Materializer)scala.concurrent.Future[akka.Done].
Unspecified value parameter materializer.
        bm.dataStream.runWith(Sink.ignore)
```
So then I add a materializer and the actor system...
```
implicit val mat = ActorMaterializer()
implicit val system = ActorSystem()
```
but that also failed as I needed to declare the system first.

Also I was puzzled, should I declare the system at all if this is specified in the documetation?
```
HttpApp creates its own ActorSystem instance when one is not provided. In case you already created an ActorSystem in your application you can pass it to startServer as illustrated in the following example
```
All in all, I like the basic concept of HttpApp but I think probably either more specific errors or comprehensive code samples which cover more real world use cases are needed.

**Comment by jlprat** [comment]
The `HttpApp` works better with the high-level API I think. That said, it would be great if it would integrate seamlessly with the low level one.
I'll think about ways to improve it. Ideas are welcome :simley:

**Comment by jlprat** [comment]
Not needed any more
