### ISSUE TITLE
In `extractStrictEntity` also change request to contain that strict entity for inner routes

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#961]
Currently, `extractStrictEntity` runs `toStrict` on the request entity and passes it to the inner route. However, if the inner route tries to access the now drained entity again, the route fails. Instead, we can also rewrite the request in the requestContext to contain the now strict entity. This way inner routes can safely access the entity.

This doesn't fix https://github.com/akka/akka-http/issues/73 (i.e. route alternatives will still fail when accessing the entity) but might still be a user experience improvement.

**Comment by jrudolph** [comment]
Basically, it can then be implemented as something like

`toStrictEntity(timeout) & extract(_.request.entity.asInstanceOf[HttpEntity.Strict])

**Comment by jonas** [comment]
Fixed in 938f62639fc6d6f6b64057a596bbd3d66154fb81
