### ISSUE TITLE
Make formatting changes a build failure

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#968]
Same as @bantonsson did in Akka.
Since this caused trouble in releasing... ~~I only thought it did it seems, bintray is soooo weird~~

Confirmed, this is what broke the 2.12 version release.

**Comment by jlprat** [comment]
So basically, is about making CI fail if somebody commits a non correctly formatted file, right?

**Comment by ktoso** [comment]
Yes, exactly. We have it in Akka

**Comment by jlprat** [comment]
I'd like to take this one :smiley:

**Comment by ktoso** [comment]
Hm, i think it's something done in CI so you can't really I fear hm...

**Comment by jlprat** [comment]
I thought maybe there was a way to make `validatePullRequest` fail when formatting is wrong.
It would fail also locally, but people could always just run `compile`.
But I guess it's way easy on CI servers.

**Comment by ktoso** [comment]
I think it likely should not be part of validatePullRequest since then it would not be possible to use it and add just specific changes to the commit using `git add -p`

**Comment by bantonsson** [comment]
Has been added to the Akka Jenkins CI and failed the test PR #985

**Comment by ktoso** [comment]
Awesome, thanks 👍
