### ISSUE TITLE
Dependant Http Requests saturate connection pool

### ISSUE THREAD

**Issue by ipsq** [akka/akka-http#970]
I'm noticing that Akka Http behaves very unstable when dealing with some more advanced Flow's that are comprised of multiple dependant Http requests. Let me show some code:

```scala
val responseToString = Flow[(Try[HttpResponse], String)]
      .flatMapConcat {
        case (Success(HttpResponse(StatusCodes.OK, _, entity, _)), s) =>
          Source.fromFuture(entity.toStrict(5.seconds).map(_.data.decodeString(StandardCharsets.UTF_8) -> s))
        case (Success(HttpResponse(_, _, entity, _)), _) =>
          entity.discardBytes()
          Source.empty
        case _ =>
          Source.empty
      }

Source.single(HttpRequest(uri = "...") -> "...")
      .via(Http().superPool[String]())
      .via(responseToString)
      .via(...) // creates multiple new HttpRequests based on the returned body
      .via(Http().superPool[String]())
      .via(responseToString)
      .via(...) // creates multiple new HttpRequests based on the returned body
      .via(Http().superPool[String]())
      .via(responseToString)
      .via(...) // creates multiple new HttpRequests based on the returned body
      .via(Http().superPool[String]())
      .runForeach {
        case (Success(HttpResponse(StatusCodes.OK, _, entity, _)), s) =>
          val file = new File(...) // some path based on s
          file.getParentFile.mkdirs()
          entity.dataBytes.runWith(
            FileIO.toPath(
              file.toPath
            )
          )
        case (Success(HttpResponse(_, _, entity, _)), _) =>
          entity.discardBytes()
      }
```

When running this code using the standard `application.conf`, the flow doesn't process more than about 5 `HttpRequest`s (by turning it into `HttpResponse`s) before grinding to a halt and throwing the infamous 
```
Aborting tcp connection to ... because of upstream failure: TCP idle-timeout encountered on connection to [...], no bytes passed in the last 1 minute
``` 
error message. When setting `max-open-requests` to 2^31 and `max-connections` to 10000, it runs a little better (some items in the Flow make it to the final `runForeach` statement) but still grinds to a halt before completing the total flow and ends up spitting out the same error message. 

I suspect it has something to do with the closing and reusing of the connections but I can't find it. I also tried simply declaring `val pool = Http().superPool[String]()` and reusing it instead of calling it over and over again but to no avail. 

Is this a bug or a "feature"?

**Comment by ipsq** [comment]
Sidenote: replacing `Source.fromFuture(entity.toStrict(5.seconds).map(_.data.decodeString(StandardCharsets.UTF_8) -> s))` with `entity.dataBytes.runFold(ByteString())(_ + _).map(_.data.decodeString(StandardCharsets.UTF_8) -> s)` doesn't improve the Flow and also grinds to a halt.

**Comment by jrudolph** [comment]
It might be that this way of structuring your flow just doesn't work. Using streams means that your whole stream graph will use backpressure to run with bounded buffers between stream components. I haven't thought deeply about it but it might be that for your flow each layer of pool invocations (starting from the last one) might reserve too much capacity in the pool for the layers before to deliver any data at all.

Not sure if that works but can you try using `mapAsync(1)(Http.singleRequest(...))` instead?

**Comment by jrudolph** [comment]
I'm going to close ticket for now because it doesn't contain enough information to fix it. If this is still an issue, please let us know. In that case, could you turn on DEBUG logging and upload the pool log somewhere?
