### ISSUE TITLE
Ｎot found 10.0.5 package for 2.12 on maven central repository

### ISSUE THREAD

**Issue by pocketberserker** [akka/akka-http#971]
http://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.11/10.0.5/
http://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.12/

**Comment by mirmasej** [comment]
@pocketberserker it's there.

**Comment by jlprat** [comment]
Now they are available. Happy hakking!

**Comment by pocketberserker** [comment]
Thank you!

**Comment by ktoso** [comment]
Right, sorry for the delay on getting those out, we had a minor glitch in the release process :)

Happy hakking!
