### ISSUE TITLE
Release notes for 10.0.5 are missing

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#975]
http://doc.akka.io/docs/akka-http/10.0.5/release-notes.html doesn't contain the release notes for version 10.0.5.

**Comment by ktoso** [comment]
I knew I'd forget something... I can add it later, now not next to a laptop
for the day hm.
Thanks for noticing

-- 
Konrad Malawski

**Comment by jlprat** [comment]
I can provide a PR with it, if you want

**Comment by ktoso** [comment]
Would be awesome :)

-- 
Konrad Malawski

**Comment by jlprat** [comment]
PR done. Can you update the existing page?
