### ISSUE TITLE
Add overloaded `startServer` with post binding hook HttpApp

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#987]
Even though `HttpApp` offers a post binding hook for the Akka HTTP server to do whatever it needs, sometimes, as a caller of `HttpApp#startServer` I might want to know when the server is up and running so I can start querying it or do whatever task needed. This, of course, can be accomplished by overriding `postHttpBinding`, but it will either do things that are not its responsibility or leak some future to the caller which is also not so nice.

WDYT?

**Comment by jrudolph** [comment]
@jlprat, is this still current. I don't quite understand the description ;)

**Comment by jlprat** [comment]
Well, it's not really a must, in the end it's just offer some callback in the `startServer` that would be called when the binding future is called. I guess this ticket can be closed as this can be done by users of `HttpApp` with not much effort.

**Comment by jrudolph** [comment]
Ok, then let's close this for now until the concrete need arises :)
