### ISSUE TITLE
Adapt Actor Examples to Akka 2.5

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#992]
Once Akka 2.5 is released, please convert all existing usages of Akka Actors to the new API introduced in Akka 2.5.

Please add some note to hint readers that this is the new Actor API and offer some links to `AbstractActor`

**Comment by ilke-zilci** [comment]
Hey, is anyone working on this?

**Comment by ktoso** [comment]
Hm, I was thinking we did that for actors.md while we released 2.5, what's missing @jlprat ?

**Comment by ktoso** [comment]
Ah, I missed this ticket is in HTTP.
Let's do this however we'll want to publish versioning formalised guidelines (Johannes will post proposal this week) and bump the version - so then we actually depend on 2.5 and should update the docs - let's keep it parked until then - should be just a few weeks

**Comment by jlprat** [comment]
Sure thing

**Comment by jlprat** [comment]
This one is up for picking @ilke-zilci would you like to take this one?

**Comment by ilke-zilci** [comment]
Yes sure. I started working on it.

**Comment by jlprat** [comment]
Awesome!

**Comment by ktoso** [comment]
Great -- thanks! -- marked as in progress :)

**Comment by jrudolph** [comment]
Fixed in #1831.
