### ISSUE TITLE
Improve `onSuccess` docs to explain Tupler magic

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#993]
Right now it shows the signature including magnets:

http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/future-directives/onSuccess.html

It should instead list more information about how it automatically converts different kinds of usage styles:

```scala
onSuccess(unitFuture: Future[Unit]) { // no extraction here
  complete(...)
}

onSuccess(intFuture: Future[Int]) { i => // single parameter
  complete(...)
}

onSuccess(hlistFuture: Future[Int :: String :: HNil]) { (i, str) => // multiple parameters
  complete(...)
}
```

**Comment by jlprat** [comment]
Closed by https://github.com/akka/akka-http/commit/8c79b306d18a05a87d380883fda959e076388cd3
