### ISSUE TITLE
akka.http.host-connection-pool vs akka.http.client.host-connection-pool

### ISSUE THREAD

**Issue by kag0** [akka/akka-http#997]
In the [documentation](http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html) on client connection pooling, it suggests to look for the setting `akka.http.client.host-connection-pool.max-connections`. However in the [default configuration file](http://doc.akka.io/docs/akka-http/current/scala/http/configuration.html) that setting appears to be at `akka.http.host-connection-pool.max-connections`. Assuming one is correct, the documentation could be updated in the other place.

**Comment by jrudolph** [comment]
Thanks good catch.
